<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-Hans" xml:lang="zh-Hans"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; 参数估计 – Introduction to Probability and Statistics for Engineers and Scientists（中文版）</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapter_8/8.html" rel="next">
<link href="../chapter_6/6.html" rel="prev">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-cb4e7b2c32f83f6f4e8c888918fcdddf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "没有结果",
    "search-matching-documents-text": "匹配的文档",
    "search-copy-link-title": "复制搜索链接",
    "search-hide-matches-text": "隐藏其它匹配结果",
    "search-more-match-text": "更多匹配结果",
    "search-more-matches-text": "更多匹配结果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "提交",
    "search-label": "搜索"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="7&nbsp; 参数估计 – Introduction to Probability and Statistics for Engineers and Scientists（中文版）">
<meta property="og:description" content="">
<meta property="og:image" content="https://wangwei1237.github.io/introduction_to_probability_and_statistics/images/chapter_7/f_7_1.png">
<meta property="og:site_name" content="Introduction to Probability and Statistics for Engineers and Scientists（中文版）">
<meta property="og:image:height" content="380">
<meta property="og:image:width" content="786">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../favicon.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Introduction to Probability and Statistics for Engineers and Scientists（中文版）</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="搜索"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="展开或折叠导航栏" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://wangwei1237.github.io/"> <i class="bi bi-house-fill" role="img">
</i> 
<span class="menu-text">博客</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-bookshelf" role="img">
</i> 
 <span class="menu-text">书籍</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-">    
        <li>
    <a class="dropdown-item" href="https://zh.d2l.ai/">
 <span class="dropdown-text">动手学深度学习</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://learnprompting.org/zh-Hans/docs/intro">
 <span class="dropdown-text">Learn Prompting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pan.baidu.com/s/1dciwgbhO-lfKyRo8lOqW9Q?pwd=cm9q">
 <span class="dropdown-text">Stabel Diffusion 提示词手册</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://wangwei1237.github.io/aboutme/"> <i class="bi bi-person-badge-fill" role="img">
</i> 
<span class="menu-text">关于</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics" title="源代码" class="quarto-navigation-tool px-1" aria-label="源代码"><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapter_7/7.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">参数估计</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">欢迎阅读</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface_17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">译者序</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">序言</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_1/1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">统计学简介</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_2/2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">描述统计</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_3/3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">概率论基础</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_4/4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">随机变量和期望</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_5/5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">特殊的随机变量</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_6/6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">抽样分布</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_7/7.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">参数估计</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_8/8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">假设检验</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_9/9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">回归</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_10/10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">方差分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_11/11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">拟合优度检验和分类数据分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_12/12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">非参数假设检验</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_13/13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">质量控制</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_14/14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Life testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_15/15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Simulation, bootstrap statistical methods, and permutation tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_16/16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Machine learning and big data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">测试脚本</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">附录</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">表格</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">目录</h2>
   
  <ul>
  <li><a href="#sec-7_1" id="toc-sec-7_1" class="nav-link active" data-scroll-target="#sec-7_1"><span class="header-section-number">7.1</span> 引言</a></li>
  <li><a href="#sec-7_2" id="toc-sec-7_2" class="nav-link" data-scroll-target="#sec-7_2"><span class="header-section-number">7.2</span> 最大似然估计</a>
  <ul class="collapse">
  <li><a href="#估计寿命分布" id="toc-估计寿命分布" class="nav-link" data-scroll-target="#估计寿命分布"><span class="header-section-number">7.2.1</span> 估计寿命分布</a></li>
  </ul></li>
  <li><a href="#sec-7_3" id="toc-sec-7_3" class="nav-link" data-scroll-target="#sec-7_3"><span class="header-section-number">7.3</span> 区间估计</a>
  <ul class="collapse">
  <li><a href="#sec-7_3_1" id="toc-sec-7_3_1" class="nav-link" data-scroll-target="#sec-7_3_1"><span class="header-section-number">7.3.1</span> 方差未知时正态分布均值的置信区间</a></li>
  <li><a href="#sec-7_3_2" id="toc-sec-7_3_2" class="nav-link" data-scroll-target="#sec-7_3_2"><span class="header-section-number">7.3.2</span> 预测区间</a></li>
  <li><a href="#sec-7_3_3" id="toc-sec-7_3_3" class="nav-link" data-scroll-target="#sec-7_3_3"><span class="header-section-number">7.3.3</span> 正态分布方差的置信区间</a></li>
  </ul></li>
  <li><a href="#sec-7_4" id="toc-sec-7_4" class="nav-link" data-scroll-target="#sec-7_4"><span class="header-section-number">7.4</span> 估计两个正态分布总体的均值差异</a>
  <ul class="collapse">
  <li><a href="#sec-7_4_1" id="toc-sec-7_4_1" class="nav-link" data-scroll-target="#sec-7_4_1"><span class="header-section-number">7.4.1</span> 总体方差未知时 <span class="math inline">\(\mu_1 - \mu_2\)</span> 的区间估计</a></li>
  </ul></li>
  <li><a href="#sec-7_5" id="toc-sec-7_5" class="nav-link" data-scroll-target="#sec-7_5"><span class="header-section-number">7.5</span> 伯努利随机变量均值的近似置信区间</a></li>
  <li><a href="#sec-7_6" id="toc-sec-7_6" class="nav-link" data-scroll-target="#sec-7_6"><span class="header-section-number">7.6</span> Confidence interval of the mean of the exponential distribution <span class="math inline">\(^*\)</span></a></li>
  <li><a href="#sec-7_7" id="toc-sec-7_7" class="nav-link" data-scroll-target="#sec-7_7"><span class="header-section-number">7.7</span> Evaluating a point estimator <span class="math inline">\(^*\)</span></a></li>
  <li><a href="#sec-7_8" id="toc-sec-7_8" class="nav-link" data-scroll-target="#sec-7_8"><span class="header-section-number">7.8</span> The Bayes estimator <span class="math inline">\(^*\)</span></a></li>
  <li><a href="#problems" id="toc-problems" class="nav-link" data-scroll-target="#problems">Problems</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/edit/main/chapter_7/7.qmd" class="toc-action"><i class="bi bi-github"></i>编辑该页面</a></li><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/issues/new" class="toc-action"><i class="bi empty"></i>反馈问题</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-7" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">参数估计</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-7_1" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="sec-7_1"><span class="header-section-number">7.1</span> 引言</h2>
<p>令 <span class="math inline">\(X_1, ..., X_n\)</span> 是来自分布为 <span class="math inline">\(F_\theta\)</span> 的随机样本，这个分布由一个未知参数向量 <span class="math inline">\(\theta\)</span> 来指定。例如，样本可能来自一个平均值未知的泊松分布；或者可能来自一个均值和方差都未知的正态分布。在概率论中，通常假设分布的所有参数都是已知的，而在统计学中，情况则恰恰相反。统计学的核心问题之一就是使用观测数据来推断未知参数。</p>
<ul>
<li>在 <a href="#sec-7_2" class="quarto-xref"><span>小节 7.2</span></a> 中，我们会介绍 <strong>最大似然方法</strong>（<em>maximum likelihood</em>）来估计未知参数。因为 <strong>最大似然估计</strong> 指定了一个单一值作为 <span class="math inline">\(\theta\)</span> 的估计，因此我们称其为 <strong>点估计</strong>（<em>point estimates</em>）。</li>
<li>在 <a href="#sec-7_3" class="quarto-xref"><span>小节 7.3</span></a> 中，我们会考虑 <strong>区间估计</strong>（<em>interval estimates</em>）的相关问题。对于区间估计而言，我们不会指定某个值作为 <span class="math inline">\(\theta\)</span> 的估计，而是会指定一个区间来估计 <span class="math inline">\(\theta\)</span>。此外，我们还考虑了可以对这样的区间估计报以多少 <strong>置信度</strong>（<em>confidence</em>）的问题。在该节中，我们会展示如何计算一个均值未知、但给定方差的正态分布的均值的区间估计。接下来，我们还会讨论区间估计中的一系列问题。在 <a href="#sec-7_3_1" class="quarto-xref"><span>小节 7.3.1</span></a> 中，我们会讨论方差未知的正态分布的均值的区间估计。在 <a href="#sec-7_3_2" class="quarto-xref"><span>小节 7.3.2</span></a> 中，我们会讨论正态分布的方差的区间估计。</li>
<li>在 <a href="#sec-7_4" class="quarto-xref"><span>小节 7.4</span></a> 中，我们会讨论两个正态分布的均值差的区间估计，我们会分两种情况进行讨论：
<ul>
<li>这两个正态分布的方差是已知的；</li>
<li>这两个正态分布的方差未知，但是我们会假设他们的方差是相同的。</li>
</ul></li>
<li>在 <a href="#sec-7_5" class="quarto-xref"><span>小节 7.5</span></a> 和 <a href="#sec-7_6" class="quarto-xref"><span>小节 7.6</span></a> 中，我们会分别讨论伯努利随机变量和指数随机变量的均值的区间估计。</li>
<li>在 <a href="#sec-7_7" class="quarto-xref"><span>小节 7.7</span></a> 中，我们会重新回到计算未知参数的点估计的一般性问题上来，并展示如何通过 <strong>均方误差</strong>（<em>mean square error</em>）来评估估计量。我们还会讨论估计量的偏差，并会探讨偏差与均方误差之间的关系。</li>
<li>在 <a href="#sec-7_8" class="quarto-xref"><span>小节 7.8</span></a> 中，我们会考虑在有先验信息可用时确定未知参数估计值的问题，这就是 <strong>贝叶斯</strong>（<em>bayesian</em>）方法。贝叶斯方法假设在观察数据之前，决策者总是可以获得关于 <span class="math inline">\(\theta\)</span> 的信息，并且该信息可以用 <span class="math inline">\(\theta\)</span> 的概率分布来表示。我们还会讨论如何使用估计量和参数 <span class="math inline">\(\theta\)</span> 之间的均方误差来计算 <strong>贝叶斯估计量</strong>（<em>Bayes estimator</em>）。</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled" title="估计量与估计值">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
估计量与估计值
</div>
</div>
<div class="callout-body-container callout-body">
<p>在下一节会讲到：任何用于估计未知参数 <span class="math inline">\(\theta\)</span> 的值的统计量都称为 <span class="math inline">\(\theta\)</span> 的 <strong>估计量</strong>（<em>estimator</em>）。估计量的观测值称为 <strong>估计值</strong>（<em>estimate</em>）。</p>
</div>
</div>
</section>
<section id="sec-7_2" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sec-7_2"><span class="header-section-number">7.2</span> 最大似然估计</h2>
<p>任何用于估计未知参数 <span class="math inline">\(\theta\)</span> 的值的统计量都称为 <span class="math inline">\(\theta\)</span> 的 <strong>估计量</strong>（<em>estimator</em>）。估计量的观测值称为 <strong>估计值</strong>（<em>estimate</em>）。例如，一般而言，对于正态分布的均值的估计量是基于样本 <span class="math inline">\(X_1, ..., X_n\)</span> 的样本均值 <span class="math inline">\(\overline{X} = \frac{\sum_i{X_i}}{n}\)</span>。如果样本的大小为 3，并且样本数据为 <span class="math inline">\(X_1=2\)</span>，<span class="math inline">\(X_2=3\)</span>，<span class="math inline">\(X_3=4\)</span>，那么根据估计量 <span class="math inline">\(\overline{X}\)</span> 则得到总体均值的估计值 3。</p>
<p>假设随机变量 <span class="math inline">\(X_1, \ldots, X_n\)</span> 的联合分布是已知的，只是有一个未知参数 <span class="math inline">\(\theta\)</span>。我们关注的问题是使用观察到的值来估计 <span class="math inline">\(\theta\)</span>。例如， <span class="math inline">\(X_i\)</span> 可能是独立的指数随机变量，每个变量具有相同的未知均值 <span class="math inline">\(\theta\)</span>。在这种情况下，随机变量的联合密度函数将由以下公式给出：</p>
<p>假设随机变量 <span class="math inline">\(X_1, ..., X_n\)</span> 的联合分布是已知的，只是有一个未知的参数 <span class="math inline">\(\theta\)</span>。我们关注的问题是：使用观察到的数据来估计 <span class="math inline">\(\theta\)</span>。例如，<span class="math inline">\(X_i\)</span> 可能是相互独立的指数随机变量，每个变量都具有相同的未知均值 <span class="math inline">\(\theta\)</span>。在这种情况下，随机变量的联合密度函数为：</p>
<p><span class="math display">\[
\begin{align}
f(x_1, x_2, ..., x_n) &amp;= f_{X_1}(x_1) f_{X_2}(x_2) \cdots f_{X_n}(x_n) \\
&amp;= \frac{1}{\theta}e^{-\frac{x_1}{\theta}} \frac{1}{\theta}e^{-\frac{x_2}{\theta}} \cdots \frac{1}{\theta}e^{-\frac{x_n}{\theta}} \\
&amp;= \frac{1}{\theta^n}e^{-{\frac{\sum_{i=1}^{n}{x_i}}{\theta}}}
\end{align}
\]</span></p>
<p>我们的目标就是根据观测数据 <span class="math inline">\(x_1, x_2, ..., x_n\)</span> 来估计 <span class="math inline">\(\theta\)</span>。</p>
<p>在统计学中，一种被广泛使用的、特殊类型的估计量就是最大似然估计量（<em>maximum likelihood estimator</em>）。最大似然估计的推导过程如下。</p>
<ol type="1">
<li>令 <span class="math inline">\(f(x_1, ..., x_n | \theta)\)</span> 表示随机变量 <span class="math inline">\(X_1, X_2, ..., X_n\)</span> 的联合概率质量函数（当它们是离散随机变量时）或者联合概率密度函数（当它们是连续随机变量时）。因为我们假定 <span class="math inline">\(\theta\)</span> 未知，所以我们也将 <span class="math inline">\(f\)</span> 写成 <span class="math inline">\(\theta\)</span> 的函数。</li>
<li>现在，<span class="math inline">\(f(x_1, ..., x_n | \theta)\)</span> 表示当参数 <span class="math inline">\(\theta\)</span> 是其真实值时，观测值为 <span class="math inline">\(x_1, x_2, ..., x_n\)</span> 的可能性（<em>likelihood</em>）。因此，<span class="math inline">\(\theta\)</span> 的合理的估计值应该是使得观测值的可能性最大的那个 <span class="math inline">\(\theta\)</span> 值。</li>
<li>换句话说，最大似然估计 <span class="math inline">\(\hat{\theta}\)</span> 就是令 <span class="math inline">\(f(x_1, ..., x_n | \theta)\)</span> 取得最大值的 <span class="math inline">\(\theta\)</span> 值，其中 <span class="math inline">\(x_1, ..., x_n\)</span> 表示观侧数据。而函数 <span class="math inline">\(f(x_1, ..., x_n | \theta)\)</span> 也被称为关于 <span class="math inline">\(\theta\)</span> 的似然函数。</li>
<li>为了确定 <span class="math inline">\(f(x_1, ..., x_n | \theta)\)</span> 最大时的 <span class="math inline">\(\theta\)</span> 值，通常会利用以下的事实：函数 <span class="math inline">\(f(x_1, ..., x_n | \theta)\)</span> 和函数 <span class="math inline">\(\textup{log}[f(x_1, ..., x_n | \theta)]\)</span> 取得最大值时的 <span class="math inline">\(\theta\)</span> 值是相同的。因此，我们也可以通过最大化 <span class="math inline">\(\textup{log}[f(x_1, ..., x_n | \theta)]\)</span> 得到 <span class="math inline">\(\hat{\theta}\)</span>。</li>
</ol>
<div id="exr-7_2_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.1</strong></span> <strong>伯努利分布参数的最大似然估计</strong>。假设执行 <span class="math inline">\(n\)</span> 个独立试验，每个试验的成功概率均为 <span class="math inline">\(p\)</span>。则 <span class="math inline">\(p\)</span> 的最大似然估计是多少？</p>
</div>
<div id="sol-7_2_a" class="proof solution">
<p><span class="proof-title"><em>解 7.1</em>. </span>观察数据由 <span class="math inline">\(X_1, ..., X_n\)</span> 的值构成，其中 <span class="math inline">\(X_i = \begin{cases} 1, \quad &amp; 第 i 次试验成功\\ 0, \quad &amp; 其它 \end{cases}\)</span></p>
<p>令 <span class="math inline">\(P\{X_i = 1\} = p = 1- P\{X_i = 0\}\)</span>，该等式可以简化为：</p>
<p><span class="math inline">\(P\{X_i = x\} = p^x(1-p)^{1-x}, \quad x = 0,1\)</span></p>
<p>因此试验之间相互独立，因此观察到的数据的可能性（<em>likelihook</em>，指的就是联合概率质量函数）为：</p>
<p><span class="math inline">\(\begin{align} f(x_1, ..., x_n | p) &amp;= P\{X_1 = x_1, ..., X_n = x_n | p\} \\ &amp;= p^{x_1}(1-p)^{1-x_1} \cdots p^{x_n}(1-p)^{1-x_n} \\ &amp;= p^{\sum_{i=1}^{n}{x_i}} (1-p)^{n - \sum_{i=1}^{n}{x_i}}, \quad x_i = 0,1, \quad i = 1,...,n \end{align}\)</span></p>
<p>为了确定是的 <span class="math inline">\(f\)</span> 取得最大值时 <span class="math inline">\(p\)</span> 的值，首先对 <span class="math inline">\(f\)</span> 取对数： <span class="math inline">\(\textup{log}f(x_1, ..., x_n | p) = \bigg(\sum_{i=1}^{n}{x_i}\bigg)\textup{log}\ p +\bigg (n - \sum_{i=1}^{n}{x_i}\bigg)\textup{log}(1 - p)\)</span></p>
<p>求导得到：</p>
<p><span class="math inline">\(\frac{d}{dp} \textup{log}\ f(x_1, ..., x_n | p) = \frac{\sum_{i=1}^{n}{x_i}}{p} -\frac{n - \sum_{i=1}^{n}{x_i}}{1-p}\)</span></p>
<p>令 <span class="math inline">\(\frac{d}{dp} \textup{log}\ f(x_1, ..., x_n | p) = 0\)</span> 并计算得到最大似然估计 <span class="math inline">\(\hat{p}\)</span> 满足：</p>
<p><span class="math inline">\(\frac{\sum_{i=1}^{n}{x_i}}{\hat{p}} -\frac{n - \sum_{i=1}^{n}{x_i}}{1-\hat{p}}\)</span></p>
<p>即，<span class="math inline">\(\hat{p} = \frac{\sum_{i=1}^{n}{x_i}}{n}\)</span></p>
<p>因此，均值未知的伯努利分布的最大似然估计量为：</p>
<p><span class="math inline">\(d(X_1, ..., X_n) = \frac{\sum_{i=1}^{n}{X_i}}{n}\)</span></p>
<p>因为 <span class="math inline">\(\sum_{i=1}^{n}{X_i}\)</span> 就是试验成功的次数，所以 <span class="math inline">\(p\)</span> 的最大似然估计就等于观察到的实验中成功次数的占比。举个例子，假设某制造商生产的 每个 RAM（运行内存）芯片的合格率是相互独立的，并且合格率为 <span class="math inline">\(p\)</span>。如果在 1000 个测试样本中，有 921 个合格品，那么 <span class="math inline">\(p\)</span> 的最大似然估计是 0.921。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="exr-7_2_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.2</strong></span> 两位编辑审验相同的一本稿件，如果第一位编辑发现 <span class="math inline">\(n_1\)</span> 个错误，第二位编辑发现 <span class="math inline">\(n_2\)</span> 个错误，其中有 <span class="math inline">\(n_{1,2}\)</span> 个错误两位编辑都发现了，估计这本稿件中的错误总数 <span class="math inline">\(N\)</span>。</p>
</div>
<div id="sol-7_2_b" class="proof solution">
<p><span class="proof-title"><em>解 7.2</em>. </span>在估计 <span class="math inline">\(N\)</span> 之前，需要对潜在的概率模型做一些假设。假设不同编辑的审验结果之间是独立的，并且稿件中的每个错误被第 <span class="math inline">\(i\)</span> 位编辑独立发现的概率为 <span class="math inline">\(p_i,\ i = 1,2\)</span>。</p>
<p>为了估计 <span class="math inline">\(N\)</span>，我们将从推导 <span class="math inline">\(p_1\)</span> 的估计量开始。为此，请注意，第一位编辑将会以 <span class="math inline">\(p_1\)</span> 的概率独立发现第二位编辑发现的 <span class="math inline">\(n_2\)</span> 个错误中的每一个错误。因为第一位编辑发现了<span class="math inline">\(n_2\)</span> 个错误中的 <span class="math inline">\(n_{1,2}\)</span> 个错误，因此，<span class="math inline">\(p_1\)</span> 的合理估计为：</p>
<p><span class="math inline">\(\hat{p}_1 = \frac{n_{1,2}}{n_2}\)</span></p>
<p>但是，对于稿件中的 <span class="math inline">\(N\)</span> 个错误，因为第一位编辑发现了其中的 <span class="math inline">\(n_1\)</span> 个错误，因此假设 <span class="math inline">\(p_1\)</span> 近似的等于 <span class="math inline">\(\frac{n_1}{N}\)</span> 也是合理的。因此 <span class="math inline">\(\hat{p}_1 \approx \frac{n_1}{N}\)</span>，即 <span class="math inline">\(\frac{n_{1,2}}{n_2}\approx \frac{n_1}{N}\)</span>，也就是说：</p>
<p><span class="math inline">\(N \approx \frac{n_1 n_2}{n_{1,2}}\)</span></p>
<p>因为如上的估计对于 <span class="math inline">\(n_1\)</span> 和 <span class="math inline">\(n_2\)</span> 是对称的，所以无论哪个编辑是第一位编辑，最终的结果都是相同的。</p>
<p>当两个研究小组宣布他们已经破译了人类遗传密码序列时，如上估计过程的一个有趣的案例发生了。作为两个研究小组工作的一部分，他们都估计人类基因组由大约 33000 个基因组成。因为这个数字是由两个小组独立得出的，许多科学家认为这个数字是可信的。但是，大多数科学家对这个相对较少的基因数量感到非常惊讶；相比之下，它只是果蝇基因数量的两倍左右。然而，对两个小组的研究结果进行更为仔细的检查表明，这两个小组均发现的基因数量大约为 17000 个（也就是说，有 17000 个相同的基因被这两个小组发现了）。因此，根据我们之前的估计量，我们会估计基因的实际数量不是 33000个，而是 <span class="math inline">\(\frac{n_1 n_2}{n_{1,2}} = \frac{33000 \times 33000}{17000} \approx 64000\)</span> 个。</p>
<p>对于声称发现的基因中的某些基因是否真的存在会有一些争议，因此，64000个基因应该被视为基因实际数量的上限。</p>
<p><strong>当有 <span class="math inline">\(m(m \gt 2)\)</span> 个编辑时，则上述采用的两位编辑的估计方法将不再适用。</strong></p>
<p>当 <span class="math inline">\(m \gt 2\)</span> 时，对于第 <span class="math inline">\(i\)</span> 为编辑，我们令 <span class="math inline">\(\hat{p}_i\)</span> 为由至少一位其他编辑 <span class="math inline">\(j(j \ne i)\)</span> 发现的错误中 <span class="math inline">\(i\)</span> 也发现的错误的占比，然后让 <span class="math inline">\(\hat{p}_i\)</span> 等于 <span class="math inline">\(\frac{n_i}{N}\)</span>，那么 <span class="math inline">\(N\)</span> 的估计值，即 <span class="math inline">\(\frac{n_i}{\hat{p}_i}\)</span>，将因不同的 <span class="math inline">\(i\)</span> 而异。</p>
<p>此外，使用这种方法时，即使第 <span class="math inline">\(i\)</span> 位编辑找到的错误比第 <span class="math inline">\(j\)</span> 位编辑的少，我们也有可能得到 <span class="math inline">\(\hat{p}_i &gt; \hat{p}_j\)</span>。例如，对于 <span class="math inline">\(m = 3\)</span>，假设第 1 位编辑和第 2 位编辑找到了完全相同的 10 个错误，而第 3 位编辑找到了 20 个错误且只有 1 个与其他编辑找到的错误是相同的。因为第 1 位编辑和第 2 位编辑都找到了 29 个错误中的 10 个（第 2 位编辑和第 3 位编辑总共找到了 29 个不同的错误），所以，<span class="math inline">\(\hat{p}_i = \frac{10}{29}\)</span>，<span class="math inline">\(i = 1, 2\)</span>。另一方面，因为第 3 位编辑仅找到了其他编辑找到的 10 个错误（第 1 位编辑和第 2 为编辑找到的 10 个错误是相同的）中的 1 个，因此 <span class="math inline">\(\hat{p}_3 = \frac{1}{10}\)</span>。因此，尽管第 3 位编辑找到的错误是 第 1 位编辑的两倍，但 <span class="math inline">\(p_3\)</span> 的估计值小于 <span class="math inline">\(p_1\)</span> 的估计值。</p>
<p>为了获得更合理的估计，我们可以将上述 <span class="math inline">\(\hat{p}_i,\ i=1, ..., m\)</span> 值作为 <span class="math inline">\(p_i\)</span> 的初步估计值。现在，令 <span class="math inline">\(n_f\)</span> 为至少由一位编辑发现的错误的数量。因为至少一位编辑发现的错误的占比为 <span class="math inline">\(\frac{n_f}{N}\)</span>，因此 <span class="math inline">\(\frac{n_f}{N}\)</span> 近似等于某个错误至少被一位编辑发现的概率 <span class="math inline">\(1 - \Pi_{i=1}^{m}{(1 - p_i)}\)</span>。因此，有：</p>
<p><span class="math inline">\(\frac{n_f}{N} \approx 1 - \Pi_{i=1}^{m}{(1-p_i)}\)</span></p>
<p>假设 <span class="math inline">\(N \approx \hat{N}\)</span>，有：</p>
<p><span id="eq-7_2_1"><span class="math display">\[
\hat{N} = \frac{n_f}{1 - \Pi_{i=1}^{m}{(1-\hat{p_i})}}
\tag{7.1}\]</span></span></p>
<p>有了 <span class="math inline">\(N\)</span> 的估计，我们可以通过 <span class="math inline">\(N\)</span> 的估计来重新估计 <span class="math inline">\(p_i\)</span>：</p>
<p><span id="eq-7_2_2"><span class="math display">\[
\hat{p_i} = \frac{n_i}{\hat{N}}, \quad i = 1, ..., m
\tag{7.2}\]</span></span></p>
<p>然后，我们可以根据新的 <span class="math inline">\(\hat{p_i}\)</span> 并利用 <a href="#eq-7_2_1" class="quarto-xref">式&nbsp;<span>7.1</span></a> 重新估计 <span class="math inline">\(N\)</span>。注意，估计的过程不应该就此停止，每当我们获得了 <span class="math inline">\(N\)</span> 的新估计 <span class="math inline">\(\hat{N}\)</span> 时，我们可以利用 <a href="#eq-7_2_2" class="quarto-xref">式&nbsp;<span>7.2</span></a> 获得 <span class="math inline">\(p_i\)</span> 的新估计，然后可以使用 <span class="math inline">\(p_i\)</span> 的新估计来获得 <span class="math inline">\(N\)</span> 的新估计，依此类推。） <span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="exr-7_2_c" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.3</strong></span> <strong>泊松分布参数的最大似然估计</strong>。假设 <span class="math inline">\(X_1, ..., X_n\)</span> 是独立的泊松随机变量，其均值为 <span class="math inline">\(\lambda\)</span>。确定 <span class="math inline">\(\lambda\)</span> 的最大似然估计量。</p>
</div>
<div id="sol-7_2_c" class="proof solution">
<p><span class="proof-title"><em>解 7.3</em>. </span><span class="math inline">\(\lambda\)</span> 的似然函数为：</p>
<p><span class="math inline">\(\begin{align} f(x_1, ..., x_n | \lambda) &amp;= \frac{\lambda^{x_1}e^{-\lambda}}{x_1!} \cdots \frac{\lambda^{x_n}e^{-\lambda}}{x_n!} \\ &amp;= \frac{\lambda^{\sum_{i=1}^{n}{x_i}}e^{-n\lambda}}{x_1! \cdots x_n!} \end{align}\)</span></p>
<p>对上式取对数有：</p>
<p><span class="math inline">\(\textup{log}\ f(x_1, ..., x_n | \lambda) = -n\lambda + \sum_{i=1}^{n}{x_i} \textup{log}\ \lambda - \textup{log}\ c\)</span></p>
<p>其中，<span class="math inline">\(c = \Pi_{i=1}^{n}{x_i!}\)</span>，对上式求导有：</p>
<p><span class="math inline">\(\frac{d}{d\lambda} \textup{log}\ f(x_1, ..., x_n | \lambda) = -n + \frac{1}{\lambda} \sum_{i=1}^{n}{x_i}\)</span></p>
<p>令上式为 0，得到最大似然估计 <span class="math inline">\(\hat{\lambda} = \frac{\sum_{i=1}^{n}{x_i}}{n}\)</span></p>
<p>因此，最大似然估计量为：</p>
<p><span class="math inline">\(d(X_1, ..., X_n) = \frac{\sum_{i=1}^{n}{x_i}}{n}\)</span></p>
<p>例如，假设任何一天进入某个零售店的人数是一个泊松随机变量，其均值 <span class="math inline">\(\lambda\)</span> 未知，我们希望估计 <span class="math inline">\(\lambda\)</span> 的值。如果 20 天后，共有857 人进入该机构，那么 <span class="math inline">\(\lambda\)</span> 的最大似然估计为 <span class="math inline">\(\frac{857}{20}=42.85\)</span>。也就是说，平均而言，我们估计在给定的一天将有 42.85 名顾客进入该零售店。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="exr-7_2_d" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.4</strong></span> 1998 年加州伯克利市在 10 个随机选择的非雨天发生的交通事故数量如下：</p>
<p>4,0,6,5,2,1,2,0,4,3</p>
<p>使用这些数据来估计非雨天最多发生 2 起交通事故的天数占比。</p>
</div>
<div id="sol-7_2_d" class="proof solution">
<p><span class="proof-title"><em>解 7.4</em>. </span>由于有大量司机，并且每个司机在某一天发生事故的可能性很小，因此假设每天的交通事故数量是泊松随机变量似乎是合理的。因为 <span class="math inline">\(\overline{X} = \frac{1}{10} \sum_{i=1}^{10}{X_i} = 2.7\)</span>，因此，泊松分布的均值的最大似然估计值为 2.7。最多发生 2 起事故的非雨天的长期占比等于 <span class="math inline">\(P\{X \le 2\}\)</span>，其中 <span class="math inline">\(X\)</span> 表示一天中的事故数。因此待计算的估计值为：</p>
<p><span class="math inline">\(\begin{align} P\{X \le 2\} &amp;= P\{X = 0\} + P\{X = 1\} + P\{X = 2\} \\ &amp;= e^{-2.7}(1 + 2.7 + \frac{{2.7}^2}{2}) \\ &amp;= 0.4936 \end{align}\)</span></p>
<p>也就是说，我们估计有不到一半的非雨天最多发生 2 起事故。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="exr-7_2_e" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.5</strong></span> <strong>正态分布总体的最大似然估计</strong>。假设 <span class="math inline">\(X_1, ..., X_n\)</span> 是相互独立的正态分布随机变量，其均值 <span class="math inline">\(\mu\)</span> 和标准差 <span class="math inline">\(\sigma\)</span> 均未知。计算其均值和标准差的最大似然估计。</p>
</div>
<div id="sol-7_2_e" class="proof solution">
<p><span class="proof-title"><em>解 7.5</em>. </span>其联合概率密度函数为：</p>
<p><span class="math inline">\(\begin{align} f(x_1, ..., x_n | \mu, \sigma) &amp;= \Pi_{i=1}^{n}{\frac{1}{\sqrt{2\pi}\sigma}e^{\frac{-(x_i - \mu)^2}{2\sigma^2}}} \\ &amp;= (\frac{1}{2\pi})^{\frac{n}{2}} \frac{1}{\sigma^n} e^{\frac{-\sum_{i=1}^{n}{(x_i - \mu)^2}}{2\sigma^2}} \end{align}\)</span></p>
<p>取对数有：</p>
<p><span class="math inline">\(\textup{log}\ f(x_1, ..., x_n | \mu, \sigma) = - \frac{n}{2} \textup{log}\ (2\pi) - n \textup{log}\ \sigma - \frac{\sum_{i=1}^{n}{(x_i - \mu)^2}}{2 \sigma^2}\)</span></p>
<p>为了找到 <span class="math inline">\(\mu\)</span> 和 <span class="math inline">\(\sigma\)</span> 以使上述值最大化，我们计算如下的偏导数：</p>
<p><span class="math inline">\(\frac{\partial}{\partial \mu} \textup{log}\ f(x_1, ..., x_n | \mu, \sigma) = \frac{\sum_{i=1}^{n}{(x_i - \mu)}}{\sigma^2}\)</span></p>
<p><span class="math inline">\(\frac{\partial}{\partial \sigma} \textup{log}\ f(x_1, ..., x_n | \mu, \sigma) = - \frac{n}{\sigma} + \frac{\sum_{i=1}^{n}{(x_i - \mu)^2}}{\sigma^3}\)</span></p>
<p>令如上的偏导数等于 0，有：</p>
<p><span class="math inline">\(\hat{\mu} = \frac{\sum_{i=1}^{n}{x_i}}{n}\)</span></p>
<p><span class="math inline">\(\hat{\sigma} = \bigg[\frac{\sum_{i=1}^{n}{(x_i - \hat{\mu})^2}}{n}\bigg]^{\frac{1}{2}}\)</span></p>
<p>因此，正态分布的均值和标准差的最大似然估计量分别为：</p>
<p><span id="eq-7_2_3"><span class="math display">\[
\begin{align}
\hat{\mu} &amp;= \overline{X} \\
\hat{\sigma} &amp;= \bigg[\frac{\sum_{i=1}^{n}{(X_i - \overline{X})^2}}{n}\bigg]^{\frac{1}{2}}
\end{align}
\tag{7.3}\]</span></span></p>
<p>需要注意的是：标准差 <span class="math inline">\(\sigma\)</span> 的最大似然估计并不等同于样本标准差：</p>
<p><span class="math inline">\(S = \bigg[\frac{\sum_{i=1}^{n}{(X_i - \overline{X})^2}}{n - 1}\bigg]^{\frac{1}{2}}\)</span></p>
<p>在 <a href="#eq-7_2_3" class="quarto-xref">式&nbsp;<span>7.3</span></a> 中，分母为 <span class="math inline">\(\sqrt{n}\)</span>，而不是样本方差中的 <span class="math inline">\(\sqrt{n - 1}\)</span>。然而，对于合理大小的 <span class="math inline">\(n\)</span>，<span class="math inline">\(\sigma\)</span> 的这两个估计量将近似相等。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="exr-7_2_f" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.6</strong></span> Kolmogorov 碎裂定律（<em>Kolmogorov’s law of fragmentation</em>）指出，由矿物化合物碎裂产生的大量颗粒中的单个颗粒的大小服从近似对数正态分布（<em>lognormal distribution</em>）。如果一个随机变量 <span class="math inline">\(X\)</span> 的对数 <span class="math inline">\(\textup{log}\ (X)\)</span> 服从正态分布，那么 <span class="math inline">\(X\)</span> 则具有对数正态分布。碎裂定律最初是通过实验证明的，后来由 Kolmogorov 提供了理论基础，并被应用于各种工程研究。例如，人们用碎裂定律来分析从一堆金砂中随机挑选出的颗粒的大小。碎裂定律还应用与地震断裂带的应力释放研究中（参见：Lomnitz, C., “Global Tectonics and Earthquake Risk,” <em>Developments in Geotectonics</em>, Elsevier, Amsterdam, 1979）。</p>
<p>假设从一大堆金属砂中取出 10 粒样品，它们的长度（以毫米为单位）分别是：</p>
<p>2.2, 3.4, 1.6, 0.8, 2.7, 3.3, 1.6, 2.8, 2.5, 1.9</p>
<p>估计整个砂堆中长度在 2~3 毫米之间的砂粒的百分比。</p>
</div>
<div id="sol-7_2_f" class="proof solution">
<p><span class="proof-title"><em>解 7.6</em>. </span>取这 10 个数据值的自然对数，得到转换后的数据集结果：</p>
<p>0.7885, 1.2238, 0.4700, -0.2231, 0.9933, 1.1939, 0.4700, 1.0296, 0.9163, 0.6419</p>
<p>因为如上数据的样本均值和样本标准差分别为：</p>
<p><span class="math inline">\(\overline{x} = 0.7504, s = 0.4351\)</span></p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.2</span>, <span class="fl">3.4</span>, <span class="fl">1.6</span>, <span class="fl">0.8</span>, <span class="fl">2.7</span>, <span class="fl">3.3</span>, <span class="fl">1.6</span>, <span class="fl">2.8</span>, <span class="fl">2.5</span>, <span class="fl">1.9</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>log_x <span class="ot">&lt;-</span> <span class="fu">log</span>(x)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>mean_log_x <span class="ot">&lt;-</span> <span class="fu">mean</span>(log_x)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>sd_log_x <span class="ot">&lt;-</span> <span class="fu">sd</span>(log_x)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean_log_x)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7504035</code></pre>
</div>
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sd_log_x)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.435063</code></pre>
</div>
</div>
<p>因此，随机选择的砂粒长度的对数服从均值为 0.7504、标准差为 0.4351 正态分布。所以，如果 <span class="math inline">\(X\)</span> 是砂粒的长度，那么</p>
<p><span class="math inline">\(\begin{align} P\{2 \lt X \lt 3\} &amp;= P\{\textup{log}\ 2 \lt \textup{log}\ X \lt \textup{log}\ 3\} \\ &amp;= P\bigg\{\frac{\textup{log}\ 2 - 0.7504}{0.4351} \lt \frac{\textup{log}\ X - 0.7504}{0.4351} \lt \frac{\textup{log}\ 3 - 0.7504}{0.4351}\bigg\} \\ &amp; \approx pnorm(\textup{log}\ 3 - 0.7504 / 0.4351) - pnorm(\textup{log}\ 2 - 0.7504 / 0.4351) \\ &amp;= 0.3405766 \end{align}\)</span></p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>((<span class="fu">log</span>(<span class="dv">3</span>) <span class="sc">-</span> <span class="fl">0.7504</span>) <span class="sc">/</span> <span class="fl">0.4351</span>) <span class="sc">-</span> <span class="fu">pnorm</span>((<span class="fu">log</span>(<span class="dv">2</span>) <span class="sc">-</span> <span class="fl">0.7504</span>) <span class="sc">/</span> <span class="fl">0.4351</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3405766</code></pre>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>当随机变量可以看作大量独立、同分布的随机变量的乘积的情况下，我们可以假设该随机变量服从对数正态分布。例如，在金融领域，经常用对数正态分布来估计股价在未来某段时间的价格分布。为了理解这种假设的合理性，我们假设当前股价是 <span class="math inline">\(s\)</span>，我们关心的是经过时间 <span class="math inline">\(t\)</span> 后的股票价格 <span class="math inline">\(S(t)\)</span>。对于一个较大的 <span class="math inline">\(n\)</span> 值，令 <span class="math inline">\(t_i = \frac{t}{n}\)</span>，并令 <span class="math inline">\(S(t_1), S(t_2), ..., S(t_n)\)</span> 表示在时间 <span class="math inline">\(t_1, t_2, ..., t_n\)</span> 时的股价。金融领域中的一个比较常见的假设是：<span class="math inline">\(\frac{S(t_i)}{S(t_{i-1})}\)</span> 近似符合独立同分布。因此，如果我们令 <span class="math inline">\(X_i = \frac{S(t_i)}{S(t_{i-1})}\)</span>，则：</p>
<p><span class="math inline">\(\begin{align} S(t) = S(t_n) &amp;= S(t_0) \cdot \frac{S(t_1)}{S(t_0)} \cdot \frac{S(t_2)}{S(t_1)} \cdot \cdots \cdot \frac{S(t_n)}{S(t_{n-1})} \\ &amp;= s \prod_{i=1}^{n} X_i \end{align}\)</span></p>
<p>对上式取对数得：</p>
<p><span class="math inline">\(\log(S(t)) = \log(s) + \sum_{i=1}^{n} \log(X_i)\)</span></p>
<p>根据中心极限定理有：<span class="math inline">\(\log(S(t))\)</span> 将近似服从正态分布。</p>
<p>已经证明，对于某些随机变量而言，对数正态分布是一个很好的拟合，例如病人的住院时长和车辆的行驶时间。</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
提示
</div>
</div>
<div class="callout-body-container callout-body">
<p>在上述所有例子中，总体均值的最大似然估计都是样本均值 <span class="math inline">\(\overline{X}\)</span>。但是并非所有情况都是如此，例如 <a href="#exm-7_2_g" class="quarto-xref">例&nbsp;<span>7.1</span></a>。</p>
</div>
</div>
<div id="exm-7_2_g" class="theorem example">
<p><span class="theorem-title"><strong>例 7.1</strong></span> <strong>均匀分布的均值的最大似然估计</strong>。假设 <span class="math inline">\(X_1, ..., Xn\)</span> 是来自均匀分布 <span class="math inline">\((0, \theta)\)</span> 的样本，其中 <span class="math inline">\(\theta\)</span> 未知。因此，<span class="math inline">\(X_i\)</span> 的联合密度函数为：</p>
<p><span class="math inline">\(f(x_1, x_2, ..., x_n | \theta) = \begin{cases} \frac{1}{\theta^n}, \quad &amp; 0 \lt x_i \lt \theta \\ 0, \quad &amp; 其它 \end{cases}\)</span></p>
<p>如果 <span class="math inline">\(\theta\)</span> 尽可能小，则 <span class="math inline">\(f(x_1, x_2, ..., x_n | \theta)\)</span> 则会尽可能的大。由于 <span class="math inline">\(\theta\)</span> 必须至少与所有观测值 <span class="math inline">\(x_i\)</span> 一样大，因此 <span class="math inline">\(\theta\)</span> 的最小的可能值等于 <span class="math inline">\(max(x_1, x_2, ..., x_n)\)</span>。因此，<span class="math inline">\(\theta\)</span> 的最大似然估计量是</p>
<p><span class="math inline">\(\hat{\theta} = max(X_1, X_2, ..., X_n)\)</span></p>
<p>因此，可以得出均匀分布均值 <span class="math inline">\(\frac{\theta}{2}\)</span> 的最大似然估计量为 <span class="math inline">\(\frac{max(X_1, X_2, ..., X_n)}{2}\)</span>。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<section id="估计寿命分布" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="估计寿命分布"><span class="header-section-number">7.2.1</span> 估计寿命分布</h3>
<p>从今天出生的孩子中随机选择一个样本，令 <span class="math inline">\(X\)</span> 表示样本中的孩子死亡时的年龄。若新生儿在其第 <span class="math inline">\(i\)</span> 年死亡，则 <span class="math inline">\(X = i\)</span>，<span class="math inline">\(i \geq 1\)</span>。为了估计 <span class="math inline">\(X\)</span> 的概率质量函数，令 <span class="math inline">\(\lambda_i\)</span> 表示一个新生儿在度过其第 <span class="math inline">\(i - 1\)</span> 年后在第 <span class="math inline">\(i\)</span> 年死亡的概率。即，</p>
<p><span class="math inline">\(\lambda_i = P\{X = i | X &gt; i - 1\} = \frac{P\{X = i\}}{P\{X &gt; i - 1\}}\)</span></p>
<p>另外，令</p>
<p><span class="math inline">\(s_i = 1 - \lambda_i = \frac{P\{X &gt; i\}}{P\{X &gt; i - 1\}}\)</span></p>
<p>表示新生儿在度过其前 <span class="math inline">\(i - 1\)</span> 年后在第 <span class="math inline">\(i\)</span> 年仍然健在的概率。我们称 <span class="math inline">\(\lambda_i\)</span> 为故障率（<em>failure rate</em>），称 <span class="math inline">\(s_i\)</span> 为生存率（<em>survival rate</em>）（个体在第 <span class="math inline">\(i\)</span> 年的生存概率）。现在，</p>
<p><span class="math inline">\(s_1 s_2 \cdots s_i = P\{X &gt; 1\} \frac{P\{X &gt; 2\}}{P\{X &gt; 1\}} \frac{P\{X &gt; 3\}}{P\{X &gt; 2\}} \cdots \frac{P\{X &gt; i\}}{P\{X &gt; i - 1\}} = P\{X &gt; i\}\)</span></p>
<p>因此，</p>
<p><span class="math inline">\(P\{X = n\} = P\{X &gt; n - 1\} \lambda_n = s_1 \cdots s_{n - 1} (1 - s_n)\)</span></p>
<p>因此，我们可以通过估计 <span class="math inline">\(s_i, i = 1, \ldots, n\)</span> 来估计 <span class="math inline">\(X\)</span> 的概率质量函数。<span class="math inline">\(s_i\)</span> 可以通过查看所有在第 <span class="math inline">\(i-1\)</span> 年健在的人在第 <span class="math inline">\(i\)</span> 年仍然健在的人来估计 <span class="math inline">\(s_i\)</span> 的值，其估计值 <span class="math inline">\(\hat{s}_i\)</span> 为他们今天仍然健在的比例。然后我们将使用 <span class="math inline">\(\hat{s}_1 \hat{s}_2 \cdots \hat{s}_{n - 1} (1 - \hat{s}_n)\)</span> 来估计 <span class="math inline">\(P\{X = n\}\)</span>。（注意，尽管我们在估计 <span class="math inline">\(s_i\)</span> 时使用了尽可能最新的数据，但我们对新生儿寿命的概率质量函数的估计是假设新生儿在达到年龄 <span class="math inline">\(i\)</span> 时的生存率与去年同年龄 <span class="math inline">\(i\)</span> 的人的生存率相同。）</p>
<p>在健康研究中，使用生存率来估计寿命分布也是很重要的，尤其是在信息不完全的情况下。例如，考虑一项研究，其中一种新药物被给与 12 名肺癌患者。假设一段时间后，我们得到了从开始服用新药到患者死亡的月份数：</p>
<p><span class="math inline">\(4, 7^*, 9, 11^*, 12, 3, 14^*, 1, 8, 7, 5, 3^*\)</span></p>
<p>其中 <span class="math inline">\(x\)</span> 表示患者在开始复用新药后的第 <span class="math inline">\(x\)</span> 个月死亡，而 <span class="math inline">\(x^*\)</span> 表示患者服药 <span class="math inline">\(x\)</span> 个月并且仍然健在。</p>
<p>令 <span class="math inline">\(X\)</span> 表示开始复用新药后的生存月份数，并令</p>
<p><span class="math inline">\(s_i = P(X &gt; i \mid X &gt; i - 1) = \frac{P(X &gt; i)}{P(X &gt; i - 1)}\)</span></p>
<p>为了估计 <span class="math inline">\(s_i\)</span>，即在第 <span class="math inline">\(i - 1\)</span> 个月存活的患者也将在第 <span class="math inline">\(i\)</span> 个月存活的概率，我们应该取那些在第 <span class="math inline">\(i\)</span> 个月开始服药并且在这个月存活的患者的比例。例如，因为 12 名患者中有 1 名在第 1 个月后死亡，所以 <span class="math inline">\(\hat{s}_1 = \frac{11}{12}\)</span>。因为所有在第 2 个月开始服药的 11 名患者都存活，所以 <span class="math inline">\(\hat{s}_2 = \frac{11}{11}\)</span>。因为 11 名患者中有 1 名在第 3 个月后死亡，所以 <span class="math inline">\(\hat{s}_3 = \frac{10}{11}\)</span>。因为 9 名患者中，有 1 名在第 4 个月后死亡，所以 <span class="math inline">\(\hat{s}_4 = \frac{8}{9}\)</span>。类似的推理适用于其他月份，于是得到以下生存率估计值：</p>
<p><span class="math inline">\(\hat{s}_1 = \frac{11}{12}\)</span></p>
<p><span class="math inline">\(\hat{s}_2 = \frac{11}{11}\)</span></p>
<p><span class="math inline">\(\hat{s}_3 = \frac{10}{11}\)</span></p>
<p><span class="math inline">\(\hat{s}_4 = \frac{8}{9}\)</span></p>
<p><span class="math inline">\(\hat{s}_5 = \frac{7}{8}\)</span></p>
<p><span class="math inline">\(\hat{s}_6 = \frac{7}{7}\)</span></p>
<p><span class="math inline">\(\hat{s}_7 = \frac{6}{7}\)</span></p>
<p><span class="math inline">\(\hat{s}_8 = \frac{4}{5}\)</span></p>
<p><span class="math inline">\(\hat{s}_9 = \frac{3}{4}\)</span></p>
<p><span class="math inline">\(\hat{s}_{10} = \frac{3}{3}\)</span></p>
<p><span class="math inline">\(\hat{s}_{11} = \frac{3}{3}\)</span></p>
<p><span class="math inline">\(\hat{s}_{12} = \frac{1}{2}\)</span></p>
<p><span class="math inline">\(\hat{s}_{13} = \frac{1}{1}\)</span></p>
<p><span class="math inline">\(\hat{s}_{14} = \frac{1}{1}\)</span></p>
<p>现在，我们可以使用 <span class="math inline">\(\prod_{i=1}^j \hat{s}_i\)</span> 来估计服用新药至少存活 <span class="math inline">\(j\)</span> 个月的概率，其中 <span class="math inline">\(j = 1, \ldots, 14\)</span>。例如，<span class="math inline">\(P\{X &gt; 6\}\)</span> 的估计是 <span class="math inline">\(\frac{35}{54}\)</span>。</p>
</section>
</section>
<section id="sec-7_3" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="sec-7_3"><span class="header-section-number">7.3</span> 区间估计</h2>
<p>假设 <span class="math inline">\(X_1, \ldots, X_n\)</span> 是来自均值 <span class="math inline">\(\mu\)</span> 未知但是方差 <span class="math inline">\(\sigma^2\)</span> 已知的正态分布总体的样本。根据 <a href="#sec-7_2" class="quarto-xref"><span>小节 7.2</span></a>，我们知道 <span class="math inline">\(\overline{X} = \frac{1}{n} \sum_{i=1}^{n} X_i\)</span> 是 <span class="math inline">\(\mu\)</span> 的最大似然估计。然而，我们不能指望样本均值 <span class="math inline">\(\overline{X}\)</span> 会正好等于 <span class="math inline">\(\mu\)</span>，我们反而更希望 <span class="math inline">\(\overline{X}\)</span> 会“接近” <span class="math inline">\(\mu\)</span>。因此，有时指定一个 <span class="math inline">\(\mu\)</span> 可能会落入的、我们有一定信心水平的区间，比一个点估计更有价值。为了得到这样的区间估计量，我们需要利用点估计量的概率分布。</p>
<p>如 <a href="../chapter_6/6.html#sec-6_2" class="quarto-xref"><span>小节 6.2</span></a> 所述，点估计量 <span class="math inline">\(\overline{X}\)</span> 服从均值为 <span class="math inline">\(\mu\)</span> 、方差为 <span class="math inline">\(\frac{\sigma^2}{n}\)</span> 的正态分布，因此：</p>
<p><span class="math inline">\(\frac{\overline{X} - \mu}{\frac{\sigma}{\sqrt{n}}} = \sqrt{n} \frac{(\overline{X} - \mu)}{\sigma}\)</span></p>
<p>服从标准正态分布。因此，</p>
<p><span class="math inline">\(P\bigg\{ -1.96 &lt; \sqrt{n} \frac{(\overline{X} - \mu)}{\sigma} &lt; 1.96 \bigg\} = 0.95\)</span></p>
<p>上式等价于：</p>
<p><span class="math inline">\(P\bigg\{ -1.96 \frac{\sigma}{\sqrt{n}} &lt; \overline{X} - \mu &lt; 1.96 \frac{\sigma}{\sqrt{n}} \bigg\} = 0.95\)</span></p>
<p>通过乘以 -1 得到等价的表述：</p>
<p><span class="math inline">\(P\bigg\{ -1.96 \frac{\sigma}{\sqrt{n}} &lt; \mu - \overline{X} &lt; 1.96 \frac{\sigma}{\sqrt{n}} \bigg\} = 0.95\)</span></p>
<p>即，</p>
<p><span class="math inline">\(P\bigg\{ \overline{X} - 1.96 \frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \overline{X} + 1.96 \frac{\sigma}{\sqrt{n}} \bigg\} = 0.95\)</span></p>
<p>也就是说，样本均值 <span class="math inline">\(\overline{X}\)</span> 有 95% 的概率落在与总体均值 <span class="math inline">\(\mu\)</span> 之间的距离小于 <span class="math inline">\(1.96 \frac{\sigma}{\sqrt{n}}\)</span> 的区间。如果我们现在观察样本，并且发现 <span class="math inline">\(\overline{X} = \overline{x}\)</span>，那么我们可以说，有 95% 的置信度使得</p>
<p><span id="eq-7_3_1"><span class="math display">\[
\overline{x} - 1.96 \frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \overline{x} + 1.96 \frac{\sigma}{\sqrt{n}}
\tag{7.4}\]</span></span></p>
<p>也就是说，我们“有95%的信心”断言总体的均值位于观测到的样本均值的 <span class="math inline">\(\pm 1.96\)</span> 个标准差的区间内。（需要注意到，<span class="math inline">\(\overline{X}\)</span> 的标准差为 <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>）。</p>
<p>我们称</p>
<p><span class="math inline">\(\left( \overline{x} - 1.96\frac{\sigma}{\sqrt{n}},\ \overline{x} + 1.96\frac{\sigma}{\sqrt{n}}\right)\)</span></p>
<p>为 <span class="math inline">\(\mu\)</span> 的 95% 置信区间估计（<em>95 percent confidence interval estimate of <span class="math inline">\(\mu\)</span> </em>）。</p>
<div id="exr-7_3_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.7</strong></span> 假设从 A 地发射一个信号 <span class="math inline">\(\mu\)</span> 到 B 地，在 B 接收到的信号的值服从均值为 <span class="math inline">\(\mu\)</span>、方差为 4 的正态分布。也就是说，如果发送的信号值为 <span class="math inline">\(\mu\)</span>，那么接收到的信号值是 <span class="math inline">\(\mu + N\)</span>，其中 <span class="math inline">\(N\)</span> 代表噪声是服从均值为 0、方差为 4 的正态分布。为了减少误差，相同的值会被发送 9 次。如果接收到的值分别是：</p>
<p>5、8.5、12、15、7、9、7.5、6.5、10.5</p>
<p>为 <span class="math inline">\(\mu\)</span> 构造一个 95% 置信区间。</p>
</div>
<div id="sol-7_3_a" class="proof solution">
<p><span class="proof-title"><em>解 7.7</em>. </span>因为 <span class="math inline">\(\overline{x} = \frac{81}{9} = 9\)</span>，因此，假设 B 地接收到的信号值之间是独立的，则 <span class="math inline">\(\mu\)</span> 的 95% 可信区间是：</p>
<p><span class="math inline">\(\left(9 - 1.96\frac{\sigma}{3},\ 9 + 1.96\frac{\sigma}{3}\right) = (7.69, 10.31)\)</span></p>
<p>因此，我们有 95% 的置信度确认真实的信号值将位于 7.69~10.31 的范围内。</p>
</div>
<p><a href="#eq-7_3_1" class="quarto-xref">式&nbsp;<span>7.4</span></a> 中的区间称为双边置信区间（<em>two-sided confidence interval</em>）。然而，有时我们感兴趣的是确定一个值，使得我们能以 95% 的置信度断言 <span class="math inline">\(\mu\)</span> 至少与该值一样大。</p>
<p>如果 <span class="math inline">\(Z\)</span> 是一个标准正态分布随机变量，则</p>
<p><span class="math inline">\(P\{Z \lt 1.645\} = 0.95\)</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注记
</div>
</div>
<div class="callout-body-container callout-body">
<p>在 R 中，可以使用 <code>qnorm()</code> 来得到该值：</p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.644854</code></pre>
</div>
</div>
</div>
</div>
<p>因此有：<span class="math inline">\(P\bigg\{\sqrt{n}\frac{(\overline{X} - \mu)}{\sigma} \lt 1.645\bigg\} = 0.95\)</span>，即</p>
<p><span class="math inline">\(P\bigg\{\overline{X} - 1.645\frac{\sigma}{\sqrt{n}} \lt \mu \bigg\} = 0.95\)</span></p>
<p>因此，<span class="math inline">\(\mu\)</span> 的 95% 单边上置信区间为：</p>
<p><span class="math inline">\(\left(\overline{x} - 1.645\frac{\sigma}{\sqrt{n}},\ \infty\right)\)</span>，其中 <span class="math inline">\(\overline{x}\)</span> 为观察到的数据的样本均值。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注记
</div>
</div>
<div class="callout-body-container callout-body">
<p>或者说，我们有 95% 的信心认为 <span class="math inline">\(\mu\)</span> 的值不可能低于 <span class="math inline">\(\overline{x} - 1.645\frac{\sigma}{\sqrt{n}}\)</span>。</p>
</div>
</div>
<p>类似的，我们可以得到单边下置信区间（<em>one-sided lower confidence interval</em>）。当我们观察到的数据的样本均值为 <span class="math inline">\(\overline{x}\)</span> 时，则 <span class="math inline">\(\mu\)</span> 的 95% 单边下置信区间为：</p>
<p><span class="math inline">\(\left(-\infty,\ \overline{x} + 1.645\frac{\sigma}{\sqrt{n}}\right)\)</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注记
</div>
</div>
<div class="callout-body-container callout-body">
<p>或者说，我们有 95% 的信心认为 <span class="math inline">\(\mu\)</span> 的值不可能大于 <span class="math inline">\(\overline{x} + 1.645\frac{\sigma}{\sqrt{n}}\)</span>。</p>
</div>
</div>
<div id="exr-7_3_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.8</strong></span> 确定 <a href="#exr-7_3_a" class="quarto-xref">习题&nbsp;<span>7.7</span></a> 中 <span class="math inline">\(\mu\)</span> 的 95% 置信区间估计的上下限。</p>
</div>
<div id="sol-7_3_b" class="proof solution">
<p><span class="proof-title"><em>解 7.8</em>. </span>因为：</p>
<p><span class="math inline">\(1.645 \frac{\sigma}{\sqrt{n}} = \frac{3.29}{3} = 1.097\)</span>，</p>
<p>所以，95% 上置信区间为：<span class="math inline">\((9 - 1.097, \infty) = (7.903, \infty)\)</span>。 95% 下置信区间为：<span class="math inline">\((-\infty, 9 + 1.097) = (-\infty, 10.097)\)</span>。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>我们也可以获得任何指定置信水平的置信区间。为此，回忆一下 <span class="math inline">\(z_{\alpha}\)</span> 的定义。<span class="math inline">\(z_{\alpha}\)</span> 是使得</p>
<p><span class="math display">\[
P\{Z &gt; z_{\alpha}\} = \alpha
\]</span></p>
<p>成立的值，其中 <span class="math inline">\(Z\)</span> 是标准正态随机变量。这意味着（见 <a href="#fig-7_1" class="quarto-xref">图&nbsp;<span>7.1</span></a>），对于任意 <span class="math inline">\(\alpha\)</span>，</p>
<p><span class="math display">\[
P\{-z_{\alpha/2} &lt; Z &lt; z_{\alpha/2}\} = 1 - \alpha
\]</span></p>
<div id="fig-7_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-7_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../images/chapter_7/f_7_1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-7_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;7.1: <span class="math inline">\(P\{-z_{\alpha/2} &lt; Z &lt; z_{\alpha/2}\} = 1 - \alpha\)</span>
</figcaption>
</figure>
</div>
<p>因此，我们有：</p>
<p><span class="math display">\[
P\left\{ -z_{\alpha/2} &lt; \sqrt{n}\left(\frac{\overline{X} - \mu}{\sigma}\right) &lt; z_{\alpha/2} \right\} = 1 - \alpha
\]</span></p>
<p>或</p>
<p><span class="math display">\[
P\left\{ -z_{\alpha/2} \frac{\sigma}{\sqrt{n}} &lt; \overline{X} - \mu &lt; z_{\alpha/2} \frac{\sigma}{\sqrt{n}} \right\} = 1 - \alpha
\]</span></p>
<p>或</p>
<p><span class="math display">\[
P \left\{-z_{\alpha/2} \frac{\sigma}{\sqrt{n}} &lt; \mu - \overline{X} &lt; z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\right\} = 1 - \alpha
\]</span></p>
<p>也就是说，</p>
<p><span class="math display">\[
P \left\{\overline{X} - z_{\alpha/2} \frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \overline{X} + z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\right\} = 1 - \alpha
\]</span></p>
<p>因此，<span class="math inline">\(\mu\)</span> 的 <span class="math inline">\(100(1−\alpha)％\)</span> 的双边置信区间是：</p>
<p><span class="math display">\[
\left(\overline{X} - z_{\alpha/2} \frac{\sigma}{\sqrt{n}}, \overline{X} + z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\right)
\]</span></p>
<p>其中 <span class="math inline">\(\overline{X}\)</span> 是观测样本均值。</p>
<p>同样地，对于一个标准正态随机变量 <span class="math inline">\(Z = \sqrt{n} \frac{(\overline{X} - \mu)}{\sigma}\)</span>，有 <span class="math inline">\(P\{Z &gt; z_{\alpha}\} = \alpha\)</span> 和 <span class="math inline">\(P\{Z &lt; -z_{\alpha}\} = \alpha\)</span>。</p>
<p>因此，我们可以得到任意置信水平的单边置信区间。具体来说，<span class="math inline">\(\mu\)</span> 的 <span class="math inline">\(100(1−\alpha)％\)</span> 单边上置信区间和 <span class="math inline">\(100(1−\alpha)％\)</span> 单边下置信区间分别为：</p>
<ul>
<li><span class="math inline">\(\left(\overline{X} - z_{\alpha} \frac{\sigma}{\sqrt{n}}, \infty\right)\)</span></li>
<li><span class="math inline">\(\left(-\infty, \overline{X} + z_{\alpha} \frac{\sigma}{\sqrt{n}}\right)\)</span></li>
</ul>
<div id="exr-7_3_c" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.9</strong></span> 使用 <a href="#exr-7_3_a" class="quarto-xref">习题&nbsp;<span>7.7</span></a> 中的数据来计算 <span class="math inline">\(\mu\)</span> 的 99% 置信区间估计，以及其 99% 单边上、下置信区间。</p>
</div>
<div id="sol-7_3_c" class="proof solution">
<p><span class="proof-title"><em>解 7.9</em>. </span>由于 <span class="math inline">\(z_{0.005} = 2.58\)</span>，且 <span class="math inline">\(2.58 \frac{\sigma}{\sqrt{n}} = \frac{5.16}{3} = 1.72\)</span>，</p>
<p>因此，<span class="math inline">\(\mu\)</span> 的 99% 置信区间为 <span class="math inline">\(9 \pm 1.72\)</span>，也就是说，99% 置信区间估计为 <span class="math inline">\((7.28, 10.72)\)</span>。</p>
<p>此外，由于 <span class="math inline">\(z_{0.01} = 2.33\)</span>，因此，99% 上置信区间为 <span class="math inline">\((9 - 2.33(\frac{2}{3}), \infty) = (7.447, \infty)\)</span>。</p>
<p>同样地，99% 下置信区间为 <span class="math inline">\((-\infty, 9 + 2.33(\frac{2}{3})) = (-\infty, 10.553)\)</span>。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>有时候，我们对某一置信水平（比如 <span class="math inline">\(1−\alpha\)</span>）的双边置信区间感兴趣，但问题是如何选择样本量 <span class="math inline">\(n\)</span> 才能使得置信区间为某个指定的大小。例如，假设我们要计算一个长度为 0.1 的区间，并且能断言该区间以 99% 的置信度包含 <span class="math inline">\(\mu\)</span>，此时我们需要多大的样本量 <span class="math inline">\(n\)</span>？</p>
<p>由于 <span class="math inline">\(z_{0.005} = 2.58\)</span>，从样本量为 <span class="math inline">\(n\)</span> 的样本中得到的 <span class="math inline">\(\mu\)</span> 的 99% 置信区间是：</p>
<p><span class="math inline">\(\left( \overline{X} - 2.58 \frac{\sigma}{\sqrt{n}}, \overline{X} + 2.58 \frac{\sigma}{\sqrt{n}} \right)\)</span></p>
<p>因此，置信区间的长度为：<span class="math inline">\(5.16 \frac{\sigma}{\sqrt{n}}\)</span>。因此，要使置信区间的长度等于 0.1，我们必须让 <span class="math inline">\(5.16 \frac{\sigma}{\sqrt{n}} = 0.1\)</span>，即：<span class="math inline">\(n = (51.6 \sigma)^2\)</span>。</p>
<div class="callout callout-style-default callout-tip callout-titled" title="注意">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注意
</div>
</div>
<div class="callout-body-container callout-body">
<p>对“<span class="math inline">\(100(1−\alpha)％\)</span> 置信区间”的解释可能会令人困惑。需要注意的是，我们并不是在断言 <span class="math inline">\(\mu \in \left( \overline{X} - 1.96 \frac{\sigma}{\sqrt{n}}, \overline{X} + 1.96 \frac{\sigma}{\sqrt{n}} \right)\)</span> 的概率为 0.95，这主要是因为在如上的断言中并没有涉及到任何 <strong>随机变量</strong>。我们所断言的是，使用这种方法得到的区间会有 95% 的概率包含 <span class="math inline">\(\mu\)</span>。换句话说，观测到数据之前，我们可以断言该区间有 0.95 的概率将包含 <span class="math inline">\(\mu\)</span>；而在观测到数据之后，我们只能断言结果区间确实以 0.95 的置信度包含 <span class="math inline">\(\mu\)</span>。</p>
</div>
</div>
<div id="exr-7_3_d" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.10</strong></span> 根据以往的经验，在商业孵化场中养殖的三文鱼的重量符合正态分布，其均值会随季节的不同而不同，但其标准差固定为 0.3 磅。如果我们想在 95% 的置信度下，估计当前季节三文鱼的平均重量，并且估计的误差在 <span class="math inline">\(\pm 0.1\)</span> 磅以内，需要多大的样本量？</p>
</div>
<div id="sol-7_3_d" class="proof solution">
<p><span class="proof-title"><em>解 7.10</em>. </span>基于样本量 <span class="math inline">\(n\)</span> 的未知均值 <span class="math inline">\(\mu\)</span> 的 95% 置信区间估计为：</p>
<p><span class="math inline">\(\mu \in \left( \overline{X} - 1.96 \frac{\sigma}{\sqrt{n}}, \overline{X} + 1.96 \frac{\sigma}{\sqrt{n}} \right)\)</span></p>
<p>因为估计区间中的任何一个估计值都在 <span class="math inline">\(\overline{X}\)</span> 的 <span class="math inline">\(1.96(\sigma / \sqrt{n}) = \frac{0.588}{\sqrt{n}}\)</span> 以内，因此我们可以 95% 地确信，<span class="math inline">\(\overline{X}\)</span> 在 <span class="math inline">\(\mu\)</span> 的 0.1 以内的前提是：</p>
<p><span class="math inline">\(\frac{0.588}{\sqrt{n}} \leq 0.1\)</span></p>
<p>也就是说 <span class="math inline">\(\sqrt{n} \geq 5.88\)</span>，即 <span class="math inline">\(n \geq 34.57\)</span>。也就是说，样本量为 35 或更大就足够了。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
<section id="sec-7_3_1" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="sec-7_3_1"><span class="header-section-number">7.3.1</span> 方差未知时正态分布均值的置信区间</h3>
<div id="fig-f_7_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-f_7_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../images/chapter_7/f_7_2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-f_7_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;7.2: t 分布的概率密度函数
</figcaption>
</figure>
</div>
<p>假设 <span class="math inline">\(X_1, ..., X_n\)</span> 是来自均值 <span class="math inline">\(\mu\)</span>、方差 <span class="math inline">\(\sigma^2\)</span> 均未知的正态分布的样本，我们希望计算 <span class="math inline">\(\mu\)</span> 的 <span class="math inline">\(100(1-\alpha)\%\)</span> 置信区间估计。当方差 <span class="math inline">\(\sigma^2\)</span> 未知时，我们不能再认为 <span class="math inline">\(\sqrt{n} \frac{\overline{X} - \mu}{\sigma}\)</span> 是一个标准正态分布的 <strong>随机变量</strong>。但是，令 <span class="math inline">\(S^2 = \sum_{i=1}^{n}(X_i - \overline{X})^2 / (n-1)\)</span> 为样本方差，那么根据 <a href="../chapter_6/6.html#cor-6_5_2" class="quarto-xref">推论&nbsp;<span>6.1</span></a> 可知</p>
<p><span class="math inline">\(\sqrt{n} \frac{\overline{X} - \mu}{S}\)</span></p>
<p>符合自由度为 <span class="math inline">\(n-1\)</span> 的 <span class="math inline">\(t\)</span> 分布。因此，根据 <span class="math inline">\(t\)</span> 分布的概率密度函数的对称性（<a href="#fig-f_7_2" class="quarto-xref">图&nbsp;<span>7.2</span></a>），对于任何 <span class="math inline">\(\alpha \in (0, 1/2)\)</span> ，我们都有</p>
<p><span class="math inline">\(P\left\{ -t_{\alpha/2, n-1} &lt; \sqrt{n} \frac{\overline{X} - \mu}{S} &lt; t_{\alpha/2, n-1} \right\} = 1 - \alpha\)</span></p>
<p>即</p>
<p><span class="math inline">\(P\left\{ -t_{\alpha/2, n-1} \frac{S}{\sqrt{n}} &lt; \overline{X} - \mu &lt; t_{\alpha/2, n-1} \frac{S}{\sqrt{n}} \right\} = 1 - \alpha\)</span></p>
<p>于是，得到</p>
<p><span class="math inline">\(P\left\{ \overline{X} - t_{\alpha/2, n-1} \frac{S}{\sqrt{n}} &lt; \mu &lt; \overline{X} + t_{\alpha/2, n-1} \frac{S}{\sqrt{n}} \right\} = 1 - \alpha\)</span></p>
<p>因此，根据观测到的样本数据 <span class="math inline">\(\overline{X} = \overline{x}\)</span> 且 <span class="math inline">\(S = s\)</span> ，我们可以说“ <span class="math inline">\(\mu\)</span> 的 <span class="math inline">\(100(1-\alpha)\%\)</span> 置信度区间估计”为：</p>
<p><span class="math inline">\(\mu \in \left( \overline{x} - t_{\alpha/2, n-1} \frac{s}{\sqrt{n}}, \overline{x} + t_{\alpha/2, n-1} \frac{s}{\sqrt{n}} \right)\)</span></p>
<div id="exr-7_3_e" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.11</strong></span> 让我们再次考虑 <a href="#exr-7_3_a" class="quarto-xref">习题&nbsp;<span>7.7</span></a>，但现在假设在 A 地传输值为 <span class="math inline">\(\mu\)</span> 的信号时，在 B 地接收到的值符合均值为 <span class="math inline">\(\mu\)</span>、方差为 <span class="math inline">\(\sigma^2\)</span> 的正态分布，但是 <span class="math inline">\(\sigma^2\)</span> 未知。如 <a href="#exr-7_3_a" class="quarto-xref">习题&nbsp;<span>7.7</span></a> 所示，如果连续发送 9 个信号，B 地接收到的信号值分别为：</p>
<p>5、8.5、12、15、7、9、7.5、6.5、10.5</p>
<p>请计算 <span class="math inline">\(\mu\)</span> 的 95% 置信区间。</p>
</div>
<div id="sol-7_3_e" class="proof solution">
<p><span class="proof-title"><em>解 7.11</em>. </span>样本均值 <span class="math inline">\(\overline{x} = 9\)</span>，样本标准差 <span class="math inline">\(s^2 = \frac{\sum(x_i - \overline{x})^2}{8} = 9.5\)</span>，即 <span class="math inline">\(s = 3.082\)</span>。</p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.025</span>, <span class="at">df=</span><span class="dv">8</span>, <span class="at">lower.tail=</span><span class="cn">FALSE</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.306004</code></pre>
</div>
</div>
<p>因为 <span class="math inline">\(t_{0.025, 8} = 2.306\)</span>，因此，<span class="math inline">\(\mu\)</span> 的 95% 置信区间为：</p>
<p><span class="math inline">\(\bigg(9-2.306 \frac{3.082}{3}, 9+2.306 \frac{3.082}{3}\bigg) = (6.63, 11.37)\)</span></p>
<p>可见，如上的结果比 <a href="#sol-7_3_a" class="quarto-xref">Solution&nbsp;<span>7.7</span></a> 中得到的区间要大，这里主要有两个原因：</p>
<ul>
<li>最主要的原因是，我们在这里对方差的估计值比 <a href="#sol-7_3_a" class="quarto-xref">Solution&nbsp;<span>7.7</span></a> 中的方差更大。也就是说，在 <a href="#sol-7_3_a" class="quarto-xref">Solution&nbsp;<span>7.7</span></a> 中，我们假设 <span class="math inline">\(\sigma^2\)</span> 已知并等于 4；而在本例中，我们假设方差是未知的，并且我们的估计值为 9.5。更大的方差导致我们得到了一个更大范围的置信区间。</li>
<li>事实上，即使我们估计的 <span class="math inline">\(\sigma^2\)</span> 依旧是 4，因为方差未知，我们仍然需要利用 <span class="math inline">\(t\)</span> 分布来估计方差。因为 <span class="math inline">\(t\)</span> 分布的方差比标准正态分布的方差更大，因此获得的区间范围也会比标准正态分布更宽。例如，如果 <span class="math inline">\(\overline{x} = 9\)</span> 且 <span class="math inline">\(s^2 = 4\)</span>，那么我们的置信区间将是：</li>
</ul>
<p><span class="math inline">\((9 - 2.306 \cdot \frac{2}{3}, 9 + 2.306 \cdot \frac{2}{3}) = (7.46, 10.54)\)</span></p>
<p>这显然比 <a href="#sol-7_3_a" class="quarto-xref">Solution&nbsp;<span>7.7</span></a> 中的 <span class="math inline">\((7.69, 10.31)\)</span> 的区间更大。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="注意">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注意
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>当 <span class="math inline">\(\sigma\)</span> 已知时，<span class="math inline">\(\mu\)</span> 的置信区间基于以下事实：<span class="math inline">\(\sqrt{n}(\overline{X} - \mu)/\sigma\)</span> 服从标准正态分布。当 <span class="math inline">\(\sigma\)</span> 未知时，可以利用样本标准差 <span class="math inline">\(S\)</span> 来估计总体标准差 <span class="math inline">\(\sigma\)</span>，然后利用以下事实——<span class="math inline">\(\sqrt{n}(\overline{X} - \mu)/S\)</span> 服从自由度为 <span class="math inline">\(n - 1\)</span> 的 <span class="math inline">\(t\)</span> 分布——来计算 <span class="math inline">\(\mu\)</span> 的置信区间估计。</p></li>
<li><p>当总体方差未知时，<span class="math inline">\(\mu\)</span> 的 <span class="math inline">\(100(1-2\alpha)\%\)</span> 置信区间的长度并不总是比方差已知时的更长。当 <span class="math inline">\(\sigma\)</span> 已知时，置信区间估计的长度是 <span class="math inline">\(2z_{\alpha}\frac{\sigma}{\sqrt{n}}\)</span>；而当 <span class="math inline">\(\sigma\)</span> 未知时，其长度是 <span class="math inline">\(2t_{\alpha, n-1}\frac{S}{\sqrt{n}}\)</span>。并且，确实存在如下的可能性：样本标准差 <span class="math inline">\(S\)</span> 远小于总体标准差 <span class="math inline">\(\sigma\)</span>。但是，我们依然可以证明，当总体方差未知时，<span class="math inline">\(\mu\)</span> 的置信区间的平均长度会更长。也就是说，可以证明：</p>
<p><span class="math inline">\(t_{\alpha, n-1} E[S] \geq z_{\alpha}\sigma\)</span></p>
<p>我们会在 <a href="../chapter_14/14.html" class="quarto-xref"><span>章节 14</span></a> 中计算 <span class="math inline">\(E[S]\)</span>，例如：</p>
<p><span class="math inline">\(E[S] = \begin{cases}0.94\sigma, \quad n = 5 &amp; \\0.97\sigma, \quad n = 9 &amp;\end{cases}\)</span></p>
<p>因为 <span class="math inline">\(z_{0.025} = 1.96\)</span>， <span class="math inline">\(t_{0.025,4} = 2.78\)</span>， <span class="math inline">\(t_{0.025,8} = 2.31\)</span>，所以样本量为 5 时，当方差已知时，95% 的置信区间长度是 <span class="math inline">\(2 \times 1.96 \times \frac{\sigma}{5} = 1.75 \sigma\)</span>；而当方差未知时，其预期长度是 <span class="math inline">\(2 \times 2.78 \times \frac{0.94\sigma}{\sqrt{5}} = 2.34\sigma\)</span>。因此可以看出，当方差未知时，置信区间的长度增加了 33.7%。如果样本量为 9，则方差已知和方差未知时的 95% 置信区间长度分别为 <span class="math inline">\(1.31\sigma\)</span> 和 <span class="math inline">\(1.49\sigma\)</span>，置信区间长度增加了 13.7%。</p></li>
</ul>
</div>
</div>
<p>当总体方差未知时，我们可以得到 <span class="math inline">\(\mu\)</span> 的单边上置信区间估计为：</p>
<p><span class="math inline">\(P\bigg\{\sqrt{n}\frac{\overline{X} - \mu}{S} \lt t_{\alpha, n-1}\bigg\} = 1 - \alpha\)</span>，即</p>
<p><span class="math inline">\(P\bigg\{\overline{X} - \mu \lt \frac{S}{\sqrt{n}}t_{\alpha, n-1} \bigg\} = 1 - \alpha\)</span>，即</p>
<p><span class="math inline">\(P\bigg\{\mu \gt \overline{X} - \frac{S}{\sqrt{n}}t_{\alpha, n-1} \bigg\} = 1 - \alpha\)</span></p>
<p>因此，对于观察到的样本数据而言，<span class="math inline">\(\overline{X} = \overline{x}\)</span>，<span class="math inline">\(S=s\)</span>，我们有“有 <span class="math inline">\(100(1-\alpha)\%\)</span> 的信心” 可以断言：</p>
<p><span class="math inline">\(\mu \in \bigg(\overline{x} - \frac{S}{\sqrt{n}}t_{\alpha, n-1}, \infty\bigg)\)</span></p>
<p>同理，我们可以得到总体方差未知时，<span class="math inline">\(\mu\)</span> 的单边下置信区间估计为：</p>
<p><span class="math inline">\(\mu \in \bigg(-\infty, \overline{x} + \frac{S}{\sqrt{n}}t_{\alpha, n-1}\bigg)\)</span></p>
<p>我们可以使用 R 来获得置信区间。要得到 <span class="math inline">\(x_1, ..., x_n\)</span> 的 <span class="math inline">\(100(1-\alpha)\%\)</span> 置信区间，我们可以在 R 中执行如下操作：</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">c</span>(x1,...,xn)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">mean</span>(d) − <span class="fu">qt</span>(<span class="dv">1</span>−α<span class="sc">/</span><span class="dv">2</span>, n−<span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(d) <span class="sc">/</span> n)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">mean</span>(d) <span class="sc">+</span> <span class="fu">qt</span>(<span class="dv">1</span>−α<span class="sc">/</span><span class="dv">2</span>, n−<span class="dv">1</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(d) <span class="sc">/</span> n) </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(l, u)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>例如，在正态分布的总体方差未知时，我们要计算该正态分布的均值的 99% 置信区间，其中数据样本为：</p>
<p>5, 9, 12, 8.6, 7.2, 13, 9.5</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">9</span>, <span class="dv">12</span>, <span class="fl">8.6</span>, <span class="fl">7.2</span>, <span class="dv">13</span>, <span class="fl">9.5</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">mean</span>(d) <span class="sc">-</span> <span class="fu">qt</span>(.<span class="dv">995</span>, <span class="dv">6</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(d) <span class="sc">/</span> <span class="dv">7</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">mean</span>(d) <span class="sc">+</span> <span class="fu">qt</span>(.<span class="dv">995</span>, <span class="dv">6</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(d) <span class="sc">/</span> <span class="dv">7</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(l, u)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">9</span>, <span class="dv">12</span>, <span class="fl">8.6</span>, <span class="fl">7.2</span>, <span class="dv">13</span>, <span class="fl">9.5</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">mean</span>(d) <span class="sc">-</span> <span class="fu">qt</span>(.<span class="dv">995</span>, <span class="dv">6</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(d) <span class="sc">/</span> <span class="dv">7</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">mean</span>(d) <span class="sc">+</span> <span class="fu">qt</span>(.<span class="dv">995</span>, <span class="dv">6</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(d) <span class="sc">/</span> <span class="dv">7</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(l, u)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  5.373463 12.997965</code></pre>
</div>
</div>
<div id="exr-7_3_f" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.12</strong></span> 从某健身俱乐部的成员中随机选择了 15 名成员并得到了如下的静息心率数据：</p>
<p>54、63、58、72、49、92、70、73、69、104、48、66、80、64、77</p>
<p>确定该健身俱乐部成员的平均静息心率的 95% 置信区间和 95% 上置信区间。</p>
</div>
<div id="sol-7_3_f" class="proof solution">
<p><span class="proof-title"><em>解 7.12</em>. </span>双边 95% 置信区间为：<span class="math inline">\((60.86694, 77.66640)\)</span></p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">54</span>, <span class="dv">63</span>, <span class="dv">58</span>, <span class="dv">72</span>, <span class="dv">49</span>, <span class="dv">92</span>, <span class="dv">70</span>, <span class="dv">73</span>, <span class="dv">69</span>, <span class="dv">104</span>, <span class="dv">48</span>, <span class="dv">66</span>, <span class="dv">80</span>, <span class="dv">64</span>, <span class="dv">77</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">mean</span>(d) <span class="sc">-</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="dv">14</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(d) <span class="sc">/</span> <span class="dv">15</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">mean</span>(d) <span class="sc">+</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="dv">14</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(d) <span class="sc">/</span> <span class="dv">15</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(l, u)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 60.86694 77.66640</code></pre>
</div>
</div>
<p>单边 95% 上置信区间为：<span class="math inline">\((62.36876, \infty)\)</span></p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">54</span>, <span class="dv">63</span>, <span class="dv">58</span>, <span class="dv">72</span>, <span class="dv">49</span>, <span class="dv">92</span>, <span class="dv">70</span>, <span class="dv">73</span>, <span class="dv">69</span>, <span class="dv">104</span>, <span class="dv">48</span>, <span class="dv">66</span>, <span class="dv">80</span>, <span class="dv">64</span>, <span class="dv">77</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ub <span class="ot">&lt;-</span> <span class="fu">mean</span>(d) <span class="sc">-</span> <span class="fu">qt</span>(.<span class="dv">95</span>, <span class="dv">14</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(d) <span class="sc">/</span> <span class="dv">15</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>ub</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 62.36876</code></pre>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>我们假定总体分布是正态分布，然后推导出总体均值 <span class="math inline">\(\mu\)</span> 的 <span class="math inline">\(100(1-\alpha) \%\)</span> 置信区间。然而，即使总体不是正态分布，根据中心极限定理（<a href="../chapter_6/6.html#thm-6_3_1" class="quarto-xref">定理&nbsp;<span>6.1</span></a>），如果样本量足够大，那么 <span class="math inline">\(\sqrt{n}(\overline{X} - \mu)/\sigma\)</span> 将近似服从正态分布，并且 <span class="math inline">\(\sqrt{n}(\overline{X} - \mu)/S\)</span> 将近似服从 <span class="math inline">\(t\)</span> 分布，因此 <span class="math inline">\(\mu\)</span> 的区间估计仍将近似于 <span class="math inline">\(100(1-\alpha) \%\)</span> 置信区间。</p>
<div id="exm-7_3_g" class="theorem example">
<p><span class="theorem-title"><strong>例 7.2</strong></span> <strong>统计模拟法</strong>（<em>simulation</em>）提供了一种强大的方法以计算一维积分和多维积分。例如，设 <span class="math inline">\(f\)</span> 是一个 <span class="math inline">\(r\)</span> 维向量 <span class="math inline">\((y_1, y_2, \ldots, y_r)\)</span> 的函数，并且假设我们想要对如下的 进行估计：</p>
<p><span class="math inline">\(\theta = \int_{0}^{1} \int_{0}^{1} \cdots \int_{0}^{1} f(y_1, y_2, \ldots, y_r) dy_1 dy_2 \ldots dy_r\)</span></p>
<p>如果 <span class="math inline">\(U_1, U_2, \ldots, U_r\)</span> 是 <span class="math inline">\((0, 1)\)</span> 上的、相互独立的均匀分布随机变量，那么</p>
<p><span class="math inline">\(\theta = E[f(U_1, U_2, \ldots, U_r)]\)</span></p>
<p>现在，我们可以（通过所谓的伪随机数）在计算机上近似模拟独立 <span class="math inline">\((0, 1)\)</span> 均匀分布随机变量的值。如果我们生成一个 <span class="math inline">\(r\)</span> 维向量，并在该向量上计算 <span class="math inline">\(f\)</span>，那么由此得到的值——<span class="math inline">\(X_1\)</span>——将是均值为 <span class="math inline">\(\theta\)</span> 的随机变量。如果我们重复这个过程，那么我们得到另一个值——<span class="math inline">\(X_2\)</span>——将与 <span class="math inline">\(X_1\)</span> 的分布相同。继续下去，我们可以生成一个序列 <span class="math inline">\(X_1, X_2, \ldots, X_n\)</span>，他们是独立、同分布的随机变量，并且均值为 <span class="math inline">\(\theta\)</span>。然后我们就可以利用 <span class="math inline">\(X_1, X_2, \ldots, X_n\)</span> 的观察值来估计 <span class="math inline">\(\theta\)</span>。我们将这种近似积分的方法称为 <strong>蒙特卡罗模拟</strong>（<em>Monte Carlo simulation</em>）。</p>
<p>例如，假设我们想要估计一维积分：</p>
<p><span class="math inline">\(\theta = \int_{0}^{1} \sqrt{1 - y^2} dy = E[\sqrt{1 - U^2}]\)</span></p>
<p>其中，<span class="math inline">\(U\)</span> 是一个 <span class="math inline">\((0, 1)\)</span> 均匀随机变量。</p>
<p>为此，设 <span class="math inline">\(U_1, \ldots, U_{100}\)</span> 为 <span class="math inline">\((0, 1)\)</span> 上的独立均匀随机变量，并设</p>
<p><span class="math inline">\(X_i = \sqrt{1 - U_i^2}, \quad i = 1, \ldots, 100\)</span></p>
<p>通过这种方式，我们生成了一个均值为 <span class="math inline">\(\theta\)</span> 的 100 个随机变量的样本。假设计算机生成的 <span class="math inline">\(U_1, \ldots, U_{100}\)</span> 的随机值所得到的样本 <span class="math inline">\(X_1, \ldots, X_{100}\)</span> 的样本均值为 0.786、样本标准差为 0.03。</p>
<p>因为 <span class="math inline">\(t_{0.025, 99} = 1.985\)</span>，因此 <span class="math inline">\(\theta\)</span> 的 95% 置信区间为：</p>
<p><span class="math inline">\(0.786 \pm 1.985 \cdot (0.003)\)</span></p>
<p>因此，我们有 95% 的信心断言，<span class="math inline">\(\theta\)</span>（实际为 <span class="math inline">\(\frac{\pi}{4}\)</span>） 位于区间 <span class="math inline">\((0.780, 0.792)\)</span> 中。<span class="math inline">\(\blacksquare\)</span></p>
</div>
</section>
<section id="sec-7_3_2" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="sec-7_3_2"><span class="header-section-number">7.3.2</span> 预测区间</h3>
<p>假设 <span class="math inline">\(X_1, \ldots, X_n, X_{n+1}\)</span> 是来自均值 <span class="math inline">\(\mu\)</span> 方差 <span class="math inline">\(\sigma\)</span> 均未知的正态分布的样本。进一步假设 <span class="math inline">\(X_1, \ldots, X_n\)</span> 的值是已知的，并且我们希望用它们来预测 <span class="math inline">\(X_{n+1}\)</span> 的值。</p>
<p>首先，如果均值 <span class="math inline">\(\mu\)</span> 是已知的，那么 <span class="math inline">\(\mu\)</span> 就是 <span class="math inline">\(X_{n+1}\)</span> 的天然预测器。但是由于 <span class="math inline">\(\mu\)</span> 未知，因此在观察到 <span class="math inline">\(X_1, \ldots, X_n\)</span> 后，使用这些观测值的平均值作为 <span class="math inline">\(X_{n+1}\)</span> 的预测值是合理的。也就是说，我们应该使用 <span class="math inline">\(\overline{X}_n = \sum_{i=1}^n X_i / n\)</span> 作为 <span class="math inline">\(X_{n+1}\)</span> 的预测值。</p>
<p>现在假设我们想要确定一个区间，在这个区间内，以某种置信度预测 <span class="math inline">\(X_{n+1}\)</span> 将位于该区间中。为了获得这样的预测区间，注意到 <span class="math inline">\(\overline{X}_n\)</span> 是具有均值 <span class="math inline">\(\mu\)</span> 和方差 <span class="math inline">\(\sigma^2 / n\)</span> 的正态分布，并且它与 <span class="math inline">\(X_{n+1}\)</span>（均值为 <span class="math inline">\(\mu\)</span>、方差为 <span class="math inline">\(\sigma^2\)</span>）是独立的。由此可以得出 <span class="math inline">\(X_{n+1} - \overline{X}_n\)</span> 的均值为 0、方差为 <span class="math inline">\(\sigma^2 / n + \sigma^2\)</span>。因此，</p>
<p><span class="math inline">\(\frac{X_{n+1} - \overline{X}_n}{\sigma \sqrt{1 + 1/n}}\)</span></p>
<p>服从标准正态分布。</p>
<p>由于 <span class="math inline">\(\frac{X_{n+1} - \overline{X}_n}{\sigma \sqrt{1 + 1/n}}\)</span> 与 <span class="math inline">\(S_n^2 = \sum_{i=1}^n (X_i - \overline{X}_n)^2 / (n - 1)\)</span> 独立，从而根据 <a href="../chapter_6/6.html#cor-6_5_2" class="quarto-xref">推论&nbsp;<span>6.1</span></a> 可知，将 <span class="math inline">\(\sigma\)</span> 替换为其估计量 <span class="math inline">\(S_n\)</span> 后的表达式是自由度为 <span class="math inline">\(n - 1\)</span> 的 <span class="math inline">\(t\)</span> 分布，即，</p>
<p><span class="math inline">\(\frac{X_{n+1} - \overline{X}_n}{S_n \sqrt{1 + 1/n}}\)</span></p>
<p>是自由度为 <span class="math inline">\(n - 1\)</span> 的 <span class="math inline">\(t\)</span> 分布随机变量。因此，对于任何 <span class="math inline">\(\alpha \in (0, 1/2)\)</span>，</p>
<p><span class="math inline">\(P \bigg\{ -t_{\alpha/2, n-1} &lt; \frac{X_{n+1} - \overline{X}_n}{S_n \sqrt{1 + 1/n}} &lt; t_{\alpha/2, n-1} \bigg\} = 1 - \alpha\)</span></p>
<p>即</p>
<p><span class="math inline">\(P \bigg\{ \overline{X}_n - t_{\alpha/2, n-1} S_n \sqrt{1 + 1/n} &lt; X_{n+1} &lt; \overline{X}_n + t_{\alpha/2, n-1} S_n \sqrt{1 + 1/n} \bigg\}\)</span></p>
<p>因此，如果 <span class="math inline">\(\overline{X}_n\)</span> 和 <span class="math inline">\(S_n\)</span> 的样本观察值分别是 <span class="math inline">\(\overline{x}_n\)</span> 和 <span class="math inline">\(s_n\)</span>，那么我们可以在 <span class="math inline">\(100(1 - \alpha) \%\)</span> 的置信度下预测 <span class="math inline">\(X_{n+1}\)</span> 将位于 <span class="math inline">\(\overline{x}_n - t_{\alpha/2, n-1} s_n \sqrt{1 + 1/n}\)</span> 和 <span class="math inline">\(\overline{x}_n + t_{\alpha/2, n-1} s_n \sqrt{1 + 1/n}\)</span> 之间。也就是说，在 <span class="math inline">\(100(1 - \alpha) \%\)</span> 的置信度下，我们可以预测</p>
<p><span class="math display">\[
X_{n+1} \in \left( \overline{x}_n - t_{\alpha/2, n-1} s_n \sqrt{1 + 1/n}, \overline{x}_n + t_{\alpha/2, n-1} s_n \sqrt{1 + 1/n} \right)
\]</span></p>
<div id="exr-7_3_h" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.13</strong></span> 以下数据是过去 7 天的步数：</p>
<p>6822, 5333, 7420, 7432, 6252, 7005, 6752</p>
<p>假设每天的步数可以认为服从正态分布，给出一个预测区间，使得在 95% 的置信度下，明天的步数将位于该预测区间。</p>
</div>
<div id="sol-7_3_h" class="proof solution">
<p><span class="proof-title"><em>解 7.13</em>. </span>计算这 7 个数据值的样本均值和样本方差： <span class="math inline">\(\overline{X}_7 = 6716.57 , \quad S_7 = 733.97\)</span></p>
<p>因为 <span class="math inline">\(t_{0.025, 6} = 2.447\)</span>，并且 <span class="math inline">\(2.4447 \cdot 733.97 \sqrt{1 + 1/7} = 1920.03\)</span>，我们可以在 95% 的置信度下预测明天的步数将在 6716.57 - 1920.03 和 6716.57 + 1920.03 之间。也就是说，在 95% 的置信度下，<span class="math inline">\(X_8\)</span> 将位于区间 (4796.54, 8636.60) 内。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
</section>
<section id="sec-7_3_3" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="sec-7_3_3"><span class="header-section-number">7.3.3</span> 正态分布方差的置信区间</h3>
<p>如果 <span class="math inline">\(X_1, \ldots, X_n\)</span> 是来自均值 <span class="math inline">\(\mu\)</span> 和方差 <span class="math inline">\(\sigma^2\)</span> 均未知的正态分布的样本，那么我们可以根据以下事实（<a href="../chapter_6/6.html#thm-6_5_1" class="quarto-xref">定理&nbsp;<span>6.2</span></a>）构造 <span class="math inline">\(\sigma^2\)</span> 的置信区间：</p>
<p><span class="math inline">\((n-1)\frac{S^2}{\sigma^2} \sim \chi^2_{n-1}\)</span></p>
<p>因此，</p>
<p><span class="math inline">\(P \left\{ \chi^2_{1-\alpha/2, n-1} \leq (n-1)\frac{S^2}{\sigma^2} \leq \chi^2_{\alpha/2, n-1} \right\} = 1-\alpha\)</span></p>
<p>即，</p>
<p><span class="math inline">\(P \left\{ \frac{(n-1)S^2}{\chi^2_{\alpha/2, n-1}} \leq \sigma^2 \leq \frac{(n-1)S^2}{\chi^2_{1-\alpha/2, n-1}} \right\} = 1-\alpha\)</span></p>
<p>因此，当 <span class="math inline">\(S^2 = s^2\)</span> 时，<span class="math inline">\(\sigma^2\)</span> 的 <span class="math inline">\(100(1 - \alpha) \%\)</span> 置信区间为：</p>
<p><span class="math inline">\(\left( \frac{(n - 1)s^2}{\chi^2_{\alpha/2, n-1}}, \frac{(n - 1)s^2}{\chi^2_{1-\alpha/2, n-1}} \right)\)</span></p>
<div id="exr-7_3_i" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.14</strong></span> 我们希望一个标准化流水线生产的垫片的厚度差异很小。假设我们选取了 10 个这样的垫片并测量其厚度。如果这些垫片的厚度（单位：英寸）如下所示：</p>
<p>0.123 0.133 0.124 0.125 0.126 0.128 0.120 0.124 0.130 0.126</p>
<p>那么，该流水线生产的垫片厚度的标准差的 90% 置信区间是多少？</p>
</div>
<div id="sol-7_3_i" class="proof solution">
<p><span class="proof-title"><em>解 7.14</em>. </span>使用 R，我们有：</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span>d <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">0.123</span>, <span class="fl">0.124</span>, <span class="fl">0.126</span>, <span class="fl">0.120</span>, <span class="fl">0.130</span>, <span class="fl">0.133</span>, <span class="fl">0.125</span>, <span class="fl">0.128</span>, <span class="fl">0.124</span>, <span class="fl">0.126</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span>l <span class="ot">=</span> <span class="dv">9</span> <span class="sc">*</span> <span class="fu">var</span>(d) <span class="sc">/</span> <span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="dv">9</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span>u <span class="ot">=</span> <span class="dv">9</span> <span class="sc">*</span> <span class="fu">var</span>(d) <span class="sc">/</span> <span class="fu">qchisq</span>(<span class="fl">0.05</span>, <span class="dv">9</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="sc">&gt;</span><span class="fu">c</span>(l, u)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">0.123</span>, <span class="fl">0.124</span>, <span class="fl">0.126</span>, <span class="fl">0.120</span>, <span class="fl">0.130</span>, <span class="fl">0.133</span>, <span class="fl">0.125</span>, <span class="fl">0.128</span>, <span class="fl">0.124</span>, <span class="fl">0.126</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>l <span class="ot">=</span> <span class="dv">9</span> <span class="sc">*</span> <span class="fu">var</span>(d) <span class="sc">/</span> <span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="dv">9</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">=</span> <span class="dv">9</span> <span class="sc">*</span> <span class="fu">var</span>(d) <span class="sc">/</span> <span class="fu">qchisq</span>(<span class="fl">0.05</span>, <span class="dv">9</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(l, u)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.264032e-06 3.696115e-05</code></pre>
</div>
</div>
<p>由此可见，<span class="math inline">\(\sigma^2\)</span> 的 90% 的置信区间为：</p>
<p><span class="math inline">\(\sigma^2 \in (7.2640 \times 10^{-6}, 36.9612 \times 10^{-6})\)</span></p>
<p>所以：</p>
<p><span class="math inline">\(\sigma \in (0.00269, 0.00608)\)</span></p>
</div>
<p>类似的，可以得到 <span class="math inline">\(\sigma^2\)</span> 的单边置信区间。<a href="#tbl-7_1" class="quarto-xref">表&nbsp;<span>7.1</span></a> 对本节的内容进行了总结。</p>
<div id="tbl-7_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-7_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;7.1: 正态分布参数的 <span class="math inline">\(100(1-\alpha)\%\)</span> 置信区间，其中 <span class="math inline">\(X_1,...,X_n \sim \mathcal{N}(\mu, \sigma^2)\)</span>，<span class="math inline">\(\overline{X} = \sum_{i=1}^{n}{X_i/n}\)</span>，<span class="math inline">\(S = \sqrt{\sum_{i=1}^{n}{(X_i - \overline{X})^2/(n-1)}}\)</span>
</figcaption>
<div aria-describedby="tbl-7_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>假设</th>
<th>参数</th>
<th>置信区间</th>
<th>单边下置信区间</th>
<th>单边上置信区间</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\sigma^2\)</span> 已知</td>
<td><span class="math inline">\(\mu\)</span></td>
<td><span class="math inline">\(\overline{X} \pm z_{\alpha/2} \frac{\sigma}{\sqrt{n}}\)</span></td>
<td><span class="math inline">\((-\infty, \overline{X} + z_{\alpha} \frac{\sigma}{\sqrt{n}})\)</span></td>
<td><span class="math inline">\((\overline{X} - z_{\alpha} \frac{\sigma}{\sqrt{n}}, \infty)\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma^2\)</span> 未知</td>
<td><span class="math inline">\(\mu\)</span></td>
<td><span class="math inline">\(\overline{X} \pm t_{\alpha/2, n-1} \frac{S}{\sqrt{n}}\)</span></td>
<td><span class="math inline">\((-\infty, \overline{X} + t_{\alpha, n-1} \frac{S}{\sqrt{n}})\)</span></td>
<td><span class="math inline">\((\overline{X} - t_{\alpha, n-1} \frac{S}{\sqrt{n}}, \infty)\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mu\)</span> 未知</td>
<td><span class="math inline">\(\sigma^2\)</span></td>
<td><span class="math inline">\(\left( \frac{(n - 1) S^2}{\chi^2_{\alpha/2, n-1}}, \frac{(n - 1) S^2}{\chi^2_{1-\alpha/2, n-1}} \right)\)</span></td>
<td><span class="math inline">\(\left(0, \frac{(n - 1) S^2}{\chi^2_{1 - \alpha, n-1}}\right)\)</span></td>
<td><span class="math inline">\(\left(\frac{(n - 1) S^2}{\chi^2_{\alpha, n-1}}, \infty\right)\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-7_4" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="sec-7_4"><span class="header-section-number">7.4</span> 估计两个正态分布总体的均值差异</h2>
<p>令 <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> 是来自均值为 <span class="math inline">\(\mu_1\)</span>、方差为 <span class="math inline">\(\sigma_1^2\)</span> 的正态分布的总体的一个样本，样本大小为 <span class="math inline">\(n\)</span>；<span class="math inline">\(Y_1, \dots, Y_m\)</span> 是来自均值为 <span class="math inline">\(\mu_2\)</span>、方差为 <span class="math inline">\(\sigma_2^2\)</span> 的另一个正态分布总体的一个样本，样本大小为 <span class="math inline">\(m\)</span>。假设这两个样本之间彼此相互独立。此时，我们感兴趣的是：如何估计 <span class="math inline">\(\mu_1 - \mu_2\)</span>？</p>
<p>因为 <span class="math inline">\(\mu_1\)</span> 和 <span class="math inline">\(\mu_2\)</span> 的最大似然估计分别是：<span class="math inline">\(\overline{X} = \sum_{i=1}^n X_i / n\)</span>、<span class="math inline">\(\overline{Y} = \sum_{i=1}^m Y_i / m\)</span>，所以直觉而言（并且可以证明）<span class="math inline">\(\mu_1 - \mu_2\)</span> 的最大似然估计是 <span class="math inline">\(\overline{X} - \overline{Y}\)</span>。</p>
<p>为了得到置信区间估计，我们需要计算 <span class="math inline">\(\overline{X} - \overline{Y}\)</span> 的分布。由于</p>
<p><span class="math inline">\(\begin{align} \overline{X} &amp;\sim \mathcal{N}\left(\mu_1, \frac{\sigma_1^2}{n}\right) \\ \overline{Y} &amp; \sim \mathcal{N}\left(\mu_2, \frac{\sigma_2^2}{m}\right) \end{align}\)</span></p>
<p>根据独立正态分布随机变量的和也是正态分布的性质，有：</p>
<p><span class="math inline">\(\overline{X} - \overline{Y} \sim \mathcal{N}\left(\mu_1 - \mu_2, \frac{\sigma_1^2}{n} + \frac{\sigma_2^2}{m}\right)\)</span></p>
<p>因此，假设 <span class="math inline">\(\sigma_1^2\)</span> 和 <span class="math inline">\(\sigma_2^2\)</span> 是已知的，我们有：</p>
<p><span id="eq-7_4_1"><span class="math display">\[
\frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{\sqrt{\frac{\sigma_1^2}{n} + \frac{\sigma_2^2}{m}}} \sim \mathcal{N}(0, 1)
\tag{7.5}\]</span></span></p>
<p>因此，</p>
<p><span class="math inline">\(P\left\{-z_{\alpha/2} &lt; \frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{\sqrt{\frac{\sigma_1^2}{n} + \frac{\sigma_2^2}{m}}} &lt; z_{\alpha/2}\right\} = 1 - \alpha\)</span></p>
<p>即：</p>
<p><span class="math inline">\(P\left\{\overline{X} - \overline{Y} - z_{\alpha/2}\sqrt{\frac{\sigma_1^2}{n} + \frac{\sigma_2^2}{m}} &lt; \mu_1 - \mu_2 &lt; \overline{X} - \overline{Y} + z_{\alpha/2}\sqrt{\frac{\sigma_1^2}{n} + \frac{\sigma_2^2}{m}}\right\} = 1 - \alpha\)</span></p>
<p>因此，如果获得了样本的观察数据，则 <span class="math inline">\(\overline{X}\)</span> 和 <span class="math inline">\(\overline{Y}\)</span> 分别等于 <span class="math inline">\(\overline{x}\)</span> 和 <span class="math inline">\(\overline{y}\)</span>，那么 <span class="math inline">\(\mu_1 - \mu_2\)</span> 的 <span class="math inline">\(100(1-\alpha)\%\)</span> 双边置信区间估计为：</p>
<p><span id="eq-7_4_001"><span class="math display">\[
\mu_1 - \mu_2 \in \left(\overline{x} - \overline{y} - z_{\alpha/2}\sqrt{\frac{\sigma_1^2}{n} + \frac{\sigma_2^2}{m}}, \, \overline{x} - \overline{y} + z_{\alpha/2}\sqrt{\frac{\sigma_1^2}{n} + \frac{\sigma_2^2}{m}}\right)
\tag{7.6}\]</span></span></p>
<p>类似的，可以得到 <span class="math inline">\(\mu_1 - \mu_2\)</span> 的 <span class="math inline">\(100(1-\alpha)\%\)</span> 的单边置信区间：</p>
<p><span id="eq-7_4_002"><span class="math display">\[
\mu_1 - \mu_2 \in \left(-\infty, \, \overline{x} - \overline{y} + z_{\alpha}\sqrt{\frac{\sigma_1^2}{n} + \frac{\sigma_2^2}{m}}\right)
\tag{7.7}\]</span></span></p>
<p><a href="#eq-7_4_002" class="quarto-xref">式&nbsp;<span>7.7</span></a> 的证明我们留给读者来进行验证。</p>
<div id="exr-7_4_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.15</strong></span> 我们对两种不同类型的电缆绝缘材料进行了测试，以确定故障发生时的电压水平。在实验室的实验中，在电压不断增加的情况下，两种类型的电缆绝缘材料在如下的电压下发生了故障：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Type A</th>
<th>Type B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>36</td>
<td>52</td>
</tr>
<tr class="even">
<td>44</td>
<td>64</td>
</tr>
<tr class="odd">
<td>41</td>
<td>38</td>
</tr>
<tr class="even">
<td>53</td>
<td>68</td>
</tr>
<tr class="odd">
<td>38</td>
<td>66</td>
</tr>
<tr class="even">
<td>36</td>
<td>52</td>
</tr>
<tr class="odd">
<td>34</td>
<td>60</td>
</tr>
<tr class="even">
<td>54</td>
<td>44</td>
</tr>
<tr class="odd">
<td>52</td>
<td>48</td>
</tr>
<tr class="even">
<td>37</td>
<td>46</td>
</tr>
<tr class="odd">
<td>51</td>
<td>70</td>
</tr>
<tr class="even">
<td>44</td>
<td>62</td>
</tr>
<tr class="odd">
<td>35</td>
<td></td>
</tr>
<tr class="even">
<td>44</td>
<td></td>
</tr>
</tbody>
</table>
<p>假设已知绝缘材料 A 所能承受的电压服从均值为 <span class="math inline">\(\mu_A\)</span>（未知）、方差为 <span class="math inline">\(\sigma_A^2 = 40\)</span> 的正态分布；而绝缘材料 B 服从均值为 <span class="math inline">\(\mu_B\)</span>（未知）、方差为 <span class="math inline">\(\sigma_B^2 = 100\)</span> 的正态分布。</p>
<ol type="1">
<li>确定 <span class="math inline">\(\mu_B - \mu_A\)</span> 的 95% 置信区间。</li>
<li>确定我们可以以 95% 的置信度断言比 <span class="math inline">\(\mu_B - \mu_A\)</span> 小的最大值。</li>
</ol>
</div>
<div id="sol-7_4_a" class="proof solution">
<p><span class="proof-title"><em>解 7.15</em>. </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">52</span>, <span class="dv">64</span>, <span class="dv">38</span>, <span class="dv">68</span>, <span class="dv">66</span>, <span class="dv">52</span>, <span class="dv">60</span>, <span class="dv">44</span>, <span class="dv">48</span>, <span class="dv">46</span>, <span class="dv">70</span>, <span class="dv">62</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">36</span>, <span class="dv">44</span>, <span class="dv">41</span>, <span class="dv">53</span>, <span class="dv">38</span>, <span class="dv">36</span>, <span class="dv">34</span>, <span class="dv">54</span>, <span class="dv">52</span>, <span class="dv">37</span>, <span class="dv">51</span>, <span class="dv">44</span>, <span class="dv">35</span>, <span class="dv">44</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="sc">-</span> <span class="fu">mean</span>(y) <span class="sc">-</span> <span class="fu">qnorm</span>(.<span class="dv">975</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">40</span> <span class="sc">/</span> <span class="dv">14</span> <span class="sc">+</span> <span class="dv">100</span> <span class="sc">/</span> <span class="dv">12</span>) </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="sc">-</span> <span class="fu">mean</span>(y) <span class="sc">+</span> <span class="fu">qnorm</span>(.<span class="dv">975</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">40</span> <span class="sc">/</span> <span class="dv">14</span> <span class="sc">+</span> <span class="dv">100</span> <span class="sc">/</span> <span class="dv">12</span>) </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(l,u)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  6.491114 19.604124</code></pre>
</div>
</div>
<p>因此，我们有 95% 的信心可以断言 <span class="math inline">\(\mu_B - \mu_A \in (6.491114, 19.604124)\)</span>。为了获得单边上置信区间，我们可以采用如下的 R 代码：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">52</span>, <span class="dv">64</span>, <span class="dv">38</span>, <span class="dv">68</span>, <span class="dv">66</span>, <span class="dv">52</span>, <span class="dv">60</span>, <span class="dv">44</span>, <span class="dv">48</span>, <span class="dv">46</span>, <span class="dv">70</span>, <span class="dv">62</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">36</span>, <span class="dv">44</span>, <span class="dv">41</span>, <span class="dv">53</span>, <span class="dv">38</span>, <span class="dv">36</span>, <span class="dv">34</span>, <span class="dv">54</span>, <span class="dv">52</span>, <span class="dv">37</span>, <span class="dv">51</span>, <span class="dv">44</span>, <span class="dv">35</span>, <span class="dv">44</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="sc">-</span> <span class="fu">mean</span>(y) <span class="sc">-</span> <span class="fu">qnorm</span>(.<span class="dv">95</span>) <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">40</span> <span class="sc">/</span> <span class="dv">14</span> <span class="sc">+</span> <span class="dv">100</span> <span class="sc">/</span> <span class="dv">12</span>) </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>u</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.545227</code></pre>
</div>
</div>
<p>因此，我们有 95% 的信心认为 <span class="math inline">\(\mu_B - \mu_A \ge 7.545227\)</span>。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<section id="sec-7_4_1" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="sec-7_4_1"><span class="header-section-number">7.4.1</span> 总体方差未知时 <span class="math inline">\(\mu_1 - \mu_2\)</span> 的区间估计</h3>
<p>现在，我们希望再次对 <span class="math inline">\(\mu_1 - \mu_2\)</span> 进行区间估计，但这次估计时的总体方差 <span class="math inline">\(\sigma_1^2\)</span> 和 <span class="math inline">\(\sigma_2^2\)</span> 均是未知的。在这种情况下，最直接的做法就是用 <strong>样本方差</strong> 来替换公式 <a href="#eq-7_4_1" class="quarto-xref">式&nbsp;<span>7.5</span></a> 中的总体方差 <span class="math inline">\(\sigma_1^2\)</span> 和 <span class="math inline">\(\sigma_2^2\)</span>：</p>
<p><span class="math inline">\(\begin{align} S_1^2 &amp;= \frac{\sum_{i=1}^n (X_i - \overline{X})^2}{n - 1} \\ S_2^2 &amp;= \frac{\sum_{i=1}^m (Y_i - \overline{Y})^2}{m - 1} \end{align}\)</span></p>
<p>也就是说，此时的区间估计很自然地变为如下的形式：</p>
<p><span id="eq-7_4_003"><span class="math display">\[
\frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{\sqrt{S_1^2/n + S_2^2/m}}
\tag{7.8}\]</span></span></p>
<p>然而，为了利用 <a href="#eq-7_4_003" class="quarto-xref">式&nbsp;<span>7.8</span></a> 计算置信区间，我们需要知道 <a href="#eq-7_4_003" class="quarto-xref">式&nbsp;<span>7.8</span></a> 的分布，并且该分布不能依赖于任何未知参数 <span class="math inline">\(\sigma_1^2\)</span> 和 <span class="math inline">\(\sigma_2^2\)</span>。不幸的是，这个分布既复杂又确实依赖于未知参数 <span class="math inline">\(\sigma_1^2\)</span> 和 <span class="math inline">\(\sigma_2^2\)</span>。事实上，只有在特殊情况下，即 <span class="math inline">\(\sigma_1^2 = \sigma_2^2\)</span> 时，我们才能获得 <span class="math inline">\(\mu_1 - \mu_2\)</span> 的区间估计。因此，虽然总体方差未知，但我们可以假设总体方差是一致的，并令 <span class="math inline">\(\sigma^2\)</span> 表示 <span class="math inline">\(\sigma_1^2\)</span> 和 <span class="math inline">\(\sigma_2^2\)</span> 的值。由 <a href="../chapter_6/6.html#thm-6_5_1" class="quarto-xref">定理&nbsp;<span>6.2</span></a> 得到：</p>
<p><span class="math inline">\(\begin{align} (n - 1)\frac{S_1^2}{\sigma^2} &amp; \sim \chi^2_{n-1} \\ (m - 1)\frac{S_2^2}{\sigma^2} &amp; \sim \chi^2_{m-1} \end{align}\)</span></p>
<p>此外，由于样本是独立的，因此这两个卡方随机变量也是独立的。由卡方随机变量的可加性，独立卡方随机变量之和也是卡方分布，其自由度等于各卡方随机变量的自由度之和，因此有：</p>
<p><span id="eq-7_4_2"><span class="math display">\[
(n - 1)\frac{S_1^2}{\sigma^2} + (m - 1)\frac{S_2^2}{\sigma^2} \sim \chi^2_{n+m-2}
\tag{7.9}\]</span></span></p>
<p>同时，由于</p>
<p><span class="math inline">\(\overline{X} - \overline{Y} \sim \mathcal{N}\left(\mu_1 - \mu_2, \frac{\sigma^2}{n} + \frac{\sigma^2}{m}\right)\)</span></p>
<p>我们可以得到：</p>
<p><span id="eq-7_4_3"><span class="math display">\[
\frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{\sqrt{\sigma^2/n + \sigma^2/m}} \sim \mathcal{N}(0, 1)
\tag{7.10}\]</span></span></p>
<p>现在，根据 <a href="../chapter_6/6.html#thm-6_5_1" class="quarto-xref">定理&nbsp;<span>6.2</span></a> 中的基本结果，在正态分布抽样中，<span class="math inline">\(\overline{X}\)</span> 和 <span class="math inline">\(S^2\)</span> 是独立的，所以 <span class="math inline">\(X_1, S_1^2, X_2, S_2^2\)</span> 是独立的随机变量。因此，如果令：</p>
<p><span class="math inline">\(S_p^2 = \frac{(n-1)S_1^2 + (m-1)S_2^2}{n+m-2}\)</span></p>
<p>使用 <span class="math inline">\(t\)</span> 随机变量的定义（<a href="../chapter_5/5.html#sec-5_8_2" class="quarto-xref"><span>小节 5.8.2</span></a>，<span class="math inline">\(t\)</span> 随机变量为两个独立随机变量的比值，其中分子为标准正态分布，分母为一个卡方随机变量除以其自由度的平方根），根据 <a href="#eq-7_4_2" class="quarto-xref">式&nbsp;<span>7.9</span></a> 和 <a href="#eq-7_4_3" class="quarto-xref">式&nbsp;<span>7.10</span></a> 可以得到：</p>
<p><span class="math inline">\(\frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{\sqrt{\sigma^2 (1/n + 1/m)}} \div \sqrt{\frac{S_p^2}{\sigma^2}} = \frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{\sqrt{S_p^2 (1/n + 1/m)}}\)</span></p>
<p>是自由度为 <span class="math inline">\(n + m - 2\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span> 随机变量。因此：</p>
<p><span class="math inline">\(P\left\{ -t_{\alpha/2, n+m-2} \leq \frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{S_p \sqrt{1/n + 1/m}} \leq t_{\alpha/2, n+m-2} \right\} = 1 - \alpha\)</span></p>
<p>因此，当观察到样本数据后，令 <span class="math inline">\(\overline{X} = \overline{x}\)</span>、<span class="math inline">\(\overline{Y} = \overline{y}\)</span>、<span class="math inline">\(S_p = s_p\)</span>，我们得到 <span class="math inline">\(\mu_1 - \mu_2\)</span> 的 <span class="math inline">\(100(1-\alpha)\%\)</span> 的置信区间：</p>
<p><span id="eq-7_4_4"><span class="math display">\[
\left(\overline{x} - \overline{y} - t_{\alpha/2, n+m-2} s_p \sqrt{1/n + 1/m}, \quad \overline{x} - \overline{y} + t_{\alpha/2, n+m-2} s_p \sqrt{1/n + 1/m}\right)
\tag{7.11}\]</span></span></p>
<p>类似地，我们可以得到方差未知时 <span class="math inline">\(\mu_1 - \mu_2\)</span> 的单边置信区间。</p>
<div id="exr-7_4_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.16</strong></span> 对于 <a href="#exr-7_4_a" class="quarto-xref">习题&nbsp;<span>7.15</span></a> 中的数据，如果两个样本的总体方差均未知、但是方差是相等的，计算 <span class="math inline">\(\mu_B - \mu_A\)</span> 的 95% 的双边置信区间？</p>
</div>
<div id="sol-7_4_b" class="proof solution">
<p><span class="proof-title"><em>解 7.16</em>. </span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">52</span>, <span class="dv">64</span>, <span class="dv">38</span>, <span class="dv">68</span>, <span class="dv">66</span>, <span class="dv">52</span>, <span class="dv">60</span>, <span class="dv">44</span>, <span class="dv">48</span>, <span class="dv">46</span>, <span class="dv">70</span>, <span class="dv">62</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">36</span>, <span class="dv">44</span>, <span class="dv">41</span>, <span class="dv">53</span>, <span class="dv">38</span>, <span class="dv">36</span>, <span class="dv">34</span>, <span class="dv">54</span>, <span class="dv">52</span>, <span class="dv">37</span>, <span class="dv">51</span>, <span class="dv">44</span>, <span class="dv">35</span>, <span class="dv">44</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>sp <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((<span class="dv">11</span> <span class="sc">*</span> <span class="fu">var</span>(x) <span class="sc">+</span> <span class="dv">13</span> <span class="sc">*</span> <span class="fu">var</span>(y)) <span class="sc">/</span> <span class="dv">24</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>l <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="sc">-</span> <span class="fu">mean</span>(y) <span class="sc">-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="dv">24</span>) <span class="sc">*</span> sp <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="dv">12</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> <span class="dv">14</span>) </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="sc">-</span> <span class="fu">mean</span>(y) <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="dv">24</span>) <span class="sc">*</span> sp <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="dv">12</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> <span class="dv">14</span>) </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(l,u)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  5.830952 20.264286</code></pre>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="备注">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
备注
</div>
</div>
<div class="callout-body-container callout-body">
<p>由 <a href="#eq-7_4_4" class="quarto-xref">式&nbsp;<span>7.11</span></a> 给出的置信区间是在假设总体方差相等的条件下的结果；假设抽样的总体的方差都是 <span class="math inline">\(\sigma^2\)</span>，则</p>
<p><span class="math inline">\(\frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{\sqrt{\sigma^2/n + \sigma^2/m}} = \frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{\sigma\sqrt{1/n + 1/m}}\)</span></p>
<p>服从标准正态分布。</p>
<p>然而，由于 <span class="math inline">\(\sigma^2\)</span> 是未知的，因此不能直接使用上式来计算置信区间。为了计算置信区间，必须首先估计 <span class="math inline">\(\sigma^2\)</span>。同时，请注意，两个样本方差都是 <span class="math inline">\(\sigma^2\)</span> 的估计量。此外，由于 <span class="math inline">\(S_1^2\)</span> 的自由度为 <span class="math inline">\(n - 1\)</span>，<span class="math inline">\(S_2^2\)</span> 的自由度为 <span class="math inline">\(m - 1\)</span>，所以取这两个样本方差的估计量的加权平均值（权重与自由度成正比）作为 <span class="math inline">\(\sigma^2\)</span> 的估计量是合理的。也就是说，<span class="math inline">\(\sigma^2\)</span> 的估计量是 <strong>池化估计量</strong>（<em>the pooled estimator</em>）：</p>
<p><span class="math inline">\(S_p^2 = \frac{(n - 1)S_1^2 + (m - 1)S_2^2}{n + m - 2}\)</span></p>
<p>于是基于以下统计量计算置信区间：</p>
<p><span class="math inline">\(\frac{\overline{X} - \overline{Y} - (\mu_1 - \mu_2)}{\sqrt{S_p^2\left(1/n + 1/m\right)}}\)</span></p>
<p>根据之前的分析，如上的统计量服从自由度为 <span class="math inline">\(n + m - 2\)</span> 的 <span class="math inline">\(t- \text{分布}\)</span>。</p>
</div>
</div>
<p><a href="#tbl-7_2" class="quarto-xref">表&nbsp;<span>7.2</span></a> 对本节的相关结论进行了总结。</p>
<div id="tbl-7_2" class="quarto-layout-panel anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-7_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;7.2: <span class="math inline">\(\mu_1 - \mu_2\)</span> 的 <span class="math inline">\(100(1 - \alpha) \%\)</span> 置信区间
</figcaption>
<div aria-describedby="tbl-7_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="tbl-7_2" style="flex-basis: 100.0%;justify-content: center;">
<div id="tbl-7_2_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-7_2_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <span class="math inline">\(X_i\)</span>，<span class="math inline">\(Y_i\)</span> 的分布
</figcaption>
<div aria-describedby="tbl-7_2_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\begin{align} &amp; X_1, ..., X_n \sim \mathcal{N}(\mu_1, \sigma_1^2) \\ &amp; Y_1, ..., Y_n \sim \mathcal{N}(\mu_2, \sigma_2^2) \\ &amp; \overline{X} = \sum_{i=1}^{n}{X_i} / n, \quad S_1^2 = \sum_{i=1}^{n}{(X_i - \overline{X})^2} / (n-1) \\ &amp; \overline{Y} = \sum_{i=1}^{m}{Y_i} / n, \quad S_2^2 = \sum_{i=1}^{m}{(Y_i - \overline{Y})^2} / (m-1)\end{align}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="tbl-7_2" style="flex-basis: 100.0%;justify-content: center;">
<div id="tbl-7_2_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-7_2_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) 双边置信区间
</figcaption>
<div aria-describedby="tbl-7_2_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 60%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Assumption</th>
<th style="text-align: left;">Confidence Interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\sigma_1, \sigma_2\)</span> 已知</td>
<td style="text-align: left;"><span class="math inline">\(\overline{X} - \overline{Y} \pm z_{\alpha/2} \sqrt{\sigma_1^2/n + \sigma_2^2/m}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\sigma_1, \sigma_2\)</span> 未知但相等</td>
<td style="text-align: left;"><span class="math inline">\(\overline{X} - \overline{Y} \pm t_{\alpha/2, n+m-2} \sqrt{\left(\frac{1}{n} + \frac{1}{m}\right) \frac{(n-1)S_1^2 + (m-1)S_2^2}{n+m-2}}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="tbl-7_2" style="flex-basis: 100.0%;justify-content: center;">
<div id="tbl-7_2_3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-7_2_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) 单边下置信区间
</figcaption>
<div aria-describedby="tbl-7_2_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 51%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Assumption</th>
<th style="text-align: left;">Lower Confidence Interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\sigma_1, \sigma_2\)</span> 已知</td>
<td style="text-align: left;"><span class="math inline">\((-\infty, \overline{X} - \overline{Y} + z_{\alpha} \sqrt{\sigma_1^2/n + \sigma_2^2/m})\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\sigma_1, \sigma_2\)</span> 未知但相等</td>
<td style="text-align: left;"><span class="math inline">\(\left(-\infty, \overline{X} - \overline{Y} + t_{\alpha, n+m-2} \sqrt{\left(\frac{1}{n} + \frac{1}{m}\right) \frac{(n-1)S_1^2 + (m-1)S_2^2}{n+m-2}}\right)\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
</div>
</figure>
</div>
<blockquote class="blockquote">
<p>注意：<span class="math inline">\(\mu_1 - \mu_2\)</span> 的单边上置信区间可以通过 <span class="math inline">\(\mu_2 - \mu_1\)</span> 的单边下执行区间得到</p>
</blockquote>
</section>
</section>
<section id="sec-7_5" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="sec-7_5"><span class="header-section-number">7.5</span> 伯努利随机变量均值的近似置信区间</h2>
<p>考虑某个物品的一个总体，总体中每个物品达到某些标准的概率都是未知概率 <span class="math inline">\(p\)</span>，并且物品之间的达标率是相互独立的。如果我们从总体中抽取 <span class="math inline">\(n\)</span> 个物品进行测试，以确定这些物品是否达到标准，我们如何利用抽检所得到的数据来计算 <span class="math inline">\(p\)</span> 的置信区间？</p>
<p>如果我们令 <span class="math inline">\(X\)</span> 表示抽取的 <span class="math inline">\(n\)</span> 个物品中符合标准的物品数量，那么 <span class="math inline">\(X\)</span> 是参数为 <span class="math inline">\((n, p)\)</span> 的二项随机变量。因此，当 <span class="math inline">\(n\)</span> 较大时，根据二项分布会近似为正态分布的特性（<a href="../chapter_6/6.html#sec-6_3" class="quarto-xref"><span>小节 6.3</span></a>），<span class="math inline">\(X\)</span> 近似服从均值为 <span class="math inline">\(np\)</span>、方差为 <span class="math inline">\(np(1-p)\)</span> 的正态分布。因此，</p>
<p><span id="eq-7_5_1"><span class="math display">\[
\frac{X - np}{\sqrt{np(1-p)}} \approx \mathcal{N}(0, 1)
\tag{7.12}\]</span></span></p>
<p>其中 <span class="math inline">\(\approx\)</span> 表示“近似服从”。因此，对于任何 <span class="math inline">\(\alpha \in (0, 1)\)</span>，我们有：</p>
<p><span class="math inline">\(P\left\{-z_{\alpha/2} &lt; \frac{X - np}{\sqrt{np(1-p)}} &lt; z_{\alpha/2}\right\} \approx 1 - \alpha\)</span></p>
<p>因此，如果对于实验数据 <span class="math inline">\(X = x\)</span> 而言，<span class="math inline">\(p\)</span> 的近似 <span class="math inline">\(100(1-\alpha)\%\)</span> 置信区为：</p>
<p><span id="eq-7_5_001"><span class="math display">\[
\left\{p : -z_{\alpha/2} &lt; \frac{x - np}{\sqrt{np(1-p)}} &lt; z_{\alpha/2}\right\}
\tag{7.13}\]</span></span></p>
<p>然而，<a href="#eq-7_5_001" class="quarto-xref">式&nbsp;<span>7.13</span></a> 的区域并非区间。令 <span class="math inline">\(\hat{p} = X/n\)</span> 表示符合标准的物品所占的比例，以便得到 <span class="math inline">\(p\)</span> 的置信区间。根据 <a href="#exr-7_2_a" class="quarto-xref">习题&nbsp;<span>7.1</span></a> 可知，<span class="math inline">\(\hat{p}\)</span> 是 <span class="math inline">\(p\)</span> 的最大似然估计，因此 <span class="math inline">\(\hat{p}\)</span> 应该近似等于 <span class="math inline">\(p\)</span>。因此，<span class="math inline">\(\sqrt{n\hat{p}(1-\hat{p})}\)</span> 将近似等于 <span class="math inline">\(\sqrt{np(1-p)}\)</span>，因此由 <a href="#eq-7_5_1" class="quarto-xref">式&nbsp;<span>7.12</span></a> 可以得到：</p>
<p><span class="math inline">\(\frac{X - np}{\sqrt{n\hat{p}(1-\hat{p})}} \approx \mathcal{N}(0, 1)\)</span></p>
<p>因此，对于任何 <span class="math inline">\(\alpha \in (0, 1)\)</span>，我们有：</p>
<p><span class="math inline">\(P\left\{-z_{\alpha/2} &lt; \frac{X - np}{\sqrt{n\hat{p}(1-\hat{p})}} &lt; z_{\alpha/2}\right\} \approx 1 - \alpha\)</span></p>
<p>即，</p>
<p><span class="math inline">\(P\{-z_{\alpha/2}\sqrt{n\hat{p}(1-\hat{p})} &lt; np - X &lt; z_{\alpha/2}\sqrt{n\hat{p}(1-\hat{p})}\} \approx 1 - \alpha\)</span></p>
<p>将上述不等式两边都除以 <span class="math inline">\(n\)</span>，并根据 <span class="math inline">\(\hat{p} = X/n\)</span>，有：</p>
<p><span id="eq-7_5_002"><span class="math display">\[
P\left\{\hat{p} - z_{\alpha/2}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}} &lt; p &lt; \hat{p} + z_{\alpha/2}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\right\} \approx 1 - \alpha
\tag{7.14}\]</span></span></p>
<p><a href="#eq-7_5_002" class="quarto-xref">式&nbsp;<span>7.14</span></a> 给出了 <span class="math inline">\(p\)</span> 的 <span class="math inline">\(100(1-\alpha)\%\)</span> 的近似置信区间。</p>
<div id="exm-7_5_a" class="theorem example">
<p><span class="theorem-title"><strong>例 7.3</strong></span> 从一批晶体管中随机抽取 100 个样本，并测试这 100 个样本是否符合当前标准。如果其中有 80 个晶体管符合标准，那么符合标准的所有晶体管的比例 <span class="math inline">\(p\)</span> 的近似 95% 置信区间为：</p>
<p><span class="math inline">\((0.8 - 1.96 \sqrt{\frac{0.8(0.2)}{100}}, \, 0.8 + 1.96 \sqrt{\frac{0.8(0.2)}{100}}) = (0.7216, \, 0.8784)\)</span></p>
<p>也就是说，在 95% 的置信度的情况下，符合标准的晶体管的比例在 72.16% 到 87.84% 之间。</p>
</div>
<div id="exr-7_5_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 7.17</strong></span> 2013 年 8 月，《纽约时报》报道了最近的一项民意调查，结果显示 52% 的人（误差范围为 <span class="math inline">\(\pm 4\%\)</span>）对奥巴马总统的工作表现呈肯定态度。这意味着什么？我们能推断出有多少人参与了调查吗？</p>
</div>
<div id="sol-7_5_b" class="proof solution">
<p><span class="proof-title"><em>解 7.17</em>. </span>新闻媒体通常会使用 95% 置信区间。由于 <span class="math inline">\(z_{0.025} = 1.96\)</span>，令 <span class="math inline">\(p\)</span> 代表肯定奥巴马总统工作表现的人的比例，那么关于 <span class="math inline">\(p\)</span> 的 95% 置信区间可以表示为：</p>
<p><span class="math inline">\(\hat{p} \pm 1.96 \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}} = 0.52 \pm 1.96 \sqrt{\frac{0.52 \times 0.48}{n}}\)</span></p>
<p>其中，<span class="math inline">\(n\)</span> 是样本的大小。由于“误差范围”是 <span class="math inline">\(\pm 4\%\)</span>，由此可以推导出：</p>
<p><span class="math inline">\(1.96 \sqrt{\frac{0.52 \times 0.48}{n}} = 0.04\)</span></p>
<p>即：</p>
<p><span class="math inline">\(n = \frac{(1.96)^2 \times 0.52 \times 0.48}{(0.04)^2} = 599.29\)</span></p>
<p>也就是说，大约有 599 人参与了调查，其中 52% 的人对奥巴马总统的工作表现持肯定态度。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>我们经常希望为 <span class="math inline">\(p\)</span> 指定一个近似的 <span class="math inline">\(100(1 - \alpha)\%\)</span> 的置信区间，并且该置信区间的长度不能超过某个给定的值（<span class="math inline">\(b\)</span>）。获得这样的、有大小限定的置信区间的问题在于确定合适的样本量 <span class="math inline">\(n\)</span>。从样本大小为 <span class="math inline">\(n\)</span> 的样本中得到的 <span class="math inline">\(p\)</span> 的近似 <span class="math inline">\(100(1 - \alpha)\%\)</span> 的置信区间的长度为：</p>
<p><span class="math inline">\(2z_{\alpha/2} \sqrt{\frac{\hat{p}(1 - \hat{p})}{n}}\)</span></p>
<p>该值近似等于 <span class="math inline">\(2z_{\alpha/2}\sqrt{\frac{p(1-p)}{n}}\)</span>。不幸的是，因为 <span class="math inline">\(p\)</span> 是未知的，因此我们不能简单地令 <span class="math inline">\(2z_{\alpha/2}\sqrt{\frac{p(1-p)}{n}} = b\)</span>，然后再确定所需的样本量 <span class="math inline">\(n\)</span>。然而，我们可以先进行一个初步的抽样，以获得 <span class="math inline">\(p\)</span> 的粗略估计，然后利用该估计来确定 <span class="math inline">\(n\)</span>。</p>
<p>也就是说，我们使用初步抽样样本中的比例 <span class="math inline">\(p^*\)</span> 作为 <span class="math inline">\(p\)</span> 的初步估计；然后通过求解下列方程确定总样本量 <span class="math inline">\(n\)</span>：</p>
<p><span class="math inline">\(2z_{\alpha/2} \sqrt{\frac{p^*(1 - p^*)}{n}} = b\)</span></p>
<p>对上式两边平方得到：</p>
<p><span class="math inline">\((2z_{\alpha/2})^2 \frac{p^*(1 - p^*)}{n} = b^2\)</span></p>
<p>即：</p>
<p><span class="math inline">\(n = \frac{(2z_{\alpha/2})^2 p^*(1 - p^*)}{b^2}\)</span></p>
<p>也就是说，如果最初抽取了 <span class="math inline">\(k\)</span> 个样本以获得 <span class="math inline">\(p\)</span> 的初步估计，那么还应再抽取 <span class="math inline">\(n - k\)</span> 个样本。</p>
<div id="exm-7_5_c" class="theorem example">
<p><span class="theorem-title"><strong>例 7.4</strong></span> 某芯片制造商生产的每个芯片的达标率为某个未知概率 <span class="math inline">\(p\)</span>（假设芯片之间的达标率是相互独立的）。已经抽取了 30 个芯片的初步样本以便获得区间长度为 0.05 的 <span class="math inline">\(p\)</span> 的近似 99% 置信区间。在抽取的 30 个芯片中，如果有 26 个芯片符合标准（达标），那么 <span class="math inline">\(p\)</span> 的初步估计为 <span class="math inline">\(26/30\)</span>。使用该值，得到长度为 0.05 的 99% 置信区间所需的样本量为：</p>
<p><span class="math inline">\(n = \frac{4(z_{0.005})^2 \cdot \frac{26}{30} \left(1 - \frac{26}{30}\right)}{(0.05)^2} = \frac{4(2.58)^2 \cdot \frac{26}{30} \cdot \frac{4}{30}}{(0.05)^2} = 1231\)</span></p>
<p>因此，我们现在应该再抽取 1201 个芯片，并且如果其中有 1040 个芯片是符合标准的，那么 <span class="math inline">\(p\)</span> 的最终 99% 置信区间为：</p>
<p><span class="math inline">\(\left(\frac{1066}{1231} - \sqrt{\frac{1066}{1231} \left(1 - \frac{1066}{1231}\right)} \cdot \frac{z_{0.005}}{\sqrt{1231}}, \, \frac{1066}{1231} + \sqrt{\frac{1066}{1231} \left(1 - \frac{1066}{1231}\right)} \cdot \frac{z_{0.005}}{\sqrt{1231}}\right)\)</span></p>
<p>即：</p>
<p><span class="math inline">\(p \in (0.84091, 0.89101)\)</span> <span class="math inline">\(\blacksquare\)</span></p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="备注">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
备注
</div>
</div>
<div class="callout-body-container callout-body">
<p>如前所示，当样本量为</p>
<p><span class="math inline">\(n = \frac{(2z_{\alpha/2})^2}{b^2} \cdot p(1-p)\)</span></p>
<p>时，<span class="math inline">\(p\)</span> 的 <span class="math inline">\(100(1-\alpha)\%\)</span> 置信区间的长度将近似为 <span class="math inline">\(b\)</span>。</p>
<p>现在很容易证明，对于函数 <span class="math inline">\(g(p) = p(1-p)\)</span>（定义域为：<span class="math inline">\(0 \leq p \leq 1\)</span>）而言，当 <span class="math inline">\(p = \frac{1}{2}\)</span> 时，<span class="math inline">\(g(p)\)</span> 取得最大值 <span class="math inline">\(\frac{1}{4}\)</span>。因此，<span class="math inline">\(n\)</span> 的上界为</p>
<p><span class="math inline">\(n \leq \frac{(z_{\alpha/2})^2}{b^2}\)</span></p>
<p>因此，样本量至少为 <span class="math inline">\(\frac{(z_{\alpha/2})^2}{b^2}\)</span> 时，可以确保在不需要任何额外的抽样的情况下，置信区间的长度不超过 <span class="math inline">\(b\)</span>。</p>
</div>
</div>
<p><a href="#tbl-7_3" class="quarto-xref">表&nbsp;<span>7.3</span></a> 对本节的内容进行了总结。</p>
<div id="tbl-7_3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-7_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;7.3: <span class="math inline">\(X \sim \mathcal{N}(n, p)\)</span>，<span class="math inline">\(\hat{p} = X/n\)</span>，<span class="math inline">\(p\)</span> 的 <span class="math inline">\(100(1-\alpha)\%\)</span> 的置信区间
</figcaption>
<div aria-describedby="tbl-7_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>置信区间类型</th>
<th>置信区间</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>双边置信区间</td>
<td><span class="math inline">\(\hat{p} \pm z_{\alpha/2} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\)</span></td>
</tr>
<tr class="even">
<td>单边下置信区间</td>
<td><span class="math inline">\(\left(-\infty, \, \hat{p} + z_{\alpha} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\right)\)</span></td>
</tr>
<tr class="odd">
<td>单边上置信区间</td>
<td><span class="math inline">\(\left(\hat{p} - z_{\alpha} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}, \, \infty\right)\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-7_6" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="sec-7_6"><span class="header-section-number">7.6</span> Confidence interval of the mean of the exponential distribution <span class="math inline">\(^*\)</span></h2>
</section>
<section id="sec-7_7" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="sec-7_7"><span class="header-section-number">7.7</span> Evaluating a point estimator <span class="math inline">\(^*\)</span></h2>
</section>
<section id="sec-7_8" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="sec-7_8"><span class="header-section-number">7.8</span> The Bayes estimator <span class="math inline">\(^*\)</span></h2>
</section>
<section id="problems" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="problems">Problems</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "已复制");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "已复制");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/wangwei1237\.github\.io\/introduction_to_probability_and_statistics\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="wangwei1237/introduction_to_probability_and_statistics" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapter_6/6.html" class="pagination-link" aria-label="抽样分布">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">抽样分布</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapter_8/8.html" class="pagination-link" aria-label="假设检验">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">假设检验</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright Wang Wei. All Rights Reserved.</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/edit/main/chapter_7/7.qmd" class="toc-action"><i class="bi bi-github"></i>编辑该页面</a></li><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/issues/new" class="toc-action"><i class="bi empty"></i>反馈问题</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>