<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-Hans" xml:lang="zh-Hans"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; 方差分析 – Introduction to Probability and Statistics for Engineers and Scientists（中文版）</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapter_11/11.html" rel="next">
<link href="../chapter_9/9.html" rel="prev">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "没有结果",
    "search-matching-documents-text": "匹配的文档",
    "search-copy-link-title": "复制搜索链接",
    "search-hide-matches-text": "隐藏其它匹配结果",
    "search-more-match-text": "更多匹配结果",
    "search-more-matches-text": "更多匹配结果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "提交",
    "search-label": "搜索"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="10&nbsp; 方差分析 – Introduction to Probability and Statistics for Engineers and Scientists（中文版）">
<meta property="og:description" content="">
<meta property="og:site_name" content="Introduction to Probability and Statistics for Engineers and Scientists（中文版）">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../favicon.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Introduction to Probability and Statistics for Engineers and Scientists（中文版）</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="搜索"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="展开或折叠导航栏" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://wangwei1237.github.io/"> <i class="bi bi-house-fill" role="img">
</i> 
<span class="menu-text">博客</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-bookshelf" role="img">
</i> 
 <span class="menu-text">书籍</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-">    
        <li>
    <a class="dropdown-item" href="https://zh.d2l.ai/">
 <span class="dropdown-text">动手学深度学习</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://learnprompting.org/zh-Hans/docs/intro">
 <span class="dropdown-text">Learn Prompting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pan.baidu.com/s/1dciwgbhO-lfKyRo8lOqW9Q?pwd=cm9q">
 <span class="dropdown-text">Stabel Diffusion 提示词手册</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://wangwei1237.github.io/aboutme/"> <i class="bi bi-person-badge-fill" role="img">
</i> 
<span class="menu-text">关于</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics" title="源代码" class="quarto-navigation-tool px-1" aria-label="源代码"><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapter_10/10.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">方差分析</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">欢迎阅读</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface_17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">译者序</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">序言</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_1/1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">统计学简介</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_2/2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">描述统计</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_3/3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">概率论基础</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_4/4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">随机变量和期望</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_5/5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">特殊的随机变量</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_6/6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">抽样分布</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_7/7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">参数估计</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_8/8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">假设检验</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_9/9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">回归</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_10/10.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">方差分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_11/11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">拟合优度检验和分类数据分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_12/12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Nonparametric hypothesis tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_13/13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Quality control</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_14/14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Life testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_15/15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Simulation, bootstrap statistical methods, and permutation tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_16/16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Machine learning and big data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">测试脚本</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">附录</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">表格</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">目录</h2>
   
  <ul>
  <li><a href="#sec-10_1" id="toc-sec-10_1" class="nav-link active" data-scroll-target="#sec-10_1"><span class="header-section-number">10.1</span> 引言</a></li>
  <li><a href="#sec-10_2" id="toc-sec-10_2" class="nav-link" data-scroll-target="#sec-10_2"><span class="header-section-number">10.2</span> 综述</a></li>
  <li><a href="#sec-10_3" id="toc-sec-10_3" class="nav-link" data-scroll-target="#sec-10_3"><span class="header-section-number">10.3</span> 单因素方差分析</a>
  <ul class="collapse">
  <li><a href="#sec-10_3_1" id="toc-sec-10_3_1" class="nav-link" data-scroll-target="#sec-10_3_1"><span class="header-section-number">10.3.1</span> 使用 R 计算统计量</a></li>
  <li><a href="#sec-10_3_2" id="toc-sec-10_3_2" class="nav-link" data-scroll-target="#sec-10_3_2"><span class="header-section-number">10.3.2</span> 样本均值的多重比较</a></li>
  <li><a href="#sec-10_3_3" id="toc-sec-10_3_3" class="nav-link" data-scroll-target="#sec-10_3_3"><span class="header-section-number">10.3.3</span> 样本大小不同的单因素方差分析</a></li>
  </ul></li>
  <li><a href="#sec-10_4" id="toc-sec-10_4" class="nav-link" data-scroll-target="#sec-10_4"><span class="header-section-number">10.4</span> 双因素方差分析：引言和参数估计</a></li>
  <li><a href="#sec-10_5" id="toc-sec-10_5" class="nav-link" data-scroll-target="#sec-10_5"><span class="header-section-number">10.5</span> 双因素方差分析：检验假设</a></li>
  <li><a href="#sec-10_6" id="toc-sec-10_6" class="nav-link" data-scroll-target="#sec-10_6"><span class="header-section-number">10.6</span> 有交互效应的双因素方差分析</a></li>
  <li><a href="#problems" id="toc-problems" class="nav-link" data-scroll-target="#problems">Problems</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/edit/main/chapter_10/10.qmd" class="toc-action"><i class="bi bi-github"></i>编辑该页面</a></li><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/issues/new" class="toc-action"><i class="bi empty"></i>反馈问题</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-10" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">方差分析</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-10_1" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="sec-10_1"><span class="header-section-number">10.1</span> 引言</h2>
<p>目前市面上有 4 款软件来教授用户学习一门新的变成语言，某大公司正在考虑大规模购买这 4 款软件中的一款。公司内部一些资深人士声称，这几款软件没有太大的区别，它们对用户的最终学习效果影响很小。为了检验这一假设，公司决定选择 160 名工程师，并将他们分成 4 组，每组 40 人。第 <span class="math inline">\(i\)</span> 组的工程师使用第 <span class="math inline">\(i\)</span>（<span class="math inline">\(i = 1, 2, 3, 4\)</span>）款软件来学习新的语言。当所有工程师完成学习后，参与学习的所有工程师将进行一次全面考试。公司希望使用这次考试的结果来确定不同的教学软件是否真的可以互换。该公司需要怎么做才能实现这一点？</p>
<p>在回答这个问题之前，我们需要明确，显然我们希望得出这样的结论：当所有分组的平均成绩相似时，可以认为这几款软件确实是可以互换的；而当不同分组的平均成绩之间有很大差异时，可以认为这几款软件在本质上是存在区别的。要得出这样的结论，我们必须注意到：将这 160 名工程师分成 4 组的方法至关重要。例如，假设第一组的成员成绩显著高于其他组，我们能从中得出什么结论？具体来说，这个结果是由于 第 1 款软件的教学效果更好，还是第一组的工程师的学习能力更好？为了能够得出这几款软件是否可以互换的结论，需要一种合理的分组方式以保证不同分组的工程师不会存在显著的差异，这一点至关重要。以完全随机的方式将工程师分成 4 组是久经考验的一种方法。也就是说，完全随机的分组方式可以使得所有可能的分组组合都有相同的概率，从而保障任何一组明显优于其他组的可能性非常小。假设我们确实使用“随机”的方式对工程师分组，虽然目前还不清楚如何才能做到。一种有效的方法是首先对这 160 名工程师进行 1~160 的编号，然后生成 1~160 的随机排列，并将排列中的前 40 名工程师放分到 第 1 组，排列中的第 41 到 80 名工程师分到 第 2 组，以此类推。</p>
<p>现在，我们可以合理的假设：每一位工程师的考试成绩应该大致服从正态分布，该分布的参数取决于他所使用的教学软件。同样，也可以合理的假设：尽管工程师的平均考试成绩取决于他所使用的教学软件，但考试成绩的变异性（<em>variability</em>）将源自 160 名工程师的内在变异（<em>inherent variation</em>），而不是来自所使用的软件。因此，如果我们令 <span class="math inline">\(X_{ij},\ i=1,...4, \ j=1,...,40\)</span> 表示第 <span class="math inline">\(i\)</span> 组中第 <span class="math inline">\(j\)</span> 名工程师的考试成绩。一个合理的模型可能是假设 <span class="math inline">\(X_{ij}\)</span> 是独立的随机变量，其中 <span class="math inline">\(X_{ij}\)</span> 服从均值为 <span class="math inline">\(\mu_i\)</span> 且方差为 <span class="math inline">\(\sigma^2\)</span> 的正态分布。不同的教学软件可以互换的假设相当于对原假设 <span class="math inline">\(H_0: \mu_1 = \mu_2 = \mu_3 = \mu_4\)</span> 进行检验。</p>
<div class="callout callout-style-default callout-note callout-titled" title="变异量">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
变异量
</div>
</div>
<div class="callout-body-container callout-body">
<p>正如在 <a href="../chapter_9/9.html#sec-9_5" class="quarto-xref"><span>小节 9.5</span></a> 中对 <strong>变异</strong> 这个术语的解释，此处再次做如下的强调。</p>
<p><strong>变异量</strong>（<em>the amount of variation</em>）是指一组数据中的变异性，即数据的波动或分散程度。这种波动可以是由多种因素引起的，包括个体差异、测量误差、随机误差等。在后续的翻译章节中，我们会根据具体的场景交叉使用 <strong>变异量</strong> 和 <strong>数据波动</strong>，如无特殊说明，这些指的都是一个概念。</p>
<p>同时，我们会避免使用 <strong>数据差异</strong>（<em>difference</em>） 来指代 <strong>变异量</strong> 的概念，因为在数学中，<strong>数据差异</strong> 更多指代两个数据之间的差值，因此和我们所讨论的数据的波动和分布程度并不是一个概念。</p>
</div>
</div>
<p>在本章中，我们将介绍一种技术可以用来检验如上案例中的假设。这种技术非常通用，可以用于推断与总体均值相关的大量参数，这种技术称之为 <strong>方差分析</strong>（<em>ANOVA, analysis of variance</em>）。</p>
</section>
<section id="sec-10_2" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="sec-10_2"><span class="header-section-number">10.2</span> 综述</h2>
<blockquote class="blockquote">
<p>本章内容还需要继续修改。</p>
</blockquote>
<p>在 <a href="../chapter_8/8.html#sec-8_4" class="quarto-xref"><span>小节 8.4</span></a>、<a href="../chapter_8/8.html#sec-8_5_1" class="quarto-xref"><span>小节 8.5.1</span></a>、<a href="../chapter_8/8.html#sec-8_6_1" class="quarto-xref"><span>小节 8.6.1</span></a>、<a href="../chapter_8/8.html#sec-8_7_1" class="quarto-xref"><span>小节 8.7.1</span></a> 章节中，我们研究了关于两个总体均值的假设检验。在本章中，我们将研究关于多个总体均值的假设检验。</p>
<p>在 <a href="#sec-10_3" class="quarto-xref"><span>小节 10.3</span></a> 中，假设我们有来自 <span class="math inline">\(m\)</span> 个不同总体的样本，每个样本的大小为 <span class="math inline">\(n\)</span>，我们希望使用这些数据来检验 <span class="math inline">\(m\)</span> 个总体均值相等的假设。对于这种场景，由于随机变量的均值仅取决于一个因素——即随机变量来自哪个样本——因此称这种情况为 <strong>单因素方差分析</strong>（<em>one-way analysis of variance</em>）。在 <a href="#sec-10_3_2" class="quarto-xref"><span>小节 10.3.2</span></a> 中，我们展示了如何获得 <span class="math inline">\(\binom{m}{2}\)</span> 对总体均值之间的 <strong>多重比较</strong>（<em>multiple comparisons</em>）。在第 <a href="#sec-10_3_3" class="quarto-xref"><span>小节 10.3.3</span></a> 中展示了当 <span class="math inline">\(m\)</span> 个样本之间的样本大小不同时，如何检验总体均值相等的假设。</p>
<p>在 <a href="#sec-10_4" class="quarto-xref"><span>小节 10.4</span></a> 和 <a href="#sec-10_5" class="quarto-xref"><span>小节 10.5</span></a> 中，我们将介绍由两个因素决定因变量均值的模型。在这些模型中，我们可以把自变量排列在一个矩阵中，在这个矩阵中，每一行和每一列都代表着一个因素或条件，矩阵中的元素代表着自变量的观测数据。此时，某个因变量的均值同时依赖于矩阵中的行和列。这种模型称为 <strong>双因素方差分析</strong>（<em>two-way analysis of variance</em>）。我们假设因变量的均值受到自变量的 <strong>加性方式</strong>（<em>additive fashion</em>）影响，具体地，第 <span class="math inline">\(i\)</span> 行、第 <span class="math inline">\(j\)</span> 列的变量对应的响应均值可以表示为 <span class="math inline">\(\mu + \alpha_i + \beta_j\)</span>。在 <a href="#sec-10_4" class="quarto-xref"><span>小节 10.4</span></a> 中，我们将介绍如何估计 <span class="math inline">\(\alpha_i\)</span>、<span class="math inline">\(\beta_j\)</span>。在 <a href="#sec-10_5" class="quarto-xref"><span>小节 10.5</span></a> 中将介绍如何进行检验假设，即某个特定因素不会影响结果的均值。</p>
<p>在 <a href="#sec-10_6" class="quarto-xref"><span>小节 10.6</span></a> 中，我们将介绍因变量的均值允许以非线性方式取决于自变量所在的行和列的情况，从而允许两个因素之间存在 <strong>交互作用</strong>（<em>interaction</em>）。我们还将介绍如何检验不存在交互作用的假设，以及关于不存在行效应和列效应对因变量均值影响的假设。</p>
<p>在本章中，我们假设所有的数据都服从正态分布，并且都具有相同（虽然未知）的方差 <span class="math inline">\(\sigma^2\)</span>。使用 ANOVA 来检验和总体均值有关的多个参数的原假设 <span class="math inline">\(H_0\)</span>，需要基于从共同的总体方差 $ ^2 $ 中推导出的两个估计量。第一个估计量是 <span class="math inline">\(\sigma^2\)</span> 的估计量，并且无论原假设是否为真，该估计量都是 <span class="math inline">\(\sigma^2\)</span> 的有效估计量。第二个估计量也是 <span class="math inline">\(\sigma^2\)</span> 的估计量，只是仅在 <span class="math inline">\(H_0\)</span> 为真时，该估计量才是 <span class="math inline">\(\sigma^2\)</span> 的有效估计量。此外，当 <span class="math inline">\(H_0\)</span> 不成立时，第二个估计量往往会超过 <span class="math inline">\(\sigma^2\)</span>。检验方法就是比较这两个估计量的值，并在第二个估计量与第一个估计量的比率足够大时拒绝 <span class="math inline">\(H_0\)</span>。换句话说，当 <span class="math inline">\(H_0\)</span> 为真时，这两个估计量应彼此接近（因为它们在这种情况下都是 <span class="math inline">\(\sigma^2\)</span> 的估计量），而当 <span class="math inline">\(H_0\)</span> 不为真时，第二个估计量通常应比第一个大，因此当第二个估计量显著大于第一个时，拒绝 <span class="math inline">\(H_0\)</span> 是自然的选择。</p>
<p>我们将使用和卡方随机变量有关的事实来获得方差 <span class="math inline">\(\sigma^2\)</span> 的估计量。假设 <span class="math inline">\(X_1, \dots, X_N\)</span> 是独立的正态分布随机变量，它们可能具有不同的均值但却具有相同的方差 <span class="math inline">\(\sigma^2\)</span>，并且设 <span class="math inline">\(\mu_i = E[X_i]\)</span>，其中 <span class="math inline">\(i = 1, \dots, N\)</span>。</p>
<p>由于随机变量</p>
<p><span class="math inline">\(Z_i = (X_i - \mu_i)/\sigma, \quad i = 1, \dots, N\)</span></p>
<p>服从标准正态分布，因此根据卡方分布随机变量的定义可知：</p>
<p><span id="eq-10_2_1"><span class="math display">\[
\sum_{i=1}^{N} Z_i^2 = \sum_{i=1}^{N} \frac{(X_i - \mu_i)^2}{\sigma^2}
\tag{10.1}\]</span></span></p>
<p>是一个自由度为 <span class="math inline">\(N\)</span> 的卡方分布随机变量。假设每一个 <span class="math inline">\(\mu_i, \ i = 1, \dots, N\)</span> 都可以表示为 <span class="math inline">\(k\)</span> 个未知参数的线性函数。同时，假设我们可以确定这 <span class="math inline">\(k\)</span> 个参数的估计量，从而给出 <span class="math inline">\(\mu_i\)</span> 的估计量。如果我们用 <span class="math inline">\(\hat{\mu}_i\)</span> 表示 <span class="math inline">\(\mu_i, \ i=1,...,N\)</span> 的估计量，那么可以证明：</p>
<p><span class="math inline">\(\sum_{i=1}^{N} \frac{(X_i - \hat{\mu}_i)^2}{\sigma^2}\)</span></p>
<p>服从自由度为 <span class="math inline">\(N - k\)</span> 的卡方分布。</p>
<p>换句话说，</p>
<p><span class="math inline">\(\sum_{i=1}^{N} \frac{(X_i - E[X_i])^2}{\sigma^2}\)</span></p>
<p>是一个自由度为 <span class="math inline">\(N\)</span> 的卡方分布随机变量。</p>
<p>如果我们用 <span class="math inline">\(k\)</span> 个参数的线性函数来表示每个 <span class="math inline">\(E[X_i]\)</span>，并用这 <span class="math inline">\(k\)</span> 个参数的估计量来替换这 <span class="math inline">\(k\)</span> 个参数，那么我们得到的表达式仍然是卡方分布，但是其自由度将因为每个参数由其估计量来代替而减少 1。</p>
<p>为了说明如上的结论，我们考虑所有均值已知并且相等的情况，即：</p>
<p><span class="math inline">\(E[X_i] = \mu, \quad i = 1, \dots, N\)</span></p>
<p>因为此时只有一个需要估计的参数，因此 <span class="math inline">\(k = 1\)</span>。把公共均值 <span class="math inline">\(\mu\)</span> 的估计量 <span class="math inline">\(\overline{X}\)</span> 代入 <a href="#eq-10_2_1" class="quarto-xref">式&nbsp;<span>10.1</span></a> 得到如下的量：</p>
<p><span id="eq-10_2_2"><span class="math display">\[
\sum_{i=1}^{N} \frac{(X_i - \overline{X})^2}{\sigma^2}
\tag{10.2}\]</span></span></p>
<p>则 <a href="#eq-10_2_2" class="quarto-xref">式&nbsp;<span>10.2</span></a> 是一个自由度为 <span class="math inline">\(N - 1\)</span> 的卡方分布随机变量。</p>
<p>在所有均值都相等的情况下，数据 <span class="math inline">\(X_1, \dots, X_N\)</span> 均来自同一个正态分布总体，因此 <a href="#eq-10_2_2" class="quarto-xref">式&nbsp;<span>10.2</span></a> 等价与 <span class="math inline">\((N - 1)S^2/\sigma^2\)</span>，其中 <span class="math inline">\(S^2\)</span> 是样本方差。换句话说，在这种场景下的结论就是：<span class="math inline">\((N - 1)S^2/\sigma^2\)</span> 是自由度为 <span class="math inline">\(N - 1\)</span> 的卡方分布随机变量（参见 <a href="../chapter_6/6.html#thm-6_5_1" class="quarto-xref">定理&nbsp;<span>6.2</span></a>）。</p>
</section>
<section id="sec-10_3" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="sec-10_3"><span class="header-section-number">10.3</span> 单因素方差分析</h2>
<p>有 <span class="math inline">\(m\)</span> 个独立的样本，每个样本的大小为 <span class="math inline">\(n\)</span>，其中第 <span class="math inline">\(i\)</span> 个样本——<span class="math inline">\(X_{i1}, X_{i2}, \dots, X_{in}\)</span>——是均值 <span class="math inline">\(\mu_i\)</span>、方差 <span class="math inline">\(\sigma^2\)</span> 均未知的正态分布随机变量。也就是说，</p>
<p><span class="math inline">\(X_{ij} \sim \mathcal{N}(\mu_i, \sigma^2), \quad i = 1, \dots, m, \quad j = 1, \dots, n\)</span></p>
<p>我们将对以下假设进行检验：</p>
<p><span class="math inline">\(H_0: \mu_1 = \mu_2 = \dots = \mu_m \quad vs \quad H_1: \text{并非所有的均值都相等}\)</span></p>
<p>也就是说，我们检验的原假设为所有总体的均值都是相等的，对应的备择假设为：至少存在两个总体的均值不同。如何理解我们所要进行的假设检验？想象一下，对于同一个物品而言，我们有 <span class="math inline">\(m\)</span> 种不同的处理方法，第 <span class="math inline">\(i\)</span> 种处理方法的结果是具有均值为 <span class="math inline">\(\mu_i\)</span>、方差为 <span class="math inline">\(\sigma^2\)</span> 的正态分布随机变量。然后我们感兴趣的是：把每种处理方法应用于 <span class="math inline">\(n\)</span> 个物品并分析结果，以检验 <em>所有处理方法的的效果相同</em> 的假设。</p>
<p>总共有 <span class="math inline">\(nm\)</span> 个独立的正态分布随机变量 <span class="math inline">\(X_{ij}\)</span>，因此 <span class="math inline">\(X_{ij}\)</span> 标准化之后的随机变量的平方和将是 自由度为 <span class="math inline">\(nm\)</span> 的卡方分布随机变量。</p>
<p><span id="eq-10_3_1"><span class="math display">\[
\sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - E[X_{ij}])^2}{\sigma^2} = \sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - \mu_i)^2}{\sigma^2} \sim \chi^2_{nm}
\tag{10.3}\]</span></span></p>
<p>为了获得 <span class="math inline">\(m\)</span> 个未知参数 <span class="math inline">\(\mu_1, \dots, \mu_m\)</span> 的估计量，设 <span class="math inline">\(X_i.\)</span> 表示第 <span class="math inline">\(i\)</span> 个样本中所有元素的平均值，即：</p>
<p><span class="math inline">\(X_i. = \frac{1}{n} \sum_{j=1}^{n} X_{ij}\)</span></p>
<p><span class="math inline">\(X_i.\)</span> 是第 <span class="math inline">\(i, \ i = 1, \dots, m\)</span> 个总体的样本均值，因此是总体均值 <span class="math inline">\(\mu_i\)</span> 的估计量。因此，用 <span class="math inline">\(\mu_i\)</span> 的估计量 <span class="math inline">\(X_i.\)</span> 替代 <a href="#eq-10_3_1" class="quarto-xref">式&nbsp;<span>10.3</span></a> 中的 <span class="math inline">\(\mu_i\)</span>，得到：</p>
<p><span id="eq-10_3_2"><span class="math display">\[
\sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - X_i.)^2}{\sigma^2}
\tag{10.4}\]</span></span></p>
<p><a href="#eq-10_3_2" class="quarto-xref">式&nbsp;<span>10.4</span></a> 是自由度为 <span class="math inline">\(nm - m\)</span> 的卡方分布。（每估计一个参数，自由度就会减少 1。）</p>
<p>令 <span class="math inline">\(SS_W = \sum_{i=1}^{m} \sum_{j=1}^{n} (X_{ij} - X_i.)^2\)</span></p>
<p>因此，<a href="#eq-10_3_2" class="quarto-xref">式&nbsp;<span>10.4</span></a> 变为 <span class="math inline">\(SS_W/\sigma^2\)</span>。</p>
<p>由于卡方分布随机变量的期望值等于其自由度，因此：<span class="math inline">\(E[SS_W/\sigma^2] = nm - m\)</span>，即 <span class="math inline">\(E\left[\frac{SS_W}{nm - m}\right] = \sigma^2\)</span>。</p>
<p>我们因此得到了方差 <span class="math inline">\(\sigma^2\)</span> 的第一个估计量，即 <span class="math inline">\(\frac{SS_W}{nm - m}\)</span>。注意，对于该估计量而言，我们并没有对原假设的真假作任何的假设。也就是说，无论原假设是否为真，我们都将有该估计量。</p>
<div id="def-10_3_1" class="theorem definition">
<p><span class="theorem-title"><strong>定义 10.1</strong></span> <strong>组内平方和</strong>（<em>within samples sum of squares</em>）</p>
<p><span class="math inline">\(SS_W = \sum_{i=1}^{m} \sum_{j=1}^{n} (X_{ij} - X_{i.})^2\)</span></p>
<p>因为 <span class="math inline">\(SS_W\)</span> 是利用样本均值代替 <a href="#eq-10_3_1" class="quarto-xref">式&nbsp;<span>10.3</span></a> 中的总体均值而得到的统计量，因此，我们称 <span class="math inline">\(SS_W\)</span> 为 <strong>组内平方和</strong>（<em>within samples sum of squares</em>）。</p>
<p><span class="math inline">\(\frac{SS_W}{nm - m}\)</span> 是 <span class="math inline">\(\sigma^2\)</span> 的一个估计量。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>方差 <span class="math inline">\(\sigma^2\)</span> 的第二个估计量是只有在原假设为真时的估计量。假设 <span class="math inline">\(H_0\)</span> 为真，因此所有总体均值 <span class="math inline">\(\mu_i\)</span> 相等，即 <span class="math inline">\(\mu_i = \mu\)</span>。此时，所有 <span class="math inline">\(m\)</span> 个样本均值 <span class="math inline">\(X_1., X_2., \dots, X_m.\)</span> 都将具有相同的均值 <span class="math inline">\(\mu\)</span> 和相同的方差 <span class="math inline">\(\sigma^2/n\)</span>。因此，对 <span class="math inline">\(X_i.\)</span> 标准化后的随机变量 <span class="math inline">\(\frac{X_i. - \mu}{\sqrt{\sigma^2 / n}} = \frac{\sqrt{n}(X_i. - \mu)}{\sigma}\)</span> 的平方和是一个自由度为 <span class="math inline">\(m\)</span> 的卡方分布随机变量。</p>
<p>即当 <span class="math inline">\(H_0\)</span> 为真时，</p>
<p><span id="eq-10_3_3"><span class="math display">\[
\frac{n \sum_{i=1}^{m} {(X_i. - \mu)^2}}{\sigma^2} \sim \chi^2_m
\tag{10.5}\]</span></span></p>
<p>当所有的总体均值都等于 <span class="math inline">\(\mu\)</span> 时，<span class="math inline">\(\mu\)</span> 的估计量是所有 <span class="math inline">\(nm\)</span> 个数据值的平均值。也就是说，<span class="math inline">\(\mu\)</span> 的估计量是 <span class="math inline">\(X_{..}\)</span>，即：</p>
<p><span class="math inline">\(X_{..} = \frac{1}{nm} \sum_{i=1}^{m} \sum_{j=1}^{n} X_{ij} = \frac{1}{m} \sum_{i=1}^{m} X_i.\)</span></p>
<p>用 <span class="math inline">\(X_{..}\)</span> 代替 <a href="#eq-10_3_3" class="quarto-xref">式&nbsp;<span>10.5</span></a> 中的位置参数 <span class="math inline">\(\mu\)</span>，则当 <span class="math inline">\(H_0\)</span> 为真时，有：</p>
<p><span class="math inline">\(\frac{n \sum_{i=1}^{m} {(X_i. - X_{..})^2}}{\sigma^2} \sim \chi_{m-1}^2\)</span></p>
<p>如果我们定义 <span class="math inline">\(SS_B\)</span> 为</p>
<p><span class="math inline">\(SS_B = n \sum_{i=1}^{m} (X_i. - X_{..})^2\)</span></p>
<p>那么，当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(SS_B/\sigma^2\)</span> 是自由度为 <span class="math inline">\(m - 1\)</span> 的卡方分布随机变量。</p>
<p>所以，当 <span class="math inline">\(H_0\)</span> 为真时，有：</p>
<p><span class="math inline">\(E\left[\frac{SS_B}{\sigma^2}\right] = m - 1\)</span></p>
<p>即，</p>
<p><span id="eq-10_3_4"><span class="math display">\[
E\left[\frac{SS_B}{(m - 1)}\right] = \sigma^2
\tag{10.6}\]</span></span></p>
<p>因此，当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(\frac{SS_B}{m - 1}\)</span> 也是 <span class="math inline">\(\sigma^2\)</span> 的估计量。</p>
<div id="def-10_3_2" class="theorem definition">
<p><span class="theorem-title"><strong>定义 10.2</strong></span> <strong>组间平方和</strong>（<em>between samples sum of squares</em>）</p>
<p><span class="math inline">\(SS_B = n \sum_{i=1}^{m} (X_i. - X_{..})^2\)</span></p>
<p>称为 <strong>组间平方和</strong>（<em>between samples sum of squares</em>）。当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(\frac{SS_B}{m - 1}\)</span> 是 <span class="math inline">\(\sigma^2\)</span> 的估计量。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>因此，我们得到：</p>
<p><span class="math inline">\(\begin{align} \frac{SS_W}{nm - m}, \quad &amp;\text{总是} \sigma^2 \text{的估计量} \\ \frac{SS_B}{m - 1}, \quad &amp;\text{仅当} H_0 \text{为真时} \sigma^2 \text{的估计量} \end{align}\)</span></p>
<p>可以证明（<em>在本节的末尾会对其进行证明</em>），当 <span class="math inline">\(H_0\)</span> 不为真时，<span class="math inline">\(\frac{SS_B}{m - 1}\)</span> 往往会超过 <span class="math inline">\(\sigma^2\)</span>，因此合理的做法是将检验统计量定义为：</p>
<p><span class="math inline">\(TS = \frac{SS_B/(m - 1)}{SS_W/(nm - m)}\)</span></p>
<p>并且当 <span class="math inline">\(TS\)</span> 足够大时，拒绝 <span class="math inline">\(H_0\)</span>。</p>
<p>接下来的问题就是：当 <span class="math inline">\(TS\)</span> 需要多大时才能拒绝 <span class="math inline">\(H_0\)</span>？可以证明：如果 <span class="math inline">\(H_0\)</span> 为真，那么 <span class="math inline">\(SS_B\)</span> 和 <span class="math inline">\(SS_W\)</span> 是独立的。这意味着，当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(TS\)</span> 服从分子自由度为 <span class="math inline">\(m - 1\)</span>、分母自由度为 <span class="math inline">\(nm - m\)</span> 的 <span class="math inline">\(F-\text{分布}\)</span>。我们使用符号 <span class="math inline">\(F_{r,s}\)</span> 表示分子自由度为 <span class="math inline">\(r\)</span>、分母自由度为 <span class="math inline">\(s\)</span> 的 <span class="math inline">\(F-\text{分布}\)</span> 随机变量，令 <span class="math inline">\(F_{\alpha, m-1, nm-m}\)</span> 表示这个 <span class="math inline">\(F-\text{分布}\)</span> 的 <span class="math inline">\(100(1 - \alpha)\%\)</span> 分位数，即：</p>
<p><span class="math inline">\(P\left \{F_{m-1, nm-m} &gt; F_{\alpha, m-1, nm-m}\right\} = \alpha\)</span></p>
<p>在显著性水平 <span class="math inline">\(\alpha\)</span> 时，<span class="math inline">\(H_0\)</span> 的检验为：</p>
<p><span id="eq-10_3_001"><span class="math display">\[
\begin{align}
\text{拒绝} H_0&amp;, \quad \text{如果} \frac{SS_B/(m - 1)}{SS_W/(nm - m)} \gt F_{\alpha, m-1, nm-m} \\
\text{不拒绝} H_0&amp;, \quad \text{其他}
\end{align}
\tag{10.7}\]</span></span></p>
<p>检验 <em>所有总体均值是否相等</em> 的假设的另一种计算方法是计算 <span class="math inline">\(p-\text{value}\)</span>。如果检验统计量 <span class="math inline">\(TS = v\)</span>，则 <span class="math inline">\(p-\text{value}\)</span> 由以下公式给出：</p>
<p><span class="math inline">\(p-\text{value} = P\{F_{m-1,nm-m} \geq v\}\)</span></p>
<p>在 R 中可以使用 <code>pf()</code> 计算 <span class="math inline">\(p-\text{value}\)</span>：</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 方式 1</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(v, m <span class="sc">-</span> <span class="dv">1</span>, nm <span class="sc">-</span> m)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 方式 2</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(v, m <span class="sc">-</span> <span class="dv">1</span>, nm <span class="sc">-</span> m, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-tip callout-titled" title="**平方和恒等式**（*the sum of squares identity*）">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>平方和恒等式</strong>（<em>the sum of squares identity</em>）
</div>
</div>
<div class="callout-body-container callout-body">
<p>如下的 <strong>代数恒等式</strong>（<em>algebraic identity</em>），称为 <strong>平方和恒等式</strong>（<em>sum of squares identity</em>），在手动计算时非常有用。</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \sum_{j=1}^{n} X_{ij}^2 = nm X^2_{..} + SS_B + SS_W\)</span></p>
<p>根据 <a href="#def-10_3_2" class="quarto-xref">定义&nbsp;<span>10.2</span></a>，我们定义 <span class="math inline">\(SS_B\)</span> 为：</p>
<p><span class="math inline">\(SS_B = n \sum_{i=1}^{m} (X_i. - X_{..})^2\)</span></p>
<p>在手动计算时，应首先计算 <span class="math inline">\(SS_B\)</span> 的值。一旦得到 <span class="math inline">\(SS_B\)</span> 后，可以根据 <strong>平方和恒等式</strong> 确定 <span class="math inline">\(SS_W\)</span>。在计算 <span class="math inline">\(SS_W\)</span> 的同时，我们也得到了 <span class="math inline">\(\sum_{i=1}^{m} \sum_{j=1}^{n} X_{ij}^2\)</span> 和 <span class="math inline">\(\overline{X}^2_{..}\)</span>。然后根据如下公式确定 <span class="math inline">\(SS_W\)</span>：</p>
<p><span class="math inline">\(SS_W = \sum_{i=1}^{m} \sum_{j=1}^{n} X_{ij}^2 - nm X^2_{..} - SS_B\)</span></p>
</div>
</div>
<div id="exr-10_3_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 10.1</strong></span> 一家汽车租赁公司使用 15 台相同的发动机在固定速度下测试 3 种不同的汽油品牌。每种汽油品牌都分配了其中的 5 台发动机，并且每台发动机分配了10 加仑汽油。以下的数据表示了不同发动机在汽油耗尽时所获得的总里程数：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>汽油品牌</th>
<th>里程（英里）</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>汽油 1</td>
<td>220, 251, 226, 246, 260</td>
</tr>
<tr class="even">
<td>汽油 2</td>
<td>244, 235, 232, 242, 225</td>
</tr>
<tr class="odd">
<td>汽油 3</td>
<td>252, 272, 250, 238, 256</td>
</tr>
</tbody>
</table>
<p>在 5% 的显著性水平下，检验假设：发动机的平均里程不受汽油品牌的影响。</p>
</div>
<div id="sol-10_3_a" class="proof solution">
<p><span class="proof-title"><em>解 10.1</em>. </span>我们手动计算 <a href="#exr-10_3_a" class="quarto-xref">习题&nbsp;<span>10.1</span></a> 的结果。</p>
<p>首先需要注意的是，每个数据值减去一个常数不会影响检验统计量的值。因此，我们从每个数据值中减去 220，得到以下信息：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>汽油品牌</th>
<th>里程（英里）</th>
<th><span class="math inline">\(\sum_j X_{ij}\)</span></th>
<th><span class="math inline">\(\sum_j X_{ij}^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0, 31, 6, 26, 40</td>
<td>103</td>
<td>3273</td>
</tr>
<tr class="even">
<td>2</td>
<td>24, 15, 12, 22, 5</td>
<td>78</td>
<td>1454</td>
</tr>
<tr class="odd">
<td>3</td>
<td>32, 52, 30, 18, 36</td>
<td>168</td>
<td>6248</td>
</tr>
</tbody>
</table>
<p>因为 <span class="math inline">\(m = 3\)</span>，<span class="math inline">\(n = 5\)</span>，并且</p>
<p><span class="math inline">\(\begin{align} X_1. &amp;= \frac{103}{5} = 20.6 \\ X_2. &amp;= \frac{78}{5} = 15.6 \\ X_3. &amp;= \frac{168}{5} = 33.6 \\ X_{..} &amp;= \frac{(103 + 78 + 168)}{15} = 23.2667 \\ X_{..}^2 &amp;= 541.3393 \end{align}\)</span></p>
<p>因此，</p>
<p><span class="math inline">\(SS_B = 5[(20.6 - 23.2667)^2 + (15.6 - 23.2667)^2 + (33.6 - 23.2667)^2] = 863.3335\)</span></p>
<p>此外，</p>
<p><span class="math inline">\(\sum \sum X_{ij}^2 = 3273 + 1454 + 6248 = 10975\)</span></p>
<p>根据平方和恒等式，</p>
<p><span class="math inline">\(SS_W = 10975 - 15(541.3393) - 863.3335 = 1991.5785\)</span></p>
<p>因此，检验统计量的值为：</p>
<p><span class="math inline">\(TS = \frac{863.3335 / 2}{1991.5785/12} = 2.60\)</span></p>
<p>使用 R 语言计算得到 <span class="math inline">\(p-\text{value}\)</span>：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(<span class="fl">2.60</span>, <span class="dv">2</span>, <span class="dv">12</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1153232</code></pre>
</div>
</div>
<p>我们同样可以使用 R 来计算整个过程：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>gas1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">31</span>, <span class="dv">6</span>, <span class="dv">26</span>, <span class="dv">40</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>gas2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">24</span>, <span class="dv">15</span>, <span class="dv">12</span>, <span class="dv">22</span>, <span class="dv">5</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>gas3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">32</span>, <span class="dv">52</span>, <span class="dv">30</span>, <span class="dv">18</span>, <span class="dv">36</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(gas1, gas2, gas3), <span class="at">ncol =</span> <span class="dv">5</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>x1. <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[<span class="dv">1</span>,])</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>x2. <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[<span class="dv">2</span>,])</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>x3. <span class="ot">&lt;-</span> <span class="fu">mean</span>(data[<span class="dv">3</span>,])</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>x.. <span class="ot">&lt;-</span> <span class="fu">mean</span>(data)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>SS_B <span class="ot">&lt;-</span> <span class="dv">5</span> <span class="sc">*</span> <span class="fu">sum</span>(<span class="fu">apply</span>(data, <span class="dv">1</span>, <span class="cf">function</span>(x) (<span class="fu">mean</span>(x) <span class="sc">-</span> <span class="fu">mean</span>(data))<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>x_ij_ss <span class="ot">&lt;-</span> <span class="fu">sum</span>(data<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>SS_W <span class="ot">&lt;-</span> x_ij_ss <span class="sc">-</span> <span class="dv">3</span> <span class="sc">*</span> <span class="dv">5</span> <span class="sc">*</span> x..<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> SS_B</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>TS <span class="ot">=</span> (SS_B <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">/</span> (SS_W <span class="sc">/</span> <span class="dv">12</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(TS, <span class="dv">2</span>, <span class="dv">12</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1152489</code></pre>
</div>
</div>
<p>由于 <span class="math inline">\(p-\text{value}\)</span> 大于 0.05，因此在 5% 的显著性水平下，我们不能拒绝汽品牌不会影响发动机里程的原假设。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>现在让我们证明：</p>
<p><span class="math inline">\(E\left[\frac{SS_B}{m-1}\right] \geq \sigma^2\)</span></p>
<p>当且仅当 <span class="math inline">\(H_0\)</span> 为真时，等号成立。</p>
<p>因此，我们必须证明：</p>
<p><span class="math inline">\(E\left[\frac{\sum_{i=1}^{m} (X_{i.} - X_{..})^2}{m-1}\right] \geq \frac{\sigma^2}{n}\)</span></p>
<p>当且仅当 <span class="math inline">\(H_0\)</span> 为真时，等号成立。</p>
<p>令 <span class="math inline">\(\mu_. = \frac{\sum_{i=1}^{m} \mu_i}{m}\)</span> 为 <span class="math inline">\(m\)</span> 个总体均值的平均值。此外，对于 <span class="math inline">\(i = 1, \dots, m\)</span>，令：</p>
<p><span class="math inline">\(Y_i = X_{i.} - \mu_i + \mu_.\)</span></p>
<p>由于 <span class="math inline">\(X_{i.}\)</span> 服从均值为 <span class="math inline">\(\mu_i\)</span>、方差为 <span class="math inline">\(\frac{\sigma^2}{n}\)</span> 的正态分布，因此 <span class="math inline">\(Y_i\)</span> 服从均值为 <span class="math inline">\(\mu_.\)</span>、方差为 <span class="math inline">\(\frac{\sigma^2}{n}\)</span> 的正态分布。因此，<span class="math inline">\(Y_1, \dots, Y_m\)</span> 构成了一个方差为 <span class="math inline">\(\frac{\sigma^2}{n}\)</span> 的正态分布总体的样本。</p>
<p>令 <span class="math inline">\(Y_{.}\)</span> 为 <span class="math inline">\(Y_i\)</span> 的均值：</p>
<p><span class="math inline">\(Y_{.} = \frac{\sum_{i=1}^{m} Y_i}{m} = X_{..} - \mu_. + \mu_. = X_{..}\)</span></p>
<p>则：</p>
<p><span class="math inline">\(X_{i.} - X_{..} = Y_i + \mu_i - \mu_. - Y_{.}\)</span></p>
<p>因此，</p>
<p><span class="math inline">\(\begin{align} E\left[\sum_{i=1}^{m} (X_{i.} - X_{..})^2\right] &amp;= E\left[\sum_{i=1}^{m} (Y_i - Y_{.} + \mu_i - \mu_.)^2\right] \\ &amp;= E\left[\sum_{i=1}^{m} \left[(Y_i - Y_{.})^2 + (\mu_i - \mu_.)^2 + 2(\mu_i - \mu_.)(Y_i - Y_{.})\right]\right] \\ &amp;= E\left[\sum_{i=1}^{m} (Y_i - Y_{.})^2\right] + \sum_{i=1}^{m} (\mu_i - \mu_.)^2 + 2\sum_{i=1}^{m} (\mu_i - \mu_.) E[Y_i - Y_{.}] \\ &amp;= (m-1)\frac{\sigma^2}{n} + \sum_{i=1}^{m} (\mu_i - \mu_.)^2 + 2\sum_{i=1}^{m} (\mu_i - \mu_.) E[Y_i - Y_{.}] \\ &amp;= (m-1)\frac{\sigma^2}{n} + \sum_{i=1}^{m} (\mu_i - \mu_.)^2\end{align}\)</span></p>
<p>在倒数第二个等式中，<span class="math inline">\(\sum_{i=1}^{m} \frac{(Y_i - Y_{.})^2}{(m-1)}\)</span> 是总体方差 <span class="math inline">\(\frac{\sigma^2}{n}\)</span> 的无偏估计量，并且最后一个等式是因为 <span class="math inline">\(E[Y_i - Y_{.}] = E[Y_i] - E[Y_{.}] = \mu_. - \mu_. = 0\)</span>。最后，在结果的等式两边都除以 <span class="math inline">\(m-1\)</span> 得到：</p>
<p><span class="math inline">\(E\left[\frac{\sum_{i=1}^{m} (X_{i.} - X_{..})^2}{m-1}\right] = \frac{\sigma^2}{n} + \frac{\sum_{i=1}^{m} (\mu_i - \mu_.)^2}{(m-1)}\)</span></p>
<p>因为 <span class="math inline">\(\sum_{i=1}^{m} (\mu_i - \mu_.)^2 \geq 0\)</span>，当且仅当所有 <span class="math inline">\(\mu_i\)</span> 相等时等号成立，所以 <span class="math inline">\(E\left[\frac{SS_B}{m-1}\right] \geq \sigma^2\)</span>。</p>
<p><a href="#tbl-10_1" class="quarto-xref">表&nbsp;<span>10.1</span></a> 总结了本节的结果：</p>
<div id="tbl-10_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-10_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;10.1: 单因素方差分析表；在显著性水平 <span class="math inline">\(\alpha\)</span> 下的检验，当 <span class="math inline">\(TS \geq F_{\alpha, m-1, nm-m}\)</span> 时拒绝 <span class="math inline">\(H_0\)</span>，否则不拒绝 <span class="math inline">\(H_0\)</span>；如果 <span class="math inline">\(TS = v\)</span>，则 <span class="math inline">\(p-\text{value} = P\{F_{m-1, nm-m} \geq v\}\)</span>
</figcaption>
<div aria-describedby="tbl-10_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>变异来源</th>
<th>平方和</th>
<th>自由度</th>
<th>检验统计量的值</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>组间</td>
<td><span class="math inline">\(SS_B = n\sum_{i=1}^{m} (X_{i.} - X_{..})^2\)</span></td>
<td><span class="math inline">\(m-1\)</span></td>
<td></td>
</tr>
<tr class="even">
<td>组内</td>
<td><span class="math inline">\(SS_W = \sum_{i=1}^{m} \sum_{j=1}^{n} (X_{ij} - X_{i.})^2\)</span></td>
<td><span class="math inline">\(nm-m\)</span></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td><span class="math inline">\(TS = \frac{SS_B/(m-1)}{SS_W/(nm-m)}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="sec-10_3_1" class="level3" data-number="10.3.1">
<h3 data-number="10.3.1" class="anchored" data-anchor-id="sec-10_3_1"><span class="header-section-number">10.3.1</span> 使用 R 计算统计量</h3>
<p>首先，需要注意的是：在 R 中定义矩阵时，矩阵元素默认按照列的方向来填充。例如，假设我们想要用 R 构建如下的矩阵并命名为 <code>A</code>：</p>
<p><span class="math display">\[\begin{pmatrix}
2 &amp; 1 &amp; 3 &amp; 4 \\
1 &amp; 5 &amp; 2 &amp; 6 \\
5 &amp; 3 &amp; 7 &amp; 9
\end{pmatrix}
\]</span></p>
<p>我们可以按如下方式进行：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">9</span>), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">4</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>R 中 <code>matrix()</code> 的定义是：在给出矩阵元素之后，给出行数，然后给出列数。因此，我们可以省略 <code>nrow =</code> 和 <code>ncol =</code>，直接定义 <code>A</code> 如下：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">9</span>), <span class="dv">3</span>, <span class="dv">4</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>要显示矩阵，我们会输入：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">9</span>), <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>A</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4]
[1,]    2    1    3    4
[2,]    1    5    2    6
[3,]    5    3    7    9</code></pre>
</div>
</div>
<p>当然，也可以通过列向量来初始化一个矩阵，例如：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>v1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">5</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>v2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">3</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>v3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">7</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>v4 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">9</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(v1, v2, v3, v4), <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>A</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3] [,4]
[1,]    2    1    3    4
[2,]    1    5    2    6
[3,]    5    3    7    9</code></pre>
</div>
</div>
<p>如果 <span class="math inline">\(A\)</span> 是一个矩阵，<span class="math inline">\(x\)</span> 是一个标量（<em>scalar</em>），那么 <span class="math inline">\(A + x\)</span> 是一个矩阵，其结果是将 <span class="math inline">\(x\)</span> 加到 <span class="math inline">\(A\)</span> 的每个元素上。矩阵的幂运算意味着矩阵中的每个元素都执行该幂次方运算。例如，如果 <span class="math inline">\(A\)</span> 是矩阵 <span class="math inline">\([a_{i,j}]\)</span>），那么 <span class="math inline">\(A^2\)</span> 就是矩阵 <span class="math inline">\([a_{i,j}^2]\)</span>。（此处的这种约定与“矩阵乘法”的概念并不一致。）</p>
<p>要对矩阵 <span class="math inline">\(A\)</span> 的所有元素求和，只需输入 R 命令 <code>sum(A)</code>；要获得矩阵 <span class="math inline">\(A\)</span> 中所有元素的平均值，使用 <code>mean(A)</code>。例如，如果我们想要计算矩阵 <span class="math inline">\(A\)</span> 中所有元素的平方求和，并且想将结果命名为 <code>ss</code>，我们可以输入：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">9</span>), <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">sum</span>(A<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>ss</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 260</code></pre>
</div>
</div>
<p>如果我们想计算矩阵 <span class="math inline">\(A\)</span> 中的每一行、或者每一列的元素的和，可以使用 <code>rowSums()</code>、<code>colSums()</code>。例如：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">9</span>), <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">sum</span>(A<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>ss</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 260</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rowSums</span>(A)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10 14 24</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(A)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  8  9 12 19</code></pre>
</div>
</div>
<p>如果想计算矩阵 <span class="math inline">\(A\)</span> 中的每一行、或者每一列的元素的平均值，可以使用 <code>rowMeans()</code>、<code>colMeans()</code>。</p>
<p>假设 <span class="math inline">\(A\)</span> 是一个具有 <span class="math inline">\(m\)</span> 行和 <span class="math inline">\(n\)</span> 列的矩阵，并且对于 <span class="math inline">\(b_1, \dots, b_m\)</span>，我们想要得到一个矩阵 <span class="math inline">\(B\)</span>。矩阵 <span class="math inline">\(B\)</span> 是从 <span class="math inline">\(A\)</span> 的第一行的每个元素中减去 <span class="math inline">\(b_1\)</span>，从 <span class="math inline">\(A\)</span> 的第二行的每个元素中减去 <span class="math inline">\(b_2\)</span>，……可以使用 R 中的 <code>sweep()</code> 来完成该操作：</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(...)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>(b1,...,bm)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">sweep</span>(A, <span class="dv">1</span>, b)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>例如：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">4</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 对矩阵 A 的每一行中的所有元素，都减去该行对应的均值</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(A)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">sweep</span>(A, <span class="dv">1</span>, b)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>B</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3]
[1,]    0    1   -1
[2,]   -1    1    0</code></pre>
</div>
</div>
<p>同样，假设 <span class="math inline">\(A\)</span> 是一个具有 <span class="math inline">\(m\)</span> 行和 <span class="math inline">\(n\)</span> 列的矩阵，并且对于 <span class="math inline">\(c_1, \dots, c_n\)</span>，我们想要得到一个矩阵 <span class="math inline">\(C\)</span>。矩阵 <span class="math inline">\(C\)</span> 是从 <span class="math inline">\(A\)</span> 的第一列的每个元素中减去 <span class="math inline">\(c_1\)</span>，从 <span class="math inline">\(A\)</span> 的第二列的每个元素中减去 <span class="math inline">\(c_2\)</span>，……同样可以使用 R 中的 <code>sweep()</code> 来完成该操作：</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(...)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">c</span>(c1,...,cn)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">sweep</span>(A, <span class="dv">2</span>, c)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>例如我们想让矩阵 <span class="math inline">\(A\)</span> 的每一列的所有元素都加上该列对应的均值：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">4</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 对矩阵 A 的每一列中的所有元素，都加上该列对应的均值</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(A)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">sweep</span>(A, <span class="dv">2</span>, <span class="sc">-</span>c)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>C</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3]
[1,]  4.5    7  3.5
[2,]  5.5    9  6.5</code></pre>
</div>
</div>
<p>接下来，我们将使用 R 来解决 <a href="#exr-10_3_a" class="quarto-xref">习题&nbsp;<span>10.1</span></a> 中所示的单因素方差分析问题。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>gas1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">220</span>, <span class="dv">251</span>, <span class="dv">226</span>, <span class="dv">246</span>, <span class="dv">260</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>gas2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">244</span>, <span class="dv">235</span>, <span class="dv">232</span>, <span class="dv">242</span>, <span class="dv">225</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>gas3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">252</span>, <span class="dv">272</span>, <span class="dv">250</span>, <span class="dv">238</span>, <span class="dv">256</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>G <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(gas1, gas2, gas3), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">nrow</span>(G)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">ncol</span>(G)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>rm <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(G)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>mm <span class="ot">&lt;-</span> <span class="fu">mean</span>(G)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> rm <span class="sc">-</span> mm</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>SS_B <span class="ot">&lt;-</span> n <span class="sc">*</span> <span class="fu">sum</span>(d<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>SS_W <span class="ot">&lt;-</span> <span class="fu">sum</span>(G<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> m <span class="sc">*</span> n <span class="sc">*</span> mm<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> SS_B</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>TS <span class="ot">=</span> (SS_B <span class="sc">/</span> (m <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">/</span> (SS_W <span class="sc">/</span> (m <span class="sc">*</span> n <span class="sc">-</span> m))</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(TS, m <span class="sc">-</span> <span class="dv">1</span>, m <span class="sc">*</span> n <span class="sc">-</span> m)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1152489</code></pre>
</div>
</div>
</section>
<section id="sec-10_3_2" class="level3" data-number="10.3.2">
<h3 data-number="10.3.2" class="anchored" data-anchor-id="sec-10_3_2"><span class="header-section-number">10.3.2</span> 样本均值的多重比较</h3>
<p>当我们拒绝了总体均值相等的原假设时，我们需要对不同总体的样本均值 <span class="math inline">\(\mu_1, \dots, \mu_m\)</span> 进行比较。实现这个目的常用方法是 <span class="math inline">\(T-\text{方法}\)</span>（<em>T-method</em>）。对于指定的 <span class="math inline">\(\alpha\)</span> 值，<span class="math inline">\(T-\text{方法}\)</span> 为所有的 <span class="math inline">\(\binom{m}{2}\)</span> 个差异 <span class="math inline">\(\mu_i - \mu_j\)</span>（<span class="math inline">\(i \neq j, i, j = 1, \dots, m\)</span>）提供了 <strong>联合置信区间</strong>（<em>joint condifence intervals</em>），从而使得这些所有的置信区间都将以 <span class="math inline">\(1 - \alpha\)</span> 的概率包含其对应的 <span class="math inline">\(\mu_i - \mu_j\)</span>。<span class="math inline">\(T-\text{方法}\)</span> 基于以下结果：</p>
<p>对于任何 <span class="math inline">\(i \neq j\)</span>，<span class="math inline">\(\mu_i - \mu_j\)</span> 都将以 <span class="math inline">\(1 - \alpha\)</span> 的概率包含于如下的区间：</p>
<p><span class="math inline">\(X_i. - X_j. - W &lt; \mu_i - \mu_j &lt; X_i. - X_j. + W\)</span></p>
<p>其中，</p>
<p><span class="math inline">\(W = \frac{1}{\sqrt{n}}C(m, nm - m, \alpha)\sqrt{\frac{SS_W}{nm - m}}\)</span></p>
<p>并且，附录中的 <a href="../appendices.html#tbl-A_2" class="quarto-xref">表&nbsp;<span>A.1</span></a> 给出了 <span class="math inline">\(\alpha = 0.05\)</span> 和 <span class="math inline">\(\alpha = 0.01\)</span> 时，<span class="math inline">\(C(m, nm - m, \alpha)\)</span> 的值。</p>
<div id="exr-10_3_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 10.2</strong></span> 某大学声称，对于该大学而言，来自三个不同高中的学生的第一学年的平均成绩没有差异。下表给出了随机选择的 12 名学生的第一学年的平均成绩，其中每个高中选取 4 名学生。假设显著性水平为 5%，这些数据是否推翻了该大学的主张？如果是，请确定来自不同高中的学生的平均成绩之间的差异的置信区间，以便我们可以在 95% 的置信水平下相信所有的置信区间都是成立的。</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>学校 1</th>
<th>学校 2</th>
<th>学校 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3.2</td>
<td>3.4</td>
<td>2.8</td>
</tr>
<tr class="even">
<td>3.4</td>
<td>3.0</td>
<td>2.6</td>
</tr>
<tr class="odd">
<td>3.3</td>
<td>3.7</td>
<td>3.0</td>
</tr>
<tr class="even">
<td>3.5</td>
<td>3.3</td>
<td>2.7</td>
</tr>
</tbody>
</table>
</div>
<div id="sol-10_3_b" class="proof solution">
<p><span class="proof-title"><em>解 10.2</em>. </span>首先，共有 <span class="math inline">\(m = 3\)</span> 个样本，每个样本的大小为 <span class="math inline">\(n = 4\)</span>。使用 R 进行计算得到的结果如下：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>school1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">3.2</span>, <span class="fl">3.4</span>, <span class="fl">3.3</span>, <span class="fl">3.5</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>school2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">3.4</span>, <span class="fl">3.0</span>, <span class="fl">3.7</span>, <span class="fl">3.3</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>school3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">2.8</span>, <span class="fl">2.6</span>, <span class="fl">3.0</span>, <span class="fl">2.7</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>G <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(school1, school2, school3), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">nrow</span>(G)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">ncol</span>(G)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>rm <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(G)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>mm <span class="ot">&lt;-</span> <span class="fu">mean</span>(G)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> rm <span class="sc">-</span> mm</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>SS_B <span class="ot">&lt;-</span> n <span class="sc">*</span> <span class="fu">sum</span>(d<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>SS_W <span class="ot">&lt;-</span> <span class="fu">sum</span>(G<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> m <span class="sc">*</span> n <span class="sc">*</span> mm<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> SS_B</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>TS <span class="ot">=</span> (SS_B <span class="sc">/</span> (m <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">/</span> (SS_W <span class="sc">/</span> (m <span class="sc">*</span> n <span class="sc">-</span> m))</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(TS, m <span class="sc">-</span> <span class="dv">1</span>, m <span class="sc">*</span> n <span class="sc">-</span> m)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00480163</code></pre>
</div>
</div>
<p>因此，我们会拒绝：来自三个高中的学生在第一学年的平均成绩相等的假设。</p>
<p>为了确定总体均值差异的置信区间，首先注意到样本均值为：</p>
<p><span class="math inline">\(X_1 = 3.350, \quad X_2 = 3.350, \quad X_3 = 2.775\)</span></p>
<p>从附录 <a href="../appendices.html#tbl-A_2" class="quarto-xref">表&nbsp;<span>A.1</span></a> 中，我们看到 <span class="math inline">\(C(3, 9, 0.05) = 3.95\)</span>，因此 <span class="math inline">\(W = \frac{3.95}{\sqrt{4}} \cdot \sqrt{0.0431} = 0.410\)</span>，我们得到以下置信区间：</p>
<p><span class="math inline">\(\begin{align} -0.410 &lt; &amp;\mu_1 - \mu_2 &lt; 0.410 \\ 0.165 &lt; &amp;\mu_1 - \mu_3 &lt; 0.985 \\ 0.165 &lt; &amp;\mu_2 - \mu_3 &lt; 0.985 \end{align}\)</span></p>
<p>因此，在 95% 的置信水平下，我们可以得出结论：</p>
<ul>
<li>第 3 所高中的学生平均成绩比第 1 所或第 2 所高中的学生的平均成绩低，差异在 0.165 到 0.985 之间</li>
<li>第 1 所高中和第 2 所高中的学生的平均成绩差异小于 0.410。<span class="math inline">\(\blacksquare\)</span></li>
</ul>
</div>
</section>
<section id="sec-10_3_3" class="level3" data-number="10.3.3">
<h3 data-number="10.3.3" class="anchored" data-anchor-id="sec-10_3_3"><span class="header-section-number">10.3.3</span> 样本大小不同的单因素方差分析</h3>
<p>在上一节的模型中，我们都假设每个样本的样本大小均相同。虽然在理想情况下，样本大小都是相同的，但实际中却无法总是保证不同样本之间的样本大小都相同。假设我们有 <span class="math inline">\(m\)</span> 个样本，样本的大小分别为 <span class="math inline">\(n_1, n_2, \dots, n_m\)</span>。也就是说，数据由独立随机变量 <span class="math inline">\(X_{ij}\)</span> 组成，其中 <span class="math inline">\(i = 1, \dots, m\)</span>，<span class="math inline">\(j = 1, \dots, n_i\)</span>，并且：</p>
<p><span class="math inline">\(X_{ij} \sim \mathcal{N}(\mu_i, \sigma^2)\)</span></p>
<p>我们仍然希望检验假设 <span class="math inline">\(H_0\)</span>，即所有样本的均值都相等。</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \sum_{j=1}^{n_i} \frac{(X_{ij} - E[X_{ij}])^2}{\sigma^2} = \sum_{i=1}^{m} \sum_{j=1}^{n_i} \frac{(X_{ij} - \mu_i)^2}{\sigma^2}\)</span></p>
<p>是自由度为 <span class="math inline">\(\sum_{i=1}^{m} n_i\)</span> 的卡方分布随机变量。因此，用 <span class="math inline">\(\mu_i\)</span> 的估计量 <span class="math inline">\(X_{i.}\)</span>（第 <span class="math inline">\(i\)</span> 个样本中的元素的平均值）代替每个总体的均值 <span class="math inline">\(\mu_i\)</span>，我们得到：</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \sum_{j=1}^{n_i} \frac{(X_{ij} - X_{i.})^2}{\sigma^2}\)</span></p>
<p>是自由度为 <span class="math inline">\(\sum_{i=1}^{m} n_i - m\)</span> 的卡方分布。因此，定义：</p>
<p><span class="math inline">\(SS_W = \sum_{i=1}^{m} \sum_{j=1}^{n_i} (X_{ij} - X_{i.})^2\)</span></p>
<p>则 <span class="math inline">\(SS_W / \left( \sum_{i=1}^{m} n_i - m \right)\)</span> 是 <span class="math inline">\(\sigma^2\)</span> 的无偏估计量。</p>
<p>此外，如果 <span class="math inline">\(H_0\)</span> 为真，并且 <span class="math inline">\(\mu\)</span> 是公同均值，则随机变量 <span class="math inline">\(X_{i.}\)</span> 将是独立的正态分布随机变量，且满足：</p>
<p><span class="math inline">\(E[X_{i.}] = \mu, \quad \text{Var}(X_{i.}) = \frac{\sigma^2}{n_i}\)</span></p>
<p>因此，当 <span class="math inline">\(H_0\)</span> 为真时：</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \frac{(X_{i.} - \mu)^2}{\sigma^2 / n_i} = \sum_{i=1}^{m} \frac{n_i (X_{i.} - \mu)^2}{\sigma^2}\)</span></p>
<p>是自由度为 <span class="math inline">\(m\)</span> 的卡方分布随机变量。因此，用估计量 <span class="math inline">\(X_{..}\)</span>（所有 <span class="math inline">\(X_{ij}\)</span> 的平均值）代替 <span class="math inline">\(\mu\)</span>，得到统计量：</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \frac{n_i (X_{i.} - X_{..})^2}{\sigma^2}\)</span></p>
<p>是自由度为 <span class="math inline">\(m - 1\)</span> 的卡方分布。因此，定义：</p>
<p><span class="math inline">\(SS_B = \sum_{i=1}^{m} n_i (X_{i.} - X_{..})^2\)</span></p>
<p>可以得出，当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(SS_B / (m - 1)\)</span> 也是 <span class="math inline">\(\sigma^2\)</span> 的无偏估计量。</p>
<p>可以证明，当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(SS_B\)</span> 和 <span class="math inline">\(SS_W\)</span> 是独立的，所以统计量：</p>
<p><span class="math inline">\(\frac{SS_B / (m - 1)}{SS_W / \left( \sum_{i=1}^{m} n_i - m \right)}\)</span></p>
<p>是一个分子自由度为 <span class="math inline">\(m - 1\)</span>、分母自由度为 <span class="math inline">\(\sum_{i=1}^{m} n_i - m\)</span> 的 <span class="math inline">\(F-\text{分布}\)</span> 随机变量。因此，我们可以得出显著性水平 为 <span class="math inline">\(\alpha\)</span> 下的零假设的检验结论：</p>
<p><span class="math display">\[
\begin{align}
\text{拒绝} H_0,&amp; \quad \text{如果} \frac{SS_B / (m - 1)}{SS_W / \left( \sum_{i=1}^{m} n_i - m \right)} &gt; F_{m-1, N, \alpha} \\
\text{接受} H_0,&amp; \quad \text{否则}
\end{align}
\]</span></p>
<p>其中，<span class="math inline">\(N = \sum_{i=1}^{m} n_i - m\)</span>。</p>
<div class="callout callout-style-default callout-tip callout-titled" title="备注">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
备注
</div>
</div>
<div class="callout-body-container callout-body">
<p>当样本大小不同时，我们称之为 <strong>不均衡场景</strong>（<em>unbalanced case</em>）。因为在样本均衡设计中，检验统计量对于总体方差不相同的场景相对不那么敏感。因此，样本均衡设计通常更稳健。所以，与不均衡场景相比，在设计检验时，我们需要尽可能的选择均衡的样本。</p>
</div>
</div>
</section>
</section>
<section id="sec-10_4" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="sec-10_4"><span class="header-section-number">10.4</span> 双因素方差分析：引言和参数估计</h2>
<p>虽然我们可以用 <a href="#sec-10_3" class="quarto-xref"><span>小节 10.3</span></a> 中的模型研究数据集中的单个因素的影响，但我们还可以研究多个因素的影响。在本节中，我们假设每个数据值都受到两个因素的影响。</p>
<div id="exm-10_4_a" class="theorem example">
<p><span class="theorem-title"><strong>例 10.1</strong></span> 对 5 名学生进行了 4 种不同标准的阅读测试，测试的结果如下表所示。表中的 20 个数据受到两个因素的影响：考试因素和学生因素。考试因素有 4 个可能的取值或 <strong>水平</strong>（<em>levels</em>），学生因素有 5 个可能的取值或 <strong>水平</strong>（<em>levels</em>）。</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>考试标准</th>
<th>学生 1</th>
<th>学生 2</th>
<th>学生 3</th>
<th>学生 4</th>
<th>学生 5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>75</td>
<td>73</td>
<td>60</td>
<td>70</td>
<td>86</td>
</tr>
<tr class="even">
<td>2</td>
<td>78</td>
<td>71</td>
<td>64</td>
<td>72</td>
<td>90</td>
</tr>
<tr class="odd">
<td>3</td>
<td>80</td>
<td>69</td>
<td>62</td>
<td>70</td>
<td>85</td>
</tr>
<tr class="even">
<td>4</td>
<td>73</td>
<td>67</td>
<td>63</td>
<td>80</td>
<td>92</td>
</tr>
</tbody>
</table>
<p>通常情况下，我们假设第一个因素有 <span class="math inline">\(m\)</span> 个可能的 <strong>水平</strong>，第二个因素有 <span class="math inline">\(n\)</span> 个可能的 <strong>水平</strong>。令 <span class="math inline">\(X_{ij}\)</span> 表示当第一个因素处于第 <span class="math inline">\(i\)</span> 个水平，第二个因素处于第 <span class="math inline">\(j\)</span> 个水平时获得的值。我们经常将数据集表示为如下的数组：</p>
<p><span class="math display">\[
\begin{matrix}
X_{11} &amp; X_{12} &amp; \dots &amp; X_{1j} &amp; \dots &amp; X_{1n} \\
X_{21} &amp; X_{22} &amp; \dots &amp; X_{2j} &amp; \dots &amp; X_{2n} \\
\vdots &amp; \vdots &amp; \dots &amp; \vdots &amp; \dots &amp; \vdots \\
X_{i1} &amp; X_{i2} &amp; \dots &amp; X_{ij} &amp; \dots &amp; X_{in} \\
\vdots &amp; \vdots &amp; \dots &amp; \vdots &amp; \dots &amp; \vdots \\
X_{m1} &amp; X_{m2} &amp; \dots &amp; X_{mj} &amp; \dots &amp; X_{mn}
\end{matrix}
\]</span></p>
<p>因此，我们称第一个因素为 “行” 因素，称第二个因素为 “列” 因素。</p>
<p>如 <a href="#sec-10_3" class="quarto-xref"><span>小节 10.3</span></a> 中，我们假设数据 <span class="math inline">\(X_{ij}, i = 1, \dots, m; j = 1, \dots, n\)</span> 是具有相同方差 <span class="math inline">\(\sigma^2\)</span> 的独立正态分布随机变量。然而，在第 <a href="#sec-10_3" class="quarto-xref"><span>小节 10.3</span></a> 中，我们假设，只有一个因素（即它所属样本的均值）会影响数据点的均值。而在本节中，我们则假设，数据点的均值以 <strong>加性方式</strong>（<em>additive manner</em>）取决于其所在的行和列。</p>
<p>在 <a href="#sec-10_3" class="quarto-xref"><span>小节 10.3</span></a> 的模型中，我们令 <span class="math inline">\(X_{ij}\)</span> 表示第 <span class="math inline">\(i\)</span> 个样本中第 <span class="math inline">\(j\)</span> 个成员的值，那么模型可以符号化表示为：</p>
<p><span class="math inline">\(E[X_{ij}] = \mu_i\)</span></p>
<p>如果我们令 <span class="math inline">\(\mu\)</span> 表示 <span class="math inline">\(\mu_i\)</span> 的平均值，即</p>
<p><span class="math inline">\(\mu = \frac{1}{m} \sum_{i=1}^{m} \mu_i\)</span></p>
<p>那么我们可以将模型重写为</p>
<p><span class="math inline">\(E[X_{ij}] = \mu + \alpha_i\)</span></p>
<p>其中 <span class="math inline">\(\alpha_i = \mu_i - \mu\)</span>。根据 <span class="math inline">\(\alpha_i\)</span> 的定义：<span class="math inline">\(\mu_i\)</span> 相对于平均值 <span class="math inline">\(\mu\)</span> 的偏差，我们很容易得到：</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \alpha_i = 0\)</span></p>
<p>一个 <strong>双因素加性模型</strong> 也可以用行偏差和列偏差来表示。如果我们令 <span class="math inline">\(\mu_{ij} = E[X_{ij}]\)</span>，则加性模型假设对于某些常数 <span class="math inline">\(a_i\)</span>（<span class="math inline">\(i = 1, \dots, m\)</span>）和 <span class="math inline">\(b_j\)</span>（<span class="math inline">\(j = 1, \dots, n\)</span>）有：</p>
<p><span class="math inline">\(\mu_{ij} = a_i + b_j\)</span></p>
<p>令：</p>
<p><span class="math inline">\(\mu_{i.} = \frac{1}{n} \sum_{j=1}^{n} \mu_{ij}, \quad \mu_{.j} = \frac{1}{m} \sum_{i=1}^{m} \mu_{ij}, \quad \mu_{..} = \frac{1}{mn} \sum_{i=1}^{m} \sum_{j=1}^{n} \mu_{ij}\)</span></p>
<p>同样地，我们定义</p>
<p><span class="math inline">\(a_{.} = \frac{1}{m} \sum_{i=1}^{m} a_i, \quad b_{.} = \frac{1}{n} \sum_{j=1}^{n} b_j\)</span></p>
<p>因为：</p>
<p><span class="math inline">\(\mu_{i.} = \frac{1}{n} \sum_{j=1}^{n} (a_i + b_j)/n = a_i + b_{.}\)</span></p>
<p>同理，</p>
<p><span class="math inline">\(\mu_{.j} = a_{.} + b_j, \quad \mu_{..} = a_{.} + b_{.}\)</span></p>
<p>如果我们令：</p>
<p><span class="math inline">\(\mu = \mu_{..} = a_{.} + b_{.}\)</span></p>
<p><span class="math inline">\(\alpha_i = \mu_{i.} - \mu = a_i - a_{.}\)</span></p>
<p><span class="math inline">\(\beta_j = \mu_{.j} - \mu = b_j - b_.\)</span></p>
<p>则我们有：</p>
<p><span class="math inline">\(\mu_{ij} = E[X_{ij}] = \mu + \alpha_i + \beta_j\)</span></p>
<p>其中，<span class="math inline">\(\sum_{i=1}^{m}{\alpha_i} = \sum_{j=1}^{n}{\beta_j} = 0\)</span></p>
<p>我们称 <span class="math inline">\(\mu\)</span> 被为 <strong>总均值</strong>（<em>the grand mean</em>），<span class="math inline">\(\alpha_i\)</span> 为由第 <span class="math inline">\(i\)</span> 行导致的相对于 <strong>总均值</strong> 的偏差，<span class="math inline">\(\beta_j\)</span> 为由第 <span class="math inline">\(j\)</span> 列导致的相对于 <strong>总均值</strong> 的偏差。</p>
<p>接下来，我们确定参数 <span class="math inline">\(\mu, \alpha_i, \beta_j\)</span>（<span class="math inline">\(i = 1, \dots, m\)</span>, <span class="math inline">\(j = 1, \dots, n\)</span>）的估计量。</p>
<p>令</p>
<p><span class="math inline">\(X_{i.} = \frac{1}{n} \sum_{j=1}^{n} X_{ij} \quad \text{表示第} i \text{行中的值的平均值}\)</span></p>
<p><span class="math inline">\(X_{.j} = \frac{1}{m} \sum_{i=1}^{m} X_{ij} \quad \text{表示第} j \text{列中的值的平均值}\)</span></p>
<p><span class="math inline">\(X_{..} = \frac{1}{nm} \sum_{i=1}^{m} \sum_{j=1}^{n} X_{ij} \quad \text{表示所有数据值的平均值}\)</span></p>
<p>则：</p>
<p><span class="math display">\[
\begin{align}
E[X_{i.}] &amp;= \frac{1}{n} \sum_{j=1}^{n} E[X_{ij}] \\
&amp;= \mu + \frac{1}{n} \sum_{j=1}^{n} \alpha_i + \frac{1}{n} \sum_{j=1}^{n} \beta_j \\
&amp;= \mu + \alpha_i \quad \because \sum_{j=1}^{n} \beta_j = 0
\end{align}
\]</span></p>
<p>同理有：</p>
<p><span class="math inline">\(E[X_{.j}] = \mu + \beta_j\)</span></p>
<p><span class="math inline">\(E[X_{..}] = \mu\)</span></p>
<p>因为上述等式等价于：</p>
<p><span class="math display">\[
\begin{align}
E[X_{..}] &amp;= \mu \\
E[X_{i.} - X_{..}] &amp;= \alpha_i \\
E[X_{.j} - X_{..}] &amp;= \beta_j
\end{align}
\]</span></p>
<p>我们发现，参数 <span class="math inline">\(\mu, \alpha_i, \beta_j\)</span> 的无偏估计量，记作 <span class="math inline">\(\hat{\mu}, \hat{\alpha_i}, \hat{\beta_j}\)</span> 为：</p>
<p><span class="math display">\[
\begin{align}
\hat{\mu} &amp;= X_{..} \\
\hat{\alpha_i} &amp;= X_{i.} - X_{..} \\
\hat{\beta_j} &amp;= X_{.j} - X_{..}
\end{align}
\]</span></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="exr-10_4_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 10.3</strong></span> 下表的数据来自 <a href="#exm-10_4_a" class="quarto-xref">例&nbsp;<span>10.1</span></a>，请使用这些数据估计模型的参数。</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>考试</th>
<th>学生 1</th>
<th>学生 2</th>
<th>学生 3</th>
<th>学生 4</th>
<th>学生 5</th>
<th>行总计</th>
<th><span class="math inline">\(X_{i.}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>75</td>
<td>73</td>
<td>60</td>
<td>70</td>
<td>86</td>
<td>364</td>
<td>72.8</td>
</tr>
<tr class="even">
<td>2</td>
<td>78</td>
<td>71</td>
<td>64</td>
<td>72</td>
<td>90</td>
<td>375</td>
<td>75</td>
</tr>
<tr class="odd">
<td>3</td>
<td>80</td>
<td>69</td>
<td>62</td>
<td>70</td>
<td>85</td>
<td>366</td>
<td>73.2</td>
</tr>
<tr class="even">
<td>4</td>
<td>73</td>
<td>67</td>
<td>63</td>
<td>80</td>
<td>92</td>
<td>375</td>
<td>75</td>
</tr>
<tr class="odd">
<td>列总计</td>
<td>306</td>
<td>280</td>
<td>249</td>
<td>292</td>
<td>353</td>
<td>1480 (grand total)</td>
<td></td>
</tr>
<tr class="even">
<td><span class="math inline">\(X_{.j}\)</span></td>
<td>76.5</td>
<td>70</td>
<td>62.25</td>
<td>73</td>
<td>88.25</td>
<td><span class="math inline">\(X_{..} = \frac{1480}{20} = 74\)</span></td>
<td></td>
</tr>
</tbody>
</table>
</div>
<div id="sol-10_4_b" class="proof solution">
<p><span class="proof-title"><em>解 10.3</em>. </span>估计量为：</p>
<p><span class="math inline">\(\hat{\mu} = 74\)</span></p>
<p><span class="math inline">\(\hat{\alpha_1} = 72.8 - 74 = -1.2 \quad \hat{\beta_1} = 76.5 - 74 = 2.5\)</span></p>
<p><span class="math inline">\(\hat{\alpha_2} = 75 - 74 = 1 \quad \hat{\beta_2} = 70 - 74 = -4\)</span></p>
<p><span class="math inline">\(\hat{\alpha_3} = 73.2 - 74 = -0.8 \quad \hat{\beta_3} = 62.25 - 74 = -11.75\)</span></p>
<p><span class="math inline">\(\hat{\alpha_4} = 75 - 74 = 1 \quad \hat{\beta_4} = 73 - 74 = -1\)</span></p>
<p><span class="math inline">\(\hat{\beta_5} = 88.25 - 74 = 14.25\)</span></p>
<p>因此，如果随机选择一名学生并随机指定一场考试，那么我们对其平均分的估计是 <span class="math inline">\(\hat{\mu} = 74\)</span>。如果我们知道该学生选择了考试 <span class="math inline">\(i\)</span>，则这会使我们对其平均分的估计增加 <span class="math inline">\(\hat{\alpha_i}\)</span>；如果我们知道学生的编号是 <span class="math inline">\(j\)</span>，则这会使我们对其平均分的估计增加 <span class="math inline">\(\hat{\beta_j}\)</span>。</p>
<p>例如，我们会估计第 1 场考试中第 2 名学生的分数是一个随机变量，其均值为：</p>
<p><span class="math inline">\(\hat{\mu} + \hat{\alpha_1} + \hat{\beta_2} = 74 - 1.2 - 4 = 68.8\)</span></p>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
</section>
<section id="sec-10_5" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="sec-10_5"><span class="header-section-number">10.5</span> 双因素方差分析：检验假设</h2>
<p>考虑一个双因素模型，数据为 <span class="math inline">\(X_{ij}\)</span>，<span class="math inline">\(i = 1, \dots, m\)</span>，<span class="math inline">\(j = 1, \dots, n\)</span>。假设 <span class="math inline">\(X_{ij}\)</span> 是具有共同方差 <span class="math inline">\(\sigma^2\)</span> 的独立正态分布随机变量，且其均值满足以下条件：</p>
<p><span class="math inline">\(E[X_{ij}] = \mu + \alpha_i + \beta_j\)</span></p>
<p>其中，</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \alpha_i = \sum_{j=1}^{n} \beta_j = 0\)</span></p>
<p>在本节中，我们将关注检验如下的假设：</p>
<p><span class="math inline">\(H_0: \text{所有的} \ \alpha_i = 0 \quad vs \quad H_1: \text{并非所有的} \ \alpha_i \ \text{都等于} 0\)</span></p>
<p>该原假设表明 <span class="math inline">\(X_{ij}\)</span> 不存在行效应，即某个数据的值不受其所在行的因素水平的影响。</p>
<p>类似的，我们还将关注有关列的假设，即</p>
<p><span class="math inline">\(H_0: \text{所有的} \ \beta_j = 0 \quad vs \quad H_1: \text{并非所有的} \ \beta_j \ \text{都等于} 0\)</span></p>
<p>我们将使用 <strong>方差分析</strong>（<em>analysis of variance</em>） 的方法来检验上述原假设。在 <strong>方差分析</strong> 中，我们会得到方差 <span class="math inline">\(\sigma^2\)</span> 的两个不同的估计量：</p>
<ul>
<li>第一个估计量总是有效估计量。</li>
<li>第二个估计量只有在原假设为真时才是有效估计量。</li>
<li>此外，当原假设不为真时，第二个估计量往往大于 <span class="math inline">\(\sigma^2\)</span>。</li>
</ul>
<p>为了获得 <span class="math inline">\(\sigma^2\)</span> 的第一个估计量，我们需要基于如下的事实：</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - E[X_{ij}])^2}{\sigma^2} = \sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - \mu - \alpha_i - \beta_j)^2}{\sigma^2}\)</span></p>
<p>是自由度为 <span class="math inline">\(nm\)</span> 的卡方随机变量。如果用未知参数的估计量替换对应的未知参数 <span class="math inline">\(\mu, \alpha_1, \alpha_2, \dots, \alpha_m, \beta_1, \beta_2, \dots, \beta_n\)</span>，则结果仍然是一个卡方分布随机变量，但其自由度将随着估计参数的增加而对应的减少（每估计一个参数，自由度减 1）。由于 <span class="math inline">\(\sum_{i=1}^{m} \alpha_i = \sum_{j=1}^{n} \beta_j = 0\)</span>，这意味着当我们估计了 <span class="math inline">\(m-1\)</span> 个 <span class="math inline">\(\alpha_i\)</span> 后，最后一个 <span class="math inline">\(\alpha_i\)</span> 也随之确定；同理，我们仅需要估计 <span class="math inline">\(n-1\)</span> 个 <span class="math inline">\(\beta_j\)</span> 就可以确定所有的 <span class="math inline">\(\beta_j\)</span>。最后，因为 <span class="math inline">\(\mu\)</span> 也需要估计，所以需要估计的参数总数为：</p>
<p><span class="math inline">\(1 + m - 1 + n - 1 = n + m - 1\)</span></p>
<p>因此，</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - \hat{\mu} - \hat{\alpha_i} - \hat{\beta_j})^2}{\sigma^2}\)</span></p>
<p>是一个自由度为 <span class="math inline">\(nm - (n + m - 1) = (n-1)(m-1)\)</span> 的卡方分布随机变量。</p>
<p>因为 <span class="math inline">\(\hat{\mu} = X_{..}, \hat{\alpha_i} = X_{i.} - X_{..}, \hat{\beta_j} = X_{.j} - X_{..}\)</span>，所以有：</p>
<p><span id="eq-10_5_1"><span class="math display">\[
\sum_{i=1}^{m} \sum_{j=1}^{n} \frac{(X_{ij} - X_{i.} - X_{.j} + X_{..})^2}{\sigma^2}
\tag{10.8}\]</span></span></p>
<p>是一个自由度为 <span class="math inline">\((n-1)(m-1)\)</span> 的卡方分布随机变量。</p>
<div id="def-10_5_1" class="theorem definition">
<p><span class="theorem-title"><strong>定义 10.3</strong></span> <strong>误差平方和</strong>（<em>error sum of squares</em>）</p>
<p>我们称统计量 <span class="math inline">\(SS_e\)</span> 为 <strong>误差平方和</strong>：</p>
<p><span class="math inline">\(SS_e = \sum_{i=1}^{m} \sum_{j=1}^{n} (X_{ij} - X_{i.} - X_{.j} + X_{..})^2\)</span> <span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>如果我们认为某个值与我们所估计的均值之间的差异是“误差”（<em>error</em>），那么 <span class="math inline">\(SS_e\)</span> 就等于这些误差的平方的总和。由于 <span class="math inline">\(SS_e / \sigma^2\)</span> 就是 <a href="#eq-10_5_1" class="quarto-xref">式&nbsp;<span>10.8</span></a>，所以我们知道 <span class="math inline">\(SS_e / \sigma^2\)</span> 是一个自由度为 <span class="math inline">\((n-1)(m-1)\)</span> 的卡方分布随机变量。因为卡方分布随机变量的期望值等于其自由度，所以：</p>
<p><span class="math inline">\(E[SS_e/\sigma^2] = (n-1)(m-1)\)</span></p>
<p>即：</p>
<p><span class="math inline">\(E\left[\frac{SS_e}{(n-1)(m-1)}\right] = \sigma^2\)</span></p>
<p>所以：</p>
<p><span class="math inline">\(\frac{SS_e}{(n-1)(m-1)}\)</span> 是 <span class="math inline">\(\sigma^2\)</span> 的无偏估计量。</p>
<p>假设我们现在想要检验 <em>不存在行效应</em> 的原假设，即我们想要检验</p>
<p><span class="math inline">\(H_0: \text{所有的} \alpha_i = 0 \quad vs \quad  H_1: \text{并不是所有的} \alpha_i \text{都为 0}\)</span></p>
<p>为了获得 <span class="math inline">\(\sigma^2\)</span> 的第二个估计量，考虑行均值 <span class="math inline">\(X_{i.}\)</span>，<span class="math inline">\(i = 1, \ldots, m\)</span>。当 <span class="math inline">\(H_0\)</span> 为真时，每个 <span class="math inline">\(\alpha_i = 0\)</span>，因此</p>
<p><span class="math inline">\(E[X_{i.}] = \mu + \alpha_i = \mu\)</span></p>
<p>因为每个 <span class="math inline">\(X_{i.}\)</span> 是 <span class="math inline">\(n\)</span> 个随机变量的均值，而每个随机变量的方差为 <span class="math inline">\(\sigma^2\)</span>，因此有</p>
<p><span class="math inline">\(\text{Var}(X_{i.}) = \frac{\sigma^2}{n}\)</span></p>
<p>因此当 <span class="math inline">\(H_0\)</span> 为真时：</p>
<p><span class="math inline">\(\sum_{i=1}^{m}(X_{i.} - E[X_{i.}])^2 / \text{Var}(X_{i.}) = n \sum_{i=1}^{m}(X_{i.} - \mu)^2 / \sigma^2\)</span></p>
<p>将服从自由度为 <span class="math inline">\(m\)</span> 的卡方分布。如果我们现在用 <span class="math inline">\(X_{..}\)</span> （<span class="math inline">\(\mu\)</span> 的估计量）代替 <span class="math inline">\(\mu\)</span>，那么得到的表达式仍将是卡方分布，但自由度会减少 1。因此，当 <span class="math inline">\(H_0\)</span> 为真时，有以下结论：</p>
<p><span class="math inline">\(n \sum_{i=1}^{m}(X_{i.} - X_{..})^2 / \sigma^2\)</span></p>
<p>服从自由度为 <span class="math inline">\(m-1\)</span> 的卡方分布。</p>
<div id="def-10_5_2" class="theorem definition">
<p><span class="theorem-title"><strong>定义 10.4</strong></span> <strong>行平方和</strong>（<em>row sum of squares</em>）</p>
<p>我们称统计量 <span class="math inline">\(SS_r\)</span> 为 <strong>行平方和</strong>：</p>
<p><span class="math inline">\(SS_r = n \sum_{i=1}^{m}(X_{i.} - X_{..})^2\)</span></p>
</div>
<p>当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(\frac{SS_r}{\sigma^2}\)</span> 服从自由度为 <span class="math inline">\(m-1\)</span> 的卡方分布。因此，当 <span class="math inline">\(H_0\)</span> 为真时，有</p>
<p><span class="math inline">\(E[SS_r / \sigma^2] = m-1\)</span></p>
<p>即：</p>
<p><span class="math inline">\(E[SS_r / (m-1)] = \sigma^2\)</span></p>
<p>此外，可以证明，当 <span class="math inline">\(H_0\)</span> 不为真时，<span class="math inline">\(\frac{SS_r}{(m-1)}\)</span> 的值将大于 <span class="math inline">\(\sigma^2\)</span>。</p>
<p>因此，我们再次获得了 <span class="math inline">\(\sigma^2\)</span> 的两个估计量：</p>
<ul>
<li>无论原假设是否为真，第一个估计量 <span class="math inline">\(\frac{SS_e}{(n-1)(m-1)}\)</span> 都是有效估计量。</li>
<li>而仅在 <span class="math inline">\(H_0\)</span> 为真时，第二个估计量 <span class="math inline">\(\frac{SS_r}{(m-1)}\)</span> 才是有效估计量；当 <span class="math inline">\(H_0\)</span> 不为真时，<span class="math inline">\(\frac{SS_r}{(m-1)}\)</span> 将大于 <span class="math inline">\(\sigma^2\)</span>。</li>
</ul>
<p>基于 <span class="math inline">\(\sigma^2\)</span> 的两个估计量（<span class="math inline">\(SS_e\)</span> 和 <span class="math inline">\(SS_r\)</span>）的比值对 <span class="math inline">\(H_0\)</span> 进行检验。具体来说，我们使用如下的检验统计量：</p>
<p><span class="math inline">\(TS = \frac{SS_r/(m-1)}{SS_e/[(n-1)(m-1)]}\)</span></p>
<p>可以证明，当 <span class="math inline">\(H_0\)</span> 为真时，估计量是独立的，所以在显著性水平为 <span class="math inline">\(\alpha\)</span> 下的检验为：</p>
<p><span class="math inline">\(\begin{align} \text{拒绝} \quad &amp;H_0, \quad \text{如果} \ TS \geq F_{\alpha, m-1, (n-1)(m-1)} \\ \text{不拒绝} \quad &amp;H_0, \quad \text{否则}\end{align}\)</span></p>
<p>或者，可以通过计算检验统计量 <span class="math inline">\(v\)</span> 的 <span class="math inline">\(p-\text{value}\)</span> 来进行检验：</p>
<p><span class="math inline">\(p-\text{value} = P(F_{m-1,(n-1)(m-1)} \geq v)\)</span></p>
<p>类似的，我们同样可以使用如上的方法检验列效应的原假设，即检验所有的 <span class="math inline">\(\beta_j = 0\)</span> 的原假设。<a href="#tbl-10_2" class="quarto-xref">表&nbsp;<span>10.2</span></a> 和 <a href="#tbl-10_2_1" class="quarto-xref">表&nbsp;<span>10.3</span></a> 对本节介绍的 <strong>行效应</strong> 和 <strong>列效应</strong> 的假设检验方法进行了总结。同时，可以使用 R 来计算相关的 <span class="math inline">\(p-\text{value}\)</span>。</p>
<div id="tbl-10_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-10_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;10.2: 行平方和，列平方和以及误差平方和
</figcaption>
<div aria-describedby="tbl-10_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>平方和</th>
<th>自由度</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>行</td>
<td><span class="math inline">\(SS_r = n \sum_{i=1}^{m} (X_{i.} - X_{..})^2\)</span></td>
<td><span class="math inline">\(m - 1\)</span></td>
</tr>
<tr class="even">
<td>列</td>
<td><span class="math inline">\(SS_c = m \sum_{j=1}^{n} (X_{.j} - X_{..})^2\)</span></td>
<td><span class="math inline">\(n - 1\)</span></td>
</tr>
<tr class="odd">
<td>误差</td>
<td><span class="math inline">\(SS_e = \sum_{i=1}^{m} \sum_{j=1}^{n} (X_{ij} - X_{i.} - X_{.j} + X_{..})^2\)</span></td>
<td><span class="math inline">\((n - 1)(m - 1)\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-10_2_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-10_2_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;10.3: 双因素方差分析（<em>Two-Factor ANOVA</em>），<span class="math inline">\(N = (n-1)(m-1)\)</span>
</figcaption>
<div aria-describedby="tbl-10_2_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>原假设</th>
<th>检验统计量</th>
<th>显著性水平 <span class="math inline">\(\alpha\)</span> 下的检验</th>
<th><span class="math inline">\(TS=v\)</span> 时的 <span class="math inline">\(p-\text{value}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>所有 <span class="math inline">\(\alpha_i = 0\)</span></td>
<td><span class="math inline">\(\frac{SS_r/(m-1)}{SS_e/N}\)</span></td>
<td>若 <span class="math inline">\(TS \geq F_{\alpha,m-1,N}\)</span>，则拒绝 <span class="math inline">\(H_0\)</span></td>
<td><span class="math inline">\(P\{F_{m-1,N} \geq v\}\)</span></td>
</tr>
<tr class="even">
<td>所有 <span class="math inline">\(\beta_j = 0\)</span></td>
<td><span class="math inline">\(\frac{SS_c/(n-1)}{SS_e/N}\)</span></td>
<td>若 <span class="math inline">\(TS \geq F_{\alpha,n-1,N}\)</span>，则拒绝 <span class="math inline">\(H_0\)</span></td>
<td><span class="math inline">\(P\{F_{n-1,N} \geq v\}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="exm-10_5_a" class="theorem example">
<p><span class="theorem-title"><strong>例 10.2</strong></span> 以下数据表示在热排放附近的 6 个站点收集的、大型无脊椎动物的不同种类的数量，数据收集的时间为 1970 年至 1977 年。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注记
</div>
</div>
<div class="callout-body-container callout-body">
<p>热排放通常是指来自工业设施（如发电厂、工厂或其他热力系统）的废热，通常以温水或蒸汽的形式排放到附近的水体或空气中。因为水温的上升可能改变栖息地的条件，影响物种的多样性和数量，所以这种排放可能会对周围的环境、生态系统以及水生生物产生影响。</p>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Station 1</th>
<th>Station 2</th>
<th>Station 3</th>
<th>Station 4</th>
<th>Station 5</th>
<th>Station 6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1970</td>
<td>53</td>
<td>35</td>
<td>31</td>
<td>37</td>
<td>40</td>
<td>43</td>
</tr>
<tr class="even">
<td>1971</td>
<td>36</td>
<td>34</td>
<td>17</td>
<td>21</td>
<td>30</td>
<td>18</td>
</tr>
<tr class="odd">
<td>1972</td>
<td>47</td>
<td>37</td>
<td>17</td>
<td>31</td>
<td>45</td>
<td>26</td>
</tr>
<tr class="even">
<td>1973</td>
<td>55</td>
<td>31</td>
<td>17</td>
<td>23</td>
<td>43</td>
<td>37</td>
</tr>
<tr class="odd">
<td>1974</td>
<td>40</td>
<td>32</td>
<td>19</td>
<td>26</td>
<td>45</td>
<td>37</td>
</tr>
<tr class="even">
<td>1975</td>
<td>52</td>
<td>42</td>
<td>20</td>
<td>27</td>
<td>26</td>
<td>32</td>
</tr>
<tr class="odd">
<td>1976</td>
<td>39</td>
<td>28</td>
<td>21</td>
<td>21</td>
<td>36</td>
<td>28</td>
</tr>
<tr class="even">
<td>1977</td>
<td>40</td>
<td>32</td>
<td>21</td>
<td>21</td>
<td>36</td>
<td>35</td>
</tr>
</tbody>
</table>
<p>我们使用 R 来检验以下假设：</p>
<ul>
<li><ol type="a">
<li>数据是否随时间变化</li>
</ol></li>
<li><ol start="2" type="a">
<li>数据是否在各站点之间变化</li>
</ol></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>v1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">53</span>, <span class="dv">36</span>, <span class="dv">47</span>, <span class="dv">55</span>, <span class="dv">40</span>, <span class="dv">52</span>, <span class="dv">39</span>, <span class="dv">40</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>v2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">35</span>, <span class="dv">34</span>, <span class="dv">37</span>, <span class="dv">31</span>, <span class="dv">32</span>, <span class="dv">42</span>, <span class="dv">28</span>, <span class="dv">32</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>v3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">31</span>, <span class="dv">17</span>, <span class="dv">17</span>, <span class="dv">17</span>, <span class="dv">19</span>, <span class="dv">20</span>, <span class="dv">21</span>, <span class="dv">21</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>v4 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">37</span>, <span class="dv">21</span>, <span class="dv">31</span>, <span class="dv">23</span>, <span class="dv">26</span>, <span class="dv">27</span>, <span class="dv">21</span>, <span class="dv">21</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>v5 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">32</span>, <span class="dv">45</span>, <span class="dv">43</span>, <span class="dv">45</span>, <span class="dv">26</span>, <span class="dv">36</span>, <span class="dv">36</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>v6 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">43</span>, <span class="dv">18</span>, <span class="dv">26</span>, <span class="dv">37</span>, <span class="dv">37</span>, <span class="dv">32</span>, <span class="dv">28</span>, <span class="dv">35</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(v1, v2, v3, v4, v5, v6), <span class="dv">8</span>, <span class="dv">6</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>H <span class="ot">&lt;-</span> <span class="fu">sweep</span>(X, <span class="dv">1</span>, <span class="fu">rowMeans</span>(X)) <span class="sc">+</span> <span class="fu">mean</span>(X)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">sweep</span>(H, <span class="dv">2</span>, <span class="fu">colMeans</span>(X))</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>SSe <span class="ot">&lt;-</span> <span class="fu">sum</span>(C<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(X) <span class="sc">-</span> <span class="fu">mean</span>(X)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>SSr <span class="ot">&lt;-</span> <span class="fu">ncol</span>(X) <span class="sc">*</span> <span class="fu">sum</span>(D<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>E <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(X) <span class="sc">-</span> <span class="fu">mean</span>(X)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>SSc <span class="ot">&lt;-</span> <span class="fu">nrow</span>(X) <span class="sc">*</span> <span class="fu">sum</span>(E<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> (<span class="fu">nrow</span>(X) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> (<span class="fu">ncol</span>(X) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>TSrow <span class="ot">&lt;-</span> (SSr <span class="sc">/</span> (<span class="fu">nrow</span>(X) <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">/</span> (SSe <span class="sc">/</span> N)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>TSrow</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.602264</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(TSrow, <span class="fu">nrow</span>(X) <span class="sc">-</span> <span class="dv">1</span>, N)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.005037051</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>TScol <span class="ot">=</span> (SSc <span class="sc">/</span> (<span class="fu">ncol</span>(X) <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">/</span> (SSe <span class="sc">/</span> N)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>TScol</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.67062</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(TScol, <span class="fu">ncol</span>(X) <span class="sc">-</span> <span class="dv">1</span>, N)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.413647e-10</code></pre>
</div>
</div>
<p>因此，数据分布是否不依赖于年份的 F 统计量的值为 3.602，其对应的 <span class="math inline">\(p-\text{value}\)</span> 为 0.005；数据分布是否不依赖于站点的 F 统计量的值为 22.67，其对应的 <span class="math inline">\(p-\text{value}\)</span> 为 <span class="math inline">\(4 \times 10^{-10}\)</span>。因此，在几乎所有的显著性水平下，这两个原假设我们都将拒绝。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
</section>
<section id="sec-10_6" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="sec-10_6"><span class="header-section-number">10.6</span> 有交互效应的双因素方差分析</h2>
<p>在 <a href="#sec-10_4" class="quarto-xref"><span>小节 10.4</span></a> 和 <a href="#sec-10_5" class="quarto-xref"><span>小节 10.5</span></a> 中，我们讨论了观察数据的分布依赖于两个因素——称之为 <strong>行因素</strong> 和 <strong>列因素</strong>——的场景。具体来说，我们假设 <span class="math inline">\(X_{ij}\)</span> 的均值可以表示为两部分的和——一部分取决于数据所在的行，另一部分取决于数据所在的列。即我们假设</p>
<p><span class="math inline">\(X_{ij} \sim \mathcal{N}(\mu + \alpha_i + \beta_j, \sigma^2), \quad i = 1, \ldots, m, \quad j = 1, \ldots, n\)</span></p>
<p>然而，上述模型的问题是：上述模型总是假设 <strong>行因素</strong> 和 <strong>列因素</strong> 的效应是可加的，它不允许 <strong>行因素</strong> 和 <strong>列因素</strong> 之间存在 <strong>交互效应</strong>。</p>
<p>例如，考虑如下的实验，在该实验中，我们需要比较四个不同的工人在使用三台不同机器时，生产的次品数量的均值。在分析结果时，我们可能假设，对于不同的工人而言，使用某台机器产生的次品数量的增量是相同的。但是，也存在如下的可能：同一机器对于不同工人而言所产生的次品数量的增量并不一致，也就是说，可能存在 <span class="math inline">\(\text{工人-机器}\)</span> 的 <strong>交互效应</strong>（<em>interation</em>）。而在加性模型中，不允许存在这种 <strong>交互效应</strong>。</p>
<div class="callout callout-style-default callout-note callout-titled" title="交互效应">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
交互效应
</div>
</div>
<div class="callout-body-container callout-body">
<p>交互效应或者交互作用指的是：在某个自变量的不同水平上，另一个自变量对因变量的效应不同。例如上面提到的，在工人这个自变量的不同水平上，同一台机器对于产品次品数量的效应并不相同。</p>
</div>
</div>
<p>为了考虑行和列之间可能的 <strong>交互效应</strong>，令</p>
<p><span class="math inline">\(\mu_{ij} = E[X_{ij}]\)</span></p>
<p>并定义 <span class="math inline">\(\mu, \alpha_i, \beta_j, \gamma_{ij}, i = 1, \ldots, m; j = 1, \ldots, n\)</span>：</p>
<p><span class="math inline">\(\begin{align} \mu &amp;= \mu_{..} \\ \alpha_i &amp;= \mu_{i.} - \mu_{..} \\ \beta_j &amp;= \mu_{.j} - \mu_{..} \\ \gamma_{ij} &amp;= \mu_{ij} - \mu_{i.} - \mu_{.j} + \mu_{..} \end{align}\)</span></p>
<p>显然有：</p>
<p><span class="math inline">\(\mu_{ij} = \mu + \alpha_i + \beta_j + \gamma_{ij}\)</span></p>
<p>并且，也可以很容易的证明：</p>
<p><span class="math inline">\(\sum_{i=1}^{m} \alpha_i = \sum_{j=1}^{n} \beta_j = \sum_{i=1}^{m} \gamma_{ij} = \sum_{j=1}^{n} \gamma_{ij} = 0\)</span></p>
<ul>
<li>参数 <span class="math inline">\(\mu\)</span> 是 <span class="math inline">\(nm\)</span> 个均值的平均值，我们称之为<strong>总体均值</strong>（<em>grand mean</em>）。</li>
<li>参数 <span class="math inline">\(\alpha_i\)</span> 表示第 <span class="math inline">\(i\)</span> 行的均值与 <strong>总体均值</strong> 之间的差值，我们被之称为 <strong>行效应</strong>（<em>effect of row</em>）。</li>
<li>参数 <span class="math inline">\(\beta_j\)</span> 表示第 <span class="math inline">\(j\)</span> 列的均值与 <strong>总体均值</strong> 之间的差值，我们称之为 <strong>列效应</strong>（<em>effect of column</em>）。</li>
<li>参数 <span class="math inline">\(\gamma_{ij} = \mu_{ij} - (\mu + \alpha_i + \beta_j)\)</span> 表示 <span class="math inline">\(\mu_{ij}\)</span> 与 <strong>总体均值</strong> 和 第 <span class="math inline">\(i\)</span> <strong>行效应</strong>、第 <span class="math inline">\(j\)</span> <strong>列效应</strong> 的和的差值，是对第 <span class="math inline">\(i\)</span> 行和第 <span class="math inline">\(j\)</span> 列的加性偏离的度量，我们称之为第 <span class="math inline">\(i\)</span> 行和第 <span class="math inline">\(j\)</span> 列的 <strong>交互效应</strong>。</li>
</ul>
<p>为了能够检验假设：行和列之间没有交互效应——也就是说，所有 <span class="math inline">\(\gamma_{ij} = 0\)</span>——每对因素需要有多个观察值。假设每行和每列都有 <span class="math inline">\(l\)</span> 个观察值。也就是说，假设数据是 <span class="math inline">\(\{X_{ijk}, i=1, \dots, m; j=1, \dots, n; k=1, \dots, l\}\)</span>，其中 <span class="math inline">\(X_{ijk}\)</span> 是第 <span class="math inline">\(i\)</span> 行和第 <span class="math inline">\(j\)</span> 列中的第 <span class="math inline">\(k\)</span> 个观察值。由于假设所有观察值都是相互独立的正态分布随机变量且具有相同的方差 <span class="math inline">\(\sigma^2\)</span>，所以：</p>
<p><span class="math inline">\(X_{ijk} \sim \mathcal{N}(\mu + \alpha_i + \beta_j + \gamma_{ij}, \sigma^2)\)</span></p>
<p>其中：</p>
<p><span id="eq-10_6_1"><span class="math display">\[
\sum_{i=1}^{m} \alpha_i = \sum_{j=1}^{n} \beta_j = \sum_{i=1}^{m} \gamma_{ij} = \sum_{j=1}^{n} \gamma_{ij} = 0
\tag{10.9}\]</span></span></p>
<p>我们将对上述参数进行估计，并检验以下原假设：</p>
<p><span class="math inline">\(\begin{align} H_0^r: \alpha_i &amp;= 0, \quad \text{for all} \ i \\ H_0^c: \beta_j &amp;= 0, \quad \text{for all} \ j \\ H_0^{int}: \gamma_{ij} &amp;= 0, \quad \text{for all} \ i, j \end{align}\)</span></p>
<p>也就是说，<span class="math inline">\(H_0^r\)</span> 是没有行效应的假设，<span class="math inline">\(H_0^c\)</span> 是没有列效应的假设，<span class="math inline">\(H_0^{int}\)</span> 是没有行和列之间交互效应的假设。</p>
<p>根据 <a href="#eq-10_6_1" class="quarto-xref">式&nbsp;<span>10.9</span></a> 和 <span class="math inline">\(E[X_{ijk}] = \mu_{ij} = \mu + \alpha_i + \beta_j + \gamma_{ij}\)</span> 可以得到：</p>
<p><span class="math inline">\(\begin{align} E[X_{ij.}] &amp;= \mu_{ij} = \mu + \alpha_i + \beta_j + \gamma_{ij} \\ E[X_{i..}] &amp;= \mu + \alpha_i \\ E[X_{.j.}] &amp;= \mu + \beta_j \\ E[X_{...}] &amp;= \mu \end{align}\)</span></p>
<p>因此，各参数的无偏估计量为：</p>
<p><span class="math inline">\(\begin{align} \hat{\mu} &amp;= X_{...} \\ \hat{\beta}_j &amp;= X_{.j.} - X_{...} \\ \hat{\alpha}_i &amp;= X_{i..} - X_{...} \\ \hat{\gamma}_{ij} &amp;= X_{ij.} - \hat{\mu} - \hat{\beta}_j - \hat{\alpha}_i = X_{ij.} - X_{i..} - X_{.j.} + X_{...} \end{align}\)</span></p>
<p>为了为原假设 <span class="math inline">\(H_0^{int}\)</span>、<span class="math inline">\(H_0^r\)</span>、<span class="math inline">\(H_0^c\)</span> 构建检验，我们首先注意到：</p>
<p><span class="math inline">\(\sum_{k=1}^{l} \sum_{j=1}^{n} \sum_{i=1}^{m} \frac{(X_{ijk} - \mu - \alpha_i - \beta_j - \gamma_{ij})^2}{\sigma^2}\)</span></p>
<p>是一个自由度为 <span class="math inline">\(nml\)</span> 的卡方分布随机变量。因此：</p>
<p><span class="math inline">\(\sum_{k=1}^{l} \sum_{j=1}^{n} \sum_{i=1}^{m} \frac{(X_{ijk} - \hat{\mu} - \hat{\alpha}_i - \hat{\beta}_j - \hat{\gamma}_{ij})^2}{\sigma^2}\)</span></p>
<p>也将是卡方分布，但是其自由度将因为每估计一个参数而减少 1。因为 <span class="math inline">\(\sum_{i} \alpha_i = 0\)</span>，所以只需要估计 <span class="math inline">\(m-1\)</span> 个 <span class="math inline">\(\alpha_i\)</span>；同样地，由于 <span class="math inline">\(\sum_{j} \beta_j = 0\)</span>，因此只需要估计 <span class="math inline">\(n-1\)</span> 个 <span class="math inline">\(\beta_j\)</span>。另外，由于 <span class="math inline">\(\sum_{i} \gamma_{ij} = \sum_{j} \gamma_{ij} = 0\)</span>，我们只需要估计 <span class="math inline">\((m-1)(n-1)\)</span> 个 <span class="math inline">\(\gamma_{ij}\)</span>。因为还需要估计 <span class="math inline">\(\mu\)</span>，因此我们总共需要估计的参数个数为：</p>
<p><span class="math inline">\(n - 1 + m - 1 + (n-1)(m-1) + 1 = nm\)</span></p>
<p>因为：</p>
<p><span class="math inline">\(\hat{\mu} + \hat{\alpha}_i + \hat{\beta}_j + \hat{\gamma}_{ij} = X_{ij\cdot}\)</span></p>
<p>因此，如果我们令：</p>
<p><span class="math inline">\(SS_e = \sum_{k=1}^{l} \sum_{j=1}^{n} \sum_{i=1}^{m} (X_{ijk} - X_{ij \cdot})^2\)</span></p>
<p>则 <span class="math inline">\(\frac{SS_e}{\sigma^2}\)</span> 是自由度为 <span class="math inline">\(nm(l-1)\)</span> 的卡方分布。因此：<span class="math inline">\(\frac{SS_e}{nm(l-1)}\)</span> 是 <span class="math inline">\(\sigma^2\)</span> 的无偏估计量。</p>
<p>假设现在我们想要检验行和列之间没有 <strong>交互效应</strong> 的假设，即检验：</p>
<p><span class="math inline">\(H_0^{int}: \gamma_{ij} = 0, \quad i=1,\dots,m, \quad j=1,\dots,n\)</span></p>
<p>如果 <span class="math inline">\(H_0^{int}\)</span> 为真，则随机变量 <span class="math inline">\(X_{ij.}\)</span> 是均值为 <span class="math inline">\(E[X_{ij.}] = \mu + \alpha_i + \beta_j\)</span> 的正态分布随机变量。</p>
<p>此外，因为 <span class="math inline">\(X_{ij.}\)</span> 是 <span class="math inline">\(l\)</span> 个方差为 <span class="math inline">\(\sigma^2\)</span> 的正态分布随机变量的平均值，因此：</p>
<p><span class="math inline">\(\text{Var}(X_{ij.}) = \frac{\sigma^2}{l}\)</span></p>
<p>因此，如果原假设 <span class="math inline">\(H_0^{int}\)</span> 为真：</p>
<p><span class="math inline">\(\sum_{j=1}^{n} \sum_{i=1}^{m} \frac{l(X_{ij.} - \mu - \alpha_i - \beta_j)^2}{\sigma^2}\)</span></p>
<p>是一个自由度为 <span class="math inline">\(nm\)</span> 的卡方分布。因为总共 <span class="math inline">\(1 + n - 1 + m - 1 = n + m - 1\)</span> 个参数 <span class="math inline">\(\mu, \alpha_i, \beta_j\)</span> 必须估计，所以：</p>
<p><span class="math inline">\(SS_{int} = \sum_{j=1}^{n} \sum_{i=1}^{m} l(X_{ij.} - \hat{\mu} - \hat{\alpha}_i - \hat{\beta}_j)^2 = \sum_{j=1}^{n} \sum_{i=1}^{m} l(X_{ij.} - X_{i..} - X_{.j.} - X_{...})^2\)</span></p>
<p>所以，在 <span class="math inline">\(H_0^{int}\)</span> 为真的情况下：</p>
<p><span class="math inline">\(\frac{SS_{int}}{\sigma^2}\)</span></p>
<p>是自由度为 <span class="math inline">\((n-1)(m-1)\)</span> 的卡方分布。</p>
<p>因此，在没有行和列的 <strong>交互效应</strong> 的假设下：</p>
<p><span class="math inline">\(\frac{SS_{int}}{(n-1)(m-1)}\)</span></p>
<p>是 <span class="math inline">\(\sigma^2\)</span> 的无偏估计量。</p>
<p>可以证明，在没有 <strong>交互效应</strong> 的假设下，<span class="math inline">\(SS_e\)</span> 和 <span class="math inline">\(SS_{int}\)</span> 是相互独立的，故当 <span class="math inline">\(H_0^{int}\)</span> 为真时，</p>
<p><span class="math inline">\(F_{int} = \frac{SS_{int}/[(n-1)(m-1)]}{SS_e/[nm(l-1)]}\)</span></p>
<p>是分子自由度为 <span class="math inline">\((n-1)(m-1)\)</span>、分母自由度为 <span class="math inline">\(nm(l-1)\)</span> 的 <span class="math inline">\(F-\text{分布}\)</span> 随机变量。在显著性水平为 <span class="math inline">\(\alpha\)</span> 下，原假设 <span class="math inline">\(H_0^{int} : 所有 \gamma_{ij} = 0\)</span> 的检验为：</p>
<p><span class="math inline">\(\begin{align} \text{拒绝} \quad &amp; H_0^{int} \quad \text{如果} \ \frac{SS_{int}/[(n-1)(m-1)]}{SS_e/[nm(l-1)]} &gt; F_{\alpha, (n-1)(m-1), nm(l-1)} \\ \text{不拒绝} \quad &amp; H_0^{int} \quad \text{否则} \end{align}\)</span></p>
<p>或者，我们可以计算 <span class="math inline">\(p-\text{value}\)</span>。如果 <span class="math inline">\(F_{int} = v\)</span>，那么检验所有交互项等于 0 的原假设的 <span class="math inline">\(p-\text{value}\)</span> 是：</p>
<p><span class="math inline">\(p-\text{value} = P\{F_{(n-1)(m-1), nm(l-1)} &gt; v\}\)</span></p>
<p>当 <span class="math inline">\(H_0^r\)</span> 为真时，<span class="math inline">\(X_{i..}\)</span> 是 <span class="math inline">\(nl\)</span> 个正态分布随机变量的均值，每个随机变量均值为 <span class="math inline">\(\mu\)</span>、方差为 <span class="math inline">\(\sigma^2\)</span>。因此，在 <span class="math inline">\(H_0^r\)</span> 为真时：</p>
<p><span class="math inline">\(E[X_{i..}] = \mu, \quad \text{Var}(X_{i..}) = \frac{\sigma^2}{nl}\)</span></p>
<p>因此，<span class="math inline">\(\sum_{i=1}^{m} \frac{nl(X_{i..} - \mu)^2}{\sigma^2}\)</span> 是自由度为 <span class="math inline">\(m\)</span> 的卡方分布。因此，如果我们令：</p>
<p><span class="math inline">\(SS_r = \sum_{i=1}^{m} nl(X_{i..} - \hat{\mu})^2 = \sum_{i=1}^{m} nl(X_{i..} - X_{...})^2\)</span></p>
<p>则当 <span class="math inline">\(H_0^r\)</span> 为真时，<span class="math inline">\(\frac{SS_r}{\sigma^2}\)</span> 是自由度为 <span class="math inline">\(m-1\)</span> 的卡方分布。因此：<span class="math inline">\(\frac{SS_r}{m-1}\)</span> 是当 <span class="math inline">\(H_0^r\)</span> 为真时，<span class="math inline">\(\sigma^2\)</span> 的无偏估计量。</p>
<p>可以证明，在 <span class="math inline">\(H_0^r\)</span> 为真时，<span class="math inline">\(SS_e\)</span>、<span class="math inline">\(SS_r\)</span> 是独立的，故当 <span class="math inline">\(H_0^r\)</span> 为真时：</p>
<p><span class="math inline">\(\frac{SS_r/(m-1)}{SS_e/[nm(l-1)]}\)</span></p>
<p>是一个 <span class="math inline">\(F_{m-1, nm(l-1)}\)</span> 分布随机变量。</p>
<p>因此，在显著性水平为 <span class="math inline">\(\alpha\)</span> 时，</p>
<p><span class="math inline">\(H_0^r : 所有 \alpha_i = 0 \quad vs \quad H_1^r : 至少一个 \alpha_i \neq 0\)</span></p>
<p>的检验为：</p>
<p><span class="math inline">\(\begin{align} \text{拒绝} \quad &amp; H_0^r \quad \text{如果} \quad \frac{SS_r/(m-1)}{SS_e/[nm(l-1)]} &gt; F_{\alpha, m-1, nm(l-1)} \\ \text{不拒绝} \quad &amp; H_0^r \quad \text{否则} \end{align}\)</span></p>
<p>如果令：<span class="math inline">\(\frac{SS_r/(m-1)}{SS_e/[nm(l-1)]} = v\)</span>，则 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p\text{-value} = P\{F_{m-1, nm(l-1)} &gt; v\}\)</span></p>
<p>同理，也可以得到 <span class="math inline">\(H_0 : \beta_j = 0\)</span> 的检验结果。<a href="#tbl-10_3" class="quarto-xref">表&nbsp;<span>10.4</span></a> 对本节的 <strong>方差分析</strong>（<em>ANOVA</em>）相关信息进行了总结。</p>
<div id="tbl-10_3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-10_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;10.4: 对于 <span class="math inline">\(m\)</span> 行 <span class="math inline">\(n\)</span> 列的每个 <span class="math inline">\(X_{ij}\)</span> 都有 <span class="math inline">\(l\)</span> 个观察数据时的双因素方差分析，其中 <span class="math inline">\(N=nm(l-1)\)</span>
</figcaption>
<div aria-describedby="tbl-10_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 19%">
<col style="width: 29%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>类型</th>
<th>自由度</th>
<th>平方和</th>
<th><span class="math inline">\(F-\text{统计量}\)</span></th>
<th>显著性水平 <span class="math inline">\(\alpha\)</span> 下的检验</th>
<th><span class="math inline">\(F = v\)</span> 时的 <span class="math inline">\(p-\text{value}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>行效应</td>
<td><span class="math inline">\(m - 1\)</span></td>
<td><span class="math inline">\(SS_r = ln \sum_{i=1}^{m} (X_{i..} - X_{...})^2\)</span></td>
<td><span class="math inline">\(F_r = \frac{SS_r/(m-1)}{SS_e/N}\)</span></td>
<td>拒绝 <span class="math inline">\(H_0^r\)</span> 如果 <span class="math inline">\(F_r &gt; F_{\alpha, m-1, N}\)</span></td>
<td><span class="math inline">\(P\{F_{m-1, N} &gt; v\}\)</span></td>
</tr>
<tr class="even">
<td>列效应</td>
<td><span class="math inline">\(n - 1\)</span></td>
<td><span class="math inline">\(SS_c = lm \sum_{j=1}^{n} (X_{.j.} - X_{...})^2\)</span></td>
<td><span class="math inline">\(F_c = \frac{SS_c/(n-1)}{SS_e/N}\)</span></td>
<td>拒绝 <span class="math inline">\(H_0^c\)</span> 如果 <span class="math inline">\(F_c &gt; F_{\alpha, n-1, N}\)</span></td>
<td><span class="math inline">\(P\{F_{n-1, N} &gt; v\}\)</span></td>
</tr>
<tr class="odd">
<td>交互效应</td>
<td><span class="math inline">\((n - 1)(m - 1)\)</span></td>
<td><span class="math inline">\(\begin{align} &amp;SS_{int} = l \sum_{j=1}^{n} \\ &amp; \times \sum_{i=1}^{m} (X_{ij.} - X_{i..} - X_{.j.} + X_{...})^2 \end{align}\)</span></td>
<td><span class="math inline">\(F_{int} = \frac{SS_{int}/[(n-1)(m-1)]}{SS_e/N}\)</span></td>
<td>拒绝 <span class="math inline">\(H_0^{int}\)</span> 如果 <span class="math inline">\(F_{int} &gt; F_{\alpha, (n-1)(m-1), N}\)</span></td>
<td><span class="math inline">\(P\{F_{(n-1)(m-1), N} &gt; v\}\)</span></td>
</tr>
<tr class="even">
<td>误差</td>
<td><span class="math inline">\(N\)</span></td>
<td><span class="math inline">\(\begin{align} &amp; SS_e = \sum_{k=1}^{l} \sum_{j=1}^{n} \\ &amp; \times \sum_{i=1}^{m} (X_{ijk} - X_{ij.})^2 \end{align}\)</span></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>注意，对于前面介绍的所有的检验而言，只有在相关的 <span class="math inline">\(F-\text{统计量}\)</span> 较大时，我们才会拒绝原假设。因为当 <span class="math inline">\(H_0\)</span> 不成立时，<span class="math inline">\(F-\text{统计量}\)</span> 的分子的分布往往会变大；而不论 <span class="math inline">\(H_0\)</span> 是否成立，<span class="math inline">\(F-\text{统计量}\)</span> 的分母的分布都是相同的。所以只有较大的（而不是较小的）<span class="math inline">\(F-\text{统计量}\)</span> 的值才会让我们拒绝原假设。</p>
<div id="exr-10_6_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 10.4</strong></span> 我们认为，某种特定类型的发电机的寿命会受到所使用的材料以及所使用场所的温度的影响。下表显示了由三种不同材料制造的发电机在两种不同温度下使用时的 24 台发电机的寿命数据。该数据是否可以表明，发电机的材料和工作场所的温度确实会影响发电机的寿命？是否有证据可以表明材料和工作场所的温度对发电机的寿命存在交互效应？</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>材料</th>
<th>10°C</th>
<th>18°C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>135, 150 <br> 176, 85</td>
<td>50, 55 <br> 64, 38</td>
</tr>
<tr class="even">
<td>2</td>
<td>150, 162 <br> 171, 120</td>
<td>76, 88 <br> 91, 57</td>
</tr>
<tr class="odd">
<td>3</td>
<td>138, 111 <br> 140, 106</td>
<td>68, 60 <br> 74, 51</td>
</tr>
</tbody>
</table>
</div>
<div id="sol-10_6_a" class="proof solution">
<p><span class="proof-title"><em>解 10.4</em>. </span>计算得出用于检验材料和温度之间没有交互效应的 <span class="math inline">\(F-\text{统计量}\)</span> 的值为 0.64525，其 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p-\text{value} = P(F_{2,18} &gt; 0.64525) &gt; 1 - pf(0.64525, 2, 18)\)</span></p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(<span class="fl">0.64525</span>, <span class="dv">2</span>, <span class="dv">18</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5362424</code></pre>
</div>
</div>
<p>因此，我们无法拒绝材料和温度之间没有交互效应的原假设。</p>
<p>计算得出用于检验发电机寿命不依赖于所使用材料（即没有行效应）的 <span class="math inline">\(F-\text{统计量}\)</span> 值为 2.47976，其 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p-\text{value} = P(F_{2,18} &gt; 2.47976) &gt; 1 - pf(2.47976, 2, 18)\)</span></p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(<span class="fl">2.47976</span>, <span class="dv">2</span>, <span class="dv">18</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.111889</code></pre>
</div>
</div>
<p>因此，在 10% 的显著性水平下，我们无法拒绝发电机寿命不依赖于所使用材料的原假设。</p>
<p>计算表明，用于检验发电机寿命不依赖于温度（即没有列效应）的 <span class="math inline">\(F-\text{统计量}\)</span> 值为 69.63223，其 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p\text{-value} = P(F_{1,18} &gt; 69.63223) = 1 - pf(69.63223, 1, 18)\)</span></p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(<span class="fl">69.63223</span>, <span class="dv">1</span>, <span class="dv">18</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.337273e-07</code></pre>
</div>
</div>
<p>因此，我们应该拒绝发电机寿命不依赖于温度的原假设。<span class="math inline">\(\blacksquare\)</span></p>
</div>
</section>
<section id="problems" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="problems">Problems</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "已复制");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "已复制");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/wangwei1237\.github\.io\/introduction_to_probability_and_statistics\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="wangwei1237/introduction_to_probability_and_statistics" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapter_9/9.html" class="pagination-link" aria-label="回归">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">回归</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapter_11/11.html" class="pagination-link" aria-label="拟合优度检验和分类数据分析">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">拟合优度检验和分类数据分析</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright Wang Wei. All Rights Reserved.</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/edit/main/chapter_10/10.qmd" class="toc-action"><i class="bi bi-github"></i>编辑该页面</a></li><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/issues/new" class="toc-action"><i class="bi empty"></i>反馈问题</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>