<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-Hans" xml:lang="zh-Hans"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8&nbsp; 假设检验 – Introduction to Probability and Statistics for Engineers and Scientists（中文版）</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapter_9/9.html" rel="next">
<link href="../chapter_7/7.html" rel="prev">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-03fb0c48514f8f3b3611eb54e83d3f6f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "没有结果",
    "search-matching-documents-text": "匹配的文档",
    "search-copy-link-title": "复制搜索链接",
    "search-hide-matches-text": "隐藏其它匹配结果",
    "search-more-match-text": "更多匹配结果",
    "search-more-matches-text": "更多匹配结果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "提交",
    "search-label": "搜索"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="8&nbsp; 假设检验 – Introduction to Probability and Statistics for Engineers and Scientists（中文版）">
<meta property="og:description" content="">
<meta property="og:image" content="https://wangwei1237.github.io/introduction_to_probability_and_statistics/chapter_8/8_files/figure-html/fig-8_1-1.png">
<meta property="og:site_name" content="Introduction to Probability and Statistics for Engineers and Scientists（中文版）">
<meta property="og:image:height" content="960">
<meta property="og:image:width" content="1344">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../favicon.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Introduction to Probability and Statistics for Engineers and Scientists（中文版）</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="搜索"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="展开或折叠导航栏" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://wangwei1237.github.io/"> <i class="bi bi-house-fill" role="img">
</i> 
<span class="menu-text">博客</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-bookshelf" role="img">
</i> 
 <span class="menu-text">书籍</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-">    
        <li>
    <a class="dropdown-item" href="https://zh.d2l.ai/">
 <span class="dropdown-text">动手学深度学习</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://learnprompting.org/zh-Hans/docs/intro">
 <span class="dropdown-text">Learn Prompting</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pan.baidu.com/s/1dciwgbhO-lfKyRo8lOqW9Q?pwd=cm9q">
 <span class="dropdown-text">Stabel Diffusion 提示词手册</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://wangwei1237.github.io/aboutme/"> <i class="bi bi-person-badge-fill" role="img">
</i> 
<span class="menu-text">关于</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics" title="源代码" class="quarto-navigation-tool px-1" aria-label="源代码"><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapter_8/8.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">假设检验</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="展开或折叠侧边栏导航" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">欢迎阅读</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface_17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">译者序</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">序言</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_1/1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">统计学简介</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_2/2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">描述统计</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_3/3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">概率论基础</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_4/4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">随机变量和期望</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_5/5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">特殊的随机变量</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_6/6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">抽样分布</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_7/7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">参数估计</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_8/8.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">假设检验</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_9/9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">回归</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_10/10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">方差分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_11/11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">拟合优度检验和分类数据分析</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_12/12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">非参数假设检验</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_13/13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">质量控制</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_14/14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Life testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_15/15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Simulation, bootstrap statistical methods, and permutation tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapter_16/16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Machine learning and big data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">测试脚本</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">附录</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="展开或折叠此栏">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">表格</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">目录</h2>
   
  <ul>
  <li><a href="#sec-8_1" id="toc-sec-8_1" class="nav-link active" data-scroll-target="#sec-8_1"><span class="header-section-number">8.1</span> 引言</a></li>
  <li><a href="#sec-8_2" id="toc-sec-8_2" class="nav-link" data-scroll-target="#sec-8_2"><span class="header-section-number">8.2</span> 显著性水平</a></li>
  <li><a href="#sec-8_3" id="toc-sec-8_3" class="nav-link" data-scroll-target="#sec-8_3"><span class="header-section-number">8.3</span> 正态分布的均值检验</a>
  <ul class="collapse">
  <li><a href="#sec-8_3_1" id="toc-sec-8_3_1" class="nav-link" data-scroll-target="#sec-8_3_1"><span class="header-section-number">8.3.1</span> 方差 <span class="math inline">\(\sigma^2\)</span> 已知的场景</a></li>
  <li><a href="#sec-8_3_2" id="toc-sec-8_3_2" class="nav-link" data-scroll-target="#sec-8_3_2"><span class="header-section-number">8.3.2</span> 方差未知的场景：<span class="math inline">\(t-\text{检验}\)</span></a></li>
  </ul></li>
  <li><a href="#sec-8_4" id="toc-sec-8_4" class="nav-link" data-scroll-target="#sec-8_4"><span class="header-section-number">8.4</span> 检验两个正态分布的均值是否相等</a>
  <ul class="collapse">
  <li><a href="#sec-8_4_1" id="toc-sec-8_4_1" class="nav-link" data-scroll-target="#sec-8_4_1"><span class="header-section-number">8.4.1</span> 方差已知的场景</a></li>
  <li><a href="#sec-8_4_2" id="toc-sec-8_4_2" class="nav-link" data-scroll-target="#sec-8_4_2"><span class="header-section-number">8.4.2</span> 方差未知的场景</a></li>
  <li><a href="#sec-8_4_3" id="toc-sec-8_4_3" class="nav-link" data-scroll-target="#sec-8_4_3"><span class="header-section-number">8.4.3</span> 方差未知且不同的场景</a></li>
  <li><a href="#sec-8_4_4" id="toc-sec-8_4_4" class="nav-link" data-scroll-target="#sec-8_4_4"><span class="header-section-number">8.4.4</span> 成对样本的 <span class="math inline">\(t-\text{检验}\)</span></a></li>
  </ul></li>
  <li><a href="#sec-8_5" id="toc-sec-8_5" class="nav-link" data-scroll-target="#sec-8_5"><span class="header-section-number">8.5</span> 关于正态总体方差的假设检验</a>
  <ul class="collapse">
  <li><a href="#sec-8_5_1" id="toc-sec-8_5_1" class="nav-link" data-scroll-target="#sec-8_5_1"><span class="header-section-number">8.5.1</span> 检验两个正态分布的方差是否相等</a></li>
  </ul></li>
  <li><a href="#sec-8_6" id="toc-sec-8_6" class="nav-link" data-scroll-target="#sec-8_6"><span class="header-section-number">8.6</span> 二项分布的假设检验</a>
  <ul class="collapse">
  <li><a href="#sec-8_6_1" id="toc-sec-8_6_1" class="nav-link" data-scroll-target="#sec-8_6_1"><span class="header-section-number">8.6.1</span> 检验两个伯努利总体的参数是否相同</a></li>
  </ul></li>
  <li><a href="#sec-8_7" id="toc-sec-8_7" class="nav-link" data-scroll-target="#sec-8_7"><span class="header-section-number">8.7</span> 关于泊松分布的均值的假设检验</a>
  <ul class="collapse">
  <li><a href="#sec-8_7_1" id="toc-sec-8_7_1" class="nav-link" data-scroll-target="#sec-8_7_1"><span class="header-section-number">8.7.1</span> 检验两个泊松分布的参数之间的关系</a></li>
  </ul></li>
  <li><a href="#problems" id="toc-problems" class="nav-link" data-scroll-target="#problems">Problems</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/edit/main/chapter_8/8.qmd" class="toc-action"><i class="bi bi-github"></i>编辑该页面</a></li><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/issues/new" class="toc-action"><i class="bi empty"></i>反馈问题</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-8" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">假设检验</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-8_1" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="sec-8_1"><span class="header-section-number">8.1</span> 引言</h2>
<p>如前一章所述，假设我们从一个分布已知但参数未知的总体中抽取随机样本。现在，我们不想对未知参数进行明确的估计，而是更多的关注使用所得到的样本来检验关于这些参数的某个特定 <strong>假设</strong>（<em>hypothesis</em>）。举例来说，假设某建筑公司刚刚购买了一大批电缆，电缆厂家保证电缆的平均断裂强度至少为每平方英寸（<em>per square inch: PSI</em>） 7000 磅。为了验证电缆厂家的声明，该公司决定随机抽取其中的 10 根电缆以确定其断裂强度。然后，该公司将使用实验结果来确定是否接受电缆厂家声明的假设：总体上，电缆强度的平均值至少为 7000 PSI。</p>
<p><strong>统计假设</strong>（<em>statistical hypothesis</em>）通常是关于总体分布的一组参数的陈述。我们称之为 <strong>假设</strong> 是因为这一陈述的真实性尚不可知。一个主要问题是开发一个流程，以确定从总体中获取的随机样本的值是否与 <strong>假设</strong> 一致。例如，一个正态分布总体的均值 <span class="math inline">\(\theta\)</span> 未知、方差为 1。“<span class="math inline">\(\theta \lt 1\)</span>” 就是一个 <strong>统计假设</strong>，我们可以通过观察来自该总体的随机样本来对该 <strong>假设</strong> 进行检验。如果随机样本与 <strong>假设</strong> 一致，我们将“接受”该 <strong>假设</strong>；否则，我们将“拒绝”该 <strong>假设</strong>。</p>
<div class="callout callout-style-default callout-warning callout-titled" title="注意">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注意
</div>
</div>
<div class="callout-body-container callout-body">
<p>务必注意，当我们接受一个给定的 <strong>假设</strong> 时，并不意味着我们实际上认为这个假设是真的，而是说结果数据与该 <strong>假设</strong> 看起来是一致的。</p>
<p>例如，在 <span class="math inline">\(\mathcal{N}(\theta，1)\)</span> 的正态分布总体中，如果大小为 10 的样本的均值为 1.25，那么虽然这样的结果不能视为支持 “<span class="math inline">\(\theta \lt 1\)</span>” 的证据，但该结果与 <strong>假设</strong> 并不矛盾，因此我们将接受该 <strong>假设</strong>。</p>
<p>另外，如果大小为 10 的样本的均值为 3，即使当 <span class="math inline">\(\theta \lt 1\)</span> 时，这样的样本值是可能存在的，但出现这样的样本值是如此的不可能，以致于这似乎与 <strong>假设</strong> 并不一致，因此我们会拒绝该 <strong>假设</strong>。</p>
</div>
</div>
</section>
<section id="sec-8_2" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-8_2"><span class="header-section-number">8.2</span> 显著性水平</h2>
<p>考虑一个分布为 <span class="math inline">\(F_{\theta}\)</span> 的总体，其中 <span class="math inline">\(\theta\)</span> 是未知的。假设我们要检验关于 <span class="math inline">\(\theta\)</span> 的特定 <strong>假设</strong>，我们将此假设记为 <span class="math inline">\(H_0\)</span>，并称之为 <strong>原假设</strong>（<em>null hypothesis</em>）。例如，如果 <span class="math inline">\(F_{\theta}\)</span> 是均值为 <span class="math inline">\(\theta\)</span>、方差为 1 的正态分布，那么关于 <span class="math inline">\(\theta\)</span> 的两个可能的 <strong>原假设</strong> 是：</p>
<ol type="1">
<li><span class="math inline">\(H_0: \theta = 1\)</span></li>
<li><span class="math inline">\(H_0: \theta \le 1\)</span></li>
</ol>
<p>因此，第一个 <strong>假设</strong> 表明总体是均值为 1 且方差为 1 的正态分布，而第二个 <strong>假设</strong> 表明总体是方差为 1 且均值小于或等于 1 的正态分布。注意，第一个 <strong>原假设</strong> 为真时，完全确定了总体分布，而当第二个 <strong>原假设</strong> 为真时，则没有完全确定总体分布。如果一个 <strong>假设</strong> 为真可以完全确定总体分布，我们称这样的 <strong>假设</strong> 为 <strong>简单假设</strong>（<em>simple hypothesis</em>）；否则，我们称之为 <strong>复合假设</strong>（<em>composite hypothesis</em>）。</p>
<p>假设现在为了检验特定的 <strong>原假设</strong> <span class="math inline">\(H_0\)</span>，我们将观察一个样本大小为 <span class="math inline">\(n\)</span> 的总体样本——例如 <span class="math inline">\(X_1, \ldots, X_n\)</span>。基于这 <span class="math inline">\(n\)</span> 个值，我们必须决定是否接受 <span class="math inline">\(H_0\)</span>。可以通过在 <span class="math inline">\(n\)</span> 维空间中定义一个区域 <span class="math inline">\(C\)</span> 来指定 <span class="math inline">\(H_0\)</span> 的检验：如果随机样本 <span class="math inline">\(X_1, \ldots, X_n\)</span> 位于 <span class="math inline">\(C\)</span> 中，则拒绝 <strong>假设</strong>，否则接受 <strong>假设</strong>。该区域 <span class="math inline">\(C\)</span> 称之为 <strong>临界区</strong>（<em>critical region</em>）。换句话说，由 <strong>临界区</strong> <span class="math inline">\(C\)</span> 确定的统计检验是：</p>
<ul>
<li>接受 <span class="math inline">\(H_0\)</span>：如果 <span class="math inline">\((X_1, X_2, \ldots, X_n) \notin C\)</span></li>
<li>拒绝 <span class="math inline">\(H_0\)</span>：如果 <span class="math inline">\((X_1, \ldots, X_n) \in C\)</span></li>
</ul>
<p>例如，一个关于方差为 1 的正态分布的均值 <span class="math inline">\(\theta\)</span> 的常见假设——均值等于 1 的检验，其 <strong>临界区</strong> 由以下公式给出：</p>
<p><span id="eq-8_2_1"><span class="math display">\[
C = \{(X_1, \ldots, X_n) : |\overline{X} - 1| &gt; 1.96 / \sqrt{n}\}
\tag{8.1}\]</span></span></p>
<p>因此，当样本均值与 1 的差值超过 1.96 除以样本大小的平方根时，则拒绝 <span class="math inline">\(\theta = 1\)</span> 的 <strong>原假设</strong>。</p>
<div class="callout callout-style-default callout-warning callout-titled" title="注意">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注意
</div>
</div>
<div class="callout-body-container callout-body">
<p>重要的是，在任何检验中，可能会出现两种不同类型的错误。</p>
<ul>
<li>第一种错误，称之为 <strong>I 型错误</strong>，是指检验错误地拒绝了实际上正确的 <span class="math inline">\(H_0\)</span>。</li>
<li>第二种错误，称之为 <strong>II 型错误</strong>，是指检验错误地接受了实际上不正确的 <span class="math inline">\(H_0\)</span>。</li>
</ul>
</div>
</div>
<p>如前所述，统计检验 <span class="math inline">\(H_0\)</span> 的目标不是明确确定 <span class="math inline">\(H_0\)</span> 是否为真，而是确定 <span class="math inline">\(H_0\)</span> 是否与结果数据一致。因此，基于这个目标，合理的做法是：仅当 <span class="math inline">\(H_0\)</span> 为真时，并且结果数据非常不可能出现时，才拒绝 <span class="math inline">\(H_0\)</span>。传统的方法是指定一个值 <span class="math inline">\(\alpha\)</span> ，然后要求检验具有这样的性质：每当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(H_0\)</span> 被拒绝的概率绝不超过 <span class="math inline">\(\alpha\)</span>。这个 <span class="math inline">\(\alpha\)</span> 值，称之为 <strong>检验的显著性水平</strong>（<em>level of significance of the test</em>）。通常会预先设定检验的显著性水平，常用的值有 <span class="math inline">\(\alpha = 0.1, 0.05, 0.005\)</span>。</p>
<p>换句话说，传统的检验 <span class="math inline">\(H_0\)</span> 的方法是固定一个显著性水平 <span class="math inline">\(\alpha\)</span> ，然后要求检验具有这样的性质：发生 <strong>I 型错误</strong> 的概率绝不能超过 <span class="math inline">\(\alpha\)</span>。</p>
<p><span class="math inline">\(\theta\)</span> 是总体的一个未知参数，假设现在我们对检验一个关于 <span class="math inline">\(\theta\)</span> 的特定 <strong>假设</strong> 感兴趣。具体来说，对于给定的参数值集合 <span class="math inline">\(w\)</span>，假设我们对如下的检验感兴趣：</p>
<p><span class="math inline">\(H_0 : \theta \in w\)</span></p>
<p>在 <span class="math inline">\(\alpha\)</span> 下检验 <span class="math inline">\(H_0\)</span> 的一种常见方法是，从确定 <span class="math inline">\(\theta\)</span> 的点估计量——记为 <span class="math inline">\(d(\mathbfit{X})\)</span> 开始。</p>
<p>当 <span class="math inline">\(d(\mathbfit{X})\)</span> 远离区域 <span class="math inline">\(w\)</span> 时，则拒绝 <strong>假设</strong>。然而，为了确定 <span class="math inline">\(d(\mathbfit{X})\)</span> 需要多远才能证明拒绝 <span class="math inline">\(H_0\)</span> 是合理的，我们需要确定当 <span class="math inline">\(H_0\)</span> 为真时 <span class="math inline">\(d(\mathbfit{X})\)</span> 的概率分布。因为这通常能帮助我们确定适当的 <strong>临界区</strong>，从而使检验达到所需的 <strong>显著性水平</strong> <span class="math inline">\(\alpha\)</span>。例如，<a href="#eq-8_2_1" class="quarto-xref">式&nbsp;<span>8.1</span></a> 给出的参数为 <span class="math inline">\((\theta, 1)\)</span> 的总体均值等于 1 的假设检验，当 <span class="math inline">\(\theta\)</span> 的 <strong>点估计量</strong>——即样本均值——与 1 之间的距离超过 <span class="math inline">\(1.96/\sqrt{n}\)</span> 时，则拒绝 <strong>假设</strong>。正如我们将在 <a href="#sec-8_3" class="quarto-xref"><span>小节 8.3</span></a> 中所讲述的，选择 <span class="math inline">\(1.96/\sqrt{n}\)</span> 是为了满足 <strong>显著性水平</strong> <span class="math inline">\(\alpha = 0.05\)</span>。</p>
</section>
<section id="sec-8_3" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-8_3"><span class="header-section-number">8.3</span> 正态分布的均值检验</h2>
<section id="sec-8_3_1" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="sec-8_3_1"><span class="header-section-number">8.3.1</span> 方差 <span class="math inline">\(\sigma^2\)</span> 已知的场景</h3>
<p><span class="math inline">\(X_1, \dots, X_n\)</span> 是从未知均值 <span class="math inline">\(\mu\)</span> 且方差为 <span class="math inline">\(\sigma^2\)</span> 的正态分布总体中抽取的大小为 <span class="math inline">\(n\)</span> 的样本，假设我们要对以下的原假设进行检验：</p>
<p><span class="math inline">\(\begin{align} H_0: \mu = \mu_0 \quad vs \quad H_1: \mu \neq \mu_0 \end{align}\)</span></p>
<p>其中 <span class="math inline">\(\mu_0\)</span> 是某个特定的常数。</p>
<p>由于 <span class="math inline">\(\overline{X} = \frac{1}{n} \sum_{i=1}^n X_i\)</span> 是 <span class="math inline">\(\mu\)</span> 的点估计量，因此如果 <span class="math inline">\(\overline{X}\)</span> 与 <span class="math inline">\(\mu_0\)</span> 相差不大，则接受 <span class="math inline">\(H_0\)</span> 是合理的。也就是说，检验的 <strong>临界区</strong> 为：</p>
<p><span id="eq-8_3_1"><span class="math display">\[
C = \{ X_1, \dots, X_n : |\overline{X} - \mu_0| &gt; c \}
\tag{8.2}\]</span></span></p>
<p>其中 <span class="math inline">\(c\)</span> 为某个合适的值。</p>
<p>如果我们要求检验的显著性水平为 <span class="math inline">\(\alpha\)</span>，我们必须确定 <a href="#eq-8_3_1" class="quarto-xref">式&nbsp;<span>8.2</span></a> 中的临界值 <span class="math inline">\(c\)</span>，以使得 I 类错误等于 <span class="math inline">\(\alpha\)</span>。即，<span class="math inline">\(c\)</span> 必须满足：</p>
<p><span id="eq-8_3_2"><span class="math display">\[
P_{\mu_0}\{ |\overline{X} - \mu_0| &gt; c \} = \alpha
\tag{8.3}\]</span></span></p>
<p><span class="math inline">\(P_{\mu_0}\)</span> 表示我们在 <span class="math inline">\(\mu = \mu_0\)</span> 的假设下计算 <a href="#eq-8_3_2" class="quarto-xref">式&nbsp;<span>8.3</span></a> 的概率。然而，当 <span class="math inline">\(\mu = \mu_0\)</span> 时，<span class="math inline">\(\overline{X}\)</span> 将服从均值为 <span class="math inline">\(\mu_0\)</span> 且方差为 <span class="math inline">\(\sigma^2/n\)</span> 的正态分布，因此 <a href="#eq-8_3_001" class="quarto-xref">式&nbsp;<span>8.4</span></a> 定义的 <span class="math inline">\(Z\)</span> 将服从标准正态分布。</p>
<p><span id="eq-8_3_001"><span class="math display">\[
Z \equiv \frac{\overline{X} - \mu_0}{\sigma/\sqrt{n}} = \sqrt{n} \frac{(\overline{X} - \mu_0)}{\sigma}
\tag{8.4}\]</span></span></p>
<p>于是，<a href="#eq-8_3_2" class="quarto-xref">式&nbsp;<span>8.3</span></a> 等价于：</p>
<p><span class="math inline">\(P\left\{ |Z| &gt; \frac{c \sqrt{n}}{\sigma} \right\} = \alpha\)</span></p>
<p>即：</p>
<p><span class="math inline">\(2P\left\{ Z &gt; \frac{c \sqrt{n}}{\sigma} \right\} = \alpha\)</span></p>
<p>其中 <span class="math inline">\(Z\)</span> 是标准正态分布随机变量。然而，我们知道</p>
<p><span class="math inline">\(P\{ Z &gt; z_{\alpha/2} \} = \alpha/2\)</span></p>
<p>因此：</p>
<p><span class="math inline">\(\frac{c \sqrt{n}}{\sigma} = z_{\alpha/2}\)</span></p>
<p>即：</p>
<p><span class="math inline">\(c = \frac{z_{\alpha/2} \sigma}{\sqrt{n}}\)</span></p>
<p>因此，显著性水平为 <span class="math inline">\(\alpha\)</span> 的检验为：</p>
<ul>
<li>如果 <span class="math inline">\(\frac{\sqrt{n}}{\sigma} |\overline{X} - \mu_0| &gt; z_{\alpha/2}\)</span>，则拒绝 <span class="math inline">\(H_0\)</span>；</li>
<li>否则，接受 <span class="math inline">\(H_0\)</span>。</li>
</ul>
<p><span id="eq-8_3_3"><span class="math display">\[
\begin{align}
\text{拒绝} H_0 &amp;: \quad \frac{\sqrt{n}}{\sigma} |\overline{X} - \mu_0| &gt; z_{\alpha/2} \\
\text{接受} H_0 &amp;: \quad \frac{\sqrt{n}}{\sigma} |\overline{X} - \mu_0| \le z_{\alpha/2}
\end{align}
\tag{8.5}\]</span></span></p>
<p>可以通过图 <a href="#fig-8_1" class="quarto-xref">图&nbsp;<span>8.1</span></a> 来直观地表示 <a href="#eq-8_3_3" class="quarto-xref">式&nbsp;<span>8.5</span></a>，在 <a href="#fig-8_1" class="quarto-xref">图&nbsp;<span>8.1</span></a> 中，我们叠加了标准正态分布的概率密度函数（即当 <span class="math inline">\(H_0\)</span> 成立时，统计量 <span class="math inline">\(\sqrt{n}(\overline{X} - \mu_0)/\sigma\)</span> 的概率密度）。</p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(latex2exp)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="fl">0.01</span>) </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)) <span class="sc">+</span> </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="sc">-</span><span class="fl">1.96</span>, <span class="at">y=</span><span class="fu">dnorm</span>(<span class="sc">-</span><span class="fl">1.96</span>) <span class="sc">*</span> <span class="fl">1.5</span>, <span class="at">xend=</span><span class="sc">-</span><span class="fl">1.96</span>, <span class="at">yend=</span><span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="fl">1.96</span>, <span class="at">y=</span><span class="fu">dnorm</span>(<span class="fl">1.96</span>) <span class="sc">*</span> <span class="fl">1.5</span>, <span class="at">xend=</span><span class="fl">1.96</span>, <span class="at">yend=</span><span class="dv">0</span>) <span class="sc">+</span> </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="sc">-</span><span class="fl">1.96</span>, <span class="at">y=</span><span class="fu">dnorm</span>(<span class="sc">-</span><span class="fl">1.96</span>) <span class="sc">*</span> <span class="fl">1.3</span>, <span class="at">xend=</span><span class="fl">1.96</span>, <span class="at">yend=</span><span class="fu">dnorm</span>(<span class="fl">1.96</span>) <span class="sc">*</span> <span class="fl">1.3</span>, </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">ends =</span> <span class="st">"both"</span>, <span class="at">type =</span> <span class="st">"closed"</span>, <span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.1</span>, <span class="st">"inches"</span>))) <span class="sc">+</span> </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="sc">-</span><span class="fl">1.86</span>, <span class="at">y =</span> <span class="sc">-</span><span class="fl">0.01</span>, <span class="at">label =</span> <span class="fu">TeX</span>(<span class="st">"$-z_{</span><span class="sc">\\</span><span class="st">alpha/2}$"</span>), <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">2.06</span>, <span class="at">y =</span> <span class="sc">-</span><span class="fl">0.01</span>, <span class="at">label =</span> <span class="fu">TeX</span>(<span class="st">"$z_{</span><span class="sc">\\</span><span class="st">alpha/2}$"</span>), <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.15</span>, <span class="at">y =</span> <span class="fu">dnorm</span>(<span class="sc">-</span><span class="fl">1.96</span>) <span class="sc">*</span> <span class="fl">1.4</span>, <span class="at">label =</span> <span class="st">"Accept"</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_blank</span>(),<span class="at">axis.title =</span> <span class="fu">element_blank</span>())</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-8_1" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-8_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="8_files/figure-html/fig-8_1-1.png" id="fig-8_1" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-8_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;8.1
</figcaption>
</figure>
</div>
</div>
</div>
<div id="exr-8_3_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.1</strong></span> 与 <a href="../chapter_7/7.html#exr-7_3_a" class="quarto-xref">习题&nbsp;<span>7.7</span></a> 类似，假设从 A 地发射一个信号 <span class="math inline">\(\mu\)</span> 到 B 地，在 B 接收到的信号的值服从均值为 <span class="math inline">\(\mu\)</span>、方差为 4 的正态分布。也就是说，B 地接收到的信号会加入随机噪声、并且该随机噪声是服从 <span class="math inline">\(\mathcal{N}(0, 4)\)</span> 的随机变量。现在，B 地的人怀疑今天 A 地发送的信号值为 <span class="math inline">\(\mu = 8\)</span>。假设 A 地独立发送了 5 次该信号，且在 B 地接收到的信号的平均值为 <span class="math inline">\(\overline{X} = 9.5\)</span>。请对 <strong>今天 A 地发送的信号值为 <span class="math inline">\(\mu = 8\)</span> </strong> 这一假设进行检验。</p>
</div>
<div id="exr-8_3_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.2</strong></span> 假设我们在 5% 的显著性水平下进行检验。首先，计算检验统计量：</p>
<p><span class="math inline">\(\frac{\sqrt{n}}{\sigma} |\overline{X} - \mu_0| = \frac{\sqrt{5}}{2} (1.5) = 1.68\)</span></p>
<p>由于 1.68 小于 <span class="math inline">\(z_{0.025} = 1.96\)</span>，因此应该接受该假设。换句话说，因为当 A 地发射的信号真的为 8 时，那么会有 5% 的可能性发生像我们观察到的样本平均值偏离 8 的这种情况，但是这个比例并没有达到足以令我们拒绝原假设，所以观察到的数据与原假设并不矛盾。但是，如果我们选择了更不严格的显著性水平——比如 <span class="math inline">\(\alpha = 0.1\)</span>，此时，因为 1.68 大于 <span class="math inline">\(z_{0.05} = 1.645\)</span>，那么我们将拒绝原假设。因此，如果我们选择了 10% 的概率会错误的拒绝原假设的情况下（<em>第 I 类错误</em>），那么我们将拒绝原假设。</p>
<p>选择合适的显著性水平（<span class="math inline">\(\alpha\)</span>）并不是一个一成不变的标准，而是需要根据具体情况进行调整。例如，如果错误的拒绝实际为真的原假设 <span class="math inline">\(H_0\)</span> 会导致巨大损失，那么我们可能会选择非常保守的显著性水平，此时可以选择 0.05 或 0.01 的显著性水平。此外，如果我们一开始就非常相信 <span class="math inline">\(H_0\)</span> 是正确的，那么我们就需要设置一个非常严格的标准并要求有强有力的数据证据才能认为 <span class="math inline">\(H_0\)</span> 是错误的。也就是说，在这种情况下，我们通常需要设置一个非常低的显著性水平（例如 0.01 或者更低）。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<p><a href="#eq-8_3_3" class="quarto-xref">式&nbsp;<span>8.5</span></a> 给出的 <strong>检验</strong> 的描述如下：对于检验统计量 <span class="math inline">\(\sqrt{n}|\overline{X} - \mu_0|/\sigma\)</span> 的任何观测值——我们称其为 <span class="math inline">\(v\)</span>——当 <span class="math inline">\(H_0\)</span> 成立时，如果检验统计量大于或等于 <span class="math inline">\(v\)</span> 的概率小于或等于显著性水平 <span class="math inline">\(\alpha\)</span>，则 <strong>检验</strong> 说明需要拒绝原假设 <span class="math inline">\(H_0\)</span>。</p>
<p>由此，我们可以通过以下步骤来确定是否接受原假设 <span class="math inline">\(H_0\)</span>：</p>
<ul>
<li>首先，计算检验统计量的值 <span class="math inline">\(v\)</span>；</li>
<li>其次，计算标准正态分布（取绝对值）的概率，即标准正态分布中大于 <span class="math inline">\(v\)</span> 的概率，我们称这一概率为检验的 <span class="math inline">\(p-\text{value}\)</span>。<span class="math inline">\(p-\text{value}\)</span> 给出了临界显著性水平的意义，即如果 <span class="math inline">\(p-\text{value}\)</span> 大于显著性水平 <span class="math inline">\(\alpha\)</span>，则接受 <span class="math inline">\(H_0\)</span>；如果 <span class="math inline">\(p-\text{value}\)</span> 小于或等于显著性水平 <span class="math inline">\(\alpha\)</span>，则拒绝 <span class="math inline">\(H_0\)</span>。</li>
</ul>
<p>在实际操作中，显著性水平往往不是预先设定的，而是会首先通过观察数据来确定 <span class="math inline">\(p-\text{value}\)</span>。</p>
<ul>
<li>有时，<span class="math inline">\(p-\text{value}\)</span> 会明显大于我们愿意使用的任何显著性水平，因此我们可以非常轻松的就接受原假设 <span class="math inline">\(H_0\)</span>。</li>
<li>而有时，<span class="math inline">\(p-\text{value}\)</span> 值又非常小（甚至小于任何我们会使用到的显著性水平），因此显然我们应该拒绝该假设。</li>
</ul>
<div id="exm-8_3_b" class="theorem example">
<p><span class="theorem-title"><strong>例 8.1</strong></span> 在 <a href="#exr-8_3_a" class="quarto-xref">习题&nbsp;<span>8.2</span></a> 中，假设接收到的 5 个值的平均值为 <span class="math inline">\(\overline{X} = 8.5\)</span>。在这种情况下，</p>
<p><span class="math inline">\(\frac{\sqrt{n}}{\sigma} |\overline{X} - \mu_0| = \frac{\sqrt{5}}{4} = 0.559\)</span></p>
<p>因为</p>
<p><span class="math inline">\(P\{|Z| &gt; 0.559\} = 2P\{Z &gt; 0.559\}= 2 \times 0.288 = 0.576\)</span></p>
<p>所以 <span class="math inline">\(p-\text{value}\)</span> 为 0.576，因此信号值为 8 的原假设在任何显著性水平 <span class="math inline">\(\alpha &lt; 0.576\)</span> 下都将被接受。显然，我们绝不会使用一个高达 0.576 的显著性水平来检验原假设，因此我们将接受 <span class="math inline">\(H_0\)</span>。</p>
<p>另一方面，如果数据的平均值为 11.5，则检验均值为 8 的 <span class="math inline">\(p-\text{value}\)</span> 值将为</p>
<p><span class="math inline">\(P\{|Z| &gt; 1.75\sqrt{5}\} = P\{|Z| &gt; 3.913\} \approx 0.00005\)</span></p>
<p>对于如此小的<span class="math inline">\(p-\text{value}\)</span>，我们将拒绝信号值为 8 的原假设。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>到现在为止，我们还没有讨论过 <strong>第 II 类错误</strong> 的概率——也就是在真实均值 <span class="math inline">\(\mu\)</span> 不等于 <span class="math inline">\(\mu_0\)</span> 时错误的接受原假设的概率。<strong>第 II 类错误</strong> 的概率取决于 <span class="math inline">\(\mu\)</span> 的值，因此我们定义 <span class="math inline">\(\beta(\mu)\)</span> 如下：</p>
<p><span class="math inline">\(\begin{align}\beta(\mu) &amp;= P_\mu\{\text{接受 } H_0\} \\ &amp;=P_{\mu}\left\{\left|\frac{\overline{X}-\mu_0}{\sigma/\sqrt{n}}\right| \le z_{\alpha/2}\right\} \\ &amp;=P_{\mu}\left\{-z_{\alpha/2} \le \frac{\overline{X}-\mu_0}{\sigma/\sqrt{n}}\le z_{\alpha/2}\right\} \end{align}\)</span></p>
<p>我们称函数 <span class="math inline">\(\beta(\mu)\)</span> 为 <strong>Operating Characteristic</strong>（<em>OC</em>）Curve，<span class="math inline">\(\beta(\mu)\)</span> 表示当真实均值为 <span class="math inline">\(\mu\)</span> 时接受原假设 <span class="math inline">\(H_0\)</span> 的概率。</p>
<p>为了计算这个概率，我们使用 <span class="math inline">\(\overline{X}\)</span> 服从均值为 <span class="math inline">\(\mu\)</span>、方差为 <span class="math inline">\(\sigma^2/n\)</span> 的正态分布的事实，因此</p>
<p><span class="math inline">\(Z \equiv \frac{\overline{X} - \mu}{\sigma/\sqrt{n}} \sim \mathcal{N}(0, 1)\)</span></p>
<p>因此，</p>
<p><span id="eq-8_3_4"><span class="math display">\[
\begin{align}
\beta(\mu) &amp;= P_\mu\left\{-z_{\alpha/2} \leq \frac{\overline{X} - \mu_0}{\sigma/\sqrt{n}} \leq z_{\alpha/2}\right\} \\
&amp;= P_\mu\left\{-z_{\alpha/2} \leq \frac{\overline{X} - \mu + \mu - \mu_0}{\sigma/\sqrt{n}} \leq z_{\alpha/2}\right\} \\
&amp;= P_\mu\left\{-z_{\alpha/2} - \frac{\mu}{\sigma / \sqrt{n}} \leq \frac{\overline{X} - \mu - \mu_0}{\sigma/\sqrt{n}} \leq z_{\alpha/2} -  \frac{\mu}{\sigma / \sqrt{n}} \right\} \\
&amp;= P_\mu\left\{ -z_{\alpha/2} - \frac{\mu}{\sigma / \sqrt{n}} \leq Z - \frac{\mu_0}{\sigma/\sqrt{n}} \leq z_{\alpha/2} -  \frac{\mu}{\sigma / \sqrt{n}} \right\} \\
&amp;= P\left\{\frac{\mu_0 - \mu}{\sigma / \sqrt{n}} - z_{\alpha/2} \le Z \le \frac{\mu_0 - \mu}{\sigma / \sqrt{n}} + z_{\alpha/2}\right\} \\
&amp;= \Phi\left(\frac{\mu_0 - \mu}{\sigma/\sqrt{n}} + z_{\alpha/2}\right) - \Phi\left(\frac{\mu_0 - \mu}{\sigma/\sqrt{n}} - z_{\alpha/2}\right)
\end{align}
\tag{8.6}\]</span></span></p>
<p>其中 <span class="math inline">\(\Phi\)</span> 是标准正态分布函数。</p>
<p>对于固定的显著性水平 <span class="math inline">\(\alpha\)</span>，由 <a href="#eq-8_3_4" class="quarto-xref">式&nbsp;<span>8.6</span></a> 给出的 OC 曲线是关于 <span class="math inline">\(\mu_0\)</span> 对称的，并且实际上仅通过 <span class="math inline">\(\sqrt{n}|\mu - \mu_0|/\sigma\)</span> 而依赖于 <span class="math inline">\(\mu\)</span>。当 <span class="math inline">\(\alpha = 0.05\)</span> 时，这条曲线的横坐标由 <span class="math inline">\(\mu\)</span> 改为 <span class="math inline">\(d = \sqrt{n}|\mu - \mu_0|/\sigma\)</span>，并且曲线如 <a href="#fig-8_2" class="quarto-xref">图&nbsp;<span>8.2</span></a> 所示。</p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># β(μ) 的计算函数</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>calculate_beta <span class="ot">&lt;-</span> <span class="cf">function</span>(mu, mu0, sigma, n, alpha) {</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  z_alpha <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">=</span> <span class="fu">sqrt</span>(n) <span class="sc">*</span> (mu0 <span class="sc">-</span> mu) <span class="sc">/</span> sigma</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  beta <span class="ot">=</span> <span class="fu">pnorm</span>(d <span class="sc">+</span> z_alpha) <span class="sc">-</span> <span class="fu">pnorm</span>(d <span class="sc">-</span> z_alpha)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(beta)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 参数设置</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>mu0 <span class="ot">&lt;-</span> <span class="dv">0</span>        <span class="co"># 原假设的均值</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="dv">3</span>      <span class="co"># 标准差</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span>         <span class="co"># 样本大小</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span>   <span class="co"># 显著性水平</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 生成一系列 μ 的值</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>mu_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># 计算每个 μ 对应的 β(μ)</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>beta_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(mu_values, calculate_beta, <span class="at">mu0 =</span> mu0, <span class="at">sigma =</span> sigma, <span class="at">n =</span> n, <span class="at">alpha =</span> alpha)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(n) <span class="sc">/</span> sigma <span class="sc">*</span> <span class="fu">abs</span>(mu0 <span class="sc">-</span> mu_values)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 创建数据框用于绘图</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">mu =</span> mu_values, <span class="at">d =</span> d, <span class="at">beta =</span> beta_values)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a><span class="co"># 绘制 OC 曲线</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> d, <span class="at">y =</span> beta)) <span class="sc">+</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5</span>)) <span class="sc">+</span> </span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.2</span>)) <span class="sc">+</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-8_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-8_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="8_files/figure-html/fig-8_2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-8_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;8.2: 显著性水平位 0.05 时双边正态分布检验的 OC 曲线图
</figcaption>
</figure>
</div>
</div>
</div>
<div id="exm-8_3_c" class="theorem example">
<p><span class="theorem-title"><strong>例 8.2</strong></span> 对于 <a href="#exr-8_3_a" class="quarto-xref">习题&nbsp;<span>8.2</span></a> 中的问题，当实际发送的值为 10 时，计算接受原假设 <span class="math inline">\(\mu = 8\)</span> 的概率？</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># β(μ) 的计算函数</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>calculate_beta <span class="ot">&lt;-</span> <span class="cf">function</span>(mu, mu0, sigma, n, alpha) {</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  z_alpha <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">=</span> <span class="fu">sqrt</span>(n) <span class="sc">*</span> (mu0 <span class="sc">-</span> mu) <span class="sc">/</span> sigma</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  beta <span class="ot">=</span> <span class="fu">pnorm</span>(d <span class="sc">+</span> z_alpha) <span class="sc">-</span> <span class="fu">pnorm</span>(d <span class="sc">-</span> z_alpha)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(beta)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">calculate_beta</span>(<span class="dv">10</span>, <span class="dv">8</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="fl">0.05</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3912205</code></pre>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="备注">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
备注
</div>
</div>
<div class="callout-body-container callout-body">
<p>我们称 <span class="math inline">\(1 - \beta(\mu)\)</span> 为 <strong>检验功效函数</strong>（<em>power-function of the test</em>）。因此，对于给定的 <span class="math inline">\(\mu\)</span> 值，<strong>检验功效</strong> 等于当 <span class="math inline">\(\mu\)</span> 为真实值时拒绝原假设的概率。</p>
</div>
</div>
<p>在确定所需的随机样本大小以满足我们对 <em>第 II 类错误</em> 的某些特定要求的场景下，<strong>Operating Characteristic</strong> 函数非常有用。例如，假设我们希望确定所需的样本大小 <span class="math inline">\(n\)</span>，以确保当真实均值实际上为 <span class="math inline">\(\mu_1\)</span> 时，接受原假设 <span class="math inline">\(H_0: \mu = \mu_0\)</span> 的概率大约为 <span class="math inline">\(\beta\)</span>。也就是说，我们希望找到 <span class="math inline">\(n\)</span> 使得：</p>
<p><span class="math inline">\(\beta(\mu_1) \approx \beta\)</span></p>
<p>但是，根据 <a href="#eq-8_3_4" class="quarto-xref">式&nbsp;<span>8.6</span></a>，我们可以推导出，如上的式子等价于</p>
<p><span id="eq-8_3_5"><span class="math display">\[
\Phi \left(\frac{\sqrt{n}(\mu_0 - \mu_1)}{\sigma} + z_{\alpha/2}\right) - \Phi \left(\frac{\sqrt{n}(\mu_0 - \mu_1)}{\sigma} - z_{\alpha/2}\right) \approx \beta \quad
\tag{8.7}\]</span></span></p>
<p>尽管无法直接对 <a href="#eq-8_3_5" class="quarto-xref">式&nbsp;<span>8.7</span></a> 进行求解并得到 <span class="math inline">\(n\)</span>，但可以使用标准正态分布表来求解得到 <span class="math inline">\(n\)</span>。此外，还可以通过 <a href="#eq-8_3_5" class="quarto-xref">式&nbsp;<span>8.7</span></a> 推导出 <span class="math inline">\(n\)</span> 的近似值 <a href="#eq-8_3_7" class="quarto-xref">式&nbsp;<span>8.9</span></a>。</p>
<p>首先，假设 <span class="math inline">\(\mu_1 &gt; \mu_0\)</span>，于是这意味着：</p>
<p><span class="math inline">\(\frac{\sqrt{n}(\mu_0 - \mu_1)}{\sigma} - z_{\alpha/2} \leq -z_{\alpha/2}\)</span></p>
<p>由于 <span class="math inline">\(\Phi\)</span> 是一个递增函数，因此：</p>
<p><span class="math inline">\(\Phi \left(\frac{\sqrt{n}(\mu_0 - \mu_1)}{\sigma} - z_{\alpha/2}\right) \leq \Phi(-z_{\alpha/2}) = P\{Z \leq -z_{\alpha/2}\} = P\{Z \geq z_{\alpha/2}\} = \alpha/2\)</span></p>
<p>因此，我们可以取</p>
<p><span class="math inline">\(\Phi \left(\frac{\sqrt{n}(\mu_0 - \mu_1)}{\sigma} - z_{\alpha/2}\right) \approx 0\)</span></p>
<p>根据 <a href="#eq-8_3_5" class="quarto-xref">式&nbsp;<span>8.7</span></a> 可以得到：</p>
<p><span id="eq-8_3_6"><span class="math display">\[
\beta \approx \Phi \left(\frac{\sqrt{n}(\mu_0 - \mu_1)}{\sigma} + z_{\alpha/2}\right)
\tag{8.8}\]</span></span></p>
<p>或者，由于</p>
<p><span class="math inline">\(\beta = P\{Z &gt; z_{\beta}\} = P\{Z &lt; -z_{\beta}\} = \Phi(-z_{\beta})\)</span></p>
<p>根据 <a href="#eq-8_3_6" class="quarto-xref">式&nbsp;<span>8.8</span></a> 得到：</p>
<p><span class="math inline">\(-z_{\beta} \approx \frac{\sqrt{n}(\mu_0 - \mu_1)}{\sigma} + z_{\alpha/2}\)</span></p>
<p>即：</p>
<p><span id="eq-8_3_7"><span class="math display">\[
n \approx \frac{(z_{\alpha/2} + z_{\beta})^2 \sigma^2}{(\mu_1 - \mu_0)^2}
\tag{8.9}\]</span></span></p>
<p>事实上，当 <span class="math inline">\(\mu_1 &lt; \mu_0\)</span> 时，我们会得到近似相同的结果（留作习题），因此，在任何情况下 <a href="#eq-8_3_7" class="quarto-xref">式&nbsp;<span>8.9</span></a> 都是如下场景的一个合理的近似值：</p>
<ul>
<li>估计所需的样本大小，以确保当真实均值为 <span class="math inline">\(\mu = \mu_1\)</span> 时，<strong>第 II 类错误</strong> 的概率大约等于 <span class="math inline">\(\beta\)</span>。</li>
</ul>
<div id="exr-8_3_d" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.3</strong></span> 对于 <a href="#exr-8_3_a" class="quarto-xref">习题&nbsp;<span>8.2</span></a> 的问题，在 0.05 的显著性水平下，当 <span class="math inline">\(\mu\)</span> 实际为 9.2 时，需要发送多少次信号才能使得原假设 <span class="math inline">\(H_0: \mu = 8\)</span> 至少有 75% 的概率被拒绝？</p>
</div>
<div id="sol-8_3_d" class="proof solution">
<p><span class="proof-title"><em>解 8.1</em>. </span>由于 <span class="math inline">\(z_{.025} = 1.96\)</span>，<span class="math inline">\(z_{0.25} = .67\)</span>，根据 <a href="#eq-8_3_7" class="quarto-xref">式&nbsp;<span>8.9</span></a> 有：</p>
<p><span class="math inline">\(n \approx \frac{(1.96 + 0.67)^2}{(1.2)^2} 4 \approx 19.21\)</span></p>
<p>因此需要一个大小为 20 的样本。</p>
<p>根据方程 <a href="#eq-8_3_4" class="quarto-xref">式&nbsp;<span>8.6</span></a>，当 <span class="math inline">\(n = 20\)</span> 时，</p>
<p><span class="math inline">\(\begin{align} \beta(9.2) &amp;= \Phi \left(-\frac{1.2\sqrt{20}}{2} + 1.96\right) - \Phi \left(-\frac{1.2\sqrt{20}}{2} - 1.96\right) \\ &amp; \approx \Phi(-0.723) - \Phi(-4.643) \\ &amp; \approx 1 - \Phi(0.723) \\ &amp; \approx 0.235 \end{align}\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># β(μ) 的计算函数</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>calculate_beta <span class="ot">&lt;-</span> <span class="cf">function</span>(mu, mu0, sigma, n, alpha) {</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  z_alpha <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">=</span> <span class="fu">sqrt</span>(n) <span class="sc">*</span> (mu0 <span class="sc">-</span> mu) <span class="sc">/</span> sigma</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  beta <span class="ot">=</span> <span class="fu">pnorm</span>(d <span class="sc">+</span> z_alpha) <span class="sc">-</span> <span class="fu">pnorm</span>(d <span class="sc">-</span> z_alpha)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(beta)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">calculate_beta</span>(<span class="fl">9.2</span>, <span class="dv">8</span>, <span class="dv">2</span>, <span class="dv">20</span>, <span class="fl">0.05</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2347407</code></pre>
</div>
</div>
<p>因此，如果发送消息 20 次，那么当真实均值为 9.2 时，有 76.5% 的概率会拒绝原假设 <span class="math inline">\(\mu = 8\)</span>。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<section id="sec-8_3_1_1" class="level4" data-number="8.3.1.1">
<h4 data-number="8.3.1.1" class="anchored" data-anchor-id="sec-8_3_1_1"><span class="header-section-number">8.3.1.1</span> 单边检验</h4>
<p>在检验原假设 <span class="math inline">\(\mu = \mu_0\)</span> 时，我们选择了一种检验以使得在 <span class="math inline">\(\overline{X}\)</span> 远离 <span class="math inline">\(\mu_0\)</span> 时拒绝原假设。也就是说，和 <span class="math inline">\(\mu_0\)</span> 相比，<span class="math inline">\(\overline{X}\)</span>（<span class="math inline">\(\mu\)</span> 的估计量）的一个非常小的值或非常大的值似乎使得 <span class="math inline">\(\mu\)</span> 不可能等于 <span class="math inline">\(\mu_0\)</span>。然而，当 <span class="math inline">\(\mu\)</span> 等于 <span class="math inline">\(\mu_0\)</span> 的唯一 <strong>备择假设</strong> 是 <span class="math inline">\(\mu &gt; \mu_0\)</span> 时会发生什么呢？也就是说，当 <strong>备择假设</strong> 为 <span class="math inline">\(H_1: \mu &gt; \mu_0\)</span> 时会发生什么？显然，此时，在 <span class="math inline">\(\overline{X}\)</span> 很小（与 <span class="math inline">\(\mu\)</span> 相比）时，<span class="math inline">\(H_0\)</span> 为真比 <span class="math inline">\(H_1\)</span> 为真更有可能发生。因此，此时，我们不希望拒绝 <span class="math inline">\(H_0\)</span>。</p>
<p>因此，对于 <a href="#eq-8_3_8" class="quarto-xref">式&nbsp;<span>8.10</span></a> 的检验</p>
<p><span id="eq-8_3_8"><span class="math display">\[
H_0: \mu = \mu_0 \quad vs. \quad H_1: \mu &gt; \mu_0
\tag{8.10}\]</span></span></p>
<p>当 <span class="math inline">\(\mu_0\)</span> 的点估计 <span class="math inline">\(\overline{X}\)</span> 远大于 <span class="math inline">\(\mu_0\)</span> 时，我们应该拒绝 <span class="math inline">\(H_0\)</span>。这意味着，<strong>临界区</strong> 应如下所示：</p>
<p><span class="math inline">\(C = \{(X_1, \dots, X_n) : \overline{X} - \mu_0 &gt; c\}\)</span></p>
<p>由于当 <span class="math inline">\(H_0\)</span> 为真时，拒绝原假设的概率应该等于 <span class="math inline">\(\alpha\)</span>，因此 <span class="math inline">\(c\)</span> 需要满足：</p>
<p><span id="eq-8_3_9"><span class="math display">\[
P_{\mu_0}\{\overline{X} - \mu_0 &gt; c\} = \alpha
\tag{8.11}\]</span></span></p>
<p>当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(Z\)</span> 服从标准正态分布：</p>
<p><span class="math inline">\(Z = \frac{\overline{X} - \mu_0}{\sigma/\sqrt{n}} = \sqrt{n}\frac{(\overline{X} - \mu_0)}{\sigma}\)</span></p>
<p>所以，<a href="#eq-8_3_9" class="quarto-xref">式&nbsp;<span>8.11</span></a> 等价于：</p>
<p><span class="math inline">\(P\left\{Z &gt; \frac{c\sqrt{n}}{\sigma}\right\} = \alpha\)</span></p>
<p>由于</p>
<p><span class="math inline">\(P\{Z &gt; z_{\alpha}\} = \alpha\)</span></p>
<p>所以有：</p>
<p><span id="eq-8_3_1_1_001"><span class="math display">\[
c = \frac{z_{\alpha}\sigma}{\sqrt{n}}
\tag{8.12}\]</span></span></p>
<p>因此，假设 <a href="#eq-8_3_8" class="quarto-xref">式&nbsp;<span>8.10</span></a> 的检验是当 <span class="math inline">\(\overline{X} - \mu_0 &gt; z_{\alpha} \sigma / \sqrt{n}\)</span> 时拒绝 <span class="math inline">\(H_0\)</span>，否则接受 <span class="math inline">\(H_0\)</span>。即：</p>
<p><span id="eq-8_3_10"><span class="math display">\[
\begin{align}
&amp;\text{接受} \ H_0 \quad \text{如果} \frac{\sqrt{n}}{\sigma} (\overline{X} - \mu_0) \leq z_{\alpha} \\
&amp;\text{拒绝} \ H_0 \quad \text{如果} \frac{\sqrt{n}}{\sigma} (\overline{X} - \mu_0) \gt z_{\alpha} \\
\end{align}
\tag{8.13}\]</span></span></p>
<p>因为仅在 <span class="math inline">\(\overline{X}\)</span> 较大时才会拒绝原假设，所以 <a href="#eq-8_3_10" class="quarto-xref">式&nbsp;<span>8.13</span></a> 称之为 <strong>单边临界区域</strong>（<em>one-sided critical region</em>）。相应地，与 <strong>备择假设</strong> 为 <span class="math inline">\(H_1: \mu \neq \mu_0\)</span> 的双边检验问题相比，<a href="#eq-8_3_1_1_002" class="quarto-xref">式&nbsp;<span>8.14</span></a> 所示的假设检验问题也称之为 <strong>单边检验问题</strong>。</p>
<p><span id="eq-8_3_1_1_002"><span class="math display">\[
\begin{align}
H_0: &amp;\mu = \mu_0 \\
H_1: &amp; \mu &gt; \mu_0
\end{align}
\tag{8.14}\]</span></span></p>
<p>为了计算 <strong>单边检验</strong> 中的 <span class="math inline">\(p-\text{value}\)</span>，我们</p>
<ul>
<li>首先使用观测数据确定统计量 <span class="math inline">\(\frac{\sqrt{n}(\overline{X} - \mu_0)}{\sigma}\)</span> 的值。</li>
<li>然后，<span class="math inline">\(p-\text{value}\)</span> 等于标准正态分布中大于等于该值的概率。</li>
</ul>
<div id="exr-8_3_e" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.4</strong></span> 假设在 <a href="#exr-8_3_a" class="quarto-xref">习题&nbsp;<span>8.2</span></a> 中，我们预先知道信号值至少是 8，那么在这种情况下可以得出什么结论？</p>
</div>
<div id="sol-8_3_e" class="proof solution">
<p><span class="proof-title"><em>解 8.2</em>. </span>为了判断观察到的数据是否与均值为 8 的假设一致，我们做如下的检验：</p>
<p><span class="math inline">\(\begin{align}H_0: &amp;\mu = 8 \\ H_1: &amp;\mu &gt; 8 \end{align}\)</span></p>
<p>单边检验统计量的值为：</p>
<p><span class="math inline">\(\sqrt{n} \frac{(\overline{X} - \mu_0)}{\sigma} = \sqrt{5} \frac{(9.5 - 8)}{2} = 1.68\)</span></p>
<p>并且 <span class="math inline">\(p-\text{value}\)</span> 为标准正态分布超过 1.68 的概率，即</p>
<p><span class="math inline">\(p-\text{value} = 1 - \Phi(1.68) = 0.0465\)</span></p>
<p>该检验将在所有大于或等于 0.0465 的显著性水平下拒绝原假设。例如，如果显著性水平 <span class="math inline">\(\alpha = 0.05\)</span>，那么我们将拒绝原假设。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
<p><a href="#eq-8_3_10" class="quarto-xref">式&nbsp;<span>8.13</span></a> 所示的单边检验的 <strong>Operating Characteristic</strong> 函数 <span class="math inline">\(\beta(\mu) = P_{\mu}\{\text{接受} H_0\}\)</span> 为：</p>
<p><span class="math inline">\(\begin{align} \beta(\mu) &amp;= P_{\mu}\left\{ \overline{X} \leq \mu_0 + z_{\alpha}\frac{\sigma}{\sqrt{n}} \right\} \\ &amp;= P\left\{ \frac{\sqrt{n}(\overline{X} - \mu_0)}{\sigma} \leq \frac{\sqrt{n}(\mu_0 - \mu)}{\sigma} + z_{\alpha} \right\} \\ &amp;= P\left\{ Z \leq \frac{\sqrt{n}(\mu_0 - \mu)}{\sigma} + z_{\alpha} \right\}, \quad Z \sim N(0, 1) \end{align}\)</span></p>
<p>即：</p>
<p><span class="math inline">\(\beta(\mu) = \Phi \left( \frac{\sqrt{n}(\mu_0 - \mu)}{\sigma} + z_{\alpha} \right)\)</span></p>
<p>由于 <span class="math inline">\(\Phi\)</span> 是概率分布函数，因此 <span class="math inline">\(\Phi\)</span> 随着自变量的增加而递增，所以从直觉而言：<span class="math inline">\(\beta(\mu)\)</span> 随 <span class="math inline">\(\mu\)</span> 的增加而减少是合理的。显然，当真实均值 <span class="math inline">\(\mu\)</span> 越大时，<span class="math inline">\(\mu \leq \mu_0\)</span> 的可能性就越小。此外，由于 <span class="math inline">\(\Phi(z_{\alpha}) = 1 - \alpha\)</span>，因此</p>
<p><span class="math inline">\(\beta(\mu_0) = 1 - \alpha\)</span></p>
<p>最初用于检验 <span class="math inline">\(H_0: \mu = \mu_0 \ vs. \ H_1: \mu &gt; \mu_0\)</span> 的 <a href="#eq-8_3_10" class="quarto-xref">式&nbsp;<span>8.13</span></a> 也可以用于：在显著性水平 <span class="math inline">\(\alpha\)</span> 下，如下假设的单边检验：</p>
<p><span id="eq-8_3_1_1_003"><span class="math display">\[
H_0: \mu \leq \mu_0 \quad vs. \quad H_1: \mu &gt; \mu_0
\tag{8.15}\]</span></span></p>
<p>为了验证它仍然是在显著性水平为 <span class="math inline">\(\alpha\)</span> 下的检验，我们需要证明：当 <span class="math inline">\(H_0\)</span> 为真时，拒绝原假设的概率不超过 <span class="math inline">\(\alpha\)</span>。也就是说，我们必须验证：</p>
<p><span class="math inline">\(1 - \beta(\mu) \leq \alpha , \quad \quad \forall \mu \leq \mu_0\)</span></p>
<p>或者</p>
<p><span class="math inline">\(\beta(\mu) \geq 1 - \alpha , \quad \quad \forall \mu \leq \mu_0\)</span></p>
<p>之前已经证明，对于由方程 <a href="#eq-8_3_10" class="quarto-xref">式&nbsp;<span>8.13</span></a> 给出的检验，<span class="math inline">\(\beta(\mu)\)</span> 随 <span class="math inline">\(\mu\)</span> 的增加而减少，且 <span class="math inline">\(\beta(\mu_0) = 1 - \alpha\)</span>。于是：</p>
<p><span class="math inline">\(\beta(\mu) \geq \beta(\mu_0) = 1 - \alpha , \quad \quad \forall \mu \leq \mu_0\)</span></p>
<p>这表明由 <a href="#eq-8_3_10" class="quarto-xref">式&nbsp;<span>8.13</span></a> 给出的检验在显著性水平 <span class="math inline">\(\alpha\)</span> 下，对 <span class="math inline">\(H_0: \mu \leq \mu_0 \quad vs. \quad H_1: \mu &gt; \mu_0\)</span> 仍然是一个 显著性水平为 <span class="math inline">\(\alpha\)</span> 的检验。</p>
<div class="callout callout-style-default callout-tip callout-titled" title="备注">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
备注
</div>
</div>
<div class="callout-body-container callout-body">
<p>我们还可以在在显著性水平 <span class="math inline">\(\alpha\)</span> 下对如下的假设</p>
<p><span class="math inline">\(H_0: \mu = \mu_0 \quad (\text{或} \quad \mu \geq \mu_0) \quad vs \quad H_1: \mu &lt; \mu_0\)</span></p>
<p>做出如下的单边检验：</p>
<p><span class="math inline">\(\begin{align} \text{接受 } H_0, &amp; \quad \text{如果} \quad \frac{\sqrt{n}}{\sigma}(\overline{X} - \mu_0) \geq -z_{\alpha} \\ \text{拒绝 } H_0, &amp; \quad \text{其他} \end{align}\)</span></p>
<p>可以通过首先计算检验统计量 <span class="math inline">\(\frac{\sqrt{n}(\overline{X} - \mu_0)}{\sigma}\)</span> 来进行该检验。<span class="math inline">\(p-\text{value}\)</span> 等于标准正态分布小于 <span class="math inline">\(\frac{\sqrt{n}(\overline{X} - \mu_0)}{\sigma}\)</span> 的概率，当 <span class="math inline">\(p-\text{value}\)</span> 小于任何的显著性水平时，我们将拒绝原假设。</p>
</div>
</div>
<div id="exr-8_3_f" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.5</strong></span> 目前，市场上的所有香烟的平均尼古丁含量至少为 1.6 毫克/支。一家生产香烟的公司声称，他们发现了一种新的烟草叶处理方法，这种方法会使香烟的平均尼古丁含量低于 1.6 毫克/支。为了测试这家公司的这一说法，我们分析了该公司的 20 支香烟的样本。已知一支香烟的尼古丁含量的标准差为 0.8 毫克，如果 20 支香烟的平均尼古丁含量为 1.54/支，那么在显著性水平为 5% 的情况下，可以得出什么结论？</p>
<p><strong>注意</strong>：如上问题中有一个问题，即我们如何事先知道标准差为 0.8。一个可能性是，香烟尼古丁含量的变化源自每支香烟中的烟草量的变化，而不是使用的处理方法。因此，可以从以往的经验中得知香烟中尼古丁含量的标准差。</p>
</div>
<div id="sol-8_3_f" class="proof solution">
<p><span class="proof-title"><em>解 8.3</em>. </span>我们必须首先确定适当的原假设。如前所述，我们的检验方法在对原假设和备择假设的处理上是不对称的，因为我们只考虑那些在原假设为真时拒绝原假设的概率永远不会超过显著性水平 <span class="math inline">\(\alpha\)</span> 的检验。因此，拒绝原假设是对数据与此假设不一致的强烈陈述，而当接受原假设时，并不能做出类似的陈述。因此，我们希望仅在有充分证据支持生产商的说法时才能接受生产商的说法，因此我们应将生产商的说法作为备择假设。也就是说，我们应该检验：</p>
<p><span class="math inline">\(H_0: \mu \geq 1.6 \quad vs \quad H_1: \mu &lt; 1.6\)</span></p>
<p>此时，检验统计量的值为</p>
<p><span class="math inline">\(\frac{\sqrt{n}(\overline{X} - \mu_0)}{\sigma} = \frac{\sqrt{20}(1.54 - 1.6)}{0.8} = -0.336\)</span></p>
<p>因此，<span class="math inline">\(p\)</span> 值为</p>
<p><span class="math inline">\(\text{p-value} = P\{Z &lt; -0.336\} = 0.368\)</span></p>
<p>由于 <span class="math inline">\(\text{p-value}\)</span> 大于 0.05，因此在显著性水平为 5% 的情况下，样本数据不足以拒绝平均尼古丁含量超过 1.6 毫克的假设。换句话说，尽管样本数据支持了香烟生产商的说法，但尚不足以证明应该接受生产商的说法。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="备注">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
备注
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><strong>置信区间估计</strong> 与 <strong>假设检验</strong> 之间有直接的类比关系。例如，对于均值为 <span class="math inline">\(\mu\)</span>、方差为 <span class="math inline">\(\sigma^2\)</span>（已知）的正态分布总体，正如我们在 <a href="../chapter_7/7.html#sec-7_3" class="quarto-xref"><span>小节 7.3</span></a> 中所述，<span class="math inline">\(\mu\)</span> 的 <span class="math inline">\(100(1 - \alpha)\%\)</span> 置信区间为：</p>
<p><span class="math inline">\(\mu \in \left( \overline{X} - z_{\alpha/2}\frac{\sigma}{\sqrt{n}}, \, \overline{X} + z_{\alpha/2}\frac{\sigma}{\sqrt{n}} \right)\)</span></p>
<p>其中 <span class="math inline">\(\overline{X}\)</span> 是观测到的样本均值。更正式地，前述置信区间等价于：</p>
<p><span class="math inline">\(P \left\{ \mu \in \left( \overline{X} - z_{\alpha/2}\frac{\sigma}{\sqrt{n}}, \, \overline{X} + z_{\alpha/2}\frac{\sigma}{\sqrt{n}} \right) \right\} = 1 - \alpha\)</span></p>
<p>因此，如果 <span class="math inline">\(\mu = \mu_0\)</span>，则 <span class="math inline">\(\mu_0\)</span> 落在区间</p>
<p><span class="math inline">\(\left( \overline{X} - z_{\alpha/2}\frac{\sigma}{\sqrt{n}}, \, \overline{X} + z_{\alpha/2}\frac{\sigma}{\sqrt{n}} \right)\)</span></p>
<p>的概率是 <span class="math inline">\(1 - \alpha\)</span>，这意味着显著性水平为 <span class="math inline">\(\alpha\)</span> 的假设——<span class="math inline">\(H_0: \mu = \mu_0 \quad vs \quad H_1: \mu \neq \mu_0\)</span> 的检验是：</p>
<p>当 <span class="math inline">\(\mu_0 \notin \left( \overline{X} - z_{\alpha/2}\frac{\sigma}{\sqrt{n}}, \, \overline{X} + z_{\alpha/2}\frac{\sigma}{\sqrt{n}} \right)\)</span> 时拒绝 <span class="math inline">\(H_0\)</span>。</p>
<p>类似地，<span class="math inline">\(\mu\)</span> 的 <span class="math inline">\(100(1 - \alpha)\%\)</span> 单边置信区间由下式给出：</p>
<p><span class="math inline">\(\mu \in \left( \overline{X} - z_{\alpha}\frac{\sigma}{\sqrt{n}}, \, \infty \right)\)</span></p>
<p>因此，显著性水平为 <span class="math inline">\(\alpha\)</span> 的假设——<span class="math inline">\(H_0: \mu \leq \mu_0 \quad vs \quad H_1: \mu &gt; \mu_0\)</span> 的检验是：</p>
<p>当 <span class="math inline">\(\mu_0 \notin \left( \overline{X} - z_{\alpha}\frac{\sigma}{\sqrt{n}}, \, \infty \right)\)</span>（即，<span class="math inline">\(\mu_0 &lt; \overline{X} - z_{\alpha}\frac{\sigma}{\sqrt{n}}\)</span>） 时拒绝 <span class="math inline">\(H_0\)</span>。</p></li>
<li><p><strong>关于稳健性（<em>robustness</em>）的说明</strong>：统计检验通常基于一些前提条件或假设（例如样本来自正态分布、方差是已知的等），当这些前提条件或假设并不满足的时候，某个检验仍能有良好的表现，那么我们认为该检验是稳健（<em>robust</em>）的。例如，<a href="#sec-8_3_1" class="quarto-xref"><span>小节 8.3.1</span></a> 和 <a href="#sec-8_3_1_1" class="quarto-xref"><span>小节 8.3.1.1</span></a> 中的检验都是基于如下的假设：总体分布是方差为 <span class="math inline">\(\sigma^2\)</span> 的正态分布。然而，在推导这些检验时，这个假设仅用于得出：<span class="math inline">\(\overline{X}\)</span> 也服从正态分布。但是，由中心极限定理（<a href="../chapter_6/6.html#thm-6_3_1" class="quarto-xref">定理&nbsp;<span>6.1</span></a>）可知，当样本量足够大时，无论总体服从什么分布，<span class="math inline">\(\overline{X}\)</span> 都将近似服从正态分布。因此，我们可以得出结论，这些检验对于任何方差为 <span class="math inline">\(\sigma^2\)</span> 的总体分布都将是相对稳健的。</p></li>
</ul>
</div>
</div>
<p><a href="#tbl-8_1" class="quarto-xref">表&nbsp;<span>8.1</span></a> 对本节的假设检验进行了总结。</p>
<div id="tbl-8_1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-8_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;8.1: <span class="math inline">\(X_1, \dots, X_n\)</span> 是来自 <span class="math inline">\((\mu, \sigma^2)\)</span> 的总体，其中 <span class="math inline">\(\sigma^2\)</span> 是已知的，<span class="math inline">\(\overline{X} = \frac{1}{n} \sum_{i=1}^n X_i\)</span>，<span class="math inline">\(Z\)</span> 是标准正态分布随机变量
</figcaption>
<div aria-describedby="tbl-8_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(H_0\)</span></th>
<th><span class="math inline">\(H_1\)</span></th>
<th>检验统计量（<em>Test Statistic</em>） <span class="math inline">\(TS\)</span></th>
<th>在显著性水平 <span class="math inline">\(\alpha\)</span> 下的检验</th>
<th><span class="math inline">\(TS=t\)</span> 时的 <span class="math inline">\(p-\text{value}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mu = \mu_0\)</span></td>
<td><span class="math inline">\(\mu \neq \mu_0\)</span></td>
<td><span class="math inline">\(\sqrt{n}\frac{(\overline{X} - \mu_0)}{\sigma}\)</span></td>
<td>拒绝 <span class="math inline">\(H_0\)</span> 如果 <span class="math inline">\(|TS| &gt; z_{\alpha/2}\)</span></td>
<td><span class="math inline">\(2P\{Z \geq |t|\}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mu \leq \mu_0\)</span></td>
<td><span class="math inline">\(\mu &gt; \mu_0\)</span></td>
<td><span class="math inline">\(\sqrt{n}\frac{(\overline{X} - \mu_0)}{\sigma}\)</span></td>
<td>拒绝 <span class="math inline">\(H_0\)</span> 如果 <span class="math inline">\(TS &gt; z_{\alpha}\)</span></td>
<td><span class="math inline">\(P\{Z \geq t\}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mu \geq \mu_0\)</span></td>
<td><span class="math inline">\(\mu &lt; \mu_0\)</span></td>
<td><span class="math inline">\(\sqrt{n}\frac{(\overline{X} - \mu_0)}{\sigma}\)</span></td>
<td>拒绝 <span class="math inline">\(H_0\)</span> 如果 <span class="math inline">\(TS &lt; -z_{\alpha}\)</span></td>
<td><span class="math inline">\(P\{Z \leq t\}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-8_3_2" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="sec-8_3_2"><span class="header-section-number">8.3.2</span> 方差未知的场景：<span class="math inline">\(t-\text{检验}\)</span></h3>
<p>到目前为止，我们假设正态分布总体的唯一未知参数是其均值。然而，更常见的情况是均值 <span class="math inline">\(\mu\)</span> 和方差 <span class="math inline">\(\sigma^2\)</span> 都未知。假设在这种情况下，再次考虑检验均值等于某个指定值 <span class="math inline">\(\mu_0\)</span> 的假设。即考虑以下假设检验：</p>
<p><span class="math inline">\(H_0: \mu = \mu_0 \quad vs \quad H_1: \mu \neq \mu_0\)</span></p>
<p>需要注意的是，此时，因为我们并没有有指定 <span class="math inline">\(\sigma^2\)</span> 的值，因此原假设并不是一个 <strong>简单假设</strong>（<a href="#sec-8_2" class="quarto-xref"><span>小节 8.2</span></a>）。</p>
<p>与 <a href="#sec-8_3_1" class="quarto-xref"><span>小节 8.3.1</span></a> 一样，当样本均值 <span class="math inline">\(\overline{X}\)</span> 远离 <span class="math inline">\(\mu_0\)</span> 时，拒绝 <span class="math inline">\(H_0\)</span> 是合理的。然而，样本均值 <span class="math inline">\(\overline{X}\)</span> 需要远离 <span class="math inline">\(\mu_0\)</span> 多远才能合理地拒绝 <span class="math inline">\(H_0\)</span> 取决于方差 <span class="math inline">\(\sigma^2\)</span>（参见 <a href="#eq-8_3_001" class="quarto-xref">式&nbsp;<span>8.4</span></a>）。如 <a href="#eq-8_3_3" class="quarto-xref">式&nbsp;<span>8.5</span></a>，<span class="math inline">\(\sigma^2\)</span> 已知时，当 <span class="math inline">\(|\overline{X} - \mu_0|\)</span> 超过 <span class="math inline">\(z_{\alpha/2}\sigma/\sqrt{n}\)</span> 时，检验会拒绝 <span class="math inline">\(H_0\)</span>，即当：</p>
<p><span class="math inline">\(\frac{\sqrt{n}|\overline{X} - \mu_0|}{\sigma} &gt; z_{\alpha/2}\)</span></p>
<p>时拒绝 <span class="math inline">\(H_0\)</span>。</p>
<p>现在，当 <span class="math inline">\(\sigma^2\)</span> 未知时，需要先估计 <span class="math inline">\(\sigma^2\)</span>：</p>
<p><span class="math inline">\(S^2 = \frac{\sum_{i=1}^{n} (X_i - \overline{X})^2}{n-1}\)</span></p>
<p>然后，当</p>
<p><span class="math inline">\(\frac{|\overline{X} - \mu_0|}{S/\sqrt{n}}\)</span></p>
<p>较大时拒绝 <span class="math inline">\(H_0\)</span>。</p>
<p>为了确定在显著性水平 <span class="math inline">\(\alpha\)</span> 下， 检验统计量</p>
<p><span class="math inline">\(\frac{\sqrt{n}|\overline{X} - \mu_0|}{S}\)</span></p>
<p>需要大到什么程度时才能拒绝 <span class="math inline">\(H_0\)</span>，我们必须确定当 <span class="math inline">\(H_0\)</span> 为真时该统计量的概率分布。然而，如 <a href="../chapter_6/6.html#sec-6_5" class="quarto-xref"><span>小节 6.5</span></a> 中的 <a href="../chapter_6/6.html#cor-6_5_2" class="quarto-xref">推论&nbsp;<span>6.1</span></a> 所述，当 <span class="math inline">\(\mu = \mu_0\)</span> 时，下式定义的统计量 <span class="math inline">\(T\)</span> 服从自由度为 <span class="math inline">\(n-1\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span>。</p>
<p><span class="math inline">\(T = \frac{\sqrt{n}(\overline{X} - \mu_0)}{S}\)</span></p>
<p>因此，</p>
<p><span id="eq-8_3_11"><span class="math display">\[
P_{\mu_0}\left\{ -t_{\alpha/2, n-1} \leq \frac{\sqrt{n}(\overline{X} - \mu_0)}{S} \leq t_{\alpha/2, n-1} \right\} = 1 - \alpha
\tag{8.16}\]</span></span></p>
<p>其中 <span class="math inline">\(t_{\alpha/2, n-1}\)</span> 是自由度为 <span class="math inline">\(n-1\)</span> 的 <span class="math inline">\(t\)</span> 分布在 <span class="math inline">\(\left (100 \frac{\alpha}{2} \right) \%\)</span> 处的上百分位数。</p>
<p>因此，从 <a href="#eq-8_3_11" class="quarto-xref">式&nbsp;<span>8.16</span></a> 中，我们可以看出，当 <span class="math inline">\(\sigma^2\)</span> 未知的情况时，在适当的显著性水平 <span class="math inline">\(\alpha\)</span> 下的</p>
<p><span class="math inline">\(H_0: \mu = \mu_0 \quad vs \quad H_1: \mu \neq \mu_0\)</span></p>
<p>的检验为：</p>
<p><span id="eq-8_3_12"><span class="math display">\[
\begin{align}
\text{接受} \ H_0, &amp;\quad \text{如果} \quad \frac{\sqrt{n}|\overline{X} - \mu_0|}{S} \leq t_{\alpha/2, n-1} \\
\text{拒绝} \ H_0, &amp;\quad \text{如果} \quad \frac{\sqrt{n}|\overline{X} - \mu_0|}{S} \gt t_{\alpha/2, n-1}
\end{align}
\tag{8.17}\]</span></span></p>
<p>我们称 <a href="#eq-8_3_12" class="quarto-xref">式&nbsp;<span>8.17</span></a> 定义的检验为 <strong>双边 <span class="math inline">\(t-\text{检验}\)</span></strong>（<em>two-sided t-test</em>），如 <a href="#fig-8_3" class="quarto-xref">图&nbsp;<span>8.3</span></a> 所示。</p>
<div id="fig-8_3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-8_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../images/chapter_8/f_8_3.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-8_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;8.3: 双边 <span class="math inline">\(t-\text{检验}\)</span>
</figcaption>
</figure>
</div>
<p>如果我们用 <span class="math inline">\(t\)</span> 表示检验统计量 <span class="math inline">\(T = \sqrt{n}(\overline{X} - \mu_0)/S\)</span> 的观察值，那么检验的 <span class="math inline">\(p-\text{value}\)</span> 是当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(|T|\)</span> 超过 <span class="math inline">\(|t|\)</span> 的概率。也就是说，<span class="math inline">\(p-\text{value}\)</span> 是自由度为 <span class="math inline">\(n - 1\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span> 的绝对值超过 <span class="math inline">\(|t|\)</span> 的概率。因此，检验要求在所有的显著性水平均大于 <span class="math inline">\(p-\text{value}\)</span> 时拒绝原假设，同时在所有的显著性水平均小于 <span class="math inline">\(p-\text{value}\)</span> 时接受原假设。</p>
<div id="exr-8_3_g" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.6</strong></span> 一家诊所的患者的血液胆固醇水平范围为中高水平（即血清中胆固醇至少为 220 毫升/分升），从这些患者中招募了 50 名志愿者来测试一种用于降低血液胆固醇的新药。这 50 名志愿者服用了 1 个月的新药，并记录了他们的血液胆固醇水平的变化。如果他们的血液胆固醇平均降低了 14.8，并且样本标准差为 6.4，可以得出什么结论？</p>
</div>
<div id="sol-8_3_g" class="proof solution">
<p><span class="proof-title"><em>解 8.4</em>. </span>首先检验该变化可能完全是由偶然因素引起的假设——即这 50 个样本的变化构成了一个均值为 0 的正态分布样本。因为用于检验正态分布均值等于 0 的假设的 <span class="math inline">\(T-\text{统计量}\)</span> 的值是</p>
<p><span class="math inline">\(T = \frac{\sqrt{n} \overline{X}}{S} = \frac{\sqrt{50} \cdot 14.8}{6.4} = 16.352\)</span></p>
<p>很明显，我们应该拒绝该变化完全是由偶然因素引起的假设。</p>
<p>然而，不幸的是，此时我们还不能得出结论：这些变化是由于特定药物而不是其他因素引起的。例如，众所周知，任何药物（无论该药物是否直接与患者的病痛相关）通常都会导致患者病情的改善——即所谓的 <strong>安慰剂效应</strong>（<em>placebo effect</em>）。此外，另一个需要考虑的可能性是测试期间的天气情况，因为可以合理地认为天气会影响血液胆固醇水平。</p>
<p>确实，必须得出结论：上述的实验设计非常不合理。为了测试某种治疗方式是否对可能受多种因素影响的疾病有作用，我们应该尝试设计实验，以避免所有其他可能因素带来的影响。实现这一目标的公认方法是将志愿者随机分成两组：一组复用新药物，另一组服用安慰剂（即一种看起来像实际药物但没有生理作用的药片）。志愿者不应该知道他们是在实验组还是对照组中，实际上，如果连临床医生都不知道这些信息（即所谓的 <strong>双盲试验</strong>（<em>double-blind test</em>）），那就更好了。此时，无论是志愿者还是临床医生，他们自己的偏见都无法在实验中发挥作用。由于这两组人员是从志愿者中随机选出的，我们现在可以认为：除了一组接受了新药而另一组接受了安慰剂之外，影响这两组的所有因素都是相同的。因此，这两组之间表现出的任何差异都可以归因于新药。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="exr-8_3_h" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.7</strong></span> 一位公共卫生官员声称，家庭的平均用水量为每天 350 加仑。为了验证这一说法，对 20 户随机选定的家庭进行了研究，结果这些家庭的平均每日用水量如下：</p>
<pre><code>340, 344, 362, 375,
356, 386, 354, 364,
332, 402, 340, 355,
362, 322, 372, 324,
318, 360, 338, 370</code></pre>
<p>这些数据是否与该官员的说法相矛盾？</p>
</div>
<div id="sol-8_3_h" class="proof solution">
<p><span class="proof-title"><em>解 8.5</em>. </span>为了确定这些数据是否与官员的说法相矛盾，我们需要检验：</p>
<p><span class="math inline">\(H_0: \mu = 350 \quad vs \quad H_1: \mu \neq 350\)</span></p>
<p>首先计算样本数据集的样本均值和样本标准差：</p>
<p><span class="math inline">\(\overline{X} = 353.75, \quad S = 21.82436\)</span></p>
<p>因此，检验统计量的值为：</p>
<p><span class="math inline">\(T = \frac{\sqrt{20} (3.75)}{21.82436} = 0.7684308\)</span></p>
<p>因为这个值小于 <span class="math inline">\(|t_{0.05, 19}| = 1.730\)</span>，所以在 10% 的显著性水平下，接受原假设。实际上，检验数据的 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p-\text{value} = P\{ |T_{19}| &gt; 0.7684308 \} = 2P\{ T_{19} &gt; 0.7684308 \} = 0.4517\)</span></p>
<p>这表明在任何合理的显著性水平下，都会接受原假设，因此数据与该公共卫生官员的说法并不矛盾。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>可以使用 R 来计算 <span class="math inline">\(t-\text{检验}\)</span>。当数据位 <span class="math inline">\(x_1, ..., x_n\)</span> 时，为了检验均值 <span class="math inline">\(\mu\)</span> 等于 <span class="math inline">\(\mu_0\)</span> 的原假设与均值 <span class="math inline">\(\mu\)</span> 不等于 <span class="math inline">\(\mu_0\)</span> 的备择假设，可以使用如下的 R 代码：</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(x1, ..., xn)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, <span class="at">mu =</span> mu0)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>如上的代码会返回 <span class="math inline">\(\mu\)</span> 的 95% 的置信区间以及原假设为真时的 <span class="math inline">\(p-\text{value}\)</span>。我们可以使用如下的代码来计算 <a href="#exr-8_3_h" class="quarto-xref">习题&nbsp;<span>8.7</span></a>：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">340</span>, <span class="dv">356</span>, <span class="dv">332</span>, <span class="dv">362</span>, <span class="dv">318</span>, <span class="dv">344</span>, <span class="dv">386</span>, <span class="dv">402</span>, <span class="dv">322</span>, <span class="dv">360</span>, <span class="dv">362</span>, <span class="dv">354</span>, <span class="dv">340</span>, <span class="dv">372</span>, <span class="dv">338</span>, <span class="dv">375</span>, <span class="dv">363</span>, <span class="dv">355</span>, <span class="dv">324</span>, <span class="dv">370</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, <span class="at">mu =</span> <span class="dv">350</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  x
t = 0.76843, df = 19, p-value = 0.4517
alternative hypothesis: true mean is not equal to 350
95 percent confidence interval:
 343.5359 363.9641
sample estimates:
mean of x 
   353.75 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注记
</div>
</div>
<div class="callout-body-container callout-body">
<p>此处与原书中的结果存在一定差异，请务必注意。</p>
</div>
</div>
<p>我们可以使用 单边 <span class="math inline">\(t-\text{检验}\)</span> 来检验假设</p>
<p><span class="math inline">\(H_0: \mu = \mu_0 \quad (\text{或 } H_0: \mu \leq \mu_0) \quad vs \quad H_1: \mu &gt; \mu_0\)</span></p>
<p>显著性水平为 <span class="math inline">\(\alpha\)</span> 的检验是：</p>
<p><span id="eq-8_3_13"><span class="math display">\[
\begin{align}
\text{接受} H_0 &amp;, \quad \text{如果} \frac{\sqrt{n}(\overline{X} - \mu_0)}{S} \leq t_{\alpha, n-1} \\
\text{拒绝} H_0 &amp;, \quad \text{如果} \frac{\sqrt{n}(\overline{X} - \mu_0)}{S} &gt; t_{\alpha, n-1}
\end{align}
\tag{8.18}\]</span></span></p>
<p>如果 <span class="math inline">\(\frac{\sqrt{n}(\overline{X} - \mu_0)}{S} = v\)</span>，那么该检验的 <span class="math inline">\(p-\text{value}\)</span> 是自由度为 <span class="math inline">\(n-1\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span> 随机变量的值大于等于 <span class="math inline">\(v\)</span> 的概率，即 <span class="math inline">\(1 - pt(v, n - 1)\)</span>。</p>
<p>假设： <span class="math inline">\(H_0: \mu = \mu_0 \quad (\text{或 } H_0: \mu \geq \mu_0) \quad vs \quad H_1: \mu &lt; \mu_0\)</span></p>
<p>在显著性水平为 <span class="math inline">\(\alpha\)</span> 下的检验是：</p>
<p><span id="eq-8_3_2_001"><span class="math display">\[
\begin{align}
\text{接受 } H_0 &amp;, \quad \text{ 如果 } \frac{\sqrt{n}(\overline{X} - \mu_0)}{S} \geq -t_{\alpha, n-1} \\
\text{拒绝 } H_0 &amp;, \quad \text{ 如果 } \frac{\sqrt{n}(\overline{X} - \mu_0)}{S} &lt; -t_{\alpha, n-1}
\end{align}
\tag{8.19}\]</span></span></p>
<p>该检验的 <span class="math inline">\(p-\text{value}\)</span> 是自由度为 <span class="math inline">\(n-1\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span> 随机变量的值小于或等于观测值 <span class="math inline">\(\frac{\sqrt{n}(\overline{X} - \mu_0)}{S}\)</span> 的概率，即 <span class="math inline">\(pt(v, n - 1)\)</span>。</p>
<div id="exr-8_3_i" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.8</strong></span> 新型玻璃纤维轮胎的制造商声称他们生产的轮胎的平均寿命至少为 40,000 英里。为了验证这一说法，测试了 12 条轮胎，其寿命（以千英里为单位）如下：</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>轮胎序号</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
<th>11</th>
<th>12</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>寿命</td>
<td>36.1</td>
<td>40.2</td>
<td>33.8</td>
<td>38.5</td>
<td>42</td>
<td>35.8</td>
<td>37</td>
<td>41</td>
<td>36.8</td>
<td>37.2</td>
<td>33</td>
<td>36</td>
</tr>
</tbody>
</table>
<p>在 5% 的显著性水平下，检验制造商的说法。</p>
</div>
<div id="sol-8_3_i" class="proof solution">
<p><span class="proof-title"><em>解 8.6</em>. </span>为了确定上述数据是否与制造商生成的其产品的平均寿命至少为 40,000 英里的假设一致，我们将检验</p>
<p><span class="math inline">\(H_0: \mu \geq 40,000 \quad vs \quad H_1: \mu &lt; 40,000\)</span></p>
<p>计算得出</p>
<p><span class="math inline">\(\overline{X} = 37.2833, \quad S = 2.7319\)</span></p>
<p>因此，检验统计量的值为</p>
<p><span class="math inline">\(T = \frac{\sqrt{12}(37.2833 - 40)}{2.7319} = -3.4448\)</span></p>
<p>由于 -3.4448 小于 <span class="math inline">\(t_{0.05, 11} = -1.796\)</span>，因此在 5% 的显著性水平下需要拒绝原假设。实际上，观察数据的 <span class="math inline">\(p-\text{value}\)</span> 为</p>
<p><span class="math inline">\(p-\text{value} = P\{ T_{11} &lt; -3.4448 \} = P\{ T_{11} &gt; 3.4448 \} = 0.0027\)</span></p>
<p>这表明在任何大于 0.003 的显著性水平下，我们都将拒绝制造商的说法。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>通过 R 提供的 单边 <span class="math inline">\(t-\text{检验}\)</span> 函数也可以解决 <a href="#exr-8_3_i" class="quarto-xref">习题&nbsp;<span>8.8</span></a> 的问题。在 R 中，通过指定备择假设是均值小于或大于 <span class="math inline">\(\mu_0\)</span> 来执行单边 <span class="math inline">\(t-\text{检验}\)</span>。也就是说，当数据为 <span class="math inline">\(x_1, ..., x_n\)</span> 时，可以使用如下 R 代码对 <span class="math inline">\(H_0: \mu = \mu_0 \quad vs \quad H_1: \mu &gt; \mu_0\)</span> 进行单边 <span class="math inline">\(t-\text{检验}\)</span>。</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(x1,...,xn)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x,  <span class="at">mu =</span> mu0, <span class="at">alternative =</span><span class="st">"less"</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>例如，对于 <a href="#exr-8_3_i" class="quarto-xref">习题&nbsp;<span>8.8</span></a> 而言，可以使用如下 R 代码：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">36.1</span>, <span class="fl">40.2</span>, <span class="fl">33.8</span>, <span class="fl">38.5</span>, <span class="dv">42</span>, <span class="fl">35.8</span>, <span class="dv">37</span>, <span class="dv">41</span>, <span class="fl">36.8</span>, <span class="fl">37.2</span>, <span class="dv">33</span>, <span class="dv">36</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, <span class="at">mu =</span> <span class="dv">40</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  x
t = -3.4448, df = 11, p-value = 0.002739
alternative hypothesis: true mean is less than 40
95 percent confidence interval:
     -Inf 38.69963
sample estimates:
mean of x 
 37.28333 </code></pre>
</div>
</div>
<div id="exr-8_3_j" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.9</strong></span> 对于一个单服务窗口的排队系统而言，如果到达的客户数量服从泊松分布，那么客户的平均排队时间取决于为客户服务时间的均值和方差。确实，如果 <span class="math inline">\(\mu\)</span> 是服务时间的均值，<span class="math inline">\(\sigma^2\)</span> 是服务时间的方差，那么客户在排队中花费的平均时间将由以下公式给出：</p>
<p><span class="math inline">\(\frac{\lambda (\mu^2 + \sigma^2)}{2(1 - \lambda \mu)}\)</span></p>
<p>其中 <span class="math inline">\(\lambda \mu &lt; 1\)</span>，并且 <span class="math inline">\(\lambda\)</span> 是到达率。如果 <span class="math inline">\(\lambda \mu \geq 1\)</span>，则平均等待时间将是无限等待。因为 <span class="math inline">\(\lambda\)</span> 是到达率，<span class="math inline">\(1/\lambda\)</span> 是到达之间的平均时间，因此根据如上的公式可见，当 <span class="math inline">\(\mu\)</span> 仅略小于 <span class="math inline">\(1/\lambda\)</span> 时，平均延迟还相当大。</p>
<p>假设服务站的平均服务时间（每人）超过 8 分钟，那么该服务站的主管就会雇用第二名服务人员。以下数据给出了该排队系统中 28 位客户的服务时间（以分钟为单位），这些数据是否表明该服务站的平均服务时间超过 8 分钟？</p>
<pre><code>8.6, 9.4, 5.0, 4.4, 3.7, 11.4, 10.0, 7.6, 14.4, 12.2, 11.0, 14.4, 9.3, 10.5, 10.3, 7.7, 8.3, 6.4, 9.2, 5.7, 7.9, 9.4, 9.0, 13.3, 11.6, 10.0, 9.5, 6.6</code></pre>
</div>
<div id="sol-8_3_j" class="proof solution">
<p><span class="proof-title"><em>解 8.7</em>. </span>使用上述数据来检验服务时间的均值小于或等于 8 分钟的原假设。一个较小的 <span class="math inline">\(p-\text{value}\)</span> 将是平均服务时间超过 8 分钟的有力证据。利用 <code>t.test()</code> 对如上数据进行 <span class="math inline">\(t-\text{检测}\)</span> 得到：检验统计量的值为 2.257，<span class="math inline">\(p-\text{value}\)</span> 为 0.016。如此小的 <span class="math inline">\(p-\text{value}\)</span> 无疑是平均服务时间超过 8 分钟的有力证据。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">8.6</span>, <span class="fl">9.4</span>, <span class="fl">5.0</span>, <span class="fl">4.4</span>, <span class="fl">3.7</span>, <span class="fl">11.4</span>, <span class="fl">10.0</span>, <span class="fl">7.6</span>, <span class="fl">14.4</span>, <span class="fl">12.2</span>, <span class="fl">11.0</span>, <span class="fl">14.4</span>, <span class="fl">9.3</span>, <span class="fl">10.5</span>, <span class="fl">10.3</span>, <span class="fl">7.7</span>, <span class="fl">8.3</span>, <span class="fl">6.4</span>, <span class="fl">9.2</span>, <span class="fl">5.7</span>, <span class="fl">7.9</span>, <span class="fl">9.4</span>, <span class="fl">9.0</span>, <span class="fl">13.3</span>, <span class="fl">11.6</span>, <span class="fl">10.0</span>, <span class="fl">9.5</span>, <span class="fl">6.6</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, <span class="at">mu =</span> <span class="dv">8</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  x
t = 2.2575, df = 27, p-value = 0.01613
alternative hypothesis: true mean is greater than 8
95 percent confidence interval:
 8.287595      Inf
sample estimates:
mean of x 
 9.171429 </code></pre>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<p><a href="#tbl-8_2" class="quarto-xref">表&nbsp;<span>8.2</span></a> 对本节的内容进行了总结。</p>
<div id="tbl-8_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-8_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;8.2: <span class="math inline">\(X_1, \dots, X_n\)</span> 是来自方差未知的 <span class="math inline">\((\mu, \sigma^2)\)</span> 总体，<span class="math inline">\(\overline{X} = \sum_{i=1}^{n} X_i/n\)</span>，<span class="math inline">\(S^2 = \sum_{i=1}^{n}(X_i - \overline{X})^2 / (n-1)\)</span>，<span class="math inline">\(T_{n-1}\)</span> 是自由度为 <span class="math inline">\(n-1\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span> 随机变量，<span class="math inline">\(P\{T_{n-1} &gt; t_{\alpha, n-1}\} = \alpha\)</span>
</figcaption>
<div aria-describedby="tbl-8_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 39%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(H_0\)</span></th>
<th><span class="math inline">\(H_1\)</span></th>
<th>统计量 TS</th>
<th>在显著性水平为 <span class="math inline">\(\alpha\)</span> 时的检验</th>
<th><span class="math inline">\(p-\text{value}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mu = \mu_0\)</span></td>
<td><span class="math inline">\(\mu \neq \mu_0\)</span></td>
<td><span class="math inline">\(\sqrt{n}(\overline{X} - \mu_0)/S\)</span></td>
<td>拒绝 <span class="math inline">\(H_0\)</span> 如果， <span class="math inline">\(|TS| &gt; t_{\alpha/2, n-1}\)</span></td>
<td><span class="math inline">\(2P\{T_{n-1} \geq |t|\}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mu \leq \mu_0\)</span></td>
<td><span class="math inline">\(\mu &gt; \mu_0\)</span></td>
<td><span class="math inline">\(\sqrt{n}(\overline{X} - \mu_0)/S\)</span></td>
<td>拒绝 <span class="math inline">\(H_0\)</span> 如果， <span class="math inline">\(TS &gt; t_{\alpha, n-1}\)</span></td>
<td><span class="math inline">\(P\{T_{n-1} \geq t\}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mu \geq \mu_0\)</span></td>
<td><span class="math inline">\(\mu &lt; \mu_0\)</span></td>
<td><span class="math inline">\(\sqrt{n}(\overline{X} - \mu_0)/S\)</span></td>
<td>拒绝 <span class="math inline">\(H_0\)</span> 如果， <span class="math inline">\(TS &lt; -t_{\alpha, n-1}\)</span></td>
<td><span class="math inline">\(P\{T_{n-1} \leq t\}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="sec-8_4" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-8_4"><span class="header-section-number">8.4</span> 检验两个正态分布的均值是否相等</h2>
<p>确定两种不同的方法是否会得出相同的结果是工程师在实践中经常遇到的一个场景。通常可以通过 <strong>假设检验</strong> 来对这种场景建模——检验两个正态分布的总体是否具有相同的均值。</p>
<section id="sec-8_4_1" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="sec-8_4_1"><span class="header-section-number">8.4.1</span> 方差已知的场景</h3>
<p>假设 <span class="math inline">\(X_1, \dots, X_n\)</span> 和 <span class="math inline">\(Y_1, \dots, Y_m\)</span> 是来自两个正态分布总体的、相互独立的样本，这两个总体的均值 <span class="math inline">\(\mu_x\)</span> 和 <span class="math inline">\(\mu_y\)</span> 均未知，但方差 <span class="math inline">\(\sigma_x^2\)</span> 和 <span class="math inline">\(\sigma_y^2\)</span> 已知。现在考虑检验以下假设：</p>
<p><span class="math inline">\(H_0: \mu_x = \mu_y \quad vs \quad  H_1: \mu_x \neq \mu_y\)</span></p>
<p>由于 <span class="math inline">\(\overline{X}\)</span> 是 <span class="math inline">\(\mu_x\)</span> 的估计值，<span class="math inline">\(\overline{Y}\)</span> 是 <span class="math inline">\(\mu_y\)</span> 的估计值，因此 <span class="math inline">\(\overline{X} - \overline{Y}\)</span> 可以用来估计 <span class="math inline">\(\mu_x - \mu_y\)</span>。因此，原假设可以写作：<span class="math inline">\(H_0: \mu_x - \mu_y = 0\)</span>，并且当 <span class="math inline">\(\overline{X} - \overline{Y}\)</span> 远大于 0 时，拒绝原假设 <span class="math inline">\(H_0\)</span> 是合理的。因此，对于某个合适的 <span class="math inline">\(c\)</span> 而言，检验如下所示：</p>
<p><span id="eq-8_4_1"><span class="math display">\[
\begin{align}
\text{拒绝} H_0 &amp;, \quad \text{如果} \left | \overline{X} - \overline{Y}\right | &gt; c \\
\text{接受} H_0 &amp;, \quad \text{如果} \left | \overline{X} - \overline{Y}\right | \le c
\end{align}
\tag{8.20}\]</span></span></p>
<p>为了确定令 <a href="#eq-8_4_1" class="quarto-xref">式&nbsp;<span>8.20</span></a> 可以满足显著性水平为 <span class="math inline">\(\alpha\)</span> 的 <span class="math inline">\(c\)</span> 的值，我们需要确定当 <span class="math inline">\(H_0\)</span> 为真时 <span class="math inline">\(\overline{X} - \overline{Y}\)</span> 的分布。如我们在 <a href="../chapter_7/7.html#sec-7_4" class="quarto-xref"><span>小节 7.4</span></a> 中所述：</p>
<p><span class="math display">\[
\overline{X} - \overline{Y} \sim \left(\mu_x - \mu_y, \frac{\sigma_x^2}{n} + \frac{\sigma_y^2}{m}\right)
\]</span></p>
<p>即（<a href="../chapter_7/7.html#eq-7_4_1" class="quarto-xref">式&nbsp;<span>7.5</span></a>）：</p>
<p><span id="eq-8_4_2"><span class="math display">\[
\frac{\overline{X} - \overline{Y} - (\mu_x - \mu_y)}{\sqrt{\frac{\sigma_x^2}{n} + \frac{\sigma_y^2}{m}}} \sim N(0, 1)
\tag{8.21}\]</span></span></p>
<p>因此，当 <span class="math inline">\(H_0\)</span> 为真时，<span class="math inline">\(\mu_x - \mu_y = 0\)</span>，所以 <span class="math inline">\(\frac{\overline{X} - \overline{Y}}{\sqrt{\frac{\sigma_x^2}{n} + \frac{\sigma_y^2}{m}}}\)</span> 服从标准正态分布。于是：</p>
<p><span id="eq-8_4_3"><span class="math display">\[
P_{H_0}\left\{-z_{\alpha/2} \leq \frac{\overline{X} - \overline{Y}}{\sqrt{\frac{\sigma_x^2}{n} + \frac{\sigma_y^2}{m}}} \leq z_{\alpha/2}\right\} = 1 - \alpha
\tag{8.22}\]</span></span></p>
<p>由此，根据 <a href="#eq-8_4_3" class="quarto-xref">式&nbsp;<span>8.22</span></a>，我们可以得出显著性水平为 <span class="math inline">\(\alpha\)</span> 时，<span class="math inline">\(H_0: \mu_x = \mu_y \quad vs \quad H_1: \mu_x \neq \mu_y\)</span> 的检验标准为：</p>
<p><span id="eq-8_4_1_001"><span class="math display">\[
\begin{align}
\text{接受} H_0, &amp;\quad \text{如果} \frac{\left|\overline{X} - \overline{Y}\right|}{\sqrt{\frac{\sigma_x^2}{n} + \frac{\sigma_y^2}{m}}} \leq z_{\alpha/2} \\
\text{拒绝} H_0, &amp;\quad \text{如果} \frac{\left|\overline{X} - \overline{Y}\right|}{\sqrt{\frac{\sigma_x^2}{n} + \frac{\sigma_y^2}{m}}} \geq z_{\alpha/2}
\end{align}
\tag{8.23}\]</span></span></p>
<div id="exr-8_4_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.10</strong></span> 如果现在新提出了两种轮胎生产方法，为了确定哪种生产方法更好，轮胎制造商使用第一种方法生产了 10 个轮胎，使用第二种方法生产了 8 个轮胎。使用第一种方法生产的轮胎在 A 地进行道路测试，使用第种方法生产的轮胎在 B 地测试。已知轮胎在这两个地点的寿命服从正态分布，其均值与轮胎质量有关，但方差主要由测试的地点决定。具体而言，A 地轮胎寿命的标准差为 4000 公里，B 地的标准差为 6000 公里。如果制造商希望检验这两种方法生产的轮胎的平均寿命是否无显著差异，那么在显著性水平为 5% 的情况下，我们可以从 <a href="#tbl-8_3" class="quarto-xref">表&nbsp;<span>8.3</span></a> 的数据中得出什么结论？</p>
<div id="tbl-8_3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-8_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;8.3: 不同地点轮胎的寿命（单位为100公里）
</figcaption>
<div aria-describedby="tbl-8_3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>在 A 地测试的轮胎寿命</th>
<th>在 B 地测试的轮胎寿命</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>61.1</td>
<td>62.2</td>
</tr>
<tr class="even">
<td>58.2</td>
<td>56.6</td>
</tr>
<tr class="odd">
<td>62.3</td>
<td>66.4</td>
</tr>
<tr class="even">
<td>64.0</td>
<td>56.2</td>
</tr>
<tr class="odd">
<td>59.7</td>
<td>57.4</td>
</tr>
<tr class="even">
<td>66.2</td>
<td>58.4</td>
</tr>
<tr class="odd">
<td>57.8</td>
<td>57.6</td>
</tr>
<tr class="even">
<td>61.4</td>
<td>65.4</td>
</tr>
<tr class="odd">
<td>62.2</td>
<td></td>
</tr>
<tr class="even">
<td>63.6</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
<div id="sol-8_4_a" class="proof solution">
<p><span class="proof-title"><em>解 8.8</em>. </span>根据 <a href="#tbl-8_3" class="quarto-xref">表&nbsp;<span>8.3</span></a> 的数据可以计算得出检验统计量的值为 0.066。对于如此小的统计量值，显然我们应该接受原假设，即两种方法生产的轮胎的寿命没有显著的差异。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>根据 <a href="#eq-8_4_1" class="quarto-xref">式&nbsp;<span>8.20</span></a>，对于单边假设 <span class="math inline">\(H_0: \mu_x = \mu_y\)</span>（或 <span class="math inline">\(H_0: \mu_x \leq \mu_y\)</span>） <span class="math inline">\(\quad vs \quad H_1: \mu_x &gt; \mu_y\)</span> 的检验为：</p>
<p><span id="eq-8_4_1_002"><span class="math display">\[
\begin{align}
\text{接受} H_0&amp;, \quad \text{如果} \overline{X} - \overline{Y} \leq z_\alpha \sqrt{\frac{\sigma_x^2}{n} + \frac{\sigma_y^2}{m}} \\
\text{拒绝} H_0&amp;, \quad \text{如果} \overline{X} - \overline{Y} \gt z_\alpha \sqrt{\frac{\sigma_x^2}{n} + \frac{\sigma_y^2}{m}}
\end{align}
\tag{8.24}\]</span></span></p>
</section>
<section id="sec-8_4_2" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="sec-8_4_2"><span class="header-section-number">8.4.2</span> 方差未知的场景</h3>
<p>继续假设 <span class="math inline">\(X_1, \dots, X_n\)</span> 和 <span class="math inline">\(Y_1, \dots, Y_m\)</span> 是来自两个正态分布总体的独立样本，这两个总体的参数分别为 <span class="math inline">\((\mu_x, \sigma_x^2)\)</span> 和 <span class="math inline">\((\mu_y, \sigma_y^2)\)</span>，现在我们假设这四个参数都是未知的。我们再次考虑以下的假设检验：</p>
<p><span class="math inline">\(H_0: \mu_x = \mu_y \quad vs \quad H_1: \mu_x \neq \mu_y\)</span></p>
<p>为了确定显著性水平为 <span class="math inline">\(\alpha\)</span> 的检验，我们需要做额外的假设：方差 <span class="math inline">\(\sigma_x^2\)</span> 和 <span class="math inline">\(\sigma_y^2\)</span> 是相等的，记为 <span class="math inline">\(\sigma^2\)</span>，即 <span class="math inline">\(\sigma^2 = \sigma_x^2 = \sigma_y^2\)</span>。</p>
<p>如 <a href="#eq-8_4_1" class="quarto-xref">式&nbsp;<span>8.20</span></a>，当 <span class="math inline">\(\left |\overline{X} - \overline{Y} \right|\)</span> 远大于零时，我们将拒绝 <span class="math inline">\(H_0\)</span>。为了确定 <span class="math inline">\(c\)</span>（<a href="#eq-8_4_1" class="quarto-xref">式&nbsp;<span>8.20</span></a>）的值，我们定义如下的样本方差：</p>
<p><span class="math inline">\(\begin{align} S_x^2 &amp;= \frac{1}{n-1} \sum_{i=1}^{n} (X_i - \overline{X})^2 \\ S_y^2 &amp;= \frac{1}{m-1} \sum_{i=1}^{m} (Y_i - \overline{Y})^2 \end{align}\)</span></p>
<p>于是如 <a href="../chapter_7/7.html#sec-7_4_1" class="quarto-xref"><span>小节 7.4.1</span></a> 所述：</p>
<p><span class="math inline">\(\frac{\overline{X} - \overline{Y} - (\mu_x - \mu_y)}{\sqrt{S_p^2 \left( \frac{1}{n} + \frac{1}{m} \right)}} \sim t_{n+m-2}\)</span></p>
<p>其中 <span class="math inline">\(S_p^2\)</span> 是两个样本的共同的方差的池化估计量（<em>pooled estimator</em>）：</p>
<p><span class="math inline">\(S_p^2 = \frac{(n-1)S_x^2 + (m-1)S_y^2}{n + m - 2}\)</span></p>
<p>因此，当 <span class="math inline">\(H_0\)</span> 为真时，由于 <span class="math inline">\(\mu_x - \mu_y = 0\)</span>，所以统计量 <span class="math inline">\(T\)</span>：</p>
<p><span class="math inline">\(T \equiv \frac{\overline{X} - \overline{Y}}{\sqrt{S_p^2 \left( \frac{1}{n} + \frac{1}{m} \right)}} \sim t_{n+m-2}\)</span></p>
<p>服从自由度为 <span class="math inline">\(n + m - 2\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span>，于是我们可以对 <span class="math inline">\(\mu_x = \mu_y\)</span> 的假设做如下的检验：</p>
<p><span id="eq-8_4_2_001"><span class="math display">\[
\begin{align} \text{接受} H_0&amp;, \quad \text{如果} |T| \leq t_{\alpha/2, n+m-2} \\ \text{拒绝} H_0&amp;, \quad \text{如果} |T| &gt; t_{\alpha/2, n+m-2} \end{align}
\tag{8.25}\]</span></span></p>
<p>其中，<span class="math inline">\(t_{\alpha/2, n+m-2}\)</span> 是自由度为 <span class="math inline">\(n + m - 2\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span> 随机变量的 <span class="math inline">\(100\ \alpha/2\)</span> 百分位数（如 <a href="#fig-8_4" class="quarto-xref">图&nbsp;<span>8.4</span></a> 所示）。</p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>dfreedom <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">10</span>, <span class="fl">0.01</span>) </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">dt</span>(x, dfreedom)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x=</span>x, <span class="at">y=</span>y)) <span class="sc">+</span> </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="sc">-</span><span class="dv">3</span>, <span class="at">y=</span><span class="fu">dt</span>(<span class="sc">-</span><span class="dv">3</span>, dfreedom), <span class="at">xend=</span><span class="sc">-</span><span class="dv">3</span>, <span class="at">yend=</span><span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">x=</span><span class="dv">3</span>, <span class="at">y=</span><span class="fu">dt</span>(<span class="dv">3</span>, dfreedom), <span class="at">xend=</span><span class="dv">3</span>, <span class="at">yend=</span><span class="dv">0</span>) <span class="sc">+</span> </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> <span class="fu">subset</span>(df, x <span class="sc">&gt;=</span> <span class="dv">3</span>), <span class="fu">aes</span>(<span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> y), <span class="at">fill =</span> <span class="st">"gray"</span>) <span class="sc">+</span> </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> <span class="fu">subset</span>(df, x <span class="sc">&lt;=</span> <span class="sc">-</span><span class="dv">3</span>), <span class="fu">aes</span>(<span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> y), <span class="at">fill =</span> <span class="st">"gray"</span>) <span class="sc">+</span> </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">3.2</span>, <span class="at">y =</span> <span class="sc">-</span><span class="fl">0.01</span>, <span class="at">label =</span> <span class="fu">TeX</span>(<span class="st">"$t_{</span><span class="sc">\\</span><span class="st">alpha, k}$"</span>), <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="sc">-</span><span class="fl">2.7</span>, <span class="at">y =</span> <span class="sc">-</span><span class="fl">0.01</span>, <span class="at">label =</span> <span class="fu">TeX</span>(<span class="st">"$-t_{</span><span class="sc">\\</span><span class="st">alpha, k}$"</span>), <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">6</span>, <span class="at">y =</span> <span class="fl">0.01</span>, <span class="at">label =</span> <span class="fu">TeX</span>(<span class="st">"Area: $</span><span class="sc">\\</span><span class="st">alpha$"</span>), <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="sc">-</span><span class="dv">5</span>, <span class="at">y =</span> <span class="fl">0.01</span>, <span class="at">label =</span> <span class="fu">TeX</span>(<span class="st">"Area: $</span><span class="sc">\\</span><span class="st">alpha$"</span>), <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_blank</span>(),<span class="at">axis.title =</span> <span class="fu">element_blank</span>())</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-8_4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-8_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="8_files/figure-html/fig-8_4-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-8_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;8.4: 自由度为 <span class="math inline">\(k\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span> 随机变量的概率密度函数
</figcaption>
</figure>
</div>
</div>
</div>
<p>我们还可以通过计算 <span class="math inline">\(p-\text{value}\)</span> 来进行检验。如果 <span class="math inline">\(T\)</span> 的观测值为 <span class="math inline">\(v\)</span>，那么对 <span class="math inline">\(H_0 \ vs \ H_1\)</span> 的检验的 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p-\text{value} = P\{|T_{n+m-2}| \geq |v|\} = 2P\{T_{n+m-2} \geq |v|\}\)</span></p>
<p>其中，<span class="math inline">\(T_{n+m-2}\)</span> 是自由度为 <span class="math inline">\(n + m - 2\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span> 随机变量。</p>
<p>如果我们需要计算单边检验：<span class="math inline">\(H_0: \mu_x \leq \mu_y \quad vs \quad H_1: \mu_x &gt; \mu_y\)</span>，那么在 <span class="math inline">\(T\)</span> 较大时，我们会拒绝 <span class="math inline">\(H_0\)</span>。因此，在显著性水平为 <span class="math inline">\(\alpha\)</span> 时的单边检验为：</p>
<p><span id="eq-8_4_2_002"><span class="math display">\[
\begin{align} \text{拒绝} H_0&amp;, \quad \text{如果} T \geq t_{\alpha, n+m-2} \\ \text{接受} H_0&amp;, \quad \text{否则} \end{align}
\tag{8.26}\]</span></span></p>
<p>如果检验统计量 <span class="math inline">\(T\)</span> 的值为 <span class="math inline">\(v\)</span>，那么 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p-\text{value} = P\{T_{n+m-2} \geq v\}\)</span></p>
<p>可以用 R 来实现两个样本的 <span class="math inline">\(t-\text{检验}\)</span>。假设 <span class="math inline">\(x_1, \dots, x_n\)</span> 和 <span class="math inline">\(y_1, \dots, y_m\)</span> 是来自两个不同的正态分布总体的独立样本，且这两个总体具有相同的方差。令 <span class="math inline">\(\mu_x\)</span> 表示第一个总体的均值，<span class="math inline">\(\mu_y\)</span> 表示第二个总体的均值。为了检验假设 <span class="math inline">\(H_0: \mu_x = \mu_y \quad vs \quad H_1: \mu_x \neq \mu_y\)</span>，可以使用如下的代码：</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(x1,...,xn)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(y1,...,ym)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>如上的代码会输出 <span class="math inline">\(p-\text{value}\)</span> 和 <span class="math inline">\(\mu_x - \mu_y\)</span> 的 95% 置信区间。例如：如果 <span class="math inline">\(x = \{3, 5, 7, 9\}\)</span>，<span class="math inline">\(y = \{6, 8, 12, 15\}\)</span>，则 <span class="math inline">\(H_0: \mu_x = \mu_y \quad vs \quad H_1: \mu_x \neq \mu_y\)</span> 的假设检验为：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">15</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  x and y
t = -1.7756, df = 6, p-value = 0.1261
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -10.106849   1.606849
sample estimates:
mean of x mean of y 
     6.00     10.25 </code></pre>
</div>
</div>
<p>我们可以通过 <code>t.test()</code> 的 <code>alternative</code> 参数来控制我们需要的检验类型（双边检验、单边检验）。如果我们想计算 <span class="math inline">\(H_0: \mu_x \le \mu_y \quad vs \quad H_1: \mu_x \gt \mu_y\)</span> 的假设检验，我们可以使用如下的代码：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">15</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  x and y
t = -1.7756, df = 6, p-value = 0.9369
alternative hypothesis: true difference in means is greater than 0
95 percent confidence interval:
 -8.901134       Inf
sample estimates:
mean of x mean of y 
     6.00     10.25 </code></pre>
</div>
</div>
<p>同理，如果我们想计算 <span class="math inline">\(H_0: \mu_x \ge \mu_y \quad vs \quad H_1: \mu_x \lt \mu_y\)</span> 的假设检验，我们可以使用如下的代码：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">9</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">15</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">var.equal =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  x and y
t = -1.7756, df = 6, p-value = 0.06307
alternative hypothesis: true difference in means is less than 0
95 percent confidence interval:
      -Inf 0.4011337
sample estimates:
mean of x mean of y 
     6.00     10.25 </code></pre>
</div>
</div>
<div id="exr-8_4_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.11</strong></span> 在一个感冒研究所，22 名志愿者在暴露于各种感冒病毒后感染了感冒。从中随机选取 10 名志愿者服用含有 1 克维生素 C 的药片，并且每天复用四次。另外的 12 名志愿者作为对照组服用看起来、尝起来与维生素 C 药片完全相同的安慰剂药片。对于每一个志愿者而言，实验会持续到医生（不知道志愿者服用的是维生素 C 还是安慰剂）认为志愿者已经康复为止，并记录志愿者感冒的持续时间。实验结束时，得到了如下数据。</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>复用维生素 C 的患者</th>
<th>复用安慰剂的患者</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5.5</td>
<td>6.5</td>
</tr>
<tr class="even">
<td>6.0</td>
<td>6.0</td>
</tr>
<tr class="odd">
<td>7.0</td>
<td>8.5</td>
</tr>
<tr class="even">
<td>6.0</td>
<td>7.0</td>
</tr>
<tr class="odd">
<td>7.5</td>
<td>6.5</td>
</tr>
<tr class="even">
<td>6.0</td>
<td>8.0</td>
</tr>
<tr class="odd">
<td>7.5</td>
<td>7.5</td>
</tr>
<tr class="even">
<td>5.5</td>
<td>6.5</td>
</tr>
<tr class="odd">
<td>7.0</td>
<td>7.5</td>
</tr>
<tr class="even">
<td>6.5</td>
<td>6.0</td>
</tr>
<tr class="odd">
<td></td>
<td>8.5</td>
</tr>
<tr class="even">
<td></td>
<td>7.0</td>
</tr>
</tbody>
</table>
<p>这些数据是否证明每天服用 4 克维生素 C 可以缩短感冒持续时间？在什么显著性水平下？</p>
</div>
<div id="sol-8_4_b" class="proof solution">
<p><span class="proof-title"><em>解 8.9</em>. </span>为了证明上述假设，我们需要在以下假设检验中拒绝原假设：</p>
<p><span class="math inline">\(H_0 : \mu_C \geq \mu_P \quad vs \quad H_1 : \mu_C &lt; \mu_P\)</span></p>
<p>其中，<span class="math inline">\(\mu_C\)</span> 是服用维生素 C 药片时感冒的平均持续时间，<span class="math inline">\(\mu_P\)</span> 是服用安慰剂时的平均持续时间。假设维生素 C 组和安慰剂组的方差相同，我们使用 R 进行上述检验。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">5.5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="fl">7.5</span>, <span class="dv">6</span>, <span class="fl">7.5</span>, <span class="fl">5.5</span>, <span class="dv">7</span>, <span class="fl">6.5</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">6.5</span>, <span class="dv">6</span>, <span class="fl">8.5</span>, <span class="dv">7</span>, <span class="fl">6.5</span>, <span class="dv">8</span>, <span class="fl">7.5</span>, <span class="fl">6.5</span>, <span class="fl">7.5</span>, <span class="dv">6</span>, <span class="fl">8.5</span>, <span class="dv">7</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x, y, <span class="at">alternative =</span> <span class="st">"less"</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  x and y
t = -1.8987, df = 20, p-value = 0.03606
alternative hypothesis: true difference in means is less than 0
95 percent confidence interval:
        -Inf -0.06185013
sample estimates:
mean of x mean of y 
    6.450     7.125 </code></pre>
</div>
</div>
<p>由于 <span class="math inline">\(p-\text{value}\)</span> 为 0.036，因此可以在 5% 的显著性水平下确定维生素 C 可以缩短感冒的持续时间。此外，值得注意的是，除了输出 <span class="math inline">\(p-\text{value}\)</span> 外，R 还提供了 <span class="math inline">\(\mu_x - \mu_y\)</span> 的单边 95% 置信区间。<span class="math inline">\(\blacksquare\)</span></p>
</div>
</section>
<section id="sec-8_4_3" class="level3" data-number="8.4.3">
<h3 data-number="8.4.3" class="anchored" data-anchor-id="sec-8_4_3"><span class="header-section-number">8.4.3</span> 方差未知且不同的场景</h3>
<p>现在，我们假设总体的方差 <span class="math inline">\(\sigma_x^2\)</span> 和 <span class="math inline">\(\sigma_y^2\)</span> 不仅未知，而且不能认为相等。在这种情况下，由于 <span class="math inline">\(S_x^2\)</span> 和 <span class="math inline">\(S_y^2\)</span> 分别是 <span class="math inline">\(\sigma_x^2\)</span> 和 <span class="math inline">\(\sigma_y^2\)</span> 的估计量，因此基于以下检验统计量进行 <span class="math inline">\(H_0: \mu_x = \mu_y \quad vs \quad H_1: \mu_x \ne \mu_y\)</span> 的假设检验似乎是合理的：</p>
<p><span id="eq-8_4_4"><span class="math display">\[
\frac{\overline{X} - \overline{Y}}{\sqrt{\frac{S_x^2}{n} + \frac{S_y^2}{m}}}
\tag{8.27}\]</span></span></p>
<p>然而，上述统计量的分布非常复杂，即使在 <span class="math inline">\(H_0\)</span> 为真时，<a href="#eq-8_4_4" class="quarto-xref">式&nbsp;<span>8.27</span></a> 的分布也依赖于未知参数，因此无法被广泛使用。唯一可以利用 <a href="#eq-8_4_4" class="quarto-xref">式&nbsp;<span>8.27</span></a> 这个统计量的场景是：<span class="math inline">\(n\)</span> 和 <span class="math inline">\(m\)</span> 都非常大。当 <span class="math inline">\(n\)</span> 和 <span class="math inline">\(m\)</span> 都非常大时，可以证明：在 <span class="math inline">\(H_0\)</span> 为真时，该统计量近似服从标准正态分布。因此，当 <span class="math inline">\(n\)</span> 和 <span class="math inline">\(m\)</span> 都很大时，<span class="math inline">\(H_0: \mu_x = \mu_y \quad vs \quad H_1: \mu_x \ne \mu_y\)</span> 在显著性水平 <span class="math inline">\(\alpha\)</span> 下的 <strong>近似</strong> 检验为：</p>
<p><span id="eq-8_4_3_001"><span class="math display">\[
\begin{align} \text{接受} H_0&amp;, \quad \text{如果} -z_{\alpha/2} \leq \frac{\overline{X} - \overline{Y}}{\sqrt{\frac{S_x^2}{n} + \frac{S_y^2}{m}}} \leq z_{\alpha/2} \\ \text{拒绝} H_0&amp;, \quad \text{否则}\end{align}
\tag{8.28}\]</span></span></p>
<p>确定两个具有未知且不一定相等方差的正态总体均值在 <strong>精确</strong> 显著性水平 <span class="math inline">\(\alpha\)</span> 下的检验的问题，我们称之为 Behrens-Fisher 问题。对于 Behrens-Fisher 问题而言，目前还没有完全令人满意的解决方案。</p>
<p><a href="#tbl-8_4" class="quarto-xref">表&nbsp;<span>8.4</span></a> 对本节的双边检验进行了总结。</p>
<div id="tbl-8_4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-8_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;8.4: <span class="math inline">\(X_1, \dots, X_n\)</span> 是来自 <span class="math inline">\((\mu_1, \sigma_1^2)\)</span> 总体的样本；<span class="math inline">\(Y_1, \dots, Y_m\)</span> 是来自 <span class="math inline">\((\mu_2, \sigma_2^2)\)</span> 总体的样本。两个总体的样本是独立的。<span class="math inline">\(H_0: \mu_1 = \mu_2 \quad vs \quad H_0: \mu_1 \neq \mu_2\)</span> 的假设检验
</figcaption>
<div aria-describedby="tbl-8_4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th><strong>假设</strong></th>
<th>假设检验统计量 <span class="math inline">\(TS\)</span></th>
<th>在显著性水平 <span class="math inline">\(\alpha\)</span> 下的检验</th>
<th>当 <span class="math inline">\(TS = t\)</span> 时的 <span class="math inline">\(p-\text{value}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\sigma_1, \sigma_2\)</span> 已知</td>
<td><span class="math inline">\(\frac{\overline{X} - \overline{Y}}{\sqrt{\sigma_1^2/n + \sigma_2^2/m}}\)</span></td>
<td>拒绝 <span class="math inline">\(H_0\)</span>，如果 <span class="math inline">\(|TS| &gt; z_{\alpha/2}\)</span></td>
<td><span class="math inline">\(2P\{Z \geq |t|\}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma_1 = \sigma_2\)</span></td>
<td><span class="math inline">\(\frac{\overline{X} - \overline{Y}}{\sqrt{\frac{(n-1)S_1^2 + (m-1)S_2^2}{n+m-2}}\sqrt{1/n + 1/m}}\)</span></td>
<td>拒绝 <span class="math inline">\(H_0\)</span>，如果 <span class="math inline">\(|TS| &gt; t_{\alpha/2, n+m-2}\)</span></td>
<td><span class="math inline">\(2P\{T_{n+m-2} \geq |t|\}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(n, m\)</span> 较大</td>
<td><span class="math inline">\(\frac{\overline{X} - \overline{Y}}{\sqrt{S_1^2/n + S_2^2/m}}\)</span></td>
<td>拒绝 <span class="math inline">\(H_0\)</span>，如果 <span class="math inline">\(|TS| &gt; z_{\alpha/2}\)</span></td>
<td><span class="math inline">\(2P\{Z \geq |t|\}\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-8_4_4" class="level3" data-number="8.4.4">
<h3 data-number="8.4.4" class="anchored" data-anchor-id="sec-8_4_4"><span class="header-section-number">8.4.4</span> 成对样本的 <span class="math inline">\(t-\text{检验}\)</span></h3>
<p>假设我们对 <strong><em>安装某种防污染装置是否会影响汽车油耗</em></strong> 这个问题感兴趣。为了检验 <strong><em>安装某种防污染装置是否会影响汽车油耗</em></strong>，我们：</p>
<ol type="1">
<li>首先，招募 <span class="math inline">\(n\)</span> 辆没有安装该装置的汽车</li>
<li>然后，分别记录每辆车在安装装置前后的每加仑行驶里程</li>
</ol>
<p>最后，我们可以通过比较安装装置前后的油耗差异来检验：防污染控制装置是否对油耗有影响？</p>
<p>假设有 <span class="math inline">\(n\)</span> 对数据 <span class="math inline">\((X_i, Y_i)\)</span>，其中 <span class="math inline">\(X_i\)</span> 是第 <span class="math inline">\(i\)</span> 辆车在安装装置前的油耗，<span class="math inline">\(Y_i\)</span> 是安装装置后的油耗。因为这 <span class="math inline">\(n\)</span> 辆车中的每辆车之间存在天然的不同，因此我们不能将 <span class="math inline">\(X_1, ..., X_n\)</span> 和 <span class="math inline">\(Y_1, ..., Y_m\)</span> 看作相互独立的样本。例如，如果我们知道 <span class="math inline">\(X_1\)</span> 很大（比如，每加仑 40 英里），我们肯定会认为 <span class="math inline">\(Y_1\)</span> 也可能很大。因此，我们不能使用本节之前所介绍的方法。</p>
<p>为了检验安装装置前后的油耗是否存在差异，我们定义差值 <span class="math inline">\(W_i = X_i - Y_i, \ i = 1,...,n\)</span>。如果防污染控制装置对油耗没有影响，<span class="math inline">\(W_i\)</span> 的均值将为 0。因此，我们可以对如下的假设进行假设检验：</p>
<p><span class="math inline">\(H_0: \mu_w = 0 \quad vs \quad H_1: \mu_w \neq 0\)</span></p>
<p>其中，我们假定 <span class="math inline">\(W_1, \dots, W_n\)</span> 为来自一个具有未知均值 <span class="math inline">\(\mu_w\)</span> 和未知方差 <span class="math inline">\(\sigma_w^2\)</span> 的正态总体。使用 <a href="#sec-8_3_2" class="quarto-xref"><span>小节 8.3.2</span></a> 中的 <span class="math inline">\(t-\text{检验}\)</span> 进行假设检验：</p>
<p><span id="eq-8_4_4_001"><span class="math display">\[
\begin{align}
\text{接受} H_0&amp;, \quad \text{如果} -t_{\alpha/2, n-1} &lt; \sqrt{n} \frac{\overline{W}}{S_w} &lt; t_{\alpha/2, n-1} \\ \text{拒绝} H_0&amp;, \quad \text{否则}
\end{align}
\tag{8.29}\]</span></span></p>
<div id="exr-8_4_c" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.12</strong></span> 计算机芯片行业最近实施了一项工业安全计划。下表显示了 10 家芯片工厂在实施该计划前后，由于事故导致的平均每周的 <strong>工时损失</strong>（<em>loss in labor-hours</em>）数据（最近一个月的平均数据）：</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>工厂</th>
<th>实施前</th>
<th>实施后</th>
<th><span class="math inline">\(A - B\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>30.5</td>
<td>23</td>
<td>-7.5</td>
</tr>
<tr class="even">
<td>2</td>
<td>18.5</td>
<td>21</td>
<td>2.5</td>
</tr>
<tr class="odd">
<td>3</td>
<td>24.5</td>
<td>22</td>
<td>-2.5</td>
</tr>
<tr class="even">
<td>4</td>
<td>32</td>
<td>28.5</td>
<td>-3.5</td>
</tr>
<tr class="odd">
<td>5</td>
<td>16</td>
<td>14.5</td>
<td>-1.5</td>
</tr>
<tr class="even">
<td>6</td>
<td>15</td>
<td>15.5</td>
<td>0.5</td>
</tr>
<tr class="odd">
<td>7</td>
<td>23.5</td>
<td>24.5</td>
<td>1</td>
</tr>
<tr class="even">
<td>8</td>
<td>25.5</td>
<td>21</td>
<td>-4.5</td>
</tr>
<tr class="odd">
<td>9</td>
<td>28</td>
<td>23.5</td>
<td>-4.5</td>
</tr>
<tr class="even">
<td>10</td>
<td>18</td>
<td>16.5</td>
<td>-1.5</td>
</tr>
</tbody>
</table>
<p>在 5% 的显著性水平下，判断该安全计划是否有效？</p>
</div>
<div id="sol-8_4_c" class="proof solution">
<p><span class="proof-title"><em>解 8.10</em>. </span>我们将检验以下假设：</p>
<p><span class="math inline">\(H_0: \mu_A - \mu_B \geq 0 \quad vs \quad H_1: \mu_A - \mu_B &lt; 0\)</span></p>
<p>如上的假设可以让我们判断原假设——安全计划没有产生有益效果——是否合理。为此，我们使用 R 首先得到检验统计量 <span class="math inline">\(v\)</span> 的值，然后计算 <span class="math inline">\(p-\text{value}\)</span>，即自由度为 9 的 <span class="math inline">\(t-\text{分布}\)</span> 随机变量小于 <span class="math inline">\(v\)</span> 的概率。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">7.5</span>, <span class="fl">2.5</span>, <span class="sc">-</span><span class="fl">2.5</span>, <span class="sc">-</span><span class="fl">3.5</span>, <span class="sc">-</span><span class="fl">1.5</span>, .<span class="dv">5</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="fl">4.5</span>, <span class="sc">-</span><span class="fl">4.5</span>, <span class="sc">-</span><span class="fl">1.5</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">10</span> <span class="sc">/</span> <span class="fu">var</span>(d)) <span class="sc">*</span> <span class="fu">mean</span>(d)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>v</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.265949</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(v, <span class="dv">9</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02484552</code></pre>
</div>
</div>
<p><span class="math inline">\(p-\text{value} = P(T_9 \leq -2.265949) = 0.02484552\)</span></p>
<p>我们使用 R 中的 <code>pt(v, n)</code> 来获得自由度为 <span class="math inline">\(n\)</span> 的 <span class="math inline">\(t-\text{分布}\)</span> 随机变量小于或等于 <span class="math inline">\(v\)</span> 的概率。</p>
<p>由于 <span class="math inline">\(p-\text{value}\)</span> 小于 0.05，因此我们拒绝安全计划没有效果的假设，并且可以得出结论：这项安全计划的有效性已经得到证实（至少对于任何显著性水平大于 0.025 的情况下）。</p>
<p>我们还可以直接使用 R 中的 <code>t.test()</code> 来进行同样的检验：</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">7.5</span>, <span class="fl">2.5</span>, <span class="sc">-</span><span class="fl">2.5</span>, <span class="sc">-</span><span class="fl">3.5</span>, <span class="sc">-</span><span class="fl">1.5</span>, .<span class="dv">5</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="fl">4.5</span>, <span class="sc">-</span><span class="fl">4.5</span>, <span class="sc">-</span><span class="fl">1.5</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(d, <span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  d
t = -2.2659, df = 9, p-value = 0.02485
alternative hypothesis: true mean is less than 0
95 percent confidence interval:
      -Inf -0.410688
sample estimates:
mean of x 
    -2.15 </code></pre>
</div>
</div>
<p><code>t.test()</code> 不仅可以给出 <span class="math inline">\(p-\text{value}\)</span>，还会同时给出 <span class="math inline">\(\mu_A - \mu_B\)</span> 的 95% 置信区间。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="注意">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注意
</div>
</div>
<div class="callout-body-container callout-body">
<p>即使样本不是独立的且总体方差不相等，也可以使用成对样本的 <span class="math inline">\(t-\text{检验}\)</span>。</p>
</div>
</div>
</section>
</section>
<section id="sec-8_5" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="sec-8_5"><span class="header-section-number">8.5</span> 关于正态总体方差的假设检验</h2>
<p>假设 <span class="math inline">\(X_1, \dots, X_n\)</span> 是来自正态分布总体的样本，该总体具有未知均值 <span class="math inline">\(\mu\)</span> 和未知方差 <span class="math inline">\(\sigma^2\)</span>，并且我们希望检验以下的假设：</p>
<p><span class="math inline">\(H_0 : \sigma^2 = \sigma_0^2 \quad vs \quad H_1 : \sigma^2 \neq \sigma_0^2\)</span></p>
<p>其中 <span class="math inline">\(\sigma_0^2\)</span> 是一个特定的值。</p>
<p>当 <span class="math inline">\(H_0\)</span> 为真时，如 <a href="../chapter_6/6.html#thm-6_5_1" class="quarto-xref">定理&nbsp;<span>6.2</span></a> 所述，<span class="math inline">\((n-1)S^2/\sigma_0^2\)</span> 服从自由度为 <span class="math inline">\(n-1\)</span> 的卡方分布，因此：</p>
<p><span class="math inline">\(\frac{(n-1)S^2}{\sigma_0^2} \sim \chi^2_{n-1}\)</span></p>
<p>由于 <span class="math inline">\(P\{\chi^2_{n-1} &lt; \chi^2_{\alpha/2, n-1}\} = 1 - \alpha/2\)</span> 且 <span class="math inline">\(P\{\chi^2_{n-1} &lt; \chi^2_{1-\alpha/2, n-1}\} = \alpha/2\)</span>，由此得出</p>
<p><span class="math inline">\(P_{H_0} \left\{ \chi^2_{1-\alpha/2, n-1} \leq \frac{(n-1)S^2}{\sigma_0^2} \leq \chi^2_{\alpha/2, n-1} \right\} = 1 - \alpha\)</span></p>
<p>因此，在显著性水平为 <span class="math inline">\(\alpha\)</span> 下的检验为：</p>
<p><span class="math display">\[
\begin{align}
\text{接受} H_0&amp;, \quad \text{如果} \chi^2_{1-\alpha/2, n-1} \leq \frac{(n-1)S^2}{\sigma_0^2} \leq \chi^2_{\alpha/2, n-1} \\
\text{拒绝} H_0&amp;, \quad \text{否则}
\end{align}
\]</span></p>
<p>如上的检验可以通过：</p>
<ol type="1">
<li>首先，计算检验统计量 <span class="math inline">\((n-1)S^2/\sigma_0^2\)</span> 的值——我们称之为 <span class="math inline">\(c\)</span>——来实现</li>
<li>然后，计算自由度为 <span class="math inline">\(n-1\)</span> 的卡方分布随机变量大于 <span class="math inline">\(c\)</span> 或者小于 <span class="math inline">\(c\)</span> 的概率</li>
<li>如果如上的概率中的任一个概率小于 <span class="math inline">\(\alpha/2\)</span>，则拒绝原假设。换句话说，该检验的 <span class="math inline">\(p-\text{value}\)</span> 为：</li>
</ol>
<p><span class="math inline">\(p-\text{value} = 2 \min \left( P\{\chi^2_{n-1} &lt; c\}, 1 - P\{\chi^2_{n-1} &lt; c\} \right)\)</span></p>
<p>同样，也可以使用类似的方法得到单边检验的 <span class="math inline">\(p-\text{value}\)</span>。我们可以使用 R 命令 <code>pchisq(c, n-1)</code> 得到 <span class="math inline">\(P\{\chi^2_{n-1} &lt; c\}\)</span> 的值。</p>
<div id="exr-8_5_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.13</strong></span> 最近安装了一台自动控制磁带长度的机器。如果磁带长度的标准差 <span class="math inline">\(\sigma\)</span> 小于 0.15 厘米，则认为该机器是有效的。如果 20 个磁带样本的方差 <span class="math inline">\(S^2 = 0.025 \ \text{cm}^2\)</span>，我们能否得出该机器无效的结论？</p>
</div>
<div id="sol-8_5_a" class="proof solution">
<p><span class="proof-title"><em>解 8.11</em>. </span>我们将检验该机器有效的假设，因为拒绝这个假设将使我们得出该机器无效的结论。因此，我们检验以下假设：</p>
<p><span class="math inline">\(H_0: \sigma^2 \leq 0.0225 \quad vs \quad H_1: \sigma^2 &gt; 0.0225\)</span></p>
<p>因此，当 <span class="math inline">\(S^2\)</span> 较大时，我们会拒绝 <span class="math inline">\(H_0\)</span>。测试数据的 <span class="math inline">\(p-\text{value}\)</span> 是自由度为 19 的卡方随机变量超过 <span class="math inline">\(19 \times 0.025 / 0.0225 = 21.111\)</span> 的概率，即：</p>
<p><span class="math inline">\(p-\text{value} = P\{\chi^2_{19} &gt; 21.111\} = 1 - \text{pchisq}(21.111, 19) = 0.3307001\)</span></p>
<p>因此，我们必须得出结论：观察到的 <span class="math inline">\(S^2 = 0.025\)</span> 的值不足以排除 <span class="math inline">\(\sigma^2 \leq 0.0225\)</span> 的可能性，因此接受原假设。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<section id="sec-8_5_1" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="sec-8_5_1"><span class="header-section-number">8.5.1</span> 检验两个正态分布的方差是否相等</h3>
<p>设 <span class="math inline">\(X_1, \dots, X_n\)</span> 和 <span class="math inline">\(Y_1, \dots, Y_m\)</span> 表示来自两个正态分布总体的独立样本，这两个总体的参数分别为 <span class="math inline">\((\mu_x, \sigma_x^2)\)</span> 和 <span class="math inline">\((\mu_y, \sigma_y^2)\)</span>，我们考虑检验如下的假设：</p>
<p><span class="math inline">\(H_0: \sigma_x^2 = \sigma_y^2 \quad vs \quad H_1: \sigma_x^2 \neq \sigma_y^2\)</span></p>
<p>如果我们令：</p>
<p><span class="math inline">\(\begin{align} S_x^2 &amp;= \frac{1}{n-1} \sum_{i=1}^{n} (X_i - \overline{X})^2 \\ S_y^2 &amp;= \frac{1}{m-1} \sum_{i=1}^{m} (Y_i - \overline{Y})^2 \end{align}\)</span></p>
<p>表示样本方差，那么如 <a href="../chapter_6/6.html#thm-6_5_1" class="quarto-xref">定理&nbsp;<span>6.2</span></a> 所示，<span class="math inline">\((n-1)S_x^2/\sigma_x^2\)</span> 和 <span class="math inline">\((m-1)S_y^2/\sigma_y^2\)</span> 服从自由度分别为 <span class="math inline">\(n-1\)</span> 和 <span class="math inline">\(m-1\)</span> 的卡方分布，因此 <span class="math inline">\((S_x^2/\sigma_x^2) / (S_y^2/\sigma_y^2)\)</span> 服从自由度为 <span class="math inline">\(n-1\)</span> 和 <span class="math inline">\(m-1\)</span> 的 <span class="math inline">\(F-\text{分布}\)</span>。所以，当 <span class="math inline">\(H_0\)</span> 为真时：</p>
<p><span class="math inline">\(S_x^2/S_y^2 \sim F_{n-1, m-1}\)</span></p>
<p>所以：</p>
<p><span class="math inline">\(P_{H_0}\{F_{1 - \alpha / 2, n-1, m-1} \leq S_x^2/S_y^2 \leq F_{\alpha / 2, n-1, m-1}\} = 1 - \alpha\)</span></p>
<p>因此，在显著性水平 <span class="math inline">\(\alpha\)</span> 下，<span class="math inline">\(H_0 \ vs \ H_1\)</span> 的检验为：</p>
<p><span class="math display">\[
\begin{align}
\text{接受} H_0&amp;, \quad \text{如果} F_{1-\alpha/2, n-1, m-1} &lt; \frac{S_x^2}{S_y^2} &lt; F_{\alpha/2, n-1, m-1}  \\
\text{拒绝} H_0&amp;, \quad \text{否则}
\end{align}
\]</span></p>
<p>上述检验可以通过：</p>
<ol type="1">
<li>首先，确定检验统计量 <span class="math inline">\(\frac{S_x^2}{S_y^2}\)</span> 的值——记为 <span class="math inline">\(v\)</span></li>
<li>然后，计算 <span class="math inline">\(P\{F_{n-1, m-1} \leq v\}\)</span>，其中 <span class="math inline">\(F_{n-1, m-1}\)</span> 是自由度为 <span class="math inline">\(n-1\)</span> 和 <span class="math inline">\(m-1\)</span> 的 <span class="math inline">\(F-\text{分布}\)</span> 随机变量</li>
<li>如果此概率小于 <span class="math inline">\(\alpha/2\)</span>（当 <span class="math inline">\(S_x^2\)</span> 显著小于 <span class="math inline">\(S_y^2\)</span> 时）或大于 <span class="math inline">\(1-\alpha/2\)</span>（当 <span class="math inline">\(S_x^2\)</span> 显著大于 <span class="math inline">\(S_y^2\)</span> 时），则拒绝原假设。</li>
</ol>
<p>换句话说，检验数据的 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p-\text{value} = 2 \min \left( P\{F_{n-1, m-1} &lt; v\}, 1 - P\{F_{n-1, m-1} &lt; v\} \right)\)</span></p>
<p>当 <span class="math inline">\(p-\text{value}\)</span> 小于等于 显著性水平 <span class="math inline">\(\alpha\)</span> 时，则拒绝原假设。</p>
<div id="exr-8_5_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.14</strong></span> 有两种不同的催化剂可用于加快某化学反应的过程。为了检验：无论使用哪种催化剂化学反应产物的方差都是相同的，我们使用第一种催化剂生产了 10 批产品，使用第二种催化剂生产了 12 批产品。如果结果数据为： <span class="math inline">\(S_1^2 = 0.14\)</span>、<span class="math inline">\(S_2^2 = 0.28\)</span>，我们能否在 5% 的显著性水平下拒绝方差相等的假设？</p>
</div>
<div id="sol-8_5_b" class="proof solution">
<p><span class="proof-title"><em>解 8.12</em>. </span>使用 R 命令 <code>pf(v, n, m)</code> 来获得具有参数 <span class="math inline">\(n\)</span> 和 <span class="math inline">\(m\)</span> 的 <span class="math inline">\(F-\text{分布}\)</span> 随机变量小于或等于 <span class="math inline">\(v\)</span> 的概率，我们得到：</p>
<p><span class="math inline">\(P(F_{9,11} \leq 0.5) = pf(0.5, 9, 11) = 0.1537596\)</span></p>
<p>因此，</p>
<p><span class="math inline">\(p-\text{value} = 2 \min(0.1537596, 1 - 0.1537596) = 0.3075\)</span></p>
<p>因此，我们不能拒绝方差相等的原假设。<span class="math inline">\(\blacksquare\)</span></p>
</div>
</section>
</section>
<section id="sec-8_6" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="sec-8_6"><span class="header-section-number">8.6</span> 二项分布的假设检验</h2>
<p>二项分布在工程问题中经常遇到。例如，考虑一种产品生产线，该生产线制造的产品可以分为两类——可接受的或有缺陷的。通常会假设生产的每个产品的缺陷概率为 <span class="math inline">\(p\)</span>，因此一个具有 <span class="math inline">\(n\)</span> 个产品的样本中的缺陷产品数量将是参数为 <span class="math inline">\((n, p)\)</span> 的二项分布。现在考虑以下的假设检验：</p>
<p><span class="math inline">\(H_0 : p \le p_0 \quad vs \quad H_1 : p &gt; p_0\)</span></p>
<p>其中 <span class="math inline">\(p_0\)</span> 是某个指定的值。</p>
<p>如果令 <span class="math inline">\(X\)</span> 表示样本大小为 <span class="math inline">\(n\)</span> 的样本中的缺陷数，那么显然当 <span class="math inline">\(X\)</span> 较大时我们希望拒绝 <span class="math inline">\(H_0\)</span>。为了计算在显著性水平 <span class="math inline">\(\alpha\)</span> 下需要多大的 <span class="math inline">\(X\)</span> 才能证明拒绝是合理的，我们关注到：</p>
<p><span class="math inline">\(P\{X \ge k\} = \sum_{i=k}^{n} P\{X = i\} = \sum_{i=k}^{n} \binom{n}{i} p^i (1 - p)^{n-i}\)</span></p>
<p>现在，很直观（并且可以证明），<span class="math inline">\(P\{X \ge k\}\)</span> 是 <span class="math inline">\(p\)</span> 的递增函数——即，样本中包含至少 <span class="math inline">\(k\)</span> 个缺陷产品的概率随着缺陷概率 <span class="math inline">\(p\)</span> 的增加而增加。使用这一点，我们看到当 <span class="math inline">\(H_0\)</span> 为真时（即 <span class="math inline">\(p \le p_0\)</span>），</p>
<p><span class="math inline">\(P\{X \ge k\} \le \sum_{i=k}^{n} \binom{n}{i} p_0^i (1 - p_0)^{n-i}\)</span></p>
<p>因此，显著性水平 <span class="math inline">\(\alpha\)</span> 下的假设检验</p>
<p><span class="math inline">\(H_0 : p \le p_0 \quad vs \quad H_1 : p &gt; p_0\)</span></p>
<p>是当 <span class="math inline">\(X \ge k^*\)</span> 时拒绝 <span class="math inline">\(H_0\)</span>，其中 <span class="math inline">\(k^*\)</span> 是使 <span class="math inline">\(\sum_{i=k}^{n} \binom{n}{i} p_0^i (1 - p_0)^{n-i} \le \alpha\)</span> 成立的最小的 <span class="math inline">\(k\)</span> 值。也就是说，</p>
<p><span class="math inline">\(k^* = \min \left\{ k : \sum_{i=k}^{n} \binom{n}{i} p_0^i (1 - p_0)^{n-i} \le \alpha \right\}\)</span></p>
<p>可以通过首先确定检验统计量的值——例如 <span class="math inline">\(X = x\)</span>，然后再计算给定的 <span class="math inline">\(p\)</span>-值 来执行假设检验。</p>
<p><span class="math display">\[
\begin{align}
p-\text{value} &amp;= P\{B(n, p_0) \ge x\} \\
&amp;= \sum_{i=x}^{n}{\left(\begin{array}{cc}  n \\ i  \end{array}\right)p_0^i(1-p_0)^{n-i}}
\end{align}
\]</span></p>
<div id="exr-8_6_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.15</strong></span> 一家电脑芯片制造商声称他们出售的芯片的缺陷率不超过 2%。一家电子公司对这家芯片公司的声明印象深刻，并购买了该芯片公司生产的大量芯片。为了确定芯片制造商的声明的可信性，该电子公司决定测试 300 个芯片样本。如果最终发现这 300 个芯片中有 10 个是有缺陷的，那么是否应该拒绝芯片制造商的声明？</p>
</div>
<div id="sol-8_6_a" class="proof solution">
<p><span class="proof-title"><em>解 8.13</em>. </span>让我们在 5% 的显著性水平上检测制造商的声明。为了判断是否需要拒绝制造商 2% 缺陷率的声明，我们需要计算当 <span class="math inline">\(p\)</span> 等于 0.02 时，300 个样本中出现 10 个或更多个缺陷产品的概率。也就是说，我们需要计算 <span class="math inline">\(p-\text{value}\)</span>。如果 <span class="math inline">\(p-\text{value}\)</span> 小于或等于 0.05，那么就应该拒绝制造商 2% 缺陷率的声明。</p>
<p><span class="math display">\[
\begin{align}
P_{0.02}\{X \ge 10\} &amp;= 1 - P_{0.02}\{X \le 9\} \\
&amp;= 1 - pbinom(9, 300, 0.02) \\
&amp;= 0.08183807
\end{align}
\]</span></p>
<p>因此，在显著性水平为 0.05 时，我们不能拒绝芯片制造商的声明。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注记
</div>
</div>
<div class="callout-body-container callout-body">
<p>当然，在 R 中，我们可以使用 <code>binom.test()</code> 来直接根据实验结果计算二项分布的 <span class="math inline">\(p-\text{value}\)</span>。</p>
<div class="cell">
<details class="code-fold">
<summary>代码</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="dv">10</span>, <span class="dv">300</span>, <span class="fl">0.02</span>, <span class="st">"greater"</span>)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  10 and 300
number of successes = 10, number of trials = 300, p-value = 0.08184
alternative hypothesis: true probability of success is greater than 0.02
95 percent confidence interval:
 0.01819384 1.00000000
sample estimates:
probability of success 
            0.03333333 </code></pre>
</div>
</div>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<div id="exr-8_6_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.16</strong></span> 为了证明编辑 A 优于编辑 B，给两位编辑提供了一份相同的稿件。如果编辑 A 发现了 28 个错误，而编辑 B 发现了 18 个错误，其中有 10 个错误两人都发现了，我们能否得出编辑 A 更优秀的结论？</p>
</div>
<div id="sol-8_6_b" class="proof solution">
<p><span class="proof-title"><em>解 8.14</em>. </span>需要注意的是，A 发现了 B 未发现的 18 个错误，B 发现了 A 未发现的 8 个错误。因此，仅由一人发现的错误总数为 26 个。如果 A 和 B 的能力相当，那么他们单独发现某个错误的概率是相等的，即为 1/2。因此，为了证明 A 是更好的编辑，26 次试验中 18 次成功的结果必须足够强大以拒绝以下假设：</p>
<p><span class="math inline">\(H_0: p \leq 1/2 \quad vs \quad H_1: p &gt; 1/2\)</span></p>
<p>其中，<span class="math inline">\(p\)</span> 是伯努利试验成功的概率。对于实验数据的 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p-\text{value} = P\{B(26, 0.5) \geq 18\} = 0.03776\)</span></p>
<p>因此，在 5% 的显著性水平下，我们将拒绝原假设，所以可以得出结论：在 5% 的显著性水平下，A 是更优秀的编辑。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>当样本量 <span class="math inline">\(n\)</span> 较大时，我们可以通过正态分布逼近二项分布来推导显著性水平为 <span class="math inline">\(\alpha\)</span> 的 <span class="math inline">\(H_0: p \leq p_0 \quad vs \quad H_1: p &gt; p_0\)</span> 的近似检验。其原理如下：因为当 <span class="math inline">\(n\)</span> 较大时，随机变量 <span class="math inline">\(X\)</span> 将近似服从均值为</p>
<p><span class="math inline">\(E[X] = np\)</span></p>
<p>方差为</p>
<p><span class="math inline">\(\text{Var}(X) = np(1-p)\)</span></p>
<p>的正态分布，因此</p>
<p><span class="math inline">\(\frac{X - np}{\sqrt{np(1-p)}}\)</span></p>
<p>将近似服从标准正态分布。因此，显著性水平为 <span class="math inline">\(\alpha\)</span> 的近似检验为：</p>
<p><span class="math inline">\(\text{拒绝} H_0, \quad \text{如果} \frac{X - np_0}{\sqrt{np_0(1-p_0)}} \geq z_\alpha\)</span></p>
<p>同样的，也可以使用正态分布来近似来计算 <span class="math inline">\(p-\text{value}\)</span>。</p>
<div id="exm-8_6_c" class="theorem example">
<p><span class="theorem-title"><strong>例 8.3</strong></span> 在 <a href="#exr-8_6_a" class="quarto-xref">习题&nbsp;<span>8.15</span></a> 中，<span class="math inline">\(np_0 = 300 \times 0.02 = 6\)</span>，且 <span class="math inline">\(\sqrt{np_0(1-p_0)} = \sqrt{5.88}\)</span>。因此，由数据 <span class="math inline">\(X = 10\)</span> 得出的 <span class="math inline">\(p-\text{value}\)</span> 为</p>
<p><span class="math inline">\(\begin{align} p-\text{value} &amp;= P_{0.02}\{X \geq 10\} \\ &amp;= P_{0.02}\{X \geq 9.5\} \\ &amp;P_{0.02}\left\{\frac{X - 6}{\sqrt{5.88}} \geq \frac{9.5 - 6}{\sqrt{5.88}}\right\} \\ &amp;\approx P\{Z \geq 1.443\} \\ &amp;= 0.0745 \end{align}\)</span></p>
<p>因此，精确的 <span class="math inline">\(p-\text{value}\)</span> 为 0.0818，正态分布给出的近似 <span class="math inline">\(p-\text{value}\)</span> 为 0.0745。</p>
</div>
<p>假设我们现在希望检验 <span class="math inline">\(p\)</span> 等于某个指定值的原假设，即我们希望检验</p>
<p><span class="math inline">\(H_0: p = p_0 \quad vs \quad H_1: p \neq p_0\)</span></p>
<p>如果一个具有参数 <span class="math inline">\(n\)</span> 和 <span class="math inline">\(p\)</span> 的二项随机变量 <span class="math inline">\(X\)</span> 的观测值等于 <span class="math inline">\(x\)</span>，如果 <span class="math inline">\(x\)</span> 的值显著大于或显著小于在 <span class="math inline">\(p = p_0\)</span> 时的预期值，那么显著性水平为 <span class="math inline">\(\alpha\)</span> 的检验将拒绝原假设 <span class="math inline">\(H_0\)</span>。更准确地说，当以下任意一项成立时，检验将拒绝 <span class="math inline">\(H_0\)</span>：</p>
<p><span class="math inline">\(P\{B(n, p_0) \geq x\} \leq \alpha/2 \quad \text{或} \quad P\{B(n, p_0) \leq x\} \leq \alpha/2\)</span></p>
<p>换句话说，当 <span class="math inline">\(X = x\)</span> 时的 <span class="math inline">\(p-\text{value}\)</span> 为</p>
<p><span class="math inline">\(p-\text{value} = 2 \min \left(P\{B(n, p_0) \geq x\}, P\{B(n, p_0) \leq x\}\right)\)</span></p>
<div id="exr-8_6_d" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.17</strong></span> 历史数据显示，某制造商生产的组件中有 4% 是不合格的。该制造商最近刚刚结束了一场特别激烈的劳资纠纷，所以管理层想知道该劳资纠纷是否会导致 不合格率的变化。如果随机抽取的 500 个样品中有 16 个不合格品（占比 3.2%），在显著性水平为 5% 的情况下，是否足以证明不合格率确实发生了变化？</p>
</div>
<div id="sol-8_6_d" class="proof solution">
<p><span class="proof-title"><em>解 8.15</em>. </span>需要足够强的数据支撑，以使得我们在检验以下的假设时拒绝原假设，才能够得出不合格率发生了变化的结论：</p>
<p><span class="math inline">\(H_0: p = 0.04 \quad vs \quad H_1: p \neq 0.04\)</span></p>
<p>其中 <span class="math inline">\(p\)</span> 是单个组件不合格的概率。500 个样品中有 16 个不合格品的数据的 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p\text{-value} = 2 \min\{P\{X \leq 16\}, P\{X \geq 16\}\}\)</span></p>
<p>其中 <span class="math inline">\(X\)</span> 是一个二项式随机变量 <span class="math inline">\(\text{binomial}(500, 0.04)\)</span>。因为 <span class="math inline">\(500 \times 0.04 = 20\)</span>，我们得知：</p>
<p><span class="math inline">\(p\text{-value} = 2P\{X \leq 16\}\)</span></p>
<p>由于 <span class="math inline">\(X\)</span> 的均值为 20，标准差为 <span class="math inline">\(\sqrt{20 \times 0.96} \approx 4.38\)</span>，显然 <span class="math inline">\(X\)</span> 小于等于 16 的概率是比均值小于一个标准差的概率略小的一个值，该值的两倍并非足够小以允许我们拒绝原假设。事实上，可以证明：</p>
<p><span class="math inline">\(p-\text{value} = 2P\{X \leq 16\} = 0.43161\)</span></p>
<p>因此，没有足够的证据拒绝原假设，即不合格品率仍将保持不变。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<section id="sec-8_6_1" class="level3" data-number="8.6.1">
<h3 data-number="8.6.1" class="anchored" data-anchor-id="sec-8_6_1"><span class="header-section-number">8.6.1</span> 检验两个伯努利总体的参数是否相同</h3>
<p>假设某类型的芯片有两种不同的生产方法，并且假设第一种生产方法生产的芯片的缺陷率为 <span class="math inline">\(p_1\)</span>，而第二种生产方法生产的芯片的缺陷率为 <span class="math inline">\(p_2\)</span>。为了检验假设 <span class="math inline">\(p_1 = p_2\)</span>，我们使用第一种方法生产了 <span class="math inline">\(n_1\)</span> 个芯片作为样本 1，使用第二种方法生产了 <span class="math inline">\(n_2\)</span> 个芯片作为样本 2。</p>
<p>令 <span class="math inline">\(X_1\)</span> 表示样本 1 中的缺陷芯片的数量，<span class="math inline">\(X_2\)</span> 表示样本 2 中的缺陷芯片的数量。因此，<span class="math inline">\(X_1\)</span> 和 <span class="math inline">\(X_2\)</span> 是相互独立的二项分布随机变量，其参数分别为 <span class="math inline">\((n_1, p_1)\)</span> 和 <span class="math inline">\((n_2, p_2)\)</span>。假设 <span class="math inline">\(X_1 + X_2 = k\)</span>，那么两个样本总共有 <span class="math inline">\(k\)</span> 个缺陷品。</p>
<p>如果 <span class="math inline">\(H_0\)</span>（<span class="math inline">\(p_1 = p_2\)</span>）成立，那么 <span class="math inline">\(n_1 + n_2\)</span> 个芯片中的每一个都有相同的概率成为缺陷品。因此 <span class="math inline">\(k\)</span> 个缺陷品的分布与从一个包含 <span class="math inline">\(n_1 + n_2\)</span> 个物品（其中 <span class="math inline">\(n_1\)</span> 是白色物品， <span class="math inline">\(n_2\)</span> 是黑色物品）中随机抽取 <span class="math inline">\(k\)</span> 个样本的分布相同。换句话说，给定总共 <span class="math inline">\(k\)</span> 个缺陷品，当 <span class="math inline">\(H_0\)</span> 成立时，使用第一种方法得到的缺陷品数量的条件分布将具有以下的超几何分布：</p>
<p><span id="eq-8_6_1"><span class="math display">\[
P_{H_0}\{X_1 = i | X_1 + X_2 = k\} = \frac{\binom{n_1}{i}\binom{n_2}{k-i}}{\binom{n_1+n_2}{k}}, \quad i = 0, 1, \ldots, k
\tag{8.30}\]</span></span></p>
<p>在检验 <span class="math inline">\(H_0: p_1 = p_2 \quad vs \quad H_1: p_1 \neq p_2\)</span> 时，当使用第一种方法生产的缺陷芯片比例与使用第二种方法生产的缺陷芯片比例差异很大时，似乎可以合理地拒绝原假设。因此，如果总共存在 <span class="math inline">\(k\)</span> 个缺陷品，那么当 <span class="math inline">\(H_0\)</span> 成立时，我们预计 <span class="math inline">\(X_1/n_1\)</span>（使用第一种方法生产的缺陷芯片比例）将接近于 <span class="math inline">\((k - X_1)/n_2\)</span> （使用第二种方法生产的缺陷芯片比例）。当 <span class="math inline">\(X_1\)</span> 非常小或非常大时，<span class="math inline">\(X_1/n_1\)</span> 和 <span class="math inline">\((k - X_1)/n_2\)</span> 之间的差异会比较大，因此，合理的显著性水平 <span class="math inline">\(\alpha\)</span> 的检验如下所示。</p>
<p>当 <span class="math inline">\(X_1 + X_2 = k\)</span> 时，</p>
<p><span class="math display">\[
\begin{align}
\text{拒绝} H_0 &amp;, \quad \text{如果} P\{X \leq x_1\} \leq \alpha/2 \quad \text{ 或 } \quad P\{X \geq x_1\} \leq \alpha/2 \\
\text{接受} H_0 &amp;, \quad 否则
\end{align}
\]</span></p>
<p>其中 <span class="math inline">\(X\)</span> 是具有以下概率质量函数的超几何随机变量：</p>
<p><span id="eq-8_6_2"><span class="math display">\[
P\{X = i\} = \frac{\binom{n_1}{i}\binom{n_2}{k-i}}{\binom{n_1+n_2}{k}}, \quad i = 0, 1, \ldots, k
\tag{8.31}\]</span></span></p>
<p><span id="eq-8_6_3"><span class="math display">\[
p-\text{value} = 2 \min(P\{X \leq x_1\}, P\{X \geq x_1\})
\tag{8.32}\]</span></span></p>
<p>换句话说，如果显著性水平至少为 <span class="math inline">\(\alpha\)</span> 大于等于 <span class="math inline">\(p-\text{value}\)</span>，我们将拒绝原假设。这种检验也称之为 Fisher-Irwin 检验。</p>
<p>可以通过使用 R 命令 <code>phyper(x, n, m, k)</code> 来计算 <a href="#eq-8_6_3" class="quarto-xref">式&nbsp;<span>8.32</span></a> 的概率，该命令用于计算超几何随机变量的概率，其参数 <span class="math inline">\(n, m, k\)</span> 代表从一个包含 <span class="math inline">\(n\)</span> 个红球和 <span class="math inline">\(m\)</span> 个蓝球的盒子中随机抽取 <span class="math inline">\(k\)</span> 个球时，抽取的红球数量小于或等于 <span class="math inline">\(x\)</span> 的概率。</p>
<div class="callout callout-style-default callout-note callout-titled" title="fisher.test() 和列联表">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
fisher.test() 和列联表
</div>
</div>
<div class="callout-body-container callout-body">
<p>在 R 中，可以直接使用 <code>fisher.test()</code> 来计算 <a href="#eq-8_6_3" class="quarto-xref">式&nbsp;<span>8.32</span></a> 所示的 <span class="math inline">\(p-\text{value}\)</span>。</p>
<p>要使用 R 的 <code>fisher.test</code> 来检验两个二项分布的参数 <span class="math inline">\(p\)</span> 是否一致，首先需要将两个二项分布的结果组织成一个 <span class="math inline">\(2 \times 2\)</span> 的列联表。这个列联表表示两个分布的成功和失败次数。然后，使用 <code>fisher.test</code> 来检验两个分布是否独立，从而间接检验它们的参数 <span class="math inline">\(p\)</span> 是否一致。</p>
<blockquote class="blockquote">
<p>列联表（<em>contingency table</em>）是按两个或更多属性对数据分类后所列出的对应分类的频数表，是由两个以上的变量进行交叉分类的频数分布表。</p>
</blockquote>
<ol type="1">
<li><p><strong>准备数据</strong>：假设我们有两个二项分布的结果，分别记录了其成功次数和失败次数。</p>
<ul>
<li>假设 A 有 8 次成功，2 次失败。</li>
<li>B 有 5 次成功，5 次失败。</li>
</ul>
<p>将如上分布数据组织成如下的 <span class="math inline">\(2 \times 2\)</span> 列联表：</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">5</span>), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Success"</span>, <span class="st">"Failure"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Distribution A"</span>, <span class="st">"Distribution B"</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(data)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>输出的表格将是：</p>
<pre><code>                Success Failure
Distribution A        8       2
Distribution B        5       5</code></pre></li>
<li><p><strong>执行 Fisher 精确检验</strong>：</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">fisher.test</span>(data)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div></li>
<li><p><strong>解释结果</strong>：</p>
<p><code>fisher.test</code> 的结果将包括 <span class="math inline">\(p-\text{value}\)</span> 以用来判断两个分布的成功率 <span class="math inline">\(p\)</span> 是否显著不同。</p>
<pre><code>Fisher's Exact Test for Count Data

data:  data
p-value = 0.315
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
  0.2943 19.3332
sample estimates:
odds ratio 
      3.98 </code></pre>
<ul>
<li><strong>p-value</strong>: 如果 <span class="math inline">\(p-\text{value}\)</span> 值大于 0.05，则我们不能拒绝原假设，即没有足够证据表明两个分布的成功率（p 值）不一致。</li>
<li><strong>odds ratio</strong>: 估计的优势比，这里为 3.98，表示 A 的成功与 B 的成功的比率。</li>
<li><strong>95 percent confidence interval</strong>: 这是对优势比的 95% 置信区间。</li>
</ul></li>
</ol>
<p>在 R 的 <code>fisher.test()</code> 中，列联表的行和列的顺序对计算结果的 <code>p-value</code> 和 <code>odds ratio</code> 等值均没有影响，即便如此，我们最好还是按照行优先来组织列联表，以保障结果的可解释性。</p>
<ol type="1">
<li><strong><code>p-value</code> 不受影响</strong>：
<ul>
<li>Fisher 精确检验的核心是计算列联表中不同行和列组合下观察到的频率是否显著偏离了独立性假设。这个计算基于全排列的可能性，所以 <code>p-value</code> 不受行列顺序的影响。</li>
<li>换句话说，无论你如何排列列联表的行和列，<code>p-value</code> 会保持一致，因为 Fisher 精确检验本质上是一种对称性检验。</li>
</ul></li>
<li><strong><code>odds ratio</code> 不受影响</strong>：
<ul>
<li><p>具体来说，<code>odds ratio</code> 是通过下列公式计算的：<span class="math inline">\(\text{odds ratio} = \frac{(a \times d)}{(b \times c)}\)</span>，其中：</p>
<ul>
<li><code>a</code> 是第一行第一列的值</li>
<li><code>b</code> 是第一行第二列的值</li>
<li><code>c</code> 是第二行第一列的值</li>
<li><code>d</code> 是第二行第二列的值</li>
</ul></li>
<li><p>根据 <code>odds ratio</code> 的计算公式可知，对于列联表而言，无论是行优先、还是列优先的存储方式，都不会影响最终的结果，但是为了保障可解释性，我们最好还是按照行优先来组织列联表，即：</p>
<pre><code>           Success Failure
Group A        8       2
Group B        5       5</code></pre></li>
</ul></li>
</ol>
</div>
</div>
<div id="exr-8_6_e" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.18</strong></span> 假设方法 1 生产的 100 个晶体管中有 20 个不合格，而方法 2 生产的 100 个晶体管中有 12 个不合格。我们能否以 10% 的显著性水平得出这两种方法是等效的这样的结论？</p>
</div>
<div id="sol-8_6_e" class="proof solution">
<p><span class="proof-title"><em>解 8.16</em>. </span>利用 R，我们得到如下的数据：</p>
<p><span class="math inline">\(\begin{align} p-\text{value} &amp; = 2 \min(P(X \leq 20), \, P(X \geq 20)) \\ &amp;= 2 \min(P(X \leq 20), \, 1 - P(X \leq 19)) \\ &amp; =2 \times \min(\text{phyper}(20, 100, 100, 32), \, 1 - \text{phyper}(19, 100, 100, 32)) \\ &amp;= 0.1763396 \end{align}\)</span></p>
<p>在上述计算中使用了 R 函数 <code>min(x, y)</code>，该函数返回 <span class="math inline">\(x\)</span> 和 <span class="math inline">\(y\)</span> 中的最小值。根据 <span class="math inline">\(p-\text{value}\)</span> 的值，我们无法拒绝这两种方法是等效的假设。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注记
</div>
</div>
<div class="callout-body-container callout-body">
<p>更简单的，我们可以直接使用 R 中的 <code>fisher.test()</code> 来计算 <span class="math inline">\(p-\text{value}\)</span>。</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">80</span>, <span class="dv">12</span>, <span class="dv">88</span>), <span class="at">ncol=</span><span class="dv">2</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Method 1"</span>, <span class="st">"Method 2"</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Unacceptable"</span>, <span class="st">"Acceptable"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(data)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  data
p-value = 0.1763
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.792462 4.381294
sample estimates:
odds ratio 
  1.827794 </code></pre>
</div>
</div>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>检验两种不同治疗方法效果是否相同的理想方法是将一组人随机分成两组，一组接受第一种治疗方法，另一组接受第二种治疗方法。然而，这种随机分组的方式并非总是万能的。例如，如果我们想研究饮酒是否会增加患前列腺癌的风险，我们不能让随机选择的样本人群去饮酒。<strong>观察性研究</strong>（<em>observational study</em>）是研究这种假设的另一种方法，这种方法：</p>
<ul>
<li>首先，随机选择一组饮酒人群和一组不饮酒人群</li>
<li>然后，在一段时间内跟踪这些随机选择的人群</li>
<li>最后，使用所得到的跟踪数据来检验假设并判断这两组人群患前列腺癌的风险是否相同</li>
</ul>
<p>接下来的 <a href="#exm-8_6_f" class="quarto-xref">例&nbsp;<span>8.4</span></a> 展示了实现 <strong>观察性研究</strong> 的另一种方法。</p>
<div id="exm-8_6_f" class="theorem example">
<p><span class="theorem-title"><strong>例 8.4</strong></span> 1970 年，研究人员 Herbst、Ulfelder 和 Poskanzer (H-U-P) 怀疑年轻女性中一种相当罕见的疾病——阴道癌，可能是由于她们的母亲在怀孕期间服用了己烯雌酚（<em>Diethylstilbestrol</em>，通常称为 DES）而引起的。为了研究这种可能性，研究人员可以通过搜索获得一组在其母亲怀孕时服用了 DES 的女性（实验组（<em>treatment</em>））和一组在其母亲怀孕时没有服用 DES 的女性（对照组（<em>control</em>））来进行 <strong>观察性研究</strong>。然后，研究人员可以在一段时间内去观察这些不同组的人群，并使用所得到的数据进行检验假设——即这两组不同人群的阴道癌发病概率是否相同。然而，对于这两组人群而言，阴道癌都非常罕见，所以这样的研究需要具备较大的群体规模，并且还需要跟踪观察多年才能获得一个显著的结果。因此，H-U-P 决定采用另一种不同的 <strong>观察性研究</strong> 方法。他们发现了年龄在 15 至 22 岁之间的患有阴道癌的 8 名女性。这些女性（称为病例）中的每一名都与 4 名其他女性（称为参照（<em>referents</em>）或对照(<em>controls</em>)）进行了匹配。每个病例的任何一个参照者都没有患癌症，并且与对应病例出生在相同医院的、相同类型的房间（无论是私人房间还是公共房间），同时其出生日期相差不超过 5 天。研究人员认为，如果 DES 对阴道癌没有影响，那么病例的母亲服用了 DES 的概率 <span class="math inline">\(p_c\)</span> 应该与参照者的母亲服用了 DES 的概率 <span class="math inline">\(p_r\)</span> 相同，所以 H-U-P 决定检验以下假设：</p>
<p><span class="math inline">\(H_0 : p_c = p_r \quad vs \quad H_1 : p_c \neq p_r\)</span></p>
<p>研究发现，8 个病例中有 7 个病例的母亲在怀孕时服用了 DES，而 32 个参照者中没有一个参照者的母亲服用了该药物。研究人员<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>得出结论：DES 与阴道癌之间存在强关联（这些数据的 <span class="math inline">\(p-\text{value}\)</span> 约等于 0）。</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
注记
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">32</span>), <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Treatment"</span>, <span class="st">"Control"</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"C"</span>, <span class="st">"NC"</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          C NC
Treatment 7  1
Control   0 32</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(data)</span></code><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  data
p-value = 4.291e-07
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 15.42963      Inf
sample estimates:
odds ratio 
       Inf </code></pre>
</div>
</div>
</div>
</div>
<p><span class="math inline">\(\blacksquare\)</span></p>
</div>
<p>当样本量 <span class="math inline">\(n1\)</span> 和 <span class="math inline">\(n2\)</span> 比较大时，我们可以通过正态分布逼近二项分布来推导显著性水平为 <span class="math inline">\(\alpha\)</span> 时的原假设 <span class="math inline">\(H_0: p_1 = p_2\)</span> 的近似检验，具体参见：习题 63。</p>
</section>
</section>
<section id="sec-8_7" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="sec-8_7"><span class="header-section-number">8.7</span> 关于泊松分布的均值的假设检验</h2>
<p>令 <span class="math inline">\(X\)</span> 表示一个均值为 <span class="math inline">\(\lambda\)</span> 的泊松分布随机变量，我们希望检验如下的假设：</p>
<p><span class="math inline">\(H_0 : \lambda = \lambda_0 \quad vs \quad H_1 : \lambda \neq \lambda_0\)</span></p>
<p>如果观察到的 <span class="math inline">\(X\)</span> 的值为 <span class="math inline">\(X = x\)</span>，那么当以下任一条件成立时，显著性水平为 <span class="math inline">\(\alpha\)</span> 时的检验将拒绝 <span class="math inline">\(H_0\)</span>：</p>
<p><span id="eq-8_7_1"><span class="math display">\[
P_{\lambda_0} \{ X \geq x \} \leq \alpha / 2 \quad \text{或} \quad P_{\lambda_0} \{ X \leq x \} \leq \alpha / 2
\tag{8.33}\]</span></span></p>
<p>其中，<span class="math inline">\(P_{\lambda_0}\)</span> 表示在泊松分布的均值为 <span class="math inline">\(\lambda_0\)</span> 的假设下计算的概率。根据 <a href="#eq-8_7_1" class="quarto-xref">式&nbsp;<span>8.33</span></a>，<span class="math inline">\(p-\text{value}\)</span> 的计算方式为：</p>
<p><span class="math inline">\(\text{p-value} = 2 \min \left( P_{\lambda_0} \{ X \geq x \}, P_{\lambda_0} \{ X \leq x \} \right)\)</span></p>
<p>可以利用 R 中的 <code>ppois(x, lamda_0)</code> 计算 <span class="math inline">\(P_{\lambda_0} \{ X \geq x \}\)</span> 或者 P_{_0} { X x } 的概率。</p>
<div id="exr-8_7_a" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.19</strong></span> 某芯片制造商的管理层声称：每天生产的计算机芯片中，存在缺陷的芯片的平均数量不超过 25 个，但是有人质疑管理层的这一说法。为了检验管理层这一说法，抽取了 5 天生产的产品作为样本，样本显示这 5 天的缺陷芯片个数分别是：28、34、32、38、22。在 5% 的显著性水平下，检验管理层的说法是否成立。</p>
</div>
<div id="sol-8_7_a" class="proof solution">
<p><span class="proof-title"><em>解 8.17</em>. </span>对于每个计算机芯片而言，检测到其有缺陷的可能性非常小，因此，假设每天生产的芯片中存在缺陷的芯片数量近似服从均值为 <span class="math inline">\(\lambda\)</span> 的泊松分布是合理的。为了确定管理层的说法是否可靠，我们将检验如下假设：</p>
<p><span class="math inline">\(H_0: \lambda \leq 25 \quad vs \quad H_1: \lambda &gt; 25\)</span></p>
<p>在 <span class="math inline">\(H_0\)</span> 下，5 天内生产的芯片中存在缺陷的芯片总数也服从泊松分布（独立的泊松分布随机变量的和也服从泊松分布），并且其均值不超过 125。由于观察到 5 天的缺陷芯片数量总数为 154，因此 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(\begin{align} p-\text{value} &amp;= P_{125}\{X \geq 154\} \\ &amp;= 1 - P_{125}\{X \leq 153\} \\ &amp;= 1 - \text{ppois}(153, 125) \\ &amp;= 0.006664794 \end{align}\)</span></p>
<p>因此，在 5% 的显著性水平下（甚至在 1% 的显著性水平下），我们将拒绝管理层的说法。<span class="math inline">\(\blacksquare\)</span></p>
</div>
<section id="sec-8_7_1" class="level3" data-number="8.7.1">
<h3 data-number="8.7.1" class="anchored" data-anchor-id="sec-8_7_1"><span class="header-section-number">8.7.1</span> 检验两个泊松分布的参数之间的关系</h3>
<p>令 <span class="math inline">\(X_1\)</span> 和 <span class="math inline">\(X_2\)</span> 为独立的泊松分布随机变量，其均值分别为 <span class="math inline">\(\lambda_1\)</span> 和 <span class="math inline">\(\lambda_2\)</span>，考虑检验如下的假设：</p>
<p><span class="math inline">\(H_0 : \lambda_2 = c\lambda_1 \quad vs \quad H_1 : \lambda_2 \neq c\lambda_1\)</span></p>
<p>其中，<span class="math inline">\(c\)</span> 为给定的常数。</p>
<p>如上假设的检验是一个条件检验（<em>a conditional test</em>），其本质类似于 <a href="#sec-8_6_1" class="quarto-xref"><span>小节 8.6.1</span></a> 中的 Fisher-Irwin 检验。在给定 <span class="math inline">\(X_1 + X_2\)</span> 下，<span class="math inline">\(X_1\)</span> 的条件概率分布服从二项分布，基于这一事实，我们有 <a href="#prp-8_7_1" class="quarto-xref">命题&nbsp;<span>8.1</span></a>。</p>
<div id="prp-8_7_1" class="theorem proposition">
<p><span class="theorem-title"><strong>命题 8.1</strong></span> <span class="math inline">\(P\{X_1 = k \mid X_1 + X_2 = n\} = \binom{n}{k} \left[\frac{\lambda_1}{\lambda_1 + \lambda_2}\right]^k \left[\frac{\lambda_2}{\lambda_1 + \lambda_2}\right]^{n-k}\)</span></p>
<div class="proof">
<p><span class="proof-title"><em>证</em>. </span><span class="math display">\[
\begin{align}
P\{X_1 = k \mid X_1 + X_2 = n\} &amp;= \frac{P\{X_1 = k, X_1 + X_2 = n\}}{P\{X_1 + X_2 = n\}} \\
&amp;= \frac{P\{X_1 = k, X_2 = n - k\}}{P\{X_1 + X_2 = n\}} \\
&amp;= \frac{P\{X_1 = k\} P\{X_2 = n - k\}}{P\{X_1 + X_2 = n\}} \quad \text{（由于独立性）} \\
&amp;= \frac{\exp\{-\lambda_1\} \lambda_1^k / k! \cdot \exp\{-\lambda_2\} \lambda_2^{n-k} / (n-k)!}{\exp\{-(\lambda_1 + \lambda_2)\} (\lambda_1 + \lambda_2)^n / n!} \\
&amp;= \frac{n!}{(n-k)!k!} \left[\frac{\lambda_1}{\lambda_1 + \lambda_2}\right]^k \left[\frac{\lambda_2}{\lambda_1 + \lambda_2}\right]^{n-k}
\end{align}
\]</span></p>
<p>其中，倒数第二个等式成立的原因是：独立泊松随机变量的和也是泊松分布。<span class="math inline">\(\blacksquare\)</span></p>
</div>
</div>
<p>根据 <a href="#prp-8_7_1" class="quarto-xref">命题&nbsp;<span>8.1</span></a> 可知，如果 <span class="math inline">\(H_0\)</span> 为真，那么在给定 <span class="math inline">\(X_1 + X_2\)</span> 下，<span class="math inline">\(X_1\)</span> 的条件概率分布是参数为 <span class="math inline">\((n, p = \frac{1}{1 + c})\)</span> 的二项分布。因此，我们可以得出结论：如果 <span class="math inline">\(X_1 + X_2 = n\)</span>，如果我们观察到 <span class="math inline">\(X_1\)</span> 的值为 <span class="math inline">\(x_1\)</span>，那么如果满足以下条件中的任何一个，则应拒绝 <span class="math inline">\(H_0\)</span>：</p>
<p><span id="eq-8_7_001"><span class="math display">\[
\begin{align}
&amp;P\{\text{B}(n, 1/(1+c)) \geq x_1\} \leq \alpha/2 \\
&amp;或 \\
&amp;P\{\text{B}(n, 1/(1+c)) \leq x_1\} \leq \alpha/2
\end{align}
\tag{8.34}\]</span></span></p>
<div id="exr-8_7_b" class="theorem exercise">
<p><span class="theorem-title"><strong>习题 8.20</strong></span> 一家企业经营着两个大型的工厂。如果工厂 1 在过去 8 周内发生的事故数量分别为 16、18、9、22、17、19、24、8，工厂 2 在过去 6 周内发生的事故数量分别为 22、18、26、30、25、28，我们是否可以在 5% 的显著性水平下得出这两个工厂的安全条件存在差异的结论？</p>
</div>
<div id="sol-8_7_b" class="proof solution">
<p><span class="proof-title"><em>解 8.18</em>. </span>对于任何一分钟而言，发生工业事故的概率很小，因此每周发生的此类事故的数量应大致符合泊松分布。如果我们令 <span class="math inline">\(X_1\)</span> 表示工厂 1 在 8 周期间发生的事故总数，<span class="math inline">\(X_2\)</span> 表示工厂 2 在 6 周期间发生的事故总数，那么如果两个工厂的安全条件没有差异，我们将有：</p>
<p><span class="math inline">\(\lambda_2 = \frac{3}{4}\lambda_1\)</span></p>
<p>其中 <span class="math inline">\(\lambda_i \equiv E[X_i],\ i = 1, 2\)</span>。</p>
<p>由于 <span class="math inline">\(X_1 = 133\)</span>, <span class="math inline">\(X_2 = 149\)</span>，根据 <a href="#eq-8_7_001" class="quarto-xref">式&nbsp;<span>8.34</span></a>，该检验的 <span class="math inline">\(p-\text{value}\)</span> 为：</p>
<p><span class="math inline">\(p-\text{value} = 2\min \left( P\{\text{B}(282, \frac{4}{7}) \geq 133\}, P\{\text{B}(282, \frac{4}{7}) \leq 133\} \right)\)</span></p>
<p>即， <span class="math inline">\(p-\text{value} = 9.408 \times 10^{-4}\)</span></p>
<p>因此，我们将拒绝原假设：两个工厂的安全条件相同。 <span class="math inline">\(\blacksquare\)</span></p>
</div>
</section>
</section>
<section id="problems" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="problems">Problems</h2>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><a href="https://www.nejm.org/doi/full/10.1056/NEJM197104222841604">Herbst, A., Ulfelder, H., and Poskanzer, D., Adenocarcinoma of the Vagina: Association of Maternal Stilbestrol Therapy with Tumor Appearance in Young Women, New England Journal of Medicine, 284, 878-881, 1971</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "已复制");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "已复制");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/wangwei1237\.github\.io\/introduction_to_probability_and_statistics\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<script src="https://utteranc.es/client.js" repo="wangwei1237/introduction_to_probability_and_statistics" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapter_7/7.html" class="pagination-link" aria-label="参数估计">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">参数估计</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapter_9/9.html" class="pagination-link" aria-label="回归">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">回归</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright Wang Wei. All Rights Reserved.</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/edit/main/chapter_8/8.qmd" class="toc-action"><i class="bi bi-github"></i>编辑该页面</a></li><li><a href="https://github.com/wangwei1237/introduction_to_probability_and_statistics/issues/new" class="toc-action"><i class="bi empty"></i>反馈问题</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>